BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "{JPN}トレーナーに ひつようなのは...\p"
	.string "{JPN}ちしき...\n"
	.string "{JPN}せんりゃく...\l"
	.string "{JPN}うん...\l"
	.string "{JPN}こんじょう...\l"
	.string "{JPN}せいしん...\l"
	.string "{JPN}ゆうき...\l"
	.string "{JPN}そして のうりょく...\p"
	.string "{JPN}よし! ぼくは すべてにおいて\n"
	.string "{JPN}かんぺきだ!\p"
	.string "{JPN}どの たてものでも\n"
	.string "{JPN}むてきだぞ!\pえ? ポケモン?\nなに それ?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "{JPN}フロンティアブレーンって\n"
	.string "{JPN}しってる?\p"
	.string "{JPN}バトルフロンティアの\n"
	.string "{JPN}ななつのしせつをきりもりする\l"
	.string "{JPN}ななにんのとくべつなトレーナーを\lエニシダがそうよんでるんだ$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "{JPN}バトルタワーで おねえさんに\n"
	.string "{JPN}バトルのさいのうが あるって\l"
	.string "{JPN}いわれたんだ!\p"
	.string "{JPN}でも わたし ポケモンコンテスト\n"
	.string "{JPN}のほうが すきなの!\p"
	.string "{JPN}だけど コンテストは\n"
	.string "{JPN}ぜんぜん だめなのよね!\pさいのうが あることと\nすきなことって おなじじゃ\lないのね$"

