SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "{JPN}ルネシティと おくりびやまには\n"
	.string "{JPN}なにか つながりが あるらしい.\p"
	.string "{JPN}ぼくと ともだちで まえ つとめて\n"
	.string "{JPN}いた けんきゅうしょで しらべたんだ.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "{JPN}おにいちゃんは むかし うみの\nけんきゅうを していたんだ.$"

