RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "{JPN}トレーナーズスクールは\n"
	.string "{JPN}すばらしいよ.\p"
	.string "{JPN}そこで べんきょうすれば\nジムリーダーにだって\nなれるかもしれないね.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "{JPN}ジムリーダーの ツツジは\n"
	.string "{JPN}ポケモンのことを とても\n"
	.string "{JPN}よく しっているんだ.\pとても つよいしね!$"

