PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "{JPN}ホウエンちほうには いわ こおり\n"
	.string "{JPN}はがね でんき りゅうの\l"
	.string "{JPN}ちからを あらわす\l"
	.string "{JPN}5ひきの ポケモンが いるんだ\p"
	.string "{JPN}それぞれが ふかい どうくつの\l"
	.string "{JPN}おくに かくれて いるって\l"
	.string "{JPN}いわれて いるよ\p"
	.string "{JPN}ぼくが ちいさい ころに きいた\lはなしなんだけどね$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "{JPN}6つの てんが 5つの とびらを\n"
	.string "{JPN}ひらく\p"
	.string "{JPN}おじいちゃんが よく いって\nいたんだけど いみは わからない\nんだ$"

