VermilionCity_House1_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "{JPN}わたしは つりおやじ \n"
	.string "{JPN}つりきょうだいの あにじゃ.\p"
	.string "{JPN}いかりのみずうみの つりめいじんに\n"
	.string "{JPN}あったことは あるかのう?\p"
	.string "{JPN}あのひとは せかいいちの\n"
	.string "{JPN}コイキングを みるのが ゆめなんじゃ.\p"
	.string "{JPN}もし よろしければ つった\n"
	.string "{JPN}コイキングを みせてくれんかのう?\p"
	.string "{JPN}もしかすると あのひとが ゆめみる\n"
	.string "{JPN}コイキングを つるかもしれんぞ.$"

VermilionCity_House1_Text_Photo:
	.string "{JPN}It's a photo of people fishing...\p"
	.string "{JPN}They're having a great time...$"
