gText_ApprenticeChallenge0::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばん でしです!\n"
	.string "{JPN}グスン... きんちょう するなあ$"

gText_ApprenticeChallenge1::
	.string "{JPN}ぼく {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}ばんの でし なんだ! いくぞー!$"

gText_ApprenticeChallenge2::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの でしだ!\n"
	.string "{JPN}いざ しょうぶ!$"

gText_ApprenticeChallenge3::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんでしです...\n"
	.string "{JPN}あたし なんかが かてる かな...?$"

gText_ApprenticeChallenge4::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_2}ばん でしなの!\n"
	.string "{JPN}しょうぶ して あげるわ!$"

gText_ApprenticeChallenge5::
	.string "{JPN}いそがしい なか {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}ばんの でし やってる オレです!$"

gText_ApprenticeChallenge6::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの\n"
	.string "{JPN}でしトレーナーよ よっろしくぅ!$"

gText_ApprenticeChallenge7::
	.string "{JPN}わたくし {STR_VAR_1}さまの {STR_VAR_2}ばんの\n"
	.string "{JPN}でしで ございますの... いきますわよ$"

gText_ApprenticeChallenge8::
	.string "{JPN}キャー! {STR_VAR_1}せんせいの\n"
	.string "{JPN}{STR_VAR_2}ばん でし ですっ! がんばります!$"

gText_ApprenticeChallenge9::
	.string "{JPN}いえーい! {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}ばん でしの おじさんと しょうぶ!$"

gText_ApprenticeChallenge10::
	.string "{JPN}{STR_VAR_1}の 1000ばんめの でしだ!\n"
	.string "{JPN}うそ ほんとは {STR_VAR_2}ばん! いくぞ!$"

gText_ApprenticeChallenge11::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの\n"
	.string "{JPN}でしだぜ! ノリノリで いってみようぜー!$"

gText_ApprenticeChallenge12::
	.string "{JPN}イヤハァ! {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}ばんの でしとは オレのことっ!$"

gText_ApprenticeChallenge13::
	.string "{JPN}...ゴホっ ゴホっ よろしく!\n"
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんでしだ!$"

gText_ApprenticeChallenge14::
	.string "{JPN}て てれますが {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}ばんの でし やってます...!$"

gText_ApprenticeChallenge15::
	.string "{JPN}うそじゃない! わたしは\n"
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの でしだ$"

gText_ApprenticePleaseTeach0::
	.string "{JPN}も もしかして {PLAYER}さん...?\l"
	.string "{JPN}ああ! グスっ...\p"
	.string "{JPN}あ... ごめんなさい!\n"
	.string "{JPN}きんちょう して なみだが でちゃった...\p"
	.string "{JPN}ぼくは {STR_VAR_1} って いって\n"
	.string "{JPN}{PLAYER}さんに あこがれて います!\l"
	.string "{JPN}い いつか {PLAYER}さんに あって\l"
	.string "{JPN}ポケモンのこと おしえて もらう って\l"
	.string "{JPN}ゆめ みて いたんです...! うう...\p"
	.string "{JPN}あのう あのう {PLAYER}さん!\n"
	.string "{JPN}できたら... ポケモンのこと\l"
	.string "{JPN}おしえて ください!$"

gText_ApprenticeRejectTeaching0::
	.string "{JPN}そ そんな...\n"
	.string "{JPN}う うう うわーん!\p"
	.string "{JPN}おねがいです... おねがい ですから...!$"

gText_ApprenticeWhichLevelMode0::
	.string "{JPN}えー ほんとですか!\n"
	.string "{JPN}やった! うれしいよう! うぉぉーん!\p"
	.string "{JPN}あ... ごめん なさい\n"
	.string "{JPN}うれしくて なみだが...\p"
	.string "{JPN}あのう じゃあ おしえて ください!\n"
	.string "{JPN}バトルタワーの へや なんですけど\l"
	.string "{JPN}レベル50と オープンレベルの へや\l"
	.string "{JPN}ぼく だったら どっちが いいのかな...?$"

gText_ApprenticeLevelModeThanks0::
	.string "{JPN}{STR_VAR_1} ですね! うぅ うわーん!\p"
	.string "{JPN}あ! ごめんなさい\n"
	.string "{JPN}{PLAYER}さんが ぼくに へやを\l"
	.string "{JPN}きめてくれた うれしさで なみだが...\p"
	.string "{JPN}...グスン\n"
	.string "{JPN}ありがとう ございました!\l"
	.string "{JPN}また おはなし してください!$"

gText_ApprenticePleaseTeach1::
	.string "{JPN}うわー! {PLAYER}さん だよね?\n"
	.string "{JPN}すごく つよい ひと なんだよね?\p"
	.string "{JPN}ボク {STR_VAR_1}!\n"
	.string "{JPN}トレーナーに なった ばかり なんだ\p"
	.string "{JPN}ねえ おねがい {PLAYER}さん!\n"
	.string "{JPN}ぼくの せんせいに なって\l"
	.string "{JPN}トレーナーのこと いっぱい おしえてよ!$"

gText_ApprenticeRejectTeaching1::
	.string "{JPN}えー? どうして?\n"
	.string "{JPN}ねーっ いいでしょ いいでしょ\l"
	.string "{JPN}せんせいに なってよ おねがい!$"

gText_ApprenticeWhichLevelMode1::
	.string "{JPN}わーい やった!\n"
	.string "{JPN}じゃあねー はじめに ききたい ことはね\l"
	.string "{JPN}バトルタワーの こと!\p"
	.string "{JPN}レベル50と オープンレベルの へや\n"
	.string "{JPN}どっちが ボクに ピッタリ かなあ?$"

gText_ApprenticeLevelModeThanks1::
	.string "{JPN}{STR_VAR_1}か! そーだよね!\n"
	.string "{JPN}じゃあ ボク がんばるね!\p"
	.string "{JPN}また こんど ここで あったら\n"
	.string "{JPN}なにか おしえてね せんせい!$"

gText_ApprenticePleaseTeach2::
	.string "{JPN}あの... {PLAYER}さん ですか!?\n"
	.string "{JPN}ぼく {STR_VAR_1} って いいます!\p"
	.string "{JPN}ぼく ポケモントレーナーに なりたいんだけど\n"
	.string "{JPN}どうすれば いいのか わからなくて...\p"
	.string "{JPN}それで ゆうめいな {PLAYER}さんに\n"
	.string "{JPN}どうすれば いいのか きいてみようと\l"
	.string "{JPN}おもったんです!\p"
	.string "{JPN}そうだんに のって もらえますか?$"

gText_ApprenticeRejectTeaching2::
	.string "{JPN}そんなあ!\n"
	.string "{JPN}ぼく どうしても ポケモントレーナーに\l"
	.string "{JPN}なりたいんです!\p"
	.string "{JPN}しつもんに こたえて もらえますか?$"

gText_ApprenticeWhichLevelMode2::
	.string "{JPN}ありがとう ございます!\n"
	.string "{JPN}じゃあ さっそく さいしょの しつもん!\p"
	.string "{JPN}バトルタワーって レベル50と オープンと\n"
	.string "{JPN}ふたつの レベルが ありますよね!\p"
	.string "{JPN}どっちの レベルが\n"
	.string "{JPN}ぼくに あってると おもいますか?$"

gText_ApprenticeLevelModeThanks2::
	.string "{JPN}{STR_VAR_1} ですね! わかりました!\n"
	.string "{JPN}じゃあ また しつもんが あったら\l"
	.string "{JPN}ここに くるので おしえて ください!$"

gText_ApprenticePleaseTeach3::
	.string "{JPN}あれ? え? あなたは...!\n"
	.string "{JPN}いえ そんなはず ないわ\l"
	.string "{JPN}あたし なんかが {PLAYER}さんに\l"
	.string "{JPN}あえるはず なんて ないもん\p"
	.string "{JPN}...ほんとに {PLAYER}さん なの?\n"
	.string "{JPN}しんじられない おはなし できるなんて!\l"
	.string "{JPN}ああ こんな いいことが あったら\l"
	.string "{JPN}あとは わるいこと ばっかり おきるんだわ\p"
	.string "{JPN}...あ ごめんなさい\n"
	.string "{JPN}あたし... {STR_VAR_1} です...\l"
	.string "{JPN}なんの とりえも ありません\l"
	.string "{JPN}って じこしょうかい なんて しても\l"
	.string "{JPN}どうせ すぐ わすれちゃいます よね...\p"
	.string "{JPN}{PLAYER}さんに あえたら\n"
	.string "{JPN}トレーナーとして そうだんに のって って\l"
	.string "{JPN}おねがい しようと おもっていたけど\l"
	.string "{JPN}どうせ ムリですよね?\p"
	.string "{JPN}...それとも もしかして\n"
	.string "{JPN}そうだんに のって もらえたり しますか?$"

gText_ApprenticeRejectTeaching3::
	.string "{JPN}やっぱり... そうですよね\n"
	.string "{JPN}あたし なんて ほんとに\l"
	.string "{JPN}つまらない おんなのこで...\p"
	.string "{JPN}でも もしかしたら って おもって...\n"
	.string "{JPN}かんがえなおして なんて くれませんよね?\p"
	.string "{JPN}けど やっぱり あきらめられない\n"
	.string "{JPN}うんが いい うちに おねがいしよう!\l"
	.string "{JPN}...そうだんに のって もらえますか?$"

gText_ApprenticeWhichLevelMode3::
	.string "{JPN}ほんとう ですか? しんじられない!\n"
	.string "{JPN}あたし なんかの そうだんに\l"
	.string "{JPN}のってもらえる なんて!\l"
	.string "{JPN}うれしい です...\p"
	.string "{JPN}ほんとうに くだらないです けど\n"
	.string "{JPN}あたし には きめられないん です\p"
	.string "{JPN}バトルタワーって レベルが\n"
	.string "{JPN}レベル50と オープンレベルと\l"
	.string "{JPN}ふたつ えらべる けど...\p"
	.string "{JPN}あたし なんか でも がんばれそうな\n"
	.string "{JPN}レベルって どっちの へや でしょうか?$"

gText_ApprenticeLevelModeThanks3::
	.string "{JPN}{STR_VAR_1} ですか わかりました!\n"
	.string "{JPN}ほんとうに こんな あたしでも\l"
	.string "{JPN}だいじょうぶ でしょうか\l"
	.string "{JPN}がんばって みます ダメかも しれないけど\p"
	.string "{JPN}きょうは あたしなんかの ために\n"
	.string "{JPN}ありがとう ございました...!$"

gText_ApprenticePleaseTeach4::
	.string "{JPN}あっ! {PLAYER}{KUN} でしょ!?\n"
	.string "{JPN}ポケモン つよいって きいてるよ!\p"
	.string "{JPN}わたしは {STR_VAR_1}\n"
	.string "{JPN}おともだちに なって あげる!\p"
	.string "{JPN}あのね トレーナーズスクール で\n"
	.string "{JPN}おそわった こと だけじゃ\l"
	.string "{JPN}バトルフロンティア では かてないの!\p"
	.string "{JPN}そうだんに のってくれても いいわよ\n"
	.string "{JPN}もちろん オーケー でしょ?$"

gText_ApprenticeRejectTeaching4::
	.string "{JPN}え? なんで ことわるの?\n"
	.string "{JPN}あたしの おねがい なんだけど!\l"
	.string "{JPN}かんがえなおしてよぉ!$"

gText_ApprenticeWhichLevelMode4::
	.string "{JPN}うん じゃあ おねがいね\n"
	.string "{JPN}さっそく きめて ほしいことが あるから\p"
	.string "{JPN}レベル50と オープンレベルの へやが\n"
	.string "{JPN}バトルタワーに あるじゃない?\l"
	.string "{JPN}{PLAYER}{KUN}は わたしには\l"
	.string "{JPN}どっちが いいと おもう?$"

gText_ApprenticeLevelModeThanks4::
	.string "{JPN}そう {STR_VAR_1}が\n"
	.string "{JPN}わたしに ふさわしいのね ありがと!\l"
	.string "{JPN}{PLAYER}{KUN}が きめた って おもえば\l"
	.string "{JPN}まけても きが らくだわ!\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}また そうだんに のってね!$"

gText_ApprenticePleaseTeach5::
	.string "{JPN}ああ きみ! {PLAYER}{KUN}!\n"
	.string "{JPN}ゆうめい だから しってるぜ\l"
	.string "{JPN}オレは {STR_VAR_1} よろしく!\p"
	.string "{JPN}オレは トライアスリート やってて\n"
	.string "{JPN}からだを きたえる かたわら\l"
	.string "{JPN}ポケモンも そだてて ほかにも\l"
	.string "{JPN}バイトに ひるねに しゃこうダンス...\p"
	.string "{JPN}いそがしくて なっかなか\n"
	.string "{JPN}いい トレーナーに なれないんだよね!\p"
	.string "{JPN}そこで おねがい!\p"
	.string "{JPN}ここで あえたのも なにかの ごえん!\n"
	.string "{JPN}{PLAYER}{KUN} たまに オレに\l"
	.string "{JPN}アドバイスを おねがい できないかな?$"

gText_ApprenticeRejectTeaching5::
	.string "{JPN}えー! たのむよ!\n"
	.string "{JPN}{PLAYER}{KUN} みたいな ひとが\l"
	.string "{JPN}オレには ひつよう なんだよー!\p"
	.string "{JPN}オレに アドバイス たのむよ!$"

gText_ApprenticeWhichLevelMode5::
	.string "{JPN}サンキュー そう こなくっちゃ!\n"
	.string "{JPN}んじゃ てはじめに かるいのを 1つね!\p"
	.string "{JPN}あのさ バトルタワー って\n"
	.string "{JPN}レベルが 2しゅるい あるじゃん?\l"
	.string "{JPN}レベル50と オープンレベル!\p"
	.string "{JPN}いそがしい オレ だったら\n"
	.string "{JPN}どっちで がんばれば いいかな?$"

gText_ApprenticeLevelModeThanks5::
	.string "{JPN}{STR_VAR_1} ね! オーケー!\n"
	.string "{JPN}なんとか じかん つくって やってみるぜ!\p"
	.string "{JPN}...っと いけね バイトのじかんだ!\n"
	.string "{JPN}じゃあ サンキュー またな!$"

gText_ApprenticePleaseTeach6::
	.string "{JPN}うっそ もしかして\n"
	.string "{JPN}ほんものの {PLAYER}さん?\p"
	.string "{JPN}あっは! すごーい!\n"
	.string "{JPN}わたし {STR_VAR_1}よ よろしくぅ!\p"
	.string "{JPN}{PLAYER}さん って なんか\n"
	.string "{JPN}とっても つよいんでしょ\l"
	.string "{JPN}みんな うわさ してるもんね!\p"
	.string "{JPN}あ! いいこと かんがえちゃった\n"
	.string "{JPN}わたし {PLAYER}さんに\l"
	.string "{JPN}アドバイスを もらおうっと!\l"
	.string "{JPN}きっと つよく なれそう!\p"
	.string "{JPN}ねっ いいでしょ?\n"
	.string "{JPN}わたしに アドバイス おねがい!$"

gText_ApprenticeRejectTeaching6::
	.string "{JPN}あははは! そんな いじわる いっても\n"
	.string "{JPN}あたし には つうじないわよん!\l"
	.string "{JPN}ほんとは オーケー なんでしょ?$"

gText_ApprenticeWhichLevelMode6::
	.string "{JPN}わーい さっすが {PLAYER}さん!\n"
	.string "{JPN}ココロひろーい!\l"
	.string "{JPN}まずは なにから きこうかなー?\l"
	.string "{JPN}...あっ おもいついた!\p"
	.string "{JPN}ジャーン しつもんです!\n"
	.string "{JPN}わたしが バトルタワーに いどむなら!\l"
	.string "{JPN}レベル50のへや! オープンレベルのへや!\l"
	.string "{JPN}さて どっちが にあっている でしょう?$"

gText_ApprenticeLevelModeThanks6::
	.string "{JPN}ほほぉー!\n"
	.string "{JPN}{STR_VAR_1} と きましたか!\l"
	.string "{JPN}シブイ おこたえ ありがとう!\p"
	.string "{JPN}ん きょうは こんなところ かな\n"
	.string "{JPN}こんど また ここで あおうね!\l"
	.string "{JPN}ありがと!$"

gText_ApprenticePleaseTeach7::
	.string "{JPN}もし {PLAYER}さんで\n"
	.string "{JPN}いらっしゃいますか?\p"
	.string "{JPN}おめに かかれて うれしゅうございます\n"
	.string "{JPN}わたくし {STR_VAR_1}と もうしますの\l"
	.string "{JPN}{PLAYER}さんに かねてより\l"
	.string "{JPN}あこがれて おりました...\p"
	.string "{JPN}... ... ...\p"
	.string "{JPN}あの... こんな おねがい\n"
	.string "{JPN}おこまりに なるかも しれませんが...\p"
	.string "{JPN}わたくしを {PLAYER}さんに\n"
	.string "{JPN}でしいり させて いただけません?$"

gText_ApprenticeRejectTeaching7::
	.string "{JPN}まあ...!\p"
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ...\p"
	.string "{JPN}...あ ショックで きを うしないましたわ\n"
	.string "{JPN}いいえ! きっと ききまちがい ですわ\p"
	.string "{JPN}おねがい! わたくしを\n"
	.string "{JPN}でしに して くださると おっしゃって!$"

gText_ApprenticeWhichLevelMode7::
	.string "{JPN}うっ うれしい ですわ...!\p"
	.string "{JPN}では さっそくですけど わたくしの\n"
	.string "{JPN}そうだんを きいて くださいませ!\p"
	.string "{JPN}わたくし いちど バトルタワーに\n"
	.string "{JPN}ちょうせん しようと おもっていますの\l"
	.string "{JPN}ただ レベルが ふたつ ありまして...\p"
	.string "{JPN}わたくしは レベル50と オープンレベル\n"
	.string "{JPN}どちらに ふさわしいと おもわれますか?$"

gText_ApprenticeLevelModeThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\n"
	.string "{JPN}わかりました がんばりますわ!\p"
	.string "{JPN}それでは {PLAYER}さん\n"
	.string "{JPN}これからも よろしく おねがいしますわ\l"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticePleaseTeach8::
	.string "{JPN}キャー! キャー!!!\n"
	.string "{JPN}{PLAYER}さんに はなしかけられた!\l"
	.string "{JPN}かっ かんげきっ...!\p"
	.string "{JPN}わたし! {STR_VAR_1}と いいますっ!\n"
	.string "{JPN}トレーナーに なって すぐに\l"
	.string "{JPN}ポケモンかいの おおもの {PLAYER}さんと\l"
	.string "{JPN}おはなし できて かんどう してますっ!\p"
	.string "{JPN}そそそそ そうだ!\n"
	.string "{JPN}{PLAYER}さん おねがいが!\l"
	.string "{JPN}わたしを でしに して くださいっ!\l"
	.string "{JPN}いろいろ おしえて ほしいのですっ!$"

gText_ApprenticeRejectTeaching8::
	.string "{JPN}うっわああ!!\n"
	.string "{JPN}{PLAYER}さんに ことわられた...\l"
	.string "{JPN}きっ きちょうな けいけん だわっ!\p"
	.string "{JPN}{PLAYER}さんっ! こんどは\n"
	.string "{JPN}よい おへんじも きかせて くださいっ!\l"
	.string "{JPN}わたしに ごしどうを おねがいしますっ!$"

gText_ApprenticeWhichLevelMode8::
	.string "{JPN}ひええええぇ! {PLAYER}さんに\n"
	.string "{JPN}はい って いわれたああぁ!!\l"
	.string "{JPN}きょうは もう ねむれない...\l"
	.string "{JPN}おありがとう ございますう!\p"
	.string "{JPN}ではっ うかがいます!\n"
	.string "{JPN}わたしは バトルタワー\l"
	.string "{JPN}レベル50のへやと オープンレベルのへや\l"
	.string "{JPN}どちらに むいてると おもわれますかっ?$"

gText_ApprenticeLevelModeThanks8::
	.string "{JPN}{STR_VAR_1} りょうかいですっ\n"
	.string "{JPN}りょうかいで ありますっ!\l"
	.string "{JPN}わたし かんげき です!\p"
	.string "{JPN}では また こんど\n"
	.string "{JPN}いろいろと おしえて くださいね!$"

gText_ApprenticePleaseTeach9::
	.string "{JPN}ワォ! きみは\n"
	.string "{JPN}もしや もしや {PLAYER}{KUN}!\l"
	.string "{JPN}ストロングで フェイマスな トレーナー!\l"
	.string "{JPN}いや おじさん ラッキーだなー!\p"
	.string "{JPN}ハロウ おじさんは {STR_VAR_1}ね!\n"
	.string "{JPN}ポケモン ティーチャー さがしてるんだ\l"
	.string "{JPN}そんな ときに グッドタイミングで\l"
	.string "{JPN}{PLAYER}{KUN}が あらわれた!\p"
	.string "{JPN}と いうわけで {PLAYER}{KUN}!\n"
	.string "{JPN}おじさんを でしいり させて くれ!$"

gText_ApprenticeRejectTeaching9::
	.string "{JPN}ぐわーっ!\n"
	.string "{JPN}きみも なかなか クールで タフだね...\l"
	.string "{JPN}そんなこと いわずに おねがいだよ!$"

gText_ApprenticeWhichLevelMode9::
	.string "{JPN}おぅー! グッと くるね!\n"
	.string "{JPN}エクセレント!\p"
	.string "{JPN}では ファースト アドバイス たのむね!\n"
	.string "{JPN}バトルタワー なんだけどさ\l"
	.string "{JPN}おじさんが やるなら レベルは\l"
	.string "{JPN}50と オープン どっちが ベターかな?$"

gText_ApprenticeLevelModeThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\n"
	.string "{JPN}オーケイ オーケイ!\l"
	.string "{JPN}おじさん バーっと がんばって くるよ!\p"
	.string "{JPN}それじゃあ これからも よろしくね\n"
	.string "{JPN}アディオース!$"

gText_ApprenticePleaseTeach10::
	.string "{JPN}お おいっ {PLAYER}{KUN}だろ!\n"
	.string "{JPN}さっき おまわりさんが さがしてたぞ!\p"
	.string "{JPN}... ... ...\n"
	.string "{JPN}なんてね うっそ うそ!\p"
	.string "{JPN}おいらは {STR_VAR_1} って いうんだ\n"
	.string "{JPN}こうみえても ポケモンチャンピオンさ!\l"
	.string "{JPN}...て いうのも ウソ!\p"
	.string "{JPN}じつは おいら ポケモンしょうぶが\n"
	.string "{JPN}あんまり とくいじゃ なくてさ!\l"
	.string "{JPN}ひとつ どうだろ\l"
	.string "{JPN}おいらの ししょうに なってくれない かな?$"

gText_ApprenticeRejectTeaching10::
	.string "{JPN}そんな つめたい こと いうと\n"
	.string "{JPN}こうだぞ!\p"
	.string "{JPN}うえーん うえーん えーん えん えん\p"
	.string "{JPN}なんてね うそなき!\p"
	.string "{JPN}ね! いいだろ\n"
	.string "{JPN}おいらの ししょうに なって おくれよ!$"

gText_ApprenticeWhichLevelMode10::
	.string "{JPN}やったー!\n"
	.string "{JPN}おれいに ふねを かって あげよう!\p"
	.string "{JPN}なんて じょうだん だけど...\n"
	.string "{JPN}ししょう! よろしく たのむぜ!\p"
	.string "{JPN}あのさ バトルタワーで\n"
	.string "{JPN}レベル50と オープンレベルと あるだろ!\p"
	.string "{JPN}どっちで がんばれば いいか\n"
	.string "{JPN}まよってるんだよ...\l"
	.string "{JPN}ししょうが きめて くれないかな?$"

gText_ApprenticeLevelModeThanks10::
	.string "{JPN}そうか\n"
	.string "{JPN}{STR_VAR_1}が いいのね!\l"
	.string "{JPN}じゃあ ちがうほうに いこうっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ありがとう ししょう!\n"
	.string "{JPN}また あったら よろしくなー$"

gText_ApprenticePleaseTeach11::
	.string "{JPN}は·じ·め·ま·し·て!\n"
	.string "{JPN}はーい はじめまして!\l"
	.string "{JPN}わし ノリノリ ふなのり {STR_VAR_1}!\l"
	.string "{JPN}きみも じこしょうかい いってみようぜ!\p"
	.string "{JPN}ふん ふん なまえは {PLAYER}{KUN}!\n"
	.string "{JPN}ポケモン だいすきで\l"
	.string "{JPN}びみょうな おとしごろね!\p"
	.string "{JPN}じつは きみは わしが はなしかけた\n"
	.string "{JPN}ほんじつ 10にんめの トレーナーでーす!\p"
	.string "{JPN}この であいを きねんして\n"
	.string "{JPN}ぜひとも わしを でしに してください!$"

gText_ApprenticeRejectTeaching11::
	.string "{JPN}そんな!\n"
	.string "{JPN}ノリが わるいじゃ ないか!\p"
	.string "{JPN}な いいじゃ ないか\n"
	.string "{JPN}ぜひとも わしを でしに してください!$"

gText_ApprenticeWhichLevelMode11::
	.string "{JPN}ようよう! ノリが いいね!\n"
	.string "{JPN}{PLAYER}さん よろしく たのみますよ!\p"
	.string "{JPN}それじゃあ 1つめの しつもん\n"
	.string "{JPN}いってみようぜ!\l"
	.string "{JPN}バトルタワーに かんする しつもんだ!\p"
	.string "{JPN}レベル50のへやと オープンレベルのへや\n"
	.string "{JPN}わしが いくなら さあ どっち?$"

gText_ApprenticeLevelModeThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで いってみるぜ!\p"
	.string "{JPN}これからも ヨロシク たのむぜ\n"
	.string "{JPN}{PLAYER}さん!$"

gText_ApprenticePleaseTeach12::
	.string "{JPN}ヒャホー {PLAYER}さんじゃなーい!?\n"
	.string "{JPN}どうする オレ? はなしかけてみる!?\l"
	.string "{JPN}ってもう はなし してるよ!!\p"
	.string "{JPN}って {PLAYER}さん あきれてる!?\n"
	.string "{JPN}しかたねー じこしょうかい してみる!?\p"
	.string "{JPN}オスっ オレっ {STR_VAR_1}!\n"
	.string "{JPN}ポケモン ギタリストかいの 1ばんぼしさ!\p"
	.string "{JPN}って きいてる!? きいてる!!\n"
	.string "{JPN}ついでに たのみごと してみる!?\p"
	.string "{JPN}あの {PLAYER}さん!\n"
	.string "{JPN}オレを {PLAYER}さんの でしに して!$"

gText_ApprenticeRejectTeaching12::
	.string "{JPN}って ことわられてる オレっ!?\n"
	.string "{JPN}しかたねー もういちど たのんでみる!?\p"
	.string "{JPN}おねがい だよ {PLAYER}さん!\n"
	.string "{JPN}オレを でしに してエェ!!$"

gText_ApprenticeWhichLevelMode12::
	.string "{JPN}やったラッキー うれしーよ オレ!!\n"
	.string "{JPN}さっそく なんか そうだんしてみる!?\l"
	.string "{JPN}しかも ここは バトルタワー だから\l"
	.string "{JPN}そのへん から きいてみる!?\p"
	.string "{JPN}あのさっ! バトルタワーで オレ\n"
	.string "{JPN}どっちの レベルが にあってる!?$"

gText_ApprenticeLevelModeThanks12::
	.string "{JPN}{STR_VAR_1}だって!\n"
	.string "{JPN}じゃ そこ いってみるよ!!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}また あおうぜ!!$"

gText_ApprenticePleaseTeach13::
	.string "{JPN}あ... きみきみ!\n"
	.string "{JPN}ちょっとさ かた もんでくれる?\p"
	.string "{JPN}...ああ そうそう そこそこ\n"
	.string "{JPN}はー きもちいい!\p"
	.string "{JPN}おれ {STR_VAR_1} って いうんだ\n"
	.string "{JPN}カラテ やってるんだけど\l"
	.string "{JPN}いまいち からだが よわくてさ...\p"
	.string "{JPN}ポケモンしょうぶも やって\n"
	.string "{JPN}きたえようと おもって いるんだよね\p"
	.string "{JPN}きみ ポケモンリーグで かった\n"
	.string "{JPN}{PLAYER}{KUN} だろう?\l"
	.string "{JPN}どうかな たまに おれの\l"
	.string "{JPN}そうだんに のって もらえない かい?$"

gText_ApprenticeRejectTeaching13::
	.string "{JPN}えー なんで!\p"
	.string "{JPN}そんなに めんどうは かけないからさ\n"
	.string "{JPN}おねがいだよ!$"

gText_ApprenticeWhichLevelMode13::
	.string "{JPN}ありがとう わるいね\n"
	.string "{JPN}...ゴホ ゴホっ!\p"
	.string "{JPN}うう はやく きたえなきゃ...\n"
	.string "{JPN}すぐに バトルタワーに いくから\l"
	.string "{JPN}レベル50のへや オープンレベルのへや\l"
	.string "{JPN}どっちが いいか きめてくれるかい?$"

gText_ApprenticeLevelModeThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\n"
	.string "{JPN}じゃあ さっそく いってくる!\p"
	.string "{JPN}これからも おれを よろしく たのむよ!\n"
	.string "{JPN}もう でしいり したんだからな!$"

gText_ApprenticePleaseTeach14::
	.string "{JPN}あ... あ...\n"
	.string "{JPN}{PLAYER}{KUN} だよね?\l"
	.string "{JPN}そ そんなに みないで くれよ!\l"
	.string "{JPN}てれるだろ\p"
	.string "{JPN}ワシは {STR_VAR_1}と いって\n"
	.string "{JPN}は はずかしい けど\l"
	.string "{JPN}いせきを さがしたり して くらしてるんだ\p"
	.string "{JPN}でも バトルフロンティア にも\n"
	.string "{JPN}はずかしながら き きょうみが あるんだ\p"
	.string "{JPN}{PLAYER}{KUN}は ポケモン つよいって\n"
	.string "{JPN}ひょうばん だから...\l"
	.string "{JPN}その いいづらいん だけど\l"
	.string "{JPN}ひとつ おねがいを したいんだ\p"
	.string "{JPN}ワシの せんせいに なって\n"
	.string "{JPN}アドバイスして もらえない かな...?$"

gText_ApprenticeRejectTeaching14::
	.string "{JPN}こ ことわらないでくれ!\n"
	.string "{JPN}ワシに はじを かかせないで くれ!\p"
	.string "{JPN}おねがい だから\n"
	.string "{JPN}ワシの せんせいに なってくれ!$"

gText_ApprenticeWhichLevelMode14::
	.string "{JPN}あ ありがとう...\p"
	.string "{JPN}いや だから そんなに みないで くれよ\n"
	.string "{JPN}てれるだろ\p"
	.string "{JPN}めを あわせずに こたえて くれ!\p"
	.string "{JPN}ば バトルタワ... バトルタワー だが\n"
	.string "{JPN}どの レベルに ちょうせん すれば いい?$"

gText_ApprenticeLevelModeThanks14::
	.string "{JPN}よ よし!\n"
	.string "{JPN}それで がんばって みるよ\p"
	.string "{JPN}うう はずかし がらずに\n"
	.string "{JPN}がんばれる かな...?\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}また こんど あえたら... よろしくね$"

gText_ApprenticePleaseTeach15::
	.string "{JPN}ん?\n"
	.string "{JPN}{PLAYER}{KUN}の ように みえるが...\l"
	.string "{JPN}ほんもの なのかね?\p"
	.string "{JPN}わたしは {STR_VAR_1}だ\n"
	.string "{JPN}いまね だれか つよい トレーナーに\l"
	.string "{JPN}でしいり したいと おもって いたんだよ\p"
	.string "{JPN}きみが いるなら よかった!\n"
	.string "{JPN}...ほんとうに {PLAYER}{KUN} だよね?\p"
	.string "{JPN}いや ほんもの なら いいんだ\n"
	.string "{JPN}わたしの でしいりを みとめて ほしい$"

gText_ApprenticeRejectTeaching15::
	.string "{JPN}え? なぜ ことわるのかね?\p"
	.string "{JPN}ほんものか どうか うたがって わるかった\n"
	.string "{JPN}あやまるから でしいり させてほしい$"

gText_ApprenticeWhichLevelMode15::
	.string "{JPN}ほんとうに みとめて くれるのかね?\n"
	.string "{JPN}ぬかよろこびは したく ないからな\p"
	.string "{JPN}いや ほんとうなら いいんだ わるかった\n"
	.string "{JPN}さっそく そうだんに のってほしい\p"
	.string "{JPN}わたしが バトルタワーに でるなら\n"
	.string "{JPN}レベル50... オープンレベル...\l"
	.string "{JPN}どちらの ほうが ふさわしいと おもうかね$"

gText_ApprenticeLevelModeThanks15::
	.string "{JPN}{STR_VAR_1}... ほんとうかね?\p"
	.string "{JPN}いや ほんとう なら いいんだ\n"
	.string "{JPN}どうも ありがとう\p"
	.string "{JPN}こんな わたし だが\n"
	.string "{JPN}でし として みとめて くれて うれしい\l"
	.string "{JPN}いずれまた あおう!$"

gText_ApprenticeWhatHeldItem0::
	.string "{JPN}はあ... シクシク\n"
	.string "{JPN}ああっ {PLAYER}さん!\p"
	.string "{JPN}ぼくね きめられない ことが あって\n"
	.string "{JPN}ちょっと こまってたんです\p"
	.string "{JPN}きめられない のは {STR_VAR_1}に\n"
	.string "{JPN}なにを もたせるかって ことなんです\l"
	.string "{JPN}おしえて ください {PLAYER}さん\l"
	.string "{JPN}なにか もたせた ほうが いいですか?$"

gText_ApprenticeHoldNothing0::
	.string "{JPN}えっ... {STR_VAR_1}は\n"
	.string "{JPN}なにも もたないほうが いいんですか?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "{JPN}わっ わかりました!\n"
	.string "{JPN}きまって うれしいです うぉぉーん!\p"
	.string "{JPN}じゃあ ありがとう ございました!$"

gText_ApprenticeThanksHeldItem0::
	.string "{JPN}よ よかった\n"
	.string "{JPN}{STR_VAR_1}なら もってるかも...\l"
	.string "{JPN}きまって うれしいです うぉぉーん!\p"
	.string "{JPN}じゃあ ありがとう ございました!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "{JPN}うわーん! ひどいです\n"
	.string "{JPN}{STR_VAR_1}は もう\l"
	.string "{JPN}おしえてもらった どうぐ です グスン\p"
	.string "{JPN}それとも {STR_VAR_2}は\n"
	.string "{JPN}なにも もたないほうが いいんですか?$"

gText_ApprenticeWhatHeldItem1::
	.string "{JPN}わー {PLAYER}さん だ!\n"
	.string "{JPN}よかった! ききたい ことが あったんだ!\p"
	.string "{JPN}あのね {PLAYER}さんは\n"
	.string "{JPN}ポケモンに どうぐを もたせてる?\l"
	.string "{JPN}ボクも もたせたいんだけど...\p"
	.string "{JPN}ボクの {STR_VAR_1}には\n"
	.string "{JPN}なにを もたせたら いいのかな\l"
	.string "{JPN}{PLAYER}さんは どう おもう?$"

gText_ApprenticeHoldNothing1::
	.string "{JPN}えっ {STR_VAR_1}は\n"
	.string "{JPN}なにも もたせなくて いいって こと?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "{JPN}わかったー じゃあ そうするー!\n"
	.string "{JPN}せんせい ありがと!$"

gText_ApprenticeThanksHeldItem1::
	.string "{JPN}へええ! {STR_VAR_1}かー\n"
	.string "{JPN}じゃあ そうするー!\p"
	.string "{JPN}せんせい ありがと!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "{JPN}あ えっと そうじゃなくて\n"
	.string "{JPN}まだ おしえて もらってない どうぐで\l"
	.string "{JPN}なにが いいか しりたいんだ!\p"
	.string "{JPN}それとも こんどは\n"
	.string "{JPN}なにも もたせなくって いいのかな?$"

gText_ApprenticeWhatHeldItem2::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}ぼくの {STR_VAR_1}の ことなんだけど\p"
	.string "{JPN}なにか もちものを もたせたいんだ!\n"
	.string "{JPN}なにか いい もちもの おしえてください!$"

gText_ApprenticeHoldNothing2::
	.string "{JPN}じゃあ {STR_VAR_1}には\n"
	.string "{JPN}なにも もたせなくても いいんだね?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "{JPN}わかりました!\n"
	.string "{JPN}じゃあ また!$"

gText_ApprenticeThanksHeldItem2::
	.string "{JPN}{STR_VAR_1} ですか!\n"
	.string "{JPN}わかりました!\p"
	.string "{JPN}がんばって さがしてきます!\n"
	.string "{JPN}じゃあ また!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}まえに おしえて もらいましたよ\p"
	.string "{JPN}それとは ちがう もちものを\n"
	.string "{JPN}もたせたいんです\p"
	.string "{JPN}それとも {STR_VAR_2}には\n"
	.string "{JPN}なにも もたせなくて いいんだね?$"

gText_ApprenticeWhatHeldItem3::
	.string "{JPN}{PLAYER}さん こんにちは...\n"
	.string "{JPN}ごめんなさい きょうも あたし\l"
	.string "{JPN}ききたい ことが あるんです\p"
	.string "{JPN}あたしの ちから だけでは\n"
	.string "{JPN}しょうぶに かてないかも しれないから\l"
	.string "{JPN}なにか どうぐを {STR_VAR_1}に\l"
	.string "{JPN}もたせようかと おもって いるんです\l"
	.string "{JPN}でも なにが いいのか...\p"
	.string "{JPN}{PLAYER}さん おねがいします\n"
	.string "{JPN}あたしの かわりに きめてください!$"

gText_ApprenticeHoldNothing3::
	.string "{JPN}あの あたしなんかの ポケモンには\n"
	.string "{JPN}なにも もたせないほうが いいんですか?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "{JPN}わかりました...\n"
	.string "{JPN}どうぐに たよるなって ことですね?\l"
	.string "{JPN}がんばって みます!\p"
	.string "{JPN}ありがとう ございます!$"

gText_ApprenticeThanksHeldItem3::
	.string "{JPN}{STR_VAR_1} ですか!\n"
	.string "{JPN}あたしに みつけられるか...\l"
	.string "{JPN}いえ! がんばって みます\p"
	.string "{JPN}ありがとう ございます!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "{JPN}え... それは\n"
	.string "{JPN}まえに おしえて いただいたと おもいます\p"
	.string "{JPN}あ もしかして\n"
	.string "{JPN}あたしが {STR_VAR_1}を\l"
	.string "{JPN}つかいこなせて いないから ですか?\p"
	.string "{JPN}それとも {STR_VAR_2}には なにも\n"
	.string "{JPN}もたせるなと いう こと でしょうか?$"

gText_ApprenticeWhatHeldItem4::
	.string "{JPN}あら {PLAYER}{KUN}\n"
	.string "{JPN}ちょっと ききたい ことが あるのよ!\p"
	.string "{JPN}わたし ポケモンは きめて もらったけど\n"
	.string "{JPN}どの どうぐを もたせるか までは\l"
	.string "{JPN}きめて もらってない じゃない?\p"
	.string "{JPN}どうせ なら さいごまで\n"
	.string "{JPN}あなたが きめて くれない?\l"
	.string "{JPN}ねえ なにが いいかしら?\l"
	.string "{JPN}{STR_VAR_1}に もたせたいの!$"

gText_ApprenticeHoldNothing4::
	.string "{JPN}あら! {STR_VAR_1}は\n"
	.string "{JPN}てぶらで がんばれ って ことかしら?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "{JPN}それが よければ そうするわ!\n"
	.string "{JPN}{PLAYER}{KUN}が きめた って おもえば\l"
	.string "{JPN}まけても きが らくだわ!\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}また そうだんに のってね!$"

gText_ApprenticeThanksHeldItem4::
	.string "{JPN}{STR_VAR_1}か\n"
	.string "{JPN}わるく ないわね そうするわ!\l"
	.string "{JPN}{PLAYER}{KUN}が きめた って おもえば\l"
	.string "{JPN}まけても きが らくだわ!\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}また そうだんに のってね!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "{JPN}えっ なに いってるのよ\n"
	.string "{JPN}{STR_VAR_1}は もう\l"
	.string "{JPN}おしえて もらった じゃない!\p"
	.string "{JPN}それとも {STR_VAR_2}は\n"
	.string "{JPN}てぶらで がんばれ って ことかしら?$"

gText_ApprenticeWhatHeldItem5::
	.string "{JPN}よっ {PLAYER}{KUN}\n"
	.string "{JPN}いそがしい わりには よく あうよね!\l"
	.string "{JPN}オレは きょうは\l"
	.string "{JPN}ウォーキング クリーニング それに\l"
	.string "{JPN}ブラッシングと たいへん そのものさ!\p"
	.string "{JPN}おかげで だいじな {STR_VAR_1}にも\n"
	.string "{JPN}どうぐ さえ かって やれなくてねー\p"
	.string "{JPN}あのさ! じかんも ないから\n"
	.string "{JPN}なにを {STR_VAR_1}に\l"
	.string "{JPN}もたせて やったら いいか\l"
	.string "{JPN}それだけでも アドバイス してよ!$"

gText_ApprenticeHoldNothing5::
	.string "{JPN}おっ それじゃ\n"
	.string "{JPN}いそがしい オレの {STR_VAR_1}は\l"
	.string "{JPN}なにも もたなくて イイ ってこと?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "{JPN}オーケー わかった!\n"
	.string "{JPN}それ なら じかんも いらないぜ\p"
	.string "{JPN}きょうは サンキュー! じゃ またな!$"

gText_ApprenticeThanksHeldItem5::
	.string "{JPN}オーケー わかった!\n"
	.string "{JPN}じゃ なんとか じかん つくって\l"
	.string "{JPN}{STR_VAR_1}を さがすぜ!\p"
	.string "{JPN}オレは いい せんせいに であえたよな\n"
	.string "{JPN}サンキュー! じゃ またな!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "{JPN}あれっ {STR_VAR_1}は\n"
	.string "{JPN}もう しってるよ!\p"
	.string "{JPN}ん? それとも\n"
	.string "{JPN}いそがしい オレの {STR_VAR_2}は\l"
	.string "{JPN}なにも もたなくて イイ ってこと?$"

gText_ApprenticeWhatHeldItem6::
	.string "{JPN}よぅ {PLAYER}さん わたしだよ!\n"
	.string "{JPN}きょうも ひとつ そうだんが あるの\l"
	.string "{JPN}アドバイス おねがい ねっ!\p"
	.string "{JPN}ジャーン では そうだんです!\n"
	.string "{JPN}わたしの {STR_VAR_1}に\l"
	.string "{JPN}なにか どうぐを もたせるなら\l"
	.string "{JPN}いったい なにに したら いいかな?$"

gText_ApprenticeHoldNothing6::
	.string "{JPN}ふーん? {STR_VAR_1}は\n"
	.string "{JPN}もちものは いらないって ことかな?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "{JPN}じゃ そうするね!\p"
	.string "{JPN}ん きょうは こんなところ かな\n"
	.string "{JPN}こんど また ここで あおうね!\l"
	.string "{JPN}ありがと!$"

gText_ApprenticeThanksHeldItem6::
	.string "{JPN}ははぁーん!\n"
	.string "{JPN}{STR_VAR_1}とは シブイわぁ\l"
	.string "{JPN}ぜひ そうして みるね!\p"
	.string "{JPN}ん きょうは こんなところ かな\n"
	.string "{JPN}こんど また ここで あおうね!\l"
	.string "{JPN}ありがと!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "{JPN}あっはは やだぁ\n"
	.string "{JPN}{STR_VAR_1}は もう\l"
	.string "{JPN}おしえて もらった じゃない!\l"
	.string "{JPN}{PLAYER}さん だいじょぶ?\p"
	.string "{JPN}あ! それとも {STR_VAR_2}は\n"
	.string "{JPN}もちものは いらないって ことかな?$"

gText_ApprenticeWhatHeldItem7::
	.string "{JPN}ごきげん いかがですか {PLAYER}さん\n"
	.string "{JPN}きいて くださる?\p"
	.string "{JPN}このまえ たたかった トレーナーさん\n"
	.string "{JPN}ポケモンに なにか どうぐを\l"
	.string "{JPN}もたせていた らしいんですの\p"
	.string "{JPN}おかげで まけて しまいましたわ...\p"
	.string "{JPN}わたくしも まけずに なにか\n"
	.string "{JPN}{STR_VAR_1}に もたせたいんですの!\l"
	.string "{JPN}なにが よろしいの でしょう\l"
	.string "{JPN}きめて いただければ うれしいのですが...$"

gText_ApprenticeHoldNothing7::
	.string "{JPN}それは つまり... どうぐは\n"
	.string "{JPN}もたせなくて よろしいんですのね?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "{JPN}わかりましたわ!\n"
	.string "{JPN}このまま がんばる ことに しますわ\p"
	.string "{JPN}それでは {PLAYER}さん\n"
	.string "{JPN}これからも よろしく おねがいしますわ\l"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticeThanksHeldItem7::
	.string "{JPN}{STR_VAR_1} ですのね!\n"
	.string "{JPN}さっそく とりよせますわ!\p"
	.string "{JPN}それでは {PLAYER}さん\n"
	.string "{JPN}これからも よろしく おねがいしますわ\l"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "{JPN}それは もう おしえて いただいて\n"
	.string "{JPN}わたくし もっておりますわ!\p"
	.string "{JPN}それとも... {STR_VAR_2}には\n"
	.string "{JPN}なにも もたせないで よろしいと...?$"

gText_ApprenticeWhatHeldItem8::
	.string "{JPN}{PLAYER}さんっ!\n"
	.string "{JPN}きょうも あえて かんげき ですっ...!\p"
	.string "{JPN}そそそそそ そうだっ!\n"
	.string "{JPN}あのっ {PLAYER}さんに\l"
	.string "{JPN}きめて ほしいことが あるのですっ!\p"
	.string "{JPN}わたしの {STR_VAR_1}には\n"
	.string "{JPN}なにを もたせれば いいですかっ?$"

gText_ApprenticeHoldNothing8::
	.string "{JPN}うわあぁっ いがいな おこたえだあ!\n"
	.string "{JPN}つまり なにも いらないの ですねっ?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "{JPN}りょうかいで ありますっ!\n"
	.string "{JPN}どうぐ なしで がんばるで あります!\p"
	.string "{JPN}では また こんど\n"
	.string "{JPN}いろいろと おしえて くださいね!$"

gText_ApprenticeThanksHeldItem8::
	.string "{JPN}{STR_VAR_1} ですねっ!\n"
	.string "{JPN}これって これって {PLAYER}さんと\l"
	.string "{JPN}もしかして おそろい だったりしてっ!\p"
	.string "{JPN}もー ぜったい もたせちゃいます!\n"
	.string "{JPN}では また こんど\l"
	.string "{JPN}いろいろと おしえて くださいね!$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "{JPN}あれ まえにも {STR_VAR_1}を\n"
	.string "{JPN}おすすめして くれました よね!\p"
	.string "{JPN}やっぱり コレが いちばん ですかっ?\n"
	.string "{JPN}あ それとも もしかして\l"
	.string "{JPN}{STR_VAR_2}には なにも\l"
	.string "{JPN}もたせなくて いいって ことですかっ?$"

gText_ApprenticeWhatHeldItem9::
	.string "{JPN}ハロウ ハローウ\n"
	.string "{JPN}マイ ティーチャー {PLAYER}{KUN}!\p"
	.string "{JPN}きょうは ポケモンの どうぐに ついて\n"
	.string "{JPN}アドバイスを おねがい したいんだ!\p"
	.string "{JPN}おじさんの {STR_VAR_1}には\n"
	.string "{JPN}どんな どうぐを もたせれば いいかな?\l"
	.string "{JPN}パーっと きめちゃって くれ!$"

gText_ApprenticeHoldNothing9::
	.string "{JPN}おっと それは\n"
	.string "{JPN}{STR_VAR_1}は なにも もたせずとも\l"
	.string "{JPN}かてる っていう こと なのかな?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "{JPN}オーケイ オーケイ!\n"
	.string "{JPN}おじさん グーっと がんばるよ!\p"
	.string "{JPN}それじゃあ これからも よろしくね\n"
	.string "{JPN}アディオース!$"

gText_ApprenticeThanksHeldItem9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\n"
	.string "{JPN}オーケイ オーケイ!\l"
	.string "{JPN}おじさん ゴーっと さがして くるよ!\p"
	.string "{JPN}それじゃあ これからも よろしくね\n"
	.string "{JPN}アディオース!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "{JPN}ノンノン! {STR_VAR_1}は\n"
	.string "{JPN}まえに おしえて もらったよ!\p"
	.string "{JPN}お それとも もしや\n"
	.string "{JPN}{STR_VAR_2}は なにも もたせずとも\l"
	.string "{JPN}かてる っていう こと なのかな?$"

gText_ApprenticeWhatHeldItem10::
	.string "{JPN}{PLAYER}{KUN} ちょっと\n"
	.string "{JPN}しんじられん ことが おきた!\p"
	.string "{JPN}けさ おきたら ポケモンが\n"
	.string "{JPN}きんのたまを 10コ もってたんだ!\l"
	.string "{JPN}... なーんて うっそさ! うわはは!\p"
	.string "{JPN}じつは おいら ポケモンの どうぐを\n"
	.string "{JPN}かんがえる こと なんて\l"
	.string "{JPN}あんまり とくいじゃ なくてさ!\l"
	.string "{JPN}ひとつ どうだろ おいらの {STR_VAR_1}\l"
	.string "{JPN}なにを もたせたら いいのか\l"
	.string "{JPN}ししょうが きめて くれない かな?$"

gText_ApprenticeHoldNothing10::
	.string "{JPN}どういう ことかな?\n"
	.string "{JPN}なにも もたせなくて いいんだな?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "{JPN}そうか てぶらで いいのね!\n"
	.string "{JPN}じゃあ なにか もたせようっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ありがとう ししょう!\n"
	.string "{JPN}また あったら よろしくなー$"

gText_ApprenticeThanksHeldItem10::
	.string "{JPN}そうか\n"
	.string "{JPN}{STR_VAR_1}が いいのね!\l"
	.string "{JPN}じゃあ それだけは やめとこっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ありがとう ししょう!\n"
	.string "{JPN}また あったら よろしくなー$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "{JPN}あー それは いちど\n"
	.string "{JPN}おしえて もらったことが あるだろ?\l"
	.string "{JPN}ちがうので なにか ないかな?\p"
	.string "{JPN}それとも {STR_VAR_2}は\n"
	.string "{JPN}なにも もたせなくて いいのかな?$"

gText_ApprenticeWhatHeldItem11::
	.string "{JPN}こ·ん·に·ち·は!\n"
	.string "{JPN}はーい こんにちは!\l"
	.string "{JPN}ノリノリ ふなのりの わしが おくる\l"
	.string "{JPN}そうだんタイム いってみよう!\l"
	.string "{JPN}どうぐに かんする そうだんだよ!\p"
	.string "{JPN}わしの {STR_VAR_1}に もたせるなら\n"
	.string "{JPN}さあ どんな どうぐがいい?$"

gText_ApprenticeHoldNothing11::
	.string "{JPN}それは あれかな? {STR_VAR_1}は\n"
	.string "{JPN}なんにも もたなくて いいのかな?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "{JPN}そうかーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで てぶらでいくぜ!\p"
	.string "{JPN}これからも ヨロシク たのむぜ\n"
	.string "{JPN}{PLAYER}さん!$"

gText_ApprenticeThanksHeldItem11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで もたせてみるぜ!\p"
	.string "{JPN}これからも ヨロシク たのむぜ\n"
	.string "{JPN}{PLAYER}さん!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{JPN}{STR_VAR_1}かーっ! おいおい!\n"
	.string "{JPN}それなら きいたことが あるぜ!\l"
	.string "{JPN}なんか ちがうやつを たのむぜ!\p"
	.string "{JPN}それとも あれかな?\n"
	.string "{JPN}なにも もたせなくて いいのかな?$"

gText_ApprenticeWhatHeldItem12::
	.string "{JPN}オッケ {PLAYER}さん!\n"
	.string "{JPN}きょうも みつけたぜェ!\l"
	.string "{JPN}どうする オレ? そうだんしてみる!?\l"
	.string "{JPN}って もう はなしかけてる!?\p"
	.string "{JPN}って {PLAYER}さん オレのこと そろそろ\n"
	.string "{JPN}きらいに なってる!? なってない!!\l"
	.string "{JPN}そうだんが あるんだけど きいてェ!\p"
	.string "{JPN}オレの {STR_VAR_1} なんだけど\n"
	.string "{JPN}いい どうぐを もたせたいんだ!\l"
	.string "{JPN}なにが いいか さあ きめて!$"

gText_ApprenticeHoldNothing12::
	.string "{JPN}エェ!? じゃあ {STR_VAR_1}には\n"
	.string "{JPN}なにも もたせなくて いいって こと!?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "{JPN}もたせないってエェ!\n"
	.string "{JPN}じゃ いうとおりに するよ!!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}また あおうぜ!!$"

gText_ApprenticeThanksHeldItem12::
	.string "{JPN}{STR_VAR_1}だってエェ!\n"
	.string "{JPN}じゃ さっそく もたせてみるよ!!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}また あおうぜ!!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "{JPN}ちょっと まったァ!\n"
	.string "{JPN}その {STR_VAR_1}って\l"
	.string "{JPN}まえに きいたことが ある!? ある!!\p"
	.string "{JPN}ほかのを おしえて!\n"
	.string "{JPN}それとも {STR_VAR_2}には\l"
	.string "{JPN}なにも もたせなくて いいって こと!?$"

gText_ApprenticeWhatHeldItem13::
	.string "{JPN}ギャッ いててっ! {PLAYER}{KUN}\n"
	.string "{JPN}うでが おれてるから さわらないでよ!\p"
	.string "{JPN}ポケモンに なにを もたせるか\n"
	.string "{JPN}じぶんで いろいろ ためしすぎちゃって\l"
	.string "{JPN}うでが おれちゃったん だよね きっと!\p"
	.string "{JPN}というわけ だからさ\n"
	.string "{JPN}かわりに きめて くれよ!\p"
	.string "{JPN}{PLAYER}{KUN}はさ おれの {STR_VAR_1}\n"
	.string "{JPN}どんな どうぐ もたせたら いいとおもう?$"

gText_ApprenticeHoldNothing13::
	.string "{JPN}いてて... えーっと それって\n"
	.string "{JPN}{STR_VAR_1}には なにも もたせなくて\l"
	.string "{JPN}いいって ことかな?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "{JPN}ん わかった\n"
	.string "{JPN}おれも いまは そのほうが たすかるよ!\p"
	.string "{JPN}これからも おれを よろしく たのむよ!$"

gText_ApprenticeThanksHeldItem13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\n"
	.string "{JPN}じゃあ ポケモンの うでは ぶじだから\l"
	.string "{JPN}さっそく もたせてみるよ!\p"
	.string "{JPN}これからも おれを よろしく たのむよ!$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "{JPN}いやいや {STR_VAR_1}は\n"
	.string "{JPN}このあいだ おしえて くれただろ?\l"
	.string "{JPN}もっと すごいの おしえてくれよ!\p"
	.string "{JPN}あ それとも\n"
	.string "{JPN}{STR_VAR_2}には なにも もたせなくて\l"
	.string "{JPN}いいって ことかな?$"

gText_ApprenticeWhatHeldItem14::
	.string "{JPN}あ... あ...\n"
	.string "{JPN}{PLAYER}{KUN}...\p"
	.string "{JPN}そ そんなに みないで くれよ\n"
	.string "{JPN}ワシの ポケモン なにも もってないからさ\p"
	.string "{JPN}ちょっと... そうだん させて くれよ\n"
	.string "{JPN}は はずかしいん だけどさ!\l"
	.string "{JPN}{STR_VAR_1}が なにを\l"
	.string "{JPN}もったら つよいか って なやんでてさ\l"
	.string "{JPN}{PLAYER}{KUN} なにが いいと おもう?$"

gText_ApprenticeHoldNothing14::
	.string "{JPN}じゃ... {STR_VAR_1}は なにも\n"
	.string "{JPN}もたない ほうが いいの かな...?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "{JPN}よ よし!\n"
	.string "{JPN}どうぐ なしで いくよ!\p"
	.string "{JPN}うう てれるな\n"
	.string "{JPN}かっこ よすぎない かな...?\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}また こんど あえたら... よろしくね$"

gText_ApprenticeThanksHeldItem14::
	.string "{JPN}よ よし!\n"
	.string "{JPN}{STR_VAR_1}に してみるよ\p"
	.string "{JPN}うう てれるな\n"
	.string "{JPN}かっこ よすぎない かな...?\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}また こんど あえたら... よろしくね$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "{JPN}それは も もう きいた じゃないか\p"
	.string "{JPN}て てを ぬかないでくれ!\n"
	.string "{JPN}ワシに はじを かかせないで くれ!\p"
	.string "{JPN}あ... それとも\n"
	.string "{JPN}{STR_VAR_2}は なにも\l"
	.string "{JPN}もたない ほうが いいの かな...?$"

gText_ApprenticeWhatHeldItem15::
	.string "{JPN}ん?\n"
	.string "{JPN}{PLAYER}{KUN}の ように みえるが...\l"
	.string "{JPN}ほんもの なのかね?\l"
	.string "{JPN}ふたごの きょうだい って ことは?\p"
	.string "{JPN}あっ いやいや いやいや!\n"
	.string "{JPN}ほんもの なら いいんだ わすれてくれ!\l"
	.string "{JPN}さらに じょげんを おねがい したい!\p"
	.string "{JPN}この わたしの {STR_VAR_1}!\n"
	.string "{JPN}なにか べんりな どうぐを もたせたい\l"
	.string "{JPN}いったい どれが ふさわしい かな?$"

gText_ApprenticeHoldNothing15::
	.string "{JPN}なにも もたない ほうが いい...?\n"
	.string "{JPN}ほんとうかね?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "{JPN}いや そうか なら いいんだ\n"
	.string "{JPN}どうも ありがとう\p"
	.string "{JPN}では いずれまた あおう!$"

gText_ApprenticeThanksHeldItem15::
	.string "{JPN}{STR_VAR_1}... ほんとうかね?\p"
	.string "{JPN}いや ほんとう なら いいんだ\n"
	.string "{JPN}どうも ありがとう\l"
	.string "{JPN}こんな わたしの ポケモンでも\l"
	.string "{JPN}つかいこなせると いいな\p"
	.string "{JPN}では いずれまた あおう!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "{JPN}いやいや まってくれ\n"
	.string "{JPN}それは まえに おしえてくれた だろう\l"
	.string "{JPN}それとは ちがった ものを\l"
	.string "{JPN}すすめられて みたいんだ\p"
	.string "{JPN}それとも {STR_VAR_2}は\n"
	.string "{JPN}なにも もたない ほうが いい...?\l"
	.string "{JPN}ほんとうかね?$"

gText_ApprenticeWhichMonFirst0::
	.string "{JPN}えーん {PLAYER}さーん!\n"
	.string "{JPN}ぼく こまって いるんです グスン\p"
	.string "{JPN}そろそろ しょうぶを して みたいけど\n"
	.string "{JPN}ポケモンを どんな じゅんばんで\l"
	.string "{JPN}だしたら つよいのか わかんない...\p"
	.string "{JPN}{PLAYER}さん だったら\n"
	.string "{JPN}どの ポケモンを さいしょに だすか\l"
	.string "{JPN}...おしえて ください!$"

gText_ApprenticeMonFirstThanks0::
	.string "{JPN}{STR_VAR_1} ですね! うぅ うわーん!\p"
	.string "{JPN}あ! ごめんなさい\n"
	.string "{JPN}じゅんばんが きまった うれしさで\l"
	.string "{JPN}なみだが...\p"
	.string "{JPN}じゃあ ありがとう ございました!$"

gText_ApprenticeWhichMonFirst1::
	.string "{JPN}わわっ! {PLAYER}さんだー!\n"
	.string "{JPN}わーい あえて よかった\l"
	.string "{JPN}そうだん したいことが あるんだ!\p"
	.string "{JPN}あのね ぼくの もってる\n"
	.string "{JPN}ポケモン たちの なかで\l"
	.string "{JPN}どれを さいしょに だせば\l"
	.string "{JPN}いいと おもう?$"

gText_ApprenticeMonFirstThanks1::
	.string "{JPN}{STR_VAR_1}かあ そーだよね!\n"
	.string "{JPN}じゃあ そうするー!\p"
	.string "{JPN}せんせい ありがと!$"

gText_ApprenticeWhichMonFirst2::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}しょうぶのときって さいしょに\p"
	.string "{JPN}どの ポケモンを だすのかが\n"
	.string "{JPN}とても だいじな きが するんです!\p"
	.string "{JPN}ぼくが もってる ポケモンの なかで\n"
	.string "{JPN}どの ポケモンを\l"
	.string "{JPN}さいしょに だすと いいでしょうか?$"

gText_ApprenticeMonFirstThanks2::
	.string "{JPN}{STR_VAR_1} ですね!\n"
	.string "{JPN}わかりました!\p"
	.string "{JPN}じゃあ また!$"

gText_ApprenticeWhichMonFirst3::
	.string "{JPN}{PLAYER}さん いつも\n"
	.string "{JPN}そうだん ばかりで すみません...\l"
	.string "{JPN}あたし じしんが なくって\l"
	.string "{JPN}{PLAYER}さんが いないと...!\p"
	.string "{JPN}あの ポケモンの じゅんばん って...\n"
	.string "{JPN}どうすれば いいと おもいますか?\p"
	.string "{JPN}あたし なんかが こだわっても\n"
	.string "{JPN}しかたが ないかも しれません けど\l"
	.string "{JPN}どうしても きめられなくて...\p"
	.string "{JPN}どの ポケモンを 1ばん\n"
	.string "{JPN}せんとうに すれば よいんでしょうか!$"

gText_ApprenticeMonFirstThanks3::
	.string "{JPN}{STR_VAR_1} ですか わかりました!\p"
	.string "{JPN}こんな あたし なんかに\n"
	.string "{JPN}なんども こたえて いただけるなんて\l"
	.string "{JPN}しんじられない!\p"
	.string "{JPN}きょうは あたしなんかの ために\n"
	.string "{JPN}ありがとう ございました...!$"

gText_ApprenticeWhichMonFirst4::
	.string "{JPN}{PLAYER}{KUN}! わたしよ\n"
	.string "{JPN}よかったわ こまっていたの!\p"
	.string "{JPN}ちょっと ポケモンの じゅんばんを\n"
	.string "{JPN}きめて もらえる かしら!\l"
	.string "{JPN}と いっても そうねえ\l"
	.string "{JPN}とりあえず 1ばんめの ポケモンで いいわ\l"
	.string "{JPN}どの ポケモンに したら いいかしら?$"

gText_ApprenticeMonFirstThanks4::
	.string "{JPN}{STR_VAR_1}ね いいわ!\n"
	.string "{JPN}{PLAYER}{KUN}が きめた って おもえば\l"
	.string "{JPN}まけても きが らくだわ!\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}また そうだんに のってね!$"

gText_ApprenticeWhichMonFirst5::
	.string "{JPN}ハイ! オレの せんせい\n"
	.string "{JPN}{PLAYER}{KUN}!\p"
	.string "{JPN}きょうも いそがしいんだ オレ\n"
	.string "{JPN}サイクリングに ショッピングに ハミング!\p"
	.string "{JPN}しょうぶに つかう ポケモンの\n"
	.string "{JPN}じゅんばんさえ きめられなくてねー\p"
	.string "{JPN}あのさ!\n"
	.string "{JPN}ちょっと オレの ポケモン みてよ!\l"
	.string "{JPN}で どいつが はじめに でれば いいかな?$"

gText_ApprenticeMonFirstThanks5::
	.string "{JPN}オーケー わかった!\n"
	.string "{JPN}{STR_VAR_1}を せんとうに する\n"
	.string "{JPN}じかん くらいは あるぜ!\p"
	.string "{JPN}...と いけね かのじょが まってる!\n"
	.string "{JPN}サンキュー! じゃ またな!$"

gText_ApprenticeWhichMonFirst6::
	.string "{JPN}ヤッホー ハーイ {PLAYER}さーん\n"
	.string "{JPN}いつも つよそうな かおで あるいてるわね\p"
	.string "{JPN}ねえねえ! きょうも\n"
	.string "{JPN}あれ... おねがい! いいでしょ!\p"
	.string "{JPN}ジャーン では ほんじつの そうだん!\n"
	.string "{JPN}わたしが もっている ポケモン!\l"
	.string "{JPN}さあ どのコを いちばん\l"
	.string "{JPN}さいしょに だせば いいでしょう?$"

gText_ApprenticeMonFirstThanks6::
	.string "{JPN}ふむふむ!\n"
	.string "{JPN}{STR_VAR_1} ですねぇ?\l"
	.string "{JPN}シブイ おこたえ ありがとう!\p"
	.string "{JPN}ん きょうは こんなところ かな\n"
	.string "{JPN}こんど また ここで あおうね!\l"
	.string "{JPN}ありがと!$"

gText_ApprenticeWhichMonFirst7::
	.string "{JPN}はなしかけて くださって\n"
	.string "{JPN}ありがとう ございます {PLAYER}さん\p"
	.string "{JPN}その おやさしさに あまえて\n"
	.string "{JPN}きょうも そうだんが ありますの...\p"
	.string "{JPN}あの ポケモンの じゅんばんを\n"
	.string "{JPN}きめて いただきたいん ですの\p"
	.string "{JPN}さいしょに だす なら\n"
	.string "{JPN}どの ポケモンが よろしいでしょうか?$"

gText_ApprenticeMonFirstThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\n"
	.string "{JPN}すぐに ならびかえますわ!\p"
	.string "{JPN}それでは {PLAYER}さん\n"
	.string "{JPN}これからも よろしく おねがいしますわ\l"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticeWhichMonFirst8::
	.string "{JPN}キャーキャー!\n"
	.string "{JPN}{PLAYER} さーんっ!\l"
	.string "{JPN}きょうも あえて かんげきっ...!\p"
	.string "{JPN}わたしの ポケモンたち\n"
	.string "{JPN}つよく なりましたよ!\l"
	.string "{JPN}でも はじめに だす ポケモンで\l"
	.string "{JPN}かったり まけたり しちゃうんです\p"
	.string "{JPN}{PLAYER}さん おねがいが!\n"
	.string "{JPN}どのコを はじめに だしたら いいのか\l"
	.string "{JPN}ぜひ きめて ほしいのですっ!$"

gText_ApprenticeMonFirstThanks8::
	.string "{JPN}はあああ... しあわせすぎる\n"
	.string "{JPN}{PLAYER}さんに きめて もらうなんて!\l"
	.string "{JPN}りょうかいですっ! わたし\l"
	.string "{JPN}{STR_VAR_1}から いくで ありますっ!\p"
	.string "{JPN}では また こんど\n"
	.string "{JPN}いろいろと おしえて くださいね!$"

gText_ApprenticeWhichMonFirst9::
	.string "{JPN}ハローウ!\n"
	.string "{JPN}マイ ティーチャー {PLAYER}{KUN}\l"
	.string "{JPN}きょうも アドバイス バンバンたのむよ!\p"
	.string "{JPN}おじさん スリー ポケモンズで\n"
	.string "{JPN}ティームを つくったのは いいんだが\l"
	.string "{JPN}まだ じゅんばんが きまって ないんだよ\p"
	.string "{JPN}そこで! {PLAYER}{KUN}が\n"
	.string "{JPN}まず はじめに だす ポケモンを\l"
	.string "{JPN}ササーっと きめちゃって くれ!$"

gText_ApprenticeMonFirstThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\n"
	.string "{JPN}オーケイ オーケイ!\l"
	.string "{JPN}おじさん ガガーっと いれかえるよ!\p"
	.string "{JPN}それじゃあ これからも よろしくね\n"
	.string "{JPN}アディオース!$"

gText_ApprenticeWhichMonFirst10::
	.string "{JPN}{PLAYER}{KUN} きいてくれ たいへんだ!\n"
	.string "{JPN}おいらの ポケモンと きたら\l"
	.string "{JPN}3びき いっしょに とびだすんだよ!\l"
	.string "{JPN}...なんて わきゃ ないな わはは!\p"
	.string "{JPN}じつは おいら ポケモンの\n"
	.string "{JPN}じゅんばん なんて きめるの\l"
	.string "{JPN}あんまり とくいじゃ なくてさ!\l"
	.string "{JPN}ひとつ どうだろ おいらの ポケモン\l"
	.string "{JPN}どいつを さいしょに だしたら いいか\l"
	.string "{JPN}ししょうが きめて くれない かな?$"

gText_ApprenticeMonFirstThanks10::
	.string "{JPN}そうか\n"
	.string "{JPN}{STR_VAR_1}が いいのね!\l"
	.string "{JPN}じゃあ そいつだけは やめようっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ありがとう ししょう!\n"
	.string "{JPN}また あったら よろしくなー$"

gText_ApprenticeWhichMonFirst11::
	.string "{JPN}こ·ん·に·ち·は!\n"
	.string "{JPN}はーい こんにちは!\l"
	.string "{JPN}ノリノリ ふなのりの わしの\l"
	.string "{JPN}きょうの そうだん いってみようよ!\l"
	.string "{JPN}じゅんばんに かんする そうだんだよ!\p"
	.string "{JPN}こたえて! この なかで\n"
	.string "{JPN}せんとうに したい ポケモンは どれ?$"

gText_ApprenticeMonFirstThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで いれかえるぜ!\p"
	.string "{JPN}これからも ヨロシク たのむぜ\n"
	.string "{JPN}{PLAYER}さん!$"

gText_ApprenticeWhichMonFirst12::
	.string "{JPN}ヤァーフゥー {PLAYER}さんじゃーん?\n"
	.string "{JPN}どうする オレ? アレきいてみる!?\l"
	.string "{JPN}そうだんが あるんだけど きいてェ!\l"
	.string "{JPN}って きいてる!? きいてる!!\p"
	.string "{JPN}オレの ポケモンの うち どいつを\n"
	.string "{JPN}さいしょに だしたら いいか きめてエェ!$"

gText_ApprenticeMonFirstThanks12::
	.string "{JPN}{STR_VAR_1}だって! イエス!\n"
	.string "{JPN}じゃ そうしてみる!!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}また あおうぜ!!$"

gText_ApprenticeWhichMonFirst13::
	.string "{JPN}うう {PLAYER}{KUN} ...\n"
	.string "{JPN}おなか いたくってさ ちょっとまって...\p"
	.string "{JPN}...ああ なおってきた...\p"
	.string "{JPN}どの ポケモンを しょうぶのとき\n"
	.string "{JPN}さいしょに だすか なやんで いて\l"
	.string "{JPN}なやみ すぎちゃったん だよね きっと!\p"
	.string "{JPN}というわけ だからさ\n"
	.string "{JPN}かわりに きめて くれよ!\p"
	.string "{JPN}{PLAYER}{KUN}はさ おれの ポケモン\n"
	.string "{JPN}どれを さいしょに だせば\l"
	.string "{JPN}かてると おもうかい?$"

gText_ApprenticeMonFirstThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\n"
	.string "{JPN}じゃあ ごはんを たべたら\l"
	.string "{JPN}そういうふうに してみるよ!\p"
	.string "{JPN}これからも おれを よろしく たのむよ!$"

gText_ApprenticeWhichMonFirst14::
	.string "{JPN}あ... あ...\n"
	.string "{JPN}{PLAYER}{KUN} だよね?\l"
	.string "{JPN}そ そんなに みないで くれよ!\l"
	.string "{JPN}てれるだろ\l"
	.string "{JPN}ひとつ... そうだん させてよ\p"
	.string "{JPN}は はずかし ながら\n"
	.string "{JPN}ポケモン 3びき きまった けどさ\l"
	.string "{JPN}じゅんばんが きまらないんだよ\p"
	.string "{JPN}どの ポケモンを 1ばんめに\n"
	.string "{JPN}だせば かっこが つくの かな...?$"

gText_ApprenticeMonFirstThanks14::
	.string "{JPN}よ よし!\n"
	.string "{JPN}{STR_VAR_1}から だして みるよ\p"
	.string "{JPN}うう はずかし がらずに\n"
	.string "{JPN}がんばれる かな...?\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}また こんど あえたら... よろしくね$"

gText_ApprenticeWhichMonFirst15::
	.string "{JPN}ん?\n"
	.string "{JPN}{PLAYER}{KUN}の ように みえるが...\l"
	.string "{JPN}かげむしゃ って ことは ないだろうね\p"
	.string "{JPN}いやいやいや! ほんものなら いいんだ\n"
	.string "{JPN}おこらないで くれ!\l"
	.string "{JPN}そして じょげんを おねがい したい!\p"
	.string "{JPN}わたしの てもちの なかから\n"
	.string "{JPN}どのポケモンを しょうぶの はじめに\l"
	.string "{JPN}だせば いいのか おしえて ほしい$"

gText_ApprenticeMonFirstThanks15::
	.string "{JPN}{STR_VAR_1}...\n"
	.string "{JPN}うそでは ないだろうね?\p"
	.string "{JPN}いや ほんとう なら いいんだ\n"
	.string "{JPN}どうも ありがとう\l"
	.string "{JPN}こんな わたしだが がんばって みよう\p"
	.string "{JPN}では いずれまた あおう!$"

gText_ApprenticeWhichMon0::
	.string "{JPN}グスン...\n"
	.string "{JPN}あっ {PLAYER}さん!\l"
	.string "{JPN}ちょうど よかったよう\l"
	.string "{JPN}ぼく きめられない ことが あって...\p"
	.string "{JPN}あのね ポケモンをね\n"
	.string "{JPN}どっちを つかうか きめられないんです\p"
	.string "{JPN}{STR_VAR_1} と {STR_VAR_2}で\n"
	.string "{JPN}まよって いるんだけど...\l"
	.string "{JPN}{PLAYER}さんは どっち だったら\l"
	.string "{JPN}ぼくでも かてそう って おもいますか?$"

gText_ApprenticeMonThanks0::
	.string "{JPN}グスっ わ わかりました!\n"
	.string "{JPN}あ ごめんなさい うれしくて なみだが...\p"
	.string "{JPN}ぼく がんばって {STR_VAR_1}を\n"
	.string "{JPN}つかまえてみます!\p"
	.string "{JPN}じゃあ ありがとう ございました!$"

gText_ApprenticeWhichMon1::
	.string "{JPN}あっ! {PLAYER}さんだー!\n"
	.string "{JPN}わーい ちょうど よかった\l"
	.string "{JPN}きょうも ボクの そうだんに のってね!\p"
	.string "{JPN}あのね ボクね\n"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}の どっちを\l"
	.string "{JPN}つかうか まよっちゃったの\p"
	.string "{JPN}どっちを そだてようかなあ\n"
	.string "{JPN}{PLAYER}さんは どう おもう?$"

gText_ApprenticeMonThanks1::
	.string "{JPN}へえ\n"
	.string "{JPN}{STR_VAR_1}が いいのか!\l"
	.string "{JPN}じゃあ そうするー!\p"
	.string "{JPN}せんせい ありがと!$"

gText_ApprenticeWhichMon2::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}ちょっと しつもん させて ください!\p"
	.string "{JPN}{STR_VAR_1} と {STR_VAR_2} で\n"
	.string "{JPN}どっちを つかうか なやんでるんです!\p"
	.string "{JPN}どっちの ポケモンが\n"
	.string "{JPN}つよいと おもいますか?$"

gText_ApprenticeMonThanks2::
	.string "{JPN}{STR_VAR_1} ですね!\n"
	.string "{JPN}わかりました!\p"
	.string "{JPN}よし さっそく\n"
	.string "{JPN}つよい {STR_VAR_1}を つかまえるぞ!\p"
	.string "{JPN}じゃあ また!$"

gText_ApprenticeWhichMon3::
	.string "{JPN}{PLAYER}さん...!\n"
	.string "{JPN}あの あたしの ことなんて\l"
	.string "{JPN}どうせ わすれて しまいました よね\p"
	.string "{JPN}...それでも いいです から\n"
	.string "{JPN}そうだんに のって ください...\p"
	.string "{JPN}あたし そだてたい ポケモン ひとつ\n"
	.string "{JPN}じぶんで きめられなくって...\l"
	.string "{JPN}{STR_VAR_1} か {STR_VAR_2}\l"
	.string "{JPN}どちらかに する までは きまったけど\l"
	.string "{JPN}そこで まよってしまって...\p"
	.string "{JPN}{PLAYER}さん いやかも しれませんが\n"
	.string "{JPN}あたしの かわりに きめてください!$"

gText_ApprenticeMonThanks3::
	.string "{JPN}あたし なんかの いうこと\n"
	.string "{JPN}{STR_VAR_1}が きいて くれるか...\p"
	.string "{JPN}でも やって みます!\p"
	.string "{JPN}そのまえに つかまえられるか...\n"
	.string "{JPN}いえ! がんばって みます\p"
	.string "{JPN}ありがとう ございます!$"

gText_ApprenticeWhichMon4::
	.string "{JPN}{PLAYER}{KUN} よかった\n"
	.string "{JPN}さがしに いこうと おもってたのよ!\p"
	.string "{JPN}ねえ わたしが つかう ポケモン\n"
	.string "{JPN}あなたが きめて くれない?\p"
	.string "{JPN}そうね...\n"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}だったら\l"
	.string "{JPN}どっちが いいと おもう?$"

gText_ApprenticeMonThanks4::
	.string "{JPN}{STR_VAR_1}ね ありがと!\n"
	.string "{JPN}{PLAYER}{KUN}が きめた って おもえば\l"
	.string "{JPN}まけても きが らくだわ!\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}また そうだんに のってね!$"

gText_ApprenticeWhichMon5::
	.string "{JPN}あっれー\n"
	.string "{JPN}{PLAYER}{KUN} じゃない げんき?\l"
	.string "{JPN}オレは あいかわらず いそがしくてさ!\p"
	.string "{JPN}ポケモンも がんばりたいんだ けど\n"
	.string "{JPN}どいつを つかうかも きまんなくてねー\p"
	.string "{JPN}あのさ!\n"
	.string "{JPN}{STR_VAR_1}って つよそう じゃん?\l"
	.string "{JPN}でも {STR_VAR_2}も すてがたいよねー\p"
	.string "{JPN}{PLAYER}{KUN} アドバイス してよ!\n"
	.string "{JPN}どっちの ポケモンが イイかな?$"

gText_ApprenticeMonThanks5::
	.string "{JPN}オーケー わかった!\n"
	.string "{JPN}じゃ なんとか じかん つくって\l"
	.string "{JPN}{STR_VAR_1}を つかまえて みるぜ!\p"
	.string "{JPN}オレは いい せんせいに であえたよな\n"
	.string "{JPN}サンキュー! じゃ またな!$"

gText_ApprenticeWhichMon6::
	.string "{JPN}あっ わーい\n"
	.string "{JPN}{PLAYER}さん じゃない!\l"
	.string "{JPN}わたし さっそく ともだちに\l"
	.string "{JPN}しりあいだって じまん しちゃったよ!\p"
	.string "{JPN}ねえねえ きょうも アドバイス おねがい!\n"
	.string "{JPN}かんたんな こと だから ねっ!\p"
	.string "{JPN}ジャーン では しつもんです!\n"
	.string "{JPN}わたしが そだてる なら!\l"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2} さあどっち?$"

gText_ApprenticeMonThanks6::
	.string "{JPN}へっえー!\n"
	.string "{JPN}{STR_VAR_1} と きますかぁ!\l"
	.string "{JPN}シブイ おこたえ ありがとう!\p"
	.string "{JPN}ん きょうは こんなところ かな\n"
	.string "{JPN}こんど また ここで あおうね!\l"
	.string "{JPN}ありがと!$"

gText_ApprenticeWhichMon7::
	.string "{JPN}まあ {PLAYER}さんでは?\n"
	.string "{JPN}ごきげんよう...!\p"
	.string "{JPN}あなたに でしいり して わたくし\n"
	.string "{JPN}すこし じしんが ついて まいりました!\l"
	.string "{JPN}ポケモンを さっそく そだてたいと\l"
	.string "{JPN}おもって おりますの!\p"
	.string "{JPN}それでね {PLAYER}さんに\n"
	.string "{JPN}わたしの ポケモンを\l"
	.string "{JPN}きめていただく わけには まいりませんか?\p"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}...\n"
	.string "{JPN}どちらの ポケモンが よろしいでしょう?$"

gText_ApprenticeMonThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\n"
	.string "{JPN}さっそく さがして きますわ!\p"
	.string "{JPN}それでは {PLAYER}さん\n"
	.string "{JPN}これからも よろしく おねがいしますわ\l"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticeWhichMon8::
	.string "{JPN}キャー {PLAYER}さんに また あえた!\n"
	.string "{JPN}かっ かんげきっ...!\p"
	.string "{JPN}そそそ そうだわっ!\n"
	.string "{JPN}せっかく あえたん ですもの\l"
	.string "{JPN}この チャンスを のがす ては ないわっ!\p"
	.string "{JPN}{PLAYER}さん おねがいが!\n"
	.string "{JPN}わたしの ポケモンを きめて くださいっ!\p"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}と\n"
	.string "{JPN}どちらが いいか きめて ほしいのですっ!$"

gText_ApprenticeMonThanks8::
	.string "{JPN}うわぁぁ きめて もらっちゃったあ!\n"
	.string "{JPN}{STR_VAR_1} ですねっ!\l"
	.string "{JPN}がんばって そだてるで あります!\p"
	.string "{JPN}では また こんど\n"
	.string "{JPN}いろいろと おしえて くださいね!$"

gText_ApprenticeWhichMon9::
	.string "{JPN}ヘイ ヘイ {PLAYER}{KUN}!\n"
	.string "{JPN}おじさんの ポケモン ティーチャー!\p"
	.string "{JPN}ハロウ きみを さがしてたんだよ\n"
	.string "{JPN}アドバイスを おねがいするよ!\p"
	.string "{JPN}おじさんが つかう ポケモン\n"
	.string "{JPN}どっちが いいかな?\l"
	.string "{JPN}{STR_VAR_1}か {STR_VAR_2}か\l"
	.string "{JPN}パーっと きめちゃって くれ!$"

gText_ApprenticeMonThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\n"
	.string "{JPN}オーケイ オーケイ!\l"
	.string "{JPN}おじさん ガーっと つかまえて くるよ!\p"
	.string "{JPN}それじゃあ これからも よろしくね\n"
	.string "{JPN}アディオース!$"

gText_ApprenticeWhichMon10::
	.string "{JPN}{PLAYER}{KUN} たいへんだ たいへんだ!\n"
	.string "{JPN}まぼろしの ポケモン つかまえちゃった!\l"
	.string "{JPN}...なんて うそさ! わっはっは\p"
	.string "{JPN}じつは おいら ポケモン つかまえるの\n"
	.string "{JPN}あんまり とくいじゃ なくてさ!\l"
	.string "{JPN}ひとつ どうだろ おいらの ポケモン\l"
	.string "{JPN}どいつを つかまえたら いいか\l"
	.string "{JPN}ししょうが きめて くれない かな?\p"
	.string "{JPN}どっちが いいかな?\n"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}だと...$"

gText_ApprenticeMonThanks10::
	.string "{JPN}そうか\n"
	.string "{JPN}{STR_VAR_1}が いいのね!\l"
	.string "{JPN}じゃあ ちがうほうに しようっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ありがとう ししょう!\n"
	.string "{JPN}また あったら よろしくなー$"

gText_ApprenticeWhichMon11::
	.string "{JPN}こ·ん·に·ち·は!\n"
	.string "{JPN}はーい こんにちは!\l"
	.string "{JPN}ノリノリ ふなのりの わし\l"
	.string "{JPN}きみは とうぜん おぼえてるだろ?\p"
	.string "{JPN}きょうも わしの しつもん いってみよう!\n"
	.string "{JPN}ポケモンに かんする そうだんだよ!\p"
	.string "{JPN}{STR_VAR_1} と {STR_VAR_2}\n"
	.string "{JPN}わしが つかまえるなら さあ どっち?$"

gText_ApprenticeMonThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで さがしてくるぜ!\p"
	.string "{JPN}これからも ヨロシク たのむぜ\n"
	.string "{JPN}{PLAYER}さん!$"

gText_ApprenticeWhichMon12::
	.string "{JPN}ゥワォ {PLAYER}さんじゃなーい!?\n"
	.string "{JPN}どうする オレ? そうだんしてみる!?\l"
	.string "{JPN}って もう はなしかけてる!?\p"
	.string "{JPN}オスっ ひさしぶり ですっ!\n"
	.string "{JPN}そうだんが あるんだけど きいてェ!\l"
	.string "{JPN}って きいてる!? きいてる!!\l"
	.string "{JPN}オレの ポケモン なにに したらいいかな!\p"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}\n"
	.string "{JPN}どっちが いいか さあ きめて!$"

gText_ApprenticeMonThanks12::
	.string "{JPN}{STR_VAR_1}だってエェ!\n"
	.string "{JPN}じゃ さっそく さがしてみるよ!!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}また あおうぜ!!$"

gText_ApprenticeWhichMon13::
	.string "{JPN}{PLAYER}{KUN}かぁ\n"
	.string "{JPN}おれ あたま いたくてさ...\p"
	.string "{JPN}どの ポケモンに するか\n"
	.string "{JPN}なやみ すぎちゃったん だよね きっと\l"
	.string "{JPN}というわけ だからさ\l"
	.string "{JPN}かわりに きめて くれよ!\p"
	.string "{JPN}{PLAYER}{KUN}はさ おれの ポケモン\n"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2} だったら\l"
	.string "{JPN}どっちが あってると おもうかい?$"

gText_ApprenticeMonThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\n"
	.string "{JPN}じゃあ たいちょうの いいときに\l"
	.string "{JPN}さがしてみるよ!\p"
	.string "{JPN}これからも おれを よろしく たのむよ!$"

gText_ApprenticeWhichMon14::
	.string "{JPN}あ... あ...\n"
	.string "{JPN}{PLAYER}{KUN} だよね?\l"
	.string "{JPN}そ そんなに みないで くれよ!\l"
	.string "{JPN}てれるだろ\l"
	.string "{JPN}ちょっと... そうだん させて くれよ\p"
	.string "{JPN}は はずかしいん だけどさ!\n"
	.string "{JPN}つかいたい ポケモンで なやんでててさ\l"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}だったら\l"
	.string "{JPN}どっちを つかったら いい かな...?$"

gText_ApprenticeMonThanks14::
	.string "{JPN}よ よし!\n"
	.string "{JPN}{STR_VAR_1}で がんばって みるよ\p"
	.string "{JPN}うう はずかし がらずに\n"
	.string "{JPN}がんばれる かな...?\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}また こんど あえたら... よろしくね$"

gText_ApprenticeWhichMon15::
	.string "{JPN}ん?\n"
	.string "{JPN}{PLAYER}{KUN}の ように みえるが...\l"
	.string "{JPN}ほんもの なのかね?\p"
	.string "{JPN}いや ほんもの なら いいんだ\n"
	.string "{JPN}ついでに でしの わたしに\l"
	.string "{JPN}じょげんを おねがい したい!\p"
	.string "{JPN}わたしが つかう ポケモンの ことだが\n"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}であれば\l"
	.string "{JPN}どちらが わたしに ふさわしい かな?$"

gText_ApprenticeMonThanks15::
	.string "{JPN}{STR_VAR_1}... ほんとうかね?\p"
	.string "{JPN}いや ほんとう なら いいんだ\n"
	.string "{JPN}どうも ありがとう\l"
	.string "{JPN}こんな わたし でも\l"
	.string "{JPN}なんとか つかい こなせると いいな\p"
	.string "{JPN}では いずれまた あおう!$"

gText_ApprenticeWhichMove0::
	.string "{JPN}うわーん {PLAYER}さんだ!\n"
	.string "{JPN}ぐすん ひっく\l"
	.string "{JPN}ぼく なやんで いるんですよう!\l"
	.string "{JPN}ぼくの {STR_VAR_1}のね わざが\l"
	.string "{JPN}なかなか きまらないん です...\p"
	.string "{JPN}あのう あのう!\n"
	.string "{JPN}{PLAYER}さん きめて もらえませんか?\p"
	.string "{JPN}{STR_VAR_1}の わざ\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}なら\l"
	.string "{JPN}どっちが いいんでしょう...?$"

gText_ApprenticeMoveThanks0::
	.string "{JPN}{STR_VAR_1} ですね!\n"
	.string "{JPN}うぅ うわああぁん!\p"
	.string "{JPN}あ! ごめんなさい\n"
	.string "{JPN}{PLAYER}さんが わざを\l"
	.string "{JPN}きめてくれた うれしさで なみだが...\p"
	.string "{JPN}...グスン\n"
	.string "{JPN}ありがとう ございました!\l"
	.string "{JPN}また おはなし してください!$"

gText_ApprenticeWhichMove1::
	.string "{JPN}{PLAYER}せんせい こんにちは!\n"
	.string "{JPN}また おしえて ほしいことが あるの!\p"
	.string "{JPN}ぼくの {STR_VAR_1}に\n"
	.string "{JPN}かっこいい わざを おしえたいの!\l"
	.string "{JPN}おすすめは どっちかな?\p"
	.string "{JPN}{STR_VAR_2}か {STR_VAR_3}が\n"
	.string "{JPN}いいんだけど...$"

gText_ApprenticeMoveThanks1::
	.string "{JPN}{STR_VAR_1}か! そーだよね!\n"
	.string "{JPN}じゃあ ボク それで いくね!\p"
	.string "{JPN}また こんど ここで あったら\n"
	.string "{JPN}なにか おしえてね せんせい!$"

gText_ApprenticeWhichMove2::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}ぼくの {STR_VAR_1}の こと なんだけど\l"
	.string "{JPN}わざの ことで なやんでるんです\p"
	.string "{JPN}{STR_VAR_2} と {STR_VAR_3}\n"
	.string "{JPN}どっちの わざが つよいのか...\p"
	.string "{JPN}{STR_VAR_1}には どっちの わざが\n"
	.string "{JPN}あってると おもいますか?$"

gText_ApprenticeMoveThanks2::
	.string "{JPN}{STR_VAR_1} ですね!\n"
	.string "{JPN}わかりました!\p"
	.string "{JPN}よし さっそく\n"
	.string "{JPN}{STR_VAR_1}を おぼえさせるぞ!\p"
	.string "{JPN}じゃあ また!$"

gText_ApprenticeWhichMove3::
	.string "{JPN}ああ {PLAYER}さん!\n"
	.string "{JPN}あたし あたし ほんと ダメなんです!\p"
	.string "{JPN}ポケモンを いざ そだてようと しても\n"
	.string "{JPN}...わざ ひとつ まともに きめられなくて\l"
	.string "{JPN}どうしようも ありません...\p"
	.string "{JPN}{PLAYER}さんには そんな こと\n"
	.string "{JPN}どうでも いいのは わかってます...\l"
	.string "{JPN}でも あたし...\p"
	.string "{JPN}おねがいです {PLAYER}さん\n"
	.string "{JPN}あたしの {STR_VAR_1}の わざ\l"
	.string "{JPN}きめて いただけませんか?\p"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}か\n"
	.string "{JPN}どちらかを えらんで くださるだけでも!$"

gText_ApprenticeMoveThanks3::
	.string "{JPN}わかりました!\p"
	.string "{JPN}あたし なんかの ために\n"
	.string "{JPN}{STR_VAR_1}を おぼえて くれるか...\l"
	.string "{JPN}いえ! がんばって みます\p"
	.string "{JPN}ありがとう ございます!$"

gText_ApprenticeWhichMove4::
	.string "{JPN}あら! {PLAYER}{KUN}\n"
	.string "{JPN}あいたいと おもって いたの!\l"
	.string "{JPN}わたしの {STR_VAR_1}に ふさわしい わざは\l"
	.string "{JPN}なにかなー って まよってて...\l"
	.string "{JPN}あなたが きめて くれない?\p"
	.string "{JPN}そうね...\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}だったら\l"
	.string "{JPN}どっちが いいと おもう?$"

gText_ApprenticeMoveThanks4::
	.string "{JPN}{STR_VAR_1}ね ありがと!\n"
	.string "{JPN}{PLAYER}{KUN}が きめた って おもえば\l"
	.string "{JPN}まけても きが らくだわ!\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}また そうだんに のってね!$"

gText_ApprenticeWhichMove5::
	.string "{JPN}あー いそがしい いそがしい!\n"
	.string "{JPN}おっと きみは {PLAYER}{KUN}!\l"
	.string "{JPN}ちょうしは どう?\p"
	.string "{JPN}こっちはさ! けさ おきてから\n"
	.string "{JPN}ジョギング スイミング クッキング\l"
	.string "{JPN}いそがしいの なんのって...!\p"
	.string "{JPN}オレの {STR_VAR_1}に\n"
	.string "{JPN}おしえさせる わざも きまんなくてねー\p"
	.string "{JPN}あのさ!\n"
	.string "{JPN}{STR_VAR_2} って よさそうじゃん?\l"
	.string "{JPN}でも {STR_VAR_3} も イイよね!\p"
	.string "{JPN}{PLAYER}{KUN}の アドバイス たのむよ!\n"
	.string "{JPN}どっちの わざが イイかな?$"

gText_ApprenticeMoveThanks5::
	.string "{JPN}オーケー わかった!\n"
	.string "{JPN}じゃ スケジュール あけて\l"
	.string "{JPN}おぼえさせて みるぜ!\p"
	.string "{JPN}ほんと きみって いい せんせい だぜ\n"
	.string "{JPN}サンキュー! じゃ またな!$"

gText_ApprenticeWhichMove6::
	.string "{JPN}おおっ ラッキー!\n"
	.string "{JPN}{PLAYER}さんに あえましたー!\l"
	.string "{JPN}さっそく ききたいことが あるのー!\p"
	.string "{JPN}ジャーン では\n"
	.string "{JPN}ほんじつの そうだんでーす!\p"
	.string "{JPN}わたしの {STR_VAR_1}には\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}\l"
	.string "{JPN}おにあいの わざは さあどっち?$"

gText_ApprenticeMoveThanks6::
	.string "{JPN}ははぁーん\n"
	.string "{JPN}{STR_VAR_1} が イイですか!\l"
	.string "{JPN}シブイ おこたえ ありがとう!\p"
	.string "{JPN}ん きょうは こんなところ かな\n"
	.string "{JPN}こんど また ここで あおうね!\l"
	.string "{JPN}ありがと!$"

gText_ApprenticeWhichMove7::
	.string "{JPN}ごきげんよう {PLAYER}さん...!\n"
	.string "{JPN}あのね きょうも\l"
	.string "{JPN}わたくし そうだんが あるのです\l"
	.string "{JPN}わたくしの かわいい\l"
	.string "{JPN}{STR_VAR_1}ちゃんの ことですの\p"
	.string "{JPN}{STR_VAR_1}ちゃんに ピッタリの わざ...\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}の\l"
	.string "{JPN}どちらを おしえたら よろしいでしょう?$"

gText_ApprenticeMoveThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\n"
	.string "{JPN}さっそく そのように しますわ!\p"
	.string "{JPN}それでは {PLAYER}さん\n"
	.string "{JPN}これからも よろしく おねがいしますわ\l"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticeWhichMove8::
	.string "{JPN}キャァァ {PLAYER}さんが いるーっ!\n"
	.string "{JPN}かっ かんげきっ...!\l"
	.string "{JPN}こまった ときは {PLAYER}さんですっ!\p"
	.string "{JPN}ほんじつは わざの オススメを\n"
	.string "{JPN}おしえて ほしいのですっ!\l"
	.string "{JPN}わたしの {STR_VAR_1}の わざを\l"
	.string "{JPN}きめて くださいっ!\p"
	.string "{JPN}どっちが いいですかっ?\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}!$"

gText_ApprenticeMoveThanks8::
	.string "{JPN}ああぁ ありがとう ございますっ!\n"
	.string "{JPN}{STR_VAR_1} ですねっ\l"
	.string "{JPN}りょうかいで ありますっ!\p"
	.string "{JPN}では また こんど\n"
	.string "{JPN}いろいろと おしえて くださいね!$"

gText_ApprenticeWhichMove9::
	.string "{JPN}ハロウ {PLAYER}{KUN} ハロウ!\n"
	.string "{JPN}おじさん きょうも きみに\l"
	.string "{JPN}アドバイスを もらいたいんだ プリーズ!\p"
	.string "{JPN}マイ ポケモン {STR_VAR_1}の\n"
	.string "{JPN}ベストな わざは なんだろう?\l"
	.string "{JPN}ババーっと かてちゃいそうな わざ!\p"
	.string "{JPN}{STR_VAR_2} かな?\n"
	.string "{JPN}オア {STR_VAR_3} かな?$"

gText_ApprenticeMoveThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ねー\n"
	.string "{JPN}オーケイ オーケイ!\l"
	.string "{JPN}おじさん ザザーっと おぼえさせるよ!\p"
	.string "{JPN}それじゃあ これからも よろしくね\n"
	.string "{JPN}アディオース!$"

gText_ApprenticeWhichMove10::
	.string "{JPN}{PLAYER}{KUN} たいへんだぞ!\n"
	.string "{JPN}おいらの ポケモンが なんと\l"
	.string "{JPN}わざを 6つ おぼえたんだ!\p"
	.string "{JPN}...なんてね ウソだよ! ははは!\p"
	.string "{JPN}じつは おいら ポケモンの わざ きめるの\n"
	.string "{JPN}あんまり とくいじゃ なくてさ!\l"
	.string "{JPN}ひとつ どうだろ ししょうが\l"
	.string "{JPN}オススメのわざ きめて くれない かな?\p"
	.string "{JPN}{STR_VAR_2} と {STR_VAR_3}\n"
	.string "{JPN}{STR_VAR_1}なら どっちが あうかい?$"

gText_ApprenticeMoveThanks10::
	.string "{JPN}そうか\n"
	.string "{JPN}{STR_VAR_1}が いいのね!\l"
	.string "{JPN}じゃあ ちがうわざに しようっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ありがとう ししょう!\n"
	.string "{JPN}また あったら よろしくなー$"

gText_ApprenticeWhichMove11::
	.string "{JPN}こ·ん·に·ち·は!\n"
	.string "{JPN}はーい こんにちは!\l"
	.string "{JPN}ノリノリ ふなのりの わしだぜー!\p"
	.string "{JPN}よーし きょうの わしの そうだん\n"
	.string "{JPN}いってみようぜー!\l"
	.string "{JPN}わざに かんする そうだんだよ!\p"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}\n"
	.string "{JPN}{STR_VAR_1}が おぼえるなら どっちだ?$"

gText_ApprenticeMoveThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで おぼえさせるぜ!\p"
	.string "{JPN}これからも ヨロシク たのむぜ\n"
	.string "{JPN}{PLAYER}さん!$"

gText_ApprenticeWhichMove12::
	.string "{JPN}イエァ {PLAYER}さんじゃないのー?\n"
	.string "{JPN}どうする オレ? また はなしかける!?\l"
	.string "{JPN}ってもう はなしかけてる!?\l"
	.string "{JPN}って {PLAYER}さん あきれてる!?\l"
	.string "{JPN}しかたねー そうだん してみる!?\p"
	.string "{JPN}きょうも そうだんに のってェ!\n"
	.string "{JPN}って きいてる!? きいてる!!\p"
	.string "{JPN}おれの {STR_VAR_1}の わざ\n"
	.string "{JPN}どうしたら いいかな? きめてエェ!\l"
	.string "{JPN}{STR_VAR_2}!? {STR_VAR_3}!?$"

gText_ApprenticeMoveThanks12::
	.string "{JPN}{STR_VAR_1}で オーライ!\n"
	.string "{JPN}じゃ さっそく おぼえさせるぜェ!!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}また あおうぜ!!$"

gText_ApprenticeWhichMove13::
	.string "{JPN}ガハゴホ あ {PLAYER}{KUN}\n"
	.string "{JPN}カゼ ひいちゃったよ おれ...\p"
	.string "{JPN}ポケモンに おしえる わざを\n"
	.string "{JPN}きめたいんだけど ムリっぽいん だよね\l"
	.string "{JPN}というわけ だからさ かわりに たのむよ!\p"
	.string "{JPN}{PLAYER}{KUN}はさ おれの {STR_VAR_1}\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}なら\l"
	.string "{JPN}どっちが あってると おもうかい?$"

gText_ApprenticeMoveThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\n"
	.string "{JPN}じゃあ カゼが なおったら\l"
	.string "{JPN}ゴホ おしえて みるよ!\p"
	.string "{JPN}これからも おれを よろしく たのむよ!$"

gText_ApprenticeWhichMove14::
	.string "{JPN}あ... あ...\n"
	.string "{JPN}{PLAYER}{KUN} だよね?\l"
	.string "{JPN}そ そんなに みないで くれよ!\l"
	.string "{JPN}てれるだろ\l"
	.string "{JPN}また... そうだん させて くれよ\p"
	.string "{JPN}は はずかしながらさ\n"
	.string "{JPN}ポケモンに おしえる わざがさ\l"
	.string "{JPN}きまんないんだ アドバイス くれよ!\p"
	.string "{JPN}ポケモンは {STR_VAR_1}なんだ\n"
	.string "{JPN}だったら どっちが いい かな...?\n"
	.string "{JPN}{STR_VAR_2}... {STR_VAR_3}...$"

gText_ApprenticeMoveThanks14::
	.string "{JPN}よ よし {STR_VAR_1}\n"
	.string "{JPN}いって みるよ!\p"
	.string "{JPN}そんな わざを おしえるなんて\n"
	.string "{JPN}て てれるな...\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}また こんど あえたら... よろしくね$"

gText_ApprenticeWhichMove15::
	.string "{JPN}ん?\n"
	.string "{JPN}{PLAYER}{KUN}の ように みえるが...\l"
	.string "{JPN}ほんものかな?\l"
	.string "{JPN}さいきん はやりの モノマネ では?\p"
	.string "{JPN}いやいや! ほんもの ならいいんだ!\n"
	.string "{JPN}きを わるく しないでくれ!\l"
	.string "{JPN}そして ついでに でしの わたしに\l"
	.string "{JPN}じょげんを おねがい したい\l"
	.string "{JPN}わたしの {STR_VAR_1}の ことだ!\p"
	.string "{JPN}{STR_VAR_2} と {STR_VAR_3}\n"
	.string "{JPN}どっちの わざが つかえたら いいかね?$"

gText_ApprenticeMoveThanks15::
	.string "{JPN}{STR_VAR_1}...\n"
	.string "{JPN}まちがいなく そうなの かね?\p"
	.string "{JPN}いや ほんとう なら いいんだ\n"
	.string "{JPN}どうも ありがとう\l"
	.string "{JPN}こんな わたしの ポケモンでも\l"
	.string "{JPN}おぼえて くれると いいな\p"
	.string "{JPN}では いずれまた あおう!$"

gText_ApprenticePickWinSpeech0::
	.string "{JPN}ああっ {PLAYER}さん\n"
	.string "{JPN}{PLAYER}さんだ! わわーん!\l"
	.string "{JPN}ぐすん ひっく きいて ください\p"
	.string "{JPN}ぼくっ ぼく しょうぶ するとき\n"
	.string "{JPN}ものすごく きんちょう して\l"
	.string "{JPN}かっても ないちゃうん です...\p"
	.string "{JPN}なにか かっこいい こと いえたら\n"
	.string "{JPN}いいなと おもうんです けど...\p"
	.string "{JPN}あのう あのう {PLAYER}さん\n"
	.string "{JPN}もし よかったら...\l"
	.string "{JPN}ぼく なかなくて いいように\l"
	.string "{JPN}なにか かったときに いう ことばを\l"
	.string "{JPN}かんがえて もらえませんか?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}... うぉぉーん!\n"
	.string "{JPN}すごく かっこいいよう!\p"
	.string "{JPN}あ ごめんなさい\n"
	.string "{JPN}うれしすぎて なみだが...\p"
	.string "{JPN}...グスン {PLAYER}さん!\n"
	.string "{JPN}いつも いつも ありがとう ございました!\l"
	.string "{JPN}ぼく {PLAYER}さんの ためにも\l"
	.string "{JPN}がんばって たたかい つづけます!\p"
	.string "{JPN}では {PLAYER}さん!\n"
	.string "{JPN}こんどは... どこかで たたかいましょう!$"

gText_ApprenticePickWinSpeech1::
	.string "{JPN}{PLAYER}せんせい こんにちは!\n"
	.string "{JPN}ぼく きめたい ことが あるの!\p"
	.string "{JPN}あのね!\n"
	.string "{JPN}ぼく しょうぶに かった とき\l"
	.string "{JPN}なにか かっこいい セリフを いいたいの!\p"
	.string "{JPN}せんせい おすすめの\n"
	.string "{JPN}かっこいい セリフって あるかな?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}うわあー いーね!\n"
	.string "{JPN}じゃあ ボク それで いくね!\p"
	.string "{JPN}せんせい いままで ありがとう!\n"
	.string "{JPN}ボク これから いろんな ところで\l"
	.string "{JPN}がんばる ことに する!\p"
	.string "{JPN}こんど あうときは しょうぶ だよ!$"

gText_ApprenticePickWinSpeech2::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}ポケモンの じゅんびは\p"
	.string "{JPN}ばんぜん なんですけど\n"
	.string "{JPN}ひとつ きに なってるんです\p"
	.string "{JPN}ポケモントレーナーって\n"
	.string "{JPN}しょうぶに かった ときに かけごえ が\p"
	.string "{JPN}あると いいかなーって おもうんです\n"
	.string "{JPN}なにか いいの かんがえて ください!$"

gText_ApprenticeWinSpeechThanks2::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}...かっこいいですね!\n"
	.string "{JPN}それ つかわせて いただきます!\p"
	.string "{JPN}じゃあ ぼくは これから\n"
	.string "{JPN}いろんな ところで しょうぶ してきます!\p"
	.string "{JPN}いつか {PLAYER}さんと\n"
	.string "{JPN}しょうぶ する ひが\l"
	.string "{JPN}くるかも しれませんね!\p"
	.string "{JPN}では こんどは しょうぶの ば で\n"
	.string "{JPN}おあい しましょう!$"

gText_ApprenticePickWinSpeech3::
	.string "{JPN}あっ {PLAYER}さん...!\n"
	.string "{JPN}あたし ほんと ダメな おんなのこです!\p"
	.string "{JPN}せっかく...\n"
	.string "{JPN}せっかく しょうぶに かっても\l"
	.string "{JPN}ことば ひとつ でてこなくって...\p"
	.string "{JPN}{PLAYER}さんには そんな こと\n"
	.string "{JPN}どうでも いいのは わかってます!\l"
	.string "{JPN}でも あたし どうしても...\p"
	.string "{JPN}おねがい! です {PLAYER}さん\n"
	.string "{JPN}かったとき って\l"
	.string "{JPN}なんて いうべき なんでしょうか...?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}すごいわ...\p"
	.string "{JPN}あ あたしなんかが\n"
	.string "{JPN}そんな こと いって いいのか...\l"
	.string "{JPN}いえ! がんばって みます\p"
	.string "{JPN}{PLAYER}さん!\p"
	.string "{JPN}いままで あたしなんかの ために\n"
	.string "{JPN}ありがとう... ございました...!\l"
	.string "{JPN}あたし いまから がんばってきます!\p"
	.string "{JPN}あたしの こと なんて\n"
	.string "{JPN}すぐに わすれて しまうと おもうけど\l"
	.string "{JPN}でも どこかで おあい しましょう!$"

gText_ApprenticePickWinSpeech4::
	.string "{JPN}あら {PLAYER}{KUN}?\n"
	.string "{JPN}ちょっと きいて ほしいんだけど!\p"
	.string "{JPN}じぶんでも わかって いるけど\n"
	.string "{JPN}わたし すこし くちが わるくて...\l"
	.string "{JPN}しょうぶに かったときに\l"
	.string "{JPN}なんか えらそうに しちゃうのよね!\p"
	.string "{JPN}だけど きらわれたく ないから\n"
	.string "{JPN}わたしに まけた あいてに\l"
	.string "{JPN}やさしい ことばを かけて あげたいのよ!\p"
	.string "{JPN}でも ぜんぜん おもいつかなくて!\n"
	.string "{JPN}あなたが かんがえて くれない?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}わるく ないわね!\n"
	.string "{JPN}うん それで いくことに するわ!\p"
	.string "{JPN}じゃあ... いままで\n"
	.string "{JPN}{PLAYER}さんに おそわった\l"
	.string "{JPN}いろいろな ことを むねに\l"
	.string "{JPN}わたし がんばって くる!\l"
	.string "{JPN}いろいろと なまいき いって\l"
	.string "{JPN}ごめんなさい!\p"
	.string "{JPN}つぎに あう ときは しょうぶよ!\n"
	.string "{JPN}じゃあね!$"

gText_ApprenticePickWinSpeech5::
	.string "{JPN}あー いそがしい いそがしい!\n"
	.string "{JPN}おっと さがしてたよ {PLAYER}{KUN}\l"
	.string "{JPN}きょうも げんきかい?\p"
	.string "{JPN}こっちはさー! あいかわらず\n"
	.string "{JPN}ランニング ファイティング マッピングと\l"
	.string "{JPN}なんで こんなに いそがしいんだ?\p"
	.string "{JPN}でもさ! いそがしい からって\n"
	.string "{JPN}しょうぶに かった ときに\l"
	.string "{JPN}なにも いわないで\l"
	.string "{JPN}たちさっちゃ しつれいだろ?\p"
	.string "{JPN}でさ!\n"
	.string "{JPN}かっこよく たちさる オレを\l"
	.string "{JPN}えんしゅつする いい ことば ないかな?\l"
	.string "{JPN}{PLAYER}{KUN} なんか たのむよ!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}オーケー わかった!\n"
	.string "{JPN}そのぐらい いう じかんは つくれるぜ!\l"
	.string "{JPN}ほんと きみ みたいな\l"
	.string "{JPN}いい せんせいに であえて よかったぜ!\p"
	.string "{JPN}オレは これから じかんを つくって\n"
	.string "{JPN}ポケモンしょうぶを してくるよ!\l"
	.string "{JPN}いままで サンキュー {PLAYER}{KUN}!\p"
	.string "{JPN}いつか オレと しょうぶ しようぜ!$"

gText_ApprenticePickWinSpeech6::
	.string "{JPN}やったねーっ\n"
	.string "{JPN}{PLAYER}さんに あえちゃった!\l"
	.string "{JPN}さっそく そうだんが あるのよ!\p"
	.string "{JPN}ジャーン\n"
	.string "{JPN}では さいごの そうだん でーす!\p"
	.string "{JPN}わたしが しょうぶで かった とき\n"
	.string "{JPN}かっこよく キメたいと したら\l"
	.string "{JPN}さあ なんて いえばいい?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}いっ イイ!\n"
	.string "{JPN}シブイ! それいただき!\p"
	.string "{JPN}...ねえ わたし\n"
	.string "{JPN}そろそろ いちにんまえに なったよね!\p"
	.string "{JPN}あのね これから いろんなひとと\n"
	.string "{JPN}たたかって みようと おもうの!\p"
	.string "{JPN}{PLAYER}さんの アドバイス\n"
	.string "{JPN}すっごく たすかったよー!\l"
	.string "{JPN}いつか しょうぶする ときが くるかもね\l"
	.string "{JPN}いままで ほんと ありがとー!$"

gText_ApprenticePickWinSpeech7::
	.string "{JPN}まあ {PLAYER}さん\n"
	.string "{JPN}あえて よかった ですわ...!\p"
	.string "{JPN}わたくし ポケモンの ほうは\n"
	.string "{JPN}もう しんぱい ないのです けれど\l"
	.string "{JPN}わたくし じしんの ほうが...\p"
	.string "{JPN}その あの ポケモントレーナーさんは\n"
	.string "{JPN}いつも しょうぶに かったとき\l"
	.string "{JPN}ことばを かけて くださいますね?\p"
	.string "{JPN}ぜひ! わたくしも あれを\n"
	.string "{JPN}やってみたいのです!\l"
	.string "{JPN}おねがいです! なにか\l"
	.string "{JPN}かったときの ことば きめて ください!$"

gText_ApprenticeWinSpeechThanks7::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}ですのね...!\p"
	.string "{JPN}ああ! なんだか わたくし\n"
	.string "{JPN}うまれかわれる きが しますわ...!\l"
	.string "{JPN}さっそく そのことば つかってみますわ!\p"
	.string "{JPN}それでは ここで おわかれです...\n"
	.string "{JPN}{PLAYER}さんの ごしどう\l"
	.string "{JPN}わたくし けっして わすれずに\l"
	.string "{JPN}みなさまと たたかって まいります!\p"
	.string "{JPN}また いずれ...\n"
	.string "{JPN}ごきげんよう!$"

gText_ApprenticePickWinSpeech8::
	.string "{JPN}キャァー!\n"
	.string "{JPN}{PLAYER}さんを はっけんーっ!\l"
	.string "{JPN}かっ かんげきっ...!\p"
	.string "{JPN}あのっ そうだんが あります!\p"
	.string "{JPN}このあいだ ポケモンしょうぶに\n"
	.string "{JPN}かったは いいんですけど!\l"
	.string "{JPN}わたし かんげき しすぎちゃって\l"
	.string "{JPN}なんにも いえなく なっちゃって...!\p"
	.string "{JPN}そこで {PLAYER}さん!\n"
	.string "{JPN}わたしが かった ときの きめぜりふ!\l"
	.string "{JPN}かんがえて ほしいのですっ!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}う うわああぁぁあ!\n"
	.string "{JPN}この ことばを わたしが!\l"
	.string "{JPN}かっ かんげき......っ!!\p"
	.string "{JPN}あああ ありがとう ございますっ!\n"
	.string "{JPN}もう おもいのこす ことは ありませんっ!\l"
	.string "{JPN}わたし これから たびだって\l"
	.string "{JPN}いろいろな ひとと しょうぶ してみます!\p"
	.string "{JPN}なにもかも {PLAYER}さんの\n"
	.string "{JPN}おかげで あります!\l"
	.string "{JPN}ほんとうに ありがとう ございますっ!\p"
	.string "{JPN}それでは それでは\n"
	.string "{JPN}いつか しょうぶの ばで あいましょう!$"

gText_ApprenticePickWinSpeech9::
	.string "{JPN}ハッローウ\n"
	.string "{JPN}ハロウ {PLAYER}{KUN}!\p"
	.string "{JPN}おじさん そろそろ あちこちで\n"
	.string "{JPN}しょうぶが したく なって きたよ!\l"
	.string "{JPN}そこで そのまえに きみに\l"
	.string "{JPN}アドバイスを もらいたいんだ プリーズ!\p"
	.string "{JPN}おじさんが もし しょうぶに かったら\n"
	.string "{JPN}あいての トレーナーに むかって\l"
	.string "{JPN}じまん するような ことばって ないかな?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}あはぁ それいいね\n"
	.string "{JPN}オーケイ オーケイ!\l"
	.string "{JPN}おじさん ババーっと いってみるよ!\p"
	.string "{JPN}それじゃあ おわかれだ!\n"
	.string "{JPN}いままで いろいろ ありがとうね\l"
	.string "{JPN}いつか しょうぶも してくれよ!\p"
	.string "{JPN}アディオース!$"

gText_ApprenticePickWinSpeech10::
	.string "{JPN}{PLAYER}{KUN} たいへんだーっ!\p"
	.string "{JPN}おいら しょうぶに かつと\n"
	.string "{JPN}1じかんも えばっちゃうんだ!\p"
	.string "{JPN}...なんてね ウソなんだよ! うっはは\p"
	.string "{JPN}じつは おいら ひとと はなし するの\n"
	.string "{JPN}あんまり とくいじゃ なくてさ!\l"
	.string "{JPN}ひとつ どうだろ\l"
	.string "{JPN}おいらが しょうぶに かったときに\l"
	.string "{JPN}いう ことばを\l"
	.string "{JPN}ししょうが きめて くれない かな?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}こう いえば いいのね!\n"
	.string "{JPN}じゃあ それだけは やめておこうっと!\p"
	.string "{JPN}... なんて じょうだん!\n"
	.string "{JPN}ちゃんと ししょうの いうこと きくよ\p"
	.string "{JPN}ずっとずっと ありがとう ししょう!\n"
	.string "{JPN}おいら やっと トレーナーって もんが\l"
	.string "{JPN}わかった きがするよ!\p"
	.string "{JPN}いまから いろんな やつと\n"
	.string "{JPN}しょうぶして かって くるぞ!\l"
	.string "{JPN}ししょう とも しょうぶ するかもな!\p"
	.string "{JPN}それじゃな!\n"
	.string "{JPN}さらばだ ししょう!$"

gText_ApprenticePickWinSpeech11::
	.string "{JPN}こ·ん·に·ち·は!\n"
	.string "{JPN}はーい こんにちは!\l"
	.string "{JPN}ノリノリ ふなのりの わしだぜー!\p"
	.string "{JPN}よーし さいごの わしの そうだん\n"
	.string "{JPN}いってみようぜー!\l"
	.string "{JPN}ことばに かんする そうだんだよ!\p"
	.string "{JPN}わしが もし しょうぶで かったら\n"
	.string "{JPN}どういう ことばで キメたら いいかな?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}なるほどーっ! ようよう!\n"
	.string "{JPN}そんなら ノリノリで それ つかうぜ!\p"
	.string "{JPN}そろそろ わしも すだつと するか\n"
	.string "{JPN}ノリノリで たたかい まくるぜ!\l"
	.string "{JPN}いろいろと ありがとうな!\p"
	.string "{JPN}お·つ·か·れ·さ·ま!\n"
	.string "{JPN}はーい おつかれさま ごきげんよう!$"

gText_ApprenticePickWinSpeech12::
	.string "{JPN}オーイェッ {PLAYER}さあん!\n"
	.string "{JPN}どうする オレ? きょうも きいてみる?\l"
	.string "{JPN}ってもう きこうとしてる!?\p"
	.string "{JPN}そもそも {PLAYER}さんって\n"
	.string "{JPN}いつも きいてる!? きいてる!!\l"
	.string "{JPN}じゃ そうだんに のってェ!\p"
	.string "{JPN}おれが かった ときに さけぶ\n"
	.string "{JPN}カッコイイ キメキメの\l"
	.string "{JPN}すんごい セリフ...\l"
	.string "{JPN}なんか かんがえてエエェ!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}オーラーイ オーライ!\n"
	.string "{JPN}じゃ さっそく それでいくぜェ!\p"
	.string "{JPN}ってオレ もう\n"
	.string "{JPN}きくことが なくなったぜ!\l"
	.string "{JPN}しかたねー これで おわかれする!?\l"
	.string "{JPN}とかいって どこかで ちゃっかり\l"
	.string "{JPN}また あえちゃったり するかも!?\p"
	.string "{JPN}まー とりあえずは おわかれだぜ!\p"
	.string "{JPN}って {PLAYER}さん\n"
	.string "{JPN}オレの こと わすれんなよ!\l"
	.string "{JPN}じゃあな {PLAYER}さん! スキだぜェ!$"

gText_ApprenticePickWinSpeech13::
	.string "{JPN}{PLAYER}{KUN} おれは\n"
	.string "{JPN}もう ダメだよ...\l"
	.string "{JPN}はなみずが とまらなくってさ...\p"
	.string "{JPN}しょうぶに かった ときに\n"
	.string "{JPN}なにか かっこいいこと いおうとして\l"
	.string "{JPN}あたまで かんがえてたら...\p"
	.string "{JPN}われながら ジーンと なけちゃって\n"
	.string "{JPN}はなみずが でたんだよね きっと!\l"
	.string "{JPN}というわけ だからさ\l"
	.string "{JPN}{PLAYER}{KUN} かんがえてよ!\p"
	.string "{JPN}しょうぶに かったら\n"
	.string "{JPN}おれ なんて いえば いいかな?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}... ... ...いいよ\n"
	.string "{JPN}それ いいよ!\l"
	.string "{JPN}ダメだ なみだが また とまらないよ\p"
	.string "{JPN}でも なみだと はなみずを こらえて\n"
	.string "{JPN}そのセリフ つかわせて もらうよ!\p"
	.string "{JPN}おれは もう {PLAYER}{KUN}に\n"
	.string "{JPN}ききたい ことは なくなった!\l"
	.string "{JPN}これからは ライバルだよ!\p"
	.string "{JPN}ん いままで ありがとうな!$"

gText_ApprenticePickWinSpeech14::
	.string "{JPN}あ... あ...\n"
	.string "{JPN}{PLAYER}{KUN} だよね?\l"
	.string "{JPN}そ そんなに みないで くれよ!\l"
	.string "{JPN}てれるだろ\p"
	.string "{JPN}また... そうだん させて くれよ\n"
	.string "{JPN}こ これで さいごに するからさ\p"
	.string "{JPN}あのさ はずかしいん だけどさ\n"
	.string "{JPN}もし もし しょうぶに かったら!\l"
	.string "{JPN}ワシは なんて いったら いいんだろう...?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}よ よし それ\n"
	.string "{JPN}いって みるよ!\l"
	.string "{JPN}は はずかしいな いえるかな...\p"
	.string "{JPN}ありがとう {PLAYER}{KUN}\n"
	.string "{JPN}さようならだ!\l"
	.string "{JPN}{PLAYER}{KUN}に いわれた こと\l"
	.string "{JPN}ぜんぶ まもって ワシ がんばるよ!$"

gText_ApprenticePickWinSpeech15::
	.string "{JPN}ん?\n"
	.string "{JPN}{PLAYER}{KUN}の ように みえるが...\l"
	.string "{JPN}ほんものかな?\l"
	.string "{JPN}{PLAYER}{KUN} ぬいぐるみ では?\p"
	.string "{JPN}いや! いやいやいやいや!\n"
	.string "{JPN}すまない ほんものなら いいんだ\l"
	.string "{JPN}まあ そう おこらないで くれ!\l"
	.string "{JPN}それでもって じょげんを おねがいする\l"
	.string "{JPN}ことばに かんする ことだ!\p"
	.string "{JPN}もし わたしが しょうぶに かったら\n"
	.string "{JPN}ぜんたい なんと いえば いいかね?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}... ... ...\n"
	.string "{JPN}しょうぶに かったら\p"
	.string "{JPN}{STR_VAR_1}\p"
	.string "{JPN}... ほんき なのかね?\p"
	.string "{JPN}いや ほんき なら いいんだ!\n"
	.string "{JPN}どうも ありがとう\l"
	.string "{JPN}こんな わたしでも いつか\l"
	.string "{JPN}つかえる ときが くれば いいな\p"
	.string "{JPN}では そろそろ\n"
	.string "{JPN}ほしい じょげんも なくなってきた\l"
	.string "{JPN}{PLAYER}{KUN}とは おわかれして\l"
	.string "{JPN}ひとりで がんばって みようかと おもう\p"
	.string "{JPN}では ありがとう!\n"
	.string "{JPN}うたがって すまなかった!$"
