FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント ハジツゲかいじょうへ\n"
	.string "{JPN}ようこそ おいでなされた!\p"
	.string "{JPN}こちらでは かちぬきチームバトルの\n"
	.string "{JPN}あんないを しておりますぞ!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}かちぬきチームバトルに\n"
	.string "{JPN}ちょうせん されますかな?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "{JPN}またの ちょうせんを\n"
	.string "{JPN}おまちして おりますぞ!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "{JPN}バトルテント ハジツゲかいじょうでは\n"
	.string "{JPN}かちぬきチームバトルを\l"
	.string "{JPN}おこなって おりますぞ!\p"
	.string "{JPN}さんかする かたには しゅつじょう させる\n"
	.string "{JPN}3ひきの ポケモンと たたかいに だす\l"
	.string "{JPN}じゅんばんを きめて いただきますぞ!\p"
	.string "{JPN}たたかいの あいだは\n"
	.string "{JPN}この じゅんばん どおりに\l"
	.string "{JPN}ポケモンを だすことに なりますな!\p"
	.string "{JPN}たたかいに いちど だした ポケモンは\n"
	.string "{JPN}けっちゃくが つくまで\l"
	.string "{JPN}こうたいさせる ことが できませぬ!\p"
	.string "{JPN}さらに 3ターン いないに\n"
	.string "{JPN}たたかいの けっちゃくが つかなければ\l"
	.string "{JPN}はんていと なりますぞ!\p"
	.string "{JPN}また とちゅうで ちょうせんを\n"
	.string "{JPN}ちゅうだんしたい ばあいは\l"
	.string "{JPN}レポートを かかないと\l"
	.string "{JPN}つづけて ちょうせんが できないので\l"
	.string "{JPN}おきをつけ くだされ!\p"
	.string "{JPN}みごと 3にんぬきを なされた あかつきには\n"
	.string "{JPN}すてきな しょうひんを\l"
	.string "{JPN}おおくり いたしますぞ!$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}バトルテントへ おつれする まえに\n"
	.string "{JPN}レポートを かきますが よろしいですかな?$"

FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50と レベル100の へやが\n"
	.string "{JPN}ありますが どちらに まいられますかな?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{JPN}では ちょうせんする ポケモンを\n"
	.string "{JPN}3ひき おえらび くだされ!$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}おきゃくじん!!\p"
	.string "{JPN}さんかできる ポケモンが\n"
	.string "{JPN}3ひき おりませんぬ!\p"
	.string "{JPN}また もたせる どうぐも\n"
	.string "{JPN}すべて ちがう どうぐに してくだされ!\p"
	.string "{JPN}なお タマゴ{STR_VAR_1}さんか させる ことは できませぬ!\p"
	.string "{JPN}じゅんびが できましたら\n"
	.string "{JPN}また おこし くだされ!$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}おきゃくじん!!\p"
	.string "{JPN}さんかできる ポケモンが\n"
	.string "{JPN}3ひき おりませぬ!\p"
	.string "{JPN}さんかする ためには\n"
	.string "{JPN}すべて ちがう しゅるいの ポケモンを\l"
	.string "{JPN}3ひき よういして くだされ\p"
	.string "{JPN}また もたせる どうぐも\n"
	.string "{JPN}すべて ちがう どうぐに してくだされ!\p"
	.string "{JPN}なお タマゴ{STR_VAR_1}さんか させる ことは できませぬ!\p"
	.string "{JPN}じゅんびが できましたら\n"
	.string "{JPN}また おこし くだされ!$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "{JPN}では バトルテントへ\n"
	.string "{JPN}おつれいたしますぞ!$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}おきゃくじん!\p"
	.string "{JPN}ぜんかい レポートを かいて\n"
	.string "{JPN}しゅうりょう しませんでしたな?\p"
	.string "{JPN}ざんねんですが その ばあい\n"
	.string "{JPN}ちょうせんは むこうと なりますぞ!\p"
	.string "{JPN}また はじめから\n"
	.string "{JPN}ちょうせん してくだされ!!$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "{JPN}3にんぬき たっせい\n"
	.string "{JPN}おみごとで ございました!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "{JPN}レポートを かきますので\n"
	.string "{JPN}おまちくだされ!$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{JPN}3にんぬきを たっせい されましたので\n"
	.string "{JPN}この しょうひんを おうけとり くだされ!$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は\n"
	.string "{JPN}{STR_VAR_1}を もらった!$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "{JPN}......おおっ!\n"
	.string "{JPN}どうぐが いっぱいの ようですな!\p"
	.string "{JPN}どうぐを せいりしてから\n"
	.string "{JPN}また おこしくだされ!$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "{JPN}おつかれさまでした!\p"
	.string "{JPN}レポートを かきますので\n"
	.string "{JPN}おまちくだされ!$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "{JPN}またの ちょうせんを\n"
	.string "{JPN}おまちして おりますぞ!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "{JPN}おまちしておりました!\p"
	.string "{JPN}バトルテントに おつれする まえに\n"
	.string "{JPN}レポートを かきますので おまちくだされ!$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント\n"
	.string "{JPN}シダケかいじょうへ ようこそ\p"
	.string "{JPN}ここでは トレーナーの\n"
	.string "{JPN}しんらいの こころを ためしておる$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}バトルテント シダケかいじょうに\n"
	.string "{JPN}ちょうせん するか?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "{JPN}バトルテント シダケかいじょうでの\n"
	.string "{JPN}たたかいには まもらなければ ならない\l"
	.string "{JPN}ひとつの おきてが ある\p"
	.string "{JPN}ここでは ポケモンは\n"
	.string "{JPN}いれかえ しか できない!\p"
	.string "{JPN}それいがいの めいれいは\n"
	.string "{JPN}いっさい きんし して おるのだ!\p"
	.string "{JPN}ポケモンには おのれの せいかくの ままに\n"
	.string "{JPN}かんがえ こうどう して もらう!\p"
	.string "{JPN}おぬしは じぶんの\n"
	.string "{JPN}ポケモンたちを しんじて\l"
	.string "{JPN}たたかいを みまもって やれ\p"
	.string "{JPN}みごと 3にんの トレーナーを\n"
	.string "{JPN}うちやぶることが できれば\l"
	.string "{JPN}しょうひんを さしあげよう\p"
	.string "{JPN}また とちゅうで ちょうせんを\n"
	.string "{JPN}ちゅうだん したい ときは\l"
	.string "{JPN}きちんと レポートを かかないと\l"
	.string "{JPN}つづけて ちょうせん できん からな\l"
	.string "{JPN}きを つけてくれ......$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "{JPN}おのれの こころと ポケモンを きたえたら\n"
	.string "{JPN}また くるがよい......$"

VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50の へやと レベル100の へやが\n"
	.string "{JPN}あるが どちらに ちょうせん するのだ?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}おぬし......\p"
	.string "{JPN}ちょうせん できる ポケモンが\n"
	.string "{JPN}3ひき おらんぞ!\p"
	.string "{JPN}ちょうせん するには\n"
	.string "{JPN}すべて ちがう しゅるいの ポケモンを\l"
	.string "{JPN}3ひき ようい してくれ\p"
	.string "{JPN}また もたせる どうぐも\n"
	.string "{JPN}すべて ちがう もので なければ いかん\p"
	.string "{JPN}なお タマゴ{STR_VAR_1}ちょうせん させる ことは できん!\p"
	.string "{JPN}じゅんびを ととのえてから また きなさい$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}おぬし......\p"
	.string "{JPN}ちょうせん できる ポケモンが\n"
	.string "{JPN}3ひき おらんぞ!\p"
	.string "{JPN}ちょうせん するには\n"
	.string "{JPN}すべて ちがう しゅるいの ポケモンを\p"
	.string "{JPN}3ひき ようい してくれ\p"
	.string "{JPN}また もたせる どうぐも\n"
	.string "{JPN}すべて ちがう もので なければ いかん\p"
	.string "{JPN}そして タマゴ{STR_VAR_1}ちょうせん\n"
	.string "{JPN}させる ことは できん!\p"
	.string "{JPN}じゅんびを ととえてから また きなさい$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{JPN}では ちょうせんする ポケモンを\n"
	.string "{JPN}3ひき えらんでくれ$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}バトルテントへ むかうまえに\n"
	.string "{JPN}レポートを かくが よろしいか?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "{JPN}それでは\n"
	.string "{JPN}わしに ついてこい......$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "{JPN}よいものを みせて もらった\p"
	.string "{JPN}それでは レポートを かこう......\n"
	.string "{JPN}しばし またれよ......$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "{JPN}3にんぬき たっせい とは......\p"
	.string "{JPN}おぬしと ポケモンの こころの きずなは\n"
	.string "{JPN}まことの ようじゃな......$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "{JPN}レポートに かくぞ\n"
	.string "{JPN}しばし またれよ......$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{JPN}3にんぬきの あかしに\n"
	.string "{JPN}こちらを さしあげよう......$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント カイナかいじょうへ\n"
	.string "{JPN}ようこそ!\p"
	.string "{JPN}バトルトレードの\n"
	.string "{JPN}ごあんないは こちらです!$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}バトルトレードに\n"
	.string "{JPN}ちょうせん しますか?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "{JPN}バトルテント カイナかいじょうでは\n"
	.string "{JPN}レンタルポケモンを つかった\l"
	.string "{JPN}バトルトレード という イベントを\l"
	.string "{JPN}おこなっています!\p"
	.string "{JPN}まずは バトルトレード せんようの\n"
	.string "{JPN}ポケモン 3ひきを おかし します!\p"
	.string "{JPN}つぎに そちらの 3ひきの ポケモンを\n"
	.string "{JPN}つかって シングルバトルを\l"
	.string "{JPN}おこなって いただきます!\p"
	.string "{JPN}みごと たたかいに しょうりすると\n"
	.string "{JPN}たたかった トレーナーと ポケモンを\l"
	.string "{JPN}トレード することが できます!\p"
	.string "{JPN}トレードと たたかいを くりかえし\n"
	.string "{JPN}みごと 3れんしょう したら\l"
	.string "{JPN}すてきな しょうひんを さしあげます!\p"
	.string "{JPN}なお とちゅうで ちょうせんを\n"
	.string "{JPN}ちゅうだん したい ときには\l"
	.string "{JPN}きちんと レポートを かかないと\l"
	.string "{JPN}つづけて ちょうせんが できません!\p"
	.string "{JPN}くれぐれも きをつけて くださいね!$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "{JPN}またの ごりようを おまちしていますよ!$"

SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50と レベル100の イベント\n"
	.string "{JPN}どちらに ちょうせん しますか?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}では ちょうせんを はじめる まえに\n"
	.string "{JPN}レポートを かきますが よろしいですか?$"

SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "{JPN}それでは ポケモンを\n"
	.string "{JPN}おあずかり します!$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "{JPN}さあさあ こちらに どうぞ!$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "{JPN}おつかれさまでした!\p"
	.string "{JPN}レンタルポケモンと\n"
	.string "{JPN}おあずかり していた ポケモンを\l"
	.string "{JPN}こうかん します!\p"
	.string "{JPN}レポートを かきますので\n"
	.string "{JPN}しょうしょう おまちください!$"

SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "{JPN}レンタルポケモンと\n"
	.string "{JPN}おあずかり していた ポケモンを\l"
	.string "{JPN}こうかん します!$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "{JPN}3れんしょう おめでとう ございます!\p"
	.string "{JPN}レンタルポケモンと\n"
	.string "{JPN}おあずかり していた ポケモンを\l"
	.string "{JPN}こうかん します!\p"
	.string "{JPN}レポートを かきますので\n"
	.string "{JPN}しょうしょう おまちください!$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "{JPN}3れんしょうを きねんして\n"
	.string "{JPN}こちらを さしあげます!$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "{JPN}おやや?\n"
	.string "{JPN}どうぐが いっぱい ですねー\p"
	.string "{JPN}どうぐを せいり してから\n"
	.string "{JPN}また きてください!$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "{JPN}おまちして おりましたよ!\p"
	.string "{JPN}ちょうせんを さいかいする まえに\n"
	.string "{JPN}レポートを かきます!$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}おきゃくさまー!!\p"
	.string "{JPN}ぜんかい ちゃんと レポートを かいて\n"
	.string "{JPN}しゅうりょう しませんでしたね!\p"
	.string "{JPN}ざんねんですが\n"
	.string "{JPN}ちょうせんは むこうと なります!$"

SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "{JPN}おきゃくさまの ポケモンを\n"
	.string "{JPN}おかえしします!$"

SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は\n"
	.string "{JPN}{STR_VAR_1}を もらった!$"

SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "{JPN}バトルトレードの ルールが かかれてる!$"

SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "{JPN}どの せつめいを よみますか?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "{JPN}バトルトレードで つかうことの できる\n"
	.string "{JPN}ポケモンは 3ひき まで です\p"
	.string "{JPN}レンタルするとき トレードするとき\n"
	.string "{JPN}どちらの ときも\l"
	.string "{JPN}おなじ しゅるいの ポケモンを\l"
	.string "{JPN}2ひき いじょう もつことは できません$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "{JPN}トレードが できる あいては\n"
	.string "{JPN}あなたが たたかいで\l"
	.string "{JPN}たおした トレーナーです\p"
	.string "{JPN}トレードで うけとる ことが できるのは\n"
	.string "{JPN}トレーナーが つかっていた ポケモンです$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "{JPN}いちど たたかいに かつ たびに\n"
	.string "{JPN}1かい 1ひき だけ ポケモンを\l"
	.string "{JPN}トレード することが できます\p"
	.string "{JPN}1かいの ちょうせんで\n"
	.string "{JPN}トレードが できるのは\l"
	.string "{JPN}2にんめの トレーナーまで です$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "{JPN}トレードを おこなう ときには\n"
	.string "{JPN}2つ ちゅういする ことが あります\p"
	.string "{JPN}その1 トレードを おこなう ときは\n"
	.string "{JPN}あいてから うけとる ポケモンの\l"
	.string "{JPN}つよさは かくにん できません\p"
	.string "{JPN}その2 ちょうせんを はじめた ときに\n"
	.string "{JPN}かりた レンタルポケモンの じゅんばんが\l"
	.string "{JPN}トレードの あとの たたかいにも\l"
	.string "{JPN}ひきつがれます$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "{JPN}バトルテント カイナの ポケモンは\n"
	.string "{JPN}すべて レンタルポケモン です\p"
	.string "{JPN}レンタルポケモンの レベルは\n"
	.string "{JPN}すべて 30に なります$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "{JPN}バトルテント シダケ かいじょうの\n"
	.string "{JPN}ルールが かかれてる!$"

VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "{JPN}どの せつめいを よみますか?$"

VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "{JPN}バトルテント シダケかいじょう では\n"
	.string "{JPN}ポケモンたちが じぶんで\l"
	.string "{JPN}かんがえ たたかいます\p"
	.string "{JPN}じゅんすいな やせいの ときとは ちがって\n"
	.string "{JPN}ひとと くらしている ポケモンは\l"
	.string "{JPN}せいかくに よって どんな こうどうを\l"
	.string "{JPN}するかが かわるのです$"

VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "{JPN}とにかく こうげきが\n"
	.string "{JPN}すきな せいかく\p"
	.string "{JPN}じぶんの みを まもることが\n"
	.string "{JPN}すきな せいかく\p"
	.string "{JPN}あいてを こまらせたり\n"
	.string "{JPN}かわったことが すきな せいかく\p"
	.string "{JPN}ポケモンは せいかくに よって\n"
	.string "{JPN}すきで とくいな わざと\l"
	.string "{JPN}きらいで にがてな わざが ちがいます$"

VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "{JPN}あいてに むかって じぶんから\n"
	.string "{JPN}ちょくせつ ダメージを あたえる\l"
	.string "{JPN}こうげきの わざ\p"
	.string "{JPN}たたかいの じゅんびや キズついた からだの\n"
	.string "{JPN}かいふくを する ぼうぎょの わざ\p"
	.string "{JPN}あいての のうりょくを さげたり\n"
	.string "{JPN}どくや まひに したり など\l"
	.string "{JPN}すこし かわった ことを する わざ\p"
	.string "{JPN}ポケモンは すべての わざを\n"
	.string "{JPN}おおきく 3つの しゅるいに わけて\l"
	.string "{JPN}どんな わざを だすか かんがえて います$"

VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "{JPN}トレーナーの めいれいを うけて いない\n"
	.string "{JPN}ポケモンは うまく わざを\l"
	.string "{JPN}だせない ことが あります\p"
	.string "{JPN}ポケモンは きらいな わざを\n"
	.string "{JPN}つかうのは とくいでは ありません\p"
	.string "{JPN}せいかくに あわない わざ ばかりを\n"
	.string "{JPN}おぼえさせて いると たたかいで\l"
	.string "{JPN}ポケモンが じぶんの ちからを はっき\l"
	.string "{JPN}できない ことが おおく なります$"

VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "{JPN}ポケモンの せいかくの なかには\n"
	.string "{JPN}ピンチに なることで もともとの\l"
	.string "{JPN}せいかくとは ちがう タイプの\l"
	.string "{JPN}わざを つかう ように\l"
	.string "{JPN}なるものが あります\p"
	.string "{JPN}ピンチに なって すこし かわった\n"
	.string "{JPN}こうどうを はじめた ポケモンには\l"
	.string "{JPN}じゅうぶん ちゅうい しましょう$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "{JPN}バトルテントでは\n"
	.string "{JPN}あなたの ポケモンの レベルに あわせて\l"
	.string "{JPN}たいせんする トレーナーの ポケモンの\l"
	.string "{JPN}レベルが かわります\p"
	.string "{JPN}ただし レベル30より ひくい レベルの\n"
	.string "{JPN}ポケモンを つれた トレーナーが\l"
	.string "{JPN}とうじょう することは ありません$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "{JPN}バトルテント シダケかいじょうの\n"
	.string "{JPN}ルールが かかれている!$"
