BattleDome_Text_Potential1::
	.string "{JPN}こんたいかいの ゆうしょうこうほ ナンバー1!$"

BattleDome_Text_Potential2::
	.string "{JPN}けっしょうまでは かくじつと いわれる チーム.$"

BattleDome_Text_Potential3::
	.string "{JPN}ベスト3に はいる ちからを もった チーム.$"

BattleDome_Text_Potential4::
	.string "{JPN}こんたいかい ゆうしょうこうほの 1チーム.$"

BattleDome_Text_Potential5::
	.string "{JPN}トップクラスの ちからを そなえた チーム.$"

BattleDome_Text_Potential6::
	.string "{JPN}こんたいかい ちゅうもくの ダークホース!$"

BattleDome_Text_Potential7::
	.string "{JPN}へいきんより すこし ちからが うえの チーム.$"

BattleDome_Text_Potential8::
	.string "{JPN}こんたいかいの へいきんてきな チーム.$"

BattleDome_Text_Potential9::
	.string "{JPN}へいきん レベルの ちからを もった チーム.$"

BattleDome_Text_Potential10::
	.string "{JPN}へいきんより やや ちからが おちる チーム.$"

BattleDome_Text_Potential11::
	.string "{JPN}まず 1しょうが もくひょうと なる チーム.$"

BattleDome_Text_Potential12::
	.string "{JPN}1しょう できれば じょうじょうの チーム.$"

BattleDome_Text_Potential13::
	.string "{JPN}ぜんたいの なかで したの レベルの チーム.$"

BattleDome_Text_Potential14::
	.string "{JPN}じつりょくは かなり したの レベルの チーム.$"

BattleDome_Text_Potential15::
	.string "{JPN}ゆうしょうは かなり むずかしい チーム.$"

BattleDome_Text_Potential16::
	.string "{JPN}ゆうしょうから もっとも とおい チーム.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "{JPN}かんぜん むてきの スーパースター!!$"

BattleDome_Text_StyleRiskDisaster::
	.string "{JPN}ときには はめつ かくごで たたかいを いどむ.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "{JPN}ちょうきせんでの ねばりが とても とくい.$"

BattleDome_Text_StyleVariesTactics::
	.string "{JPN}あいてに おうじて たさいな わざで たたかう.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "{JPN}かちパターンを もっていて はまると つよい.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "{JPN}とても めずらしい わざを ときどき つかう.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "{JPN}いひょうを つく わざで たたかいを みだす.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "{JPN}つねに たいりょくに きを くばって たたかう.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "{JPN}ちからを ためて いっきに せめるのが とくい.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "{JPN}あいての ちからを おとすのが とくい.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "{JPN}うんに まかせた たたかいかたを このむ.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "{JPN}おうじゃの ふうかく ただよう せめを する.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "{JPN}PPの すくない おおわざで しょうぶする.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "{JPN}よわらせてから こうげきを するのが とくい.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "{JPN}あらゆる こうげきに たえながら たたかう.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "{JPN}あいての こころを かきみだすのが とくい.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "{JPN}つよくて あつかいやすい わざを つかう.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "{JPN}きょうりょくな わざで どんどん おしまくる.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "{JPN}こうげきを うまく かわしながら たたかう.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "{JPN}あいてが いやがる たたかいが とくい.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "{JPN}にんきの ある わざを たくさん つかう.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "{JPN}きょうりょくな コンボになる わざを もつ.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "{JPN}てがたい わざで きっちりと こうげきする.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "{JPN}はでな わざを つかって どんどん せめる.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "{JPN}まもりより とにかく せめを だいじに する.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "{JPN}せめるより まもりを だいじに する.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "{JPN}つよいわざで しょうぶの しかけが はやい.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "{JPN}ついかこうかが ある わざを よく つかう.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "{JPN}バランスよく いろいろな わざで たちむかう.$"

BattleDome_Text_StyleSampleMessage1::
	.string "{JPN}ダミーメッセージ1です.$"

BattleDome_Text_StyleSampleMessage2::
	.string "{JPN}ダミーメッセージ2です.$"

BattleDome_Text_StyleSampleMessage3::
	.string "{JPN}ダミーメッセージ3です.$"

BattleDome_Text_StyleSampleMessage4::
	.string "{JPN}ダミーメッセージ4です.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "{JPN}HPと こうげきに ちからを いれている.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "{JPN}HPと ぼうぎょに ちからを いれている.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "{JPN}HPと すばやさに ちからを いれている.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "{JPN}HPと とくこうに ちからを いれている.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "{JPN}HPと とくぼうに ちからを いれている.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "{JPN}こうげきと ぼうぎょに ちからを いれている.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "{JPN}こうげきと すばやさに ちからを いれている.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "{JPN}こうげきと とくこうに ちからを いれている.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "{JPN}こうげきと とくぼうに ちからを いれている.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "{JPN}ぼうぎょと すばやさに ちからを いれている.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "{JPN}ぼうぎょと とくこうに ちからを いれている.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "{JPN}ぼうぎょと とくぼうに ちからを いれている.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "{JPN}すばやさと とくこうに ちからを いれている.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "{JPN}すばやさと とくぼうに ちからを いれている.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "{JPN}とくこうと とくぼうに ちからを いれている.$"

BattleDome_Text_EmphasizesHP::
	.string "{JPN}HPに ちからを いれている.$"

BattleDome_Text_EmphasizesAtk::
	.string "{JPN}こうげきに ちからを いれている.$"

BattleDome_Text_EmphasizesDef::
	.string "{JPN}ぼうぎょに ちからを いれている.$"

BattleDome_Text_EmphasizesSpeed::
	.string "{JPN}すばやさに ちからを いれている.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "{JPN}とくこうに ちからを いれている.$"

BattleDome_Text_EmphasizesSpDef::
	.string "{JPN}とくぼうに ちからを いれている.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "{JPN}HPと こうげきに ちからを いれていない!$"

BattleDome_Text_NeglectsHPAndDef::
	.string "{JPN}HPと ぼうぎょに ちからを いれていない!$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "{JPN}HPと すばやさに ちからを いれていない!$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "{JPN}HPと とくこうに ちからを いれていない!$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "{JPN}HPと とくぼうに ちからを いれていない!$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "{JPN}こうげきと ぼうぎょに ちからを いれていない!$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "{JPN}こうげきと すばやさに ちからを いれていない!$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "{JPN}こうげきと とくこうに ちからを いれていない!$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "{JPN}こうげきと とくぼうに ちからを いれていない!$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "{JPN}ぼうぎょと すばやさに ちからを いれていない!$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "{JPN}ぼうぎょと とくこうに ちからを いれていない!$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "{JPN}ぼうぎょと とくぼうに ちからを いれていない!$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "{JPN}すばやさと とくこうに ちからを いれていない!$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "{JPN}すばやさと とくぼうに ちからを いれていない!$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "{JPN}とくこうと とくぼうに ちからを いれていない!$"

BattleDome_Text_NeglectsHP::
	.string "{JPN}HPには ちからを いれていない!$"

BattleDome_Text_NeglectsAtk::
	.string "{JPN}こうげきには ちからを いれていない!$"

BattleDome_Text_NeglectsDef::
	.string "{JPN}ぼうぎょには ちからを いれていない!$"

BattleDome_Text_NeglectsSpeed::
	.string "{JPN}すばやさには ちからを いれていない!$"

BattleDome_Text_NeglectsSpAtk::
	.string "{JPN}とくこうには ちからを いれていない!$"

BattleDome_Text_NeglectsSpDef::
	.string "{JPN}とくぼうには ちからを いれていない!$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "{JPN}バランスよく ポケモンを そだてている.$"

BattleDome_Text_LetTheBattleBegin::
	.string "{JPN}これより たいけつ!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{JPN}{STR_VAR_2} などで {STR_VAR_1}が しょうり!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{JPN}{STR_VAR_2} などで {STR_VAR_1} ゆうしょう!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{JPN}あいての リタイアで {STR_VAR_1}が しょうり!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{JPN}あいての リタイアで {STR_VAR_1} ゆうしょう!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{JPN}わざを つかわずに {STR_VAR_1}が しょうり!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{JPN}わざを つかわずに {STR_VAR_1} ゆうしょう!$"

BattleDome_Text_Round1Match1::
	.string "{JPN} 1かいせん だい1しあい$"

BattleDome_Text_Round1Match2::
	.string "{JPN} 1かいせん だい2しあい$"

BattleDome_Text_Round1Match3::
	.string "{JPN} 1かいせん だい3しあい$"

BattleDome_Text_Round1Match4::
	.string "{JPN} 1かいせん だい4しあい$"

BattleDome_Text_Round1Match5::
	.string "{JPN} 1かいせん だい5しあい$"

BattleDome_Text_Round1Match6::
	.string "{JPN} 1かいせん だい6しあい$"

BattleDome_Text_Round1Match7::
	.string "{JPN} 1かいせん だい7しあい$"

BattleDome_Text_Round1Match8::
	.string "{JPN} 1かいせん だい8しあい$"

BattleDome_Text_Round2Match1::
	.string "{JPN} 2かいせん だい1しあい$"

BattleDome_Text_Round2Match2::
	.string "{JPN} 2かいせん だい2しあい$"

BattleDome_Text_Round2Match3::
	.string "{JPN} 2かいせん だい3しあい$"

BattleDome_Text_Round2Match4::
	.string "{JPN} 2かいせん だい4しあい$"

BattleDome_Text_SemifinalMatch1::
	.string "{JPN}じゅんけっしょう だい1しあい$"

BattleDome_Text_SemifinalMatch2::
	.string "{JPN}じゅんけっしょう だい2しあい$"

BattleDome_Text_FinalMatch::
	.string "{JPN}    けっしょうせん$"
