PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "{JPN}パパ: やあ {PLAYER}!\p"
	.string "{JPN}めずらしい きのみを てに いれたから\n"
	.string "{JPN}プレゼント するよ!$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "{JPN}ふかふかの つちに はえている きのみは\n"
	.string "{JPN}じゆうに とっても よいのじゃが...\p"
	.string "{JPN}1つだけ きのみを おなじ ばしょに うめる\n"
	.string "{JPN}それが れいぎと いうものじゃ\p"
	.string "{JPN}ほれ これを わけてやろう$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "{JPN}あんた みたところ トレーナーじゃろ?\p"
	.string "{JPN}トレーナーは よく きのみを ポケモンに\n"
	.string "{JPN}もたせとるわい\p"
	.string "{JPN}ふやすも つかうも あんた しだいじゃ$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "{JPN}いつも みずを あげてたら\n"
	.string "{JPN}たくさん はなが さいたんだ\p"
	.string "{JPN}そしたら きのみも たくさん できた!\p"
	.string "{JPN}はい!\n"
	.string "{JPN}これ あげる$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "{JPN}がんばって いろんな いろの\n"
	.string "{JPN}きのみを そだてるんだ!\l"
	.string "{JPN}{STR_VAR_1}も がんばってね!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "{JPN}きょうは なにいろの きのみを\n"
	.string "{JPN}さがそっかなー$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "{JPN}きのみクラッシュが だいすきだから\n"
	.string "{JPN}きのみを あつめているんだ\p"
	.string "{JPN}よかったら きみにも わけて あげるよ!$"

Route114_Text_TryBerryCrushWithFriends:
	.string "{JPN}きみも ともだちと\n"
	.string "{JPN}きのみクラッシュ やってみなよ!$"

Route114_Text_FunToThinkAboutBerries:
	.string "{JPN}どの きのみを うめるか?\n"
	.string "{JPN}きのみは つかうのか ふやすのか?\p"
	.string "{JPN}って なやむのも また たのしいよ$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "{JPN}ひかりを いっぱい あびて\n"
	.string "{JPN}そだつ きのみたち...\p"
	.string "{JPN}そして きのみが げんきに そだつように\n"
	.string "{JPN}じょうろで みずを あげる わたしたち...\p"
	.string "{JPN}これって あい だよね?$"

Route120_Text_YesYouUnderstand:
	.string "{JPN}うん うん!\n"
	.string "{JPN}やっぱ わかるひとには わかるよね\p"
	.string "{JPN}これ あげる$"

Route120_Text_MakeYourOwnImpressions:
	.string "{JPN}そっか...\n"
	.string "{JPN}でも ちがうと かんじることも たいせつだね\p"
	.string "{JPN}これ あげる$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "{JPN}その きのみは めずらしいもの らしいから\n"
	.string "{JPN}たいせつに そだててね!$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "{JPN}また きのみめいじんに もらって こようっと$"

LilycoveCity_Text_BerrySuitsYou:
	.string "{JPN}やっぱり\p"
	.string "{JPN}わたしに スーツが にあうように\n"
	.string "{JPN}うみには しおかぜが にあうな\l"
	.string "{JPN}そして きみには きのみが にあいそうだ...\p"
	.string "{JPN}なんでだろうね?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "{JPN}やっぱり それは......\p"
	.string "{JPN}きみが トレーナーだからだ!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "{JPN}やっぱり\p"
	.string "{JPN}わたしに シンプルさが にあうように\n"
	.string "{JPN}ポケモンには ポロックが にあうな$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "{JPN}わしは きのみめいじんと よばれておる\p"
	.string "{JPN}わしは せかいじゅうを うつくしい はなで\n"
	.string "{JPN}うめつくそうと きのみを そだてて\l"
	.string "{JPN}そして くばり まくって おるのじゃ\p"
	.string "{JPN}きみにも きのみを わけて あげよう!$"

Route123_BerryMastersHouse_Text_YoureDeservingOfMulch:
	.string "{JPN}ほれ えんりょ せずに もう ひとつ!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "{JPN}カナズミの ちかくにある サン·トウカという\n"
	.string "{JPN}フラワーショップも よろしくの\p"
	.string "{JPN}せかいに はなを さかせましょう!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "{JPN}きょうは もう おしまいじゃ\n"
	.string "{JPN}また おいで\p"
	.string "{JPN}せかいに はなを さかせましょう!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "{JPN}じいさんの きのみの そだてかたは\n"
	.string "{JPN}そりゃあ せかいいちじゃ\p"
	.string "{JPN}わしも はなが たかいわい\p"
	.string "{JPN}ところで あんた\n"
	.string "{JPN}いい ことばを きいたことが ないかい?$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "{JPN}おお! とても よい ことばじゃ!\n"
	.string "{JPN}かんどう したわい\p"
	.string "{JPN}ほれ これを もっていきなされ$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "{JPN}おお! なかなか よい ことばじゃ\n"
	.string "{JPN}あんたも たいしたもんじゃ\p"
	.string "{JPN}ほれ これを もっていきなされ$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "{JPN}まごたち 4にんも じいさんを しのぐ\n"
	.string "{JPN}おおものに なるじゃろうて\p"
	.string "{JPN}じんせい たのしいことが つきんのう!$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "{JPN}ほう...$"

Route123_BerryMastersHouse_Text_Ah:
	.string "{JPN}あら...$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "{JPN}こんにちは!\p"
	.string "{JPN}はなを せかいに ひろめる\n"
	.string "{JPN}フラワーショップ サン·トウカです!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{JPN}{PLAYER}{KUN} きのみの こと しりたい?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "{JPN}あなたの なまえは...\p"
	.string "{JPN}{PLAYER}{KUN}ね!\n"
	.string "{JPN}とっても いい なまえだね!\l"
	.string "{JPN}{PLAYER}{KUN} きのみのこと しりたい?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "{JPN}きのみはね くろい ふかふかの つちの\n"
	.string "{JPN}ところで たまに とれるの\l"
	.string "{JPN}でね...\p"
	.string "{JPN}とったら その1つを また うめるの!\p"
	.string "{JPN}そうすると その きのみ から\n"
	.string "{JPN}めがでて みきが できて はながさいて\l"
	.string "{JPN}また きのみ が できるの\p"
	.string "{JPN}そうやって はなを ふやして\n"
	.string "{JPN}せかいじゅうを はなに するのが\l"
	.string "{JPN}わたしの ゆめ なんだ!\p"
	.string "{JPN}だから {PLAYER}{KUN}も きのみを うめて\n"
	.string "{JPN}せかいに はなを ふやしてね!$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "{JPN}おはなって とっても しあわせな きぶんに\n"
	.string "{JPN}してくれるよね$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "{JPN}こんにちは!\p"
	.string "{JPN}おはなは せわを すれば するほど\n"
	.string "{JPN}たくさん きれいに さいて くれるの\p"
	.string "{JPN}あなたも せわを したく なった でしょ?\n"
	.string "{JPN}これ あげるわ$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "{JPN}きのみが そだつ たびに\n"
	.string "{JPN}じょうろで みずを あげてね!\p"
	.string "{JPN}あとね\p"
	.string "{JPN}きのみは ずっと ずっと ほうっておくと\n"
	.string "{JPN}じめんに おちてしまうの\l"
	.string "{JPN}でもね そこから また めがでて くるの!\p"
	.string "{JPN}すごいよね!\n"
	.string "{JPN}いきものの ちからを かんじるよね$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "{JPN}おねーちゃんたちを みならって\n"
	.string "{JPN}がんばって おはなを そだててるの\p"
	.string "{JPN}はい! これあげる!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "{JPN}きのみは うめて おおきく したり\n"
	.string "{JPN}ポケモンに もたせたり できるの\p"
	.string "{JPN}でも さいきん きのみを いくつか まぜると\n"
	.string "{JPN}ポケモンの おかしになる きかいが\l"
	.string "{JPN}ある らしいんだ\p"
	.string "{JPN}あたしも おかし ほしー$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "{JPN}{STR_VAR_1} なまえ なんていうの?\p"
	.string "...... ...... ......\n"
	.string "{JPN}へー いいねー\p"
	.string "{JPN}わたしは キリ っていう なまえなの\p"
	.string "{JPN}パパと ママが すくすくと そだって\n"
	.string "{JPN}こころの あたたかい おんなのこに なって\l"
	.string "{JPN}ほしいっていう ねがいを こめたんだって!\p"
	.string "{JPN}{STR_VAR_1}にも これ あげる$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "{JPN}あと {STR_VAR_1}には キリの だいすきな\n"
	.string "{JPN}この きのみも あげちゃう!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "{JPN}{STR_VAR_1}の なまえには\n"
	.string "{JPN}どんな ねがいが こめられてるの?$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "{JPN}はる なつ あき ふゆ\n"
	.string "{JPN}はるに うまれると はるが すきで\l"
	.string "{JPN}なつに うまれると なつが すきなのかな?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "{JPN}じゃあ キリは あきに うまれたから\n"
	.string "{JPN}あきが だいすき!\p"
	.string "{JPN}{STR_VAR_1}は いつが すき?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "{JPN}そっか...\n"
	.string "{JPN}かんけいないのか...\p"
	.string "{JPN}しりたいことって たくさんあるなー$"
