gText_Birch_Welcome::
	.string "{JPN}いやあ またせた!\p"
	.string "{JPN}ポケットモンスターの\nせかいへ ようこそ!\p"
	.string "{JPN}わしの なまえは オーキド\p"
	.string "{JPN}みんなからは ポケモンはかせと\nしたわれておるよ\p"
	.string "{JPN}ところで きみは\nぼうけんは はじめてかな?\p"
	.string "{JPN}まずは わしが\nこのせかいのことを おしえよう!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "{JPN}このせかいには\nポケットモンスター...\l"
	.string "{JPN}ちぢめて ポケモンと\l"
	.string "{JPN}よばれている いきものたちが\l"
	.string "{JPN}いたるところに すんでいる!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "{JPN}われわれ にんげんは\nポケモンと なかよく くらしている\p"
	.string "{JPN}いっしょに あそんだり\nちからを あわせて しごとをしたり\p"
	.string "{JPN}そして ポケモンどうしを たたかわせ\nきずなを ふかめていったり...\p"
	.string "{JPN}わしは そんな ポケモンのことを\nくわしく しるために\p"
	.string "{JPN}まいにち けんきゅうを\nつづけている というわけじゃ!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "{JPN}さて... そろそろ\nきみのことを おしえてもらおう!"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "{JPN}きみは おとこのこかな?\nそれとも おんなのこかな?\lどちらか おしえてくれ"
	.string "$"

gText_Birch_Difficulty::
	.string "{JPN}なるほど\p"
	.string "{JPN}それで この ぼうけんは\nどんなものになると おもうかね"
	.string "$"

gText_Birch_LockDifficulty::
	.string "{JPN}なんいどを かえたければ\nオプションメニューから\lかえることが できるぞ\p"
	.string "{JPN}こていすることも できる\nいま えらんだ なんいどを\lこていするかね\p"
	.string "{JPN}あとで かえることは できん"
	.string "$"

gText_Birch_Challenge::
	.string "{JPN}そうか\p"
	.string "{JPN}よし それなら\nたびで チャレンジは\lきたいするかね\p"
	.string "{JPN}そして きみの なまえは"
	.string "$"

gText_Birch_WhatsYourName::
	.string "{JPN}では なまえを おしえてくれ!"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "{JPN}{PLAYER}{KUN}じゃな?"
	.string "$"

gText_Birch_YourePlayer::
	.string "{JPN}{PLAYER}!!\nじゅんびは いいかな?\p"
	.string "{JPN}いよいよ これから\nきみだけの ものがたりが はじまる!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{JPN}たのしいことも くるしいことも\nいっぱい きみを まっているだろう!\p"
	.string "{JPN}ゆめと ぼうけんと!\nポケットモンスターの せかいへ!\l"
	.string "{JPN}レッツゴー!\p"
	.string "{JPN}では また あとで あおう!\p"
	.string "$"
