BerryBlender_Text_BlendWithTheBlendMaster:
	.string "{JPN}めいじん: いかにも!\n"
	.string "{JPN}わしが ブレンドめいじん じゃ!\p"
	.string "{JPN}いっしょに まわして\n"
	.string "{JPN}わしの すごい わざを みるがよい$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "{JPN}めいじん: ふむむむっ! おぬし\n"
	.string "{JPN}わしの すごい わざを みたいのじゃな?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "{JPN}ふむむむっ!\p"
	.string "{JPN}いまは いそがしいのじゃな!\p"
	.string "{JPN}あんしん するのじゃ!\n"
	.string "{JPN}わしは きょう ずっと ここに おる\l"
	.string "{JPN}ようが すんだら すぐに くるのじゃぞ!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "{JPN}ふむむむっ!\p"
	.string "{JPN}おぬし きのみを もっておらんぞ!\p"
	.string "{JPN}わしは きょう ずっと ここに おるから\n"
	.string "{JPN}はやく きのみを みつけて くるのじゃぞ!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "{JPN}そうじゃろう!\n"
	.string "{JPN}そうじゃろう!\p"
	.string "{JPN}とろころで おぬし...\n"
	.string "{JPN}むろん ポロックの つくりかたは\l"
	.string "{JPN}しっておる じゃろうな?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "{JPN}ふむむむっ!\p"
	.string "{JPN}まあ かんたんな ことじゃ!\p"
	.string "{JPN}きのみ ブレンダーの マークが\n"
	.string "{JPN}じぶんの ところに きたら\l"
	.string "{JPN}ボタンを おせば いいだけじゃ!\p"
	.string "{JPN}わしの かんぺきな おしかたを みれば\n"
	.string "{JPN}すぐに わかるはずじゃ!$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "{JPN}よしっ!\p"
	.string "{JPN}では はじめるぞ!\p"
	.string "{JPN}めいじんと いっしょに\n"
	.string "{JPN}レッツ きのみブレンダー!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "{JPN}ふむむむっ!\p"
	.string "{JPN}おぬし ポロックケースを\n"
	.string "{JPN}まだ もっておらん ようじゃぞ!\p"
	.string "{JPN}わしは きょう ずっと ここに おるから\n"
	.string "{JPN}ポロックケースを もらってから\l"
	.string "{JPN}また くるのじゃ!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "{JPN}ふむむむっ!\p"
	.string "{JPN}おぬし ポロックケースが\n"
	.string "{JPN}いっぱいの ようじゃぞ!\p"
	.string "{JPN}わしは きょう ずっと ここに おるから\n"
	.string "{JPN}ポロックを へらしてから\l"
	.string "{JPN}また くるのじゃ!$"

BerryBlender_Text_WhoaAwesome:
	.string "{JPN}すげぇー!$"

BerryBlender_Text_WickedlyFast:
	.string "{JPN}はぇー!$"

BerryBlender_Text_WhatAnExpert:
	.string "{JPN}うめぇー!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "{JPN}めいじんと いっしょに やったら\n"
	.string "{JPN}とっても すごい ポロック できたの$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "{JPN}やじるしを おっていく\n"
	.string "{JPN}スキのない めの うごき!\p"
	.string "{JPN}ボタンを おすときの\n"
	.string "{JPN}せいかくな ての うごき!\p"
	.string "{JPN}この ふたつを あわせもつ\n"
	.string "{JPN}めいじんは ホント すごいね!$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "{JPN}めいじんは どこかの やまおくで\n"
	.string "{JPN}しゅぎょう しているらしいの\p"
	.string "{JPN}そして ときどき\n"
	.string "{JPN}ミナモシティに やってきて\l"
	.string "{JPN}きのみブレンダーを 1にちじゅう\l"
	.string "{JPN}するらしいわ$"
