CableClub_Text_WelcomeWhichCableClubService:
	.string "{JPN}つうしん ケーブル クラブに\n"
	.string "{JPN}ようこそ!\p"
	.string "{JPN}どちらを ごりよう ですか?$"

CableClub_Text_WhichService:
	.string "{JPN}どちらを ごりよう ですか?$"

CableClub_Text_TradeUsingLinkCable::
	.string "{JPN}ケーブルで つないだ おともだちと\n"
	.string "{JPN}ポケモン こうかんが できます$"

CableClub_Text_BattleUsingLinkCable::
	.string "{JPN}ケーブルで つないだ おともだちと\n"
	.string "{JPN}ポケモン たいせんが できます$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "{JPN}ケーブルで つないだ おともだちと\n"
	.string "{JPN}レコードコーナーが できます$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "{JPN}おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "{JPN}ダブルバトルでは 2ひき いじょうの\n"
	.string "{JPN}ポケモンが ひつようです$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "{JPN}こうかんでは 2ひき いじょうの\n"
	.string "{JPN}てもちが ひつようです$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "{JPN}{STR_VAR_1}のみを もっている\n"
	.string "{JPN}ポケモンは こうかん できません!$"

gText_PleaseWaitForLink::
	.string "{JPN}しょうしょう おまち ください\n"
	.string "{JPN}...Bボタンで キャンセル$"

gText_ConfirmLinkWhenPlayersReady::
	.string "{JPN}そろったら Aボタンで すすむ\n"
	.string "{JPN}...Bボタンで キャンセル$"

gText_ConfirmStartLinkWithXPlayers::
	.string "{JPN}{STR_VAR_1}にんで つうしんを はじめます\n"
	.string "{JPN}Aボタン...けってい Bボタン...もどる$"

gText_AwaitingLinkup::
	.string "{JPN}つうしんかいしを まっています\n"
	.string "{JPN}...Bボタンで キャンセル$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "{JPN}はじめる まえに レポートを\n"
	.string "{JPN}かきますが よろしいですか?$"

CableClub_Text_PleaseEnter:
	.string "{JPN}それでは へやへ どうぞ$"

CableClub_Text_DirectYouToYourRoom:
	.string "{JPN}それでは\n"
	.string "{JPN}へやに ごあんないします$"

Text_SomeoneIsNotReadyToLink:
	.string "{JPN}おともだちの じゅんびが\n"
	.string "{JPN}できて いない ようです\p"
	.string "{JPN}じゅんびが できましたら\n"
	.string "{JPN}また おこしください$"

Text_LinkErrorPleaseReset:
	.string "{JPN}つうしんエラー です\n"
	.string "{JPN}リセットして やりなおしてください$"

Text_PlayersMadeDifferentSelections:
	.string "{JPN}おたがいが えらんだ ものが\n"
	.string "{JPN}ちがっている ようです$"

CableClub_Text_PleaseVisitAgain:
	.string "{JPN}それでは また おこしください$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "{JPN}さんかしている にんずうが\n"
	.string "{JPN}ただしく ありません$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "{JPN}シングルバトルは {STR_VAR_1}にんで\n"
	.string "{JPN}あそぶことは できません!$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "{JPN}ダブルバトルは {STR_VAR_1}にんでは\n"
	.string "{JPN}あそぶことは できません!$"

CableClub_Text_NeedFourPlayers:
	.string "{JPN}さんか にんずうが 4にん いないと\n"
	.string "{JPN}たいせん することが できません!$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "{JPN}もういちど にんずうを たしかめて\n"
	.string "{JPN}はじめから やりなおして ください$"

Text_TerminateLinkConfirmation:
	.string "{JPN}へやからでると つうしんが\n"
	.string "{JPN}おわりますが よろしいですか?$"

Text_TerminateLinkPleaseWait:
	.string "{JPN}つうしんを しゅうりょう します\n"
	.string "{JPN}しばらく おまちください$"

CableClub_Text_TooBusyToNotice:
	.string "{JPN}とりこみちゅうの ようだ...$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "{JPN}{STR_VAR_1}の トレーナーカードを\n"
	.string "{JPN}みせてもらった!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "{JPN}{STR_VAR_1}の トレーナーカードを\n"
	.string "{JPN}みせてもらった!\p"
	.string "{JPN}...{STR_VAR_2}カードだ!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "{JPN}しょていの いちに ついて\n"
	.string "{JPN}たいせんを はじめて ください$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "{JPN}しょていの いちに ついて\n"
	.string "{JPN}こうかんを はじめて ください$"

RecordCorner_Text_ThanksForComing:
	.string "{JPN}ごりよう ありがとう ございました$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "{JPN}トレーナーカードの\n"
	.string "{JPN}きろくを かきかえます!$"

CableClub_Text_HopeToSeeYouAgain:
	.string "{JPN}では また どうぞ!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "{JPN}おきゃくさま\n"
	.string "{JPN}もうしわけ ありません\p"
	.string "{JPN}とおい ちほうの かたと\n"
	.string "{JPN}ポケモンを こうかん することは\l"
	.string "{JPN}いまは できません...$"

CableClub_Text_OtherTrainerNotReady:
	.string "{JPN}あいての じゅんびが\n"
	.string "{JPN}できていません$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "{JPN}てもちに つれていけない\n"
	.string "{JPN}ポケモンが います$"

RecordCorner_Text_TakeSeatAndWait:
	.string "{JPN}しょていの いちに ついて\n"
	.string "{JPN}おまち ください$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{JPN}{STR_VAR_1}さんから\n"
	.string "{JPN}{STR_VAR_2}が おくられてきた!$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "{JPN}ワイヤレスアダプタが\n"
	.string "{JPN}つながって いません$"

CableClub_Text_AdapterNotConnected:
	.string "{JPN}さんか したい ひとは\n"
	.string "{JPN}カウンターに おこしください$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "{JPN}こんにちは!$"

@ Unused
CableClub_Text_Hello:
	.string "{JPN}しょうしょう おまちください$"

@ Unused
CableClub_Text_PleaseWait:
	.string "{JPN}ともだちと ポケモンの\n"
	.string "{JPN}こうかんが たのしめます$"

CableClub_Text_YouMayTradeHere::
	.string "{JPN}ともだちと ポケモンの\n"
	.string "{JPN}たいせんが たのしめます$"

CableClub_Text_YouMayBattleHere::
	.string "{JPN}2にんから 5にんの ともだちと\n"
	.string "{JPN}きのみで こなを つくります$"

CableClub_Text_CanMakeBerryPowder::
	.string "{JPN}2にんから 4にんの ともだちと\n"
	.string "{JPN}レコードを まぜます$"

CableClub_Text_CanMixRecords::
	.string "{JPN}ワイヤレス クラブでの\n"
	.string "{JPN}あそびかたを せつめいします$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "{JPN}やめます$"

CableClub_Text_CancelSelectedItem::
	.string "{JPN}どちらの しょうぶに しますか?$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "{JPN}ひとつ まえに もどります$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "{JPN}きのみを もって いないと\n"
	.string "{JPN}きのみクラッシュは できません$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "{JPN}ユニオンルームに はいるには\n"
	.string "{JPN}2ひき いじょうの ポケモンを\l"
	.string "{JPN}もって おこしください$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "{JPN}{STR_VAR_1}のみを もっている\n"
	.string "{JPN}ポケモンを おもちの かたは\l"
	.string "{JPN}ユニオンルームには はいれません...$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "{JPN}こちらは\n"
	.string "{JPN}ポケモン ワイヤレス クラブ\l"
	.string "{JPN}ユニオン ルームです\p"
	.string "{JPN}ワイヤレスアダプタが\n"
	.string "{JPN}つながって いません\p"
	.string "{JPN}また おこしください$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "{JPN}あ...\n"
	.string "{JPN}おきゃくさま!$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "{JPN}あ...\n"
	.string "{JPN}おきゃくさま!$"

CableClub_Text_PlayerIsWaiting:
	.string "{JPN}あら! いま {STR_VAR_1}さんも\n"
	.string "{JPN}プレイちゅう みたいですね\l"
	.string "{JPN}がんばって くださいね!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "{JPN}ぼくは ゲームの せつめいを\n"
	.string "{JPN}しますよ!\l"
	.string "{JPN}どの せつめいを ききますか?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "{JPN}‘ミニポケモンでジャンプ’は\n"
	.string "{JPN}ツルの なわを Aボタンで\l"
	.string "{JPN}タイミングよく とぶ ゲームです\p"
	.string "{JPN}さんか できる ポケモンは\n"
	.string "{JPN}たかさ 70センチくらい までの\l"
	.string "{JPN}ちいさい ポケモンに なります\p"
	.string "{JPN}もぐっていたり とんでいたり する\n"
	.string "{JPN}ポケモンは ジャンプが\l"
	.string "{JPN}じょうずに できないので\l"
	.string "{JPN}ざんねんながら さんか できません\p"
	.string "{JPN}みんなの ジャンプの タイミングが\n"
	.string "{JPN}ピッタリ あえば\l"
	.string "{JPN}よいことが ありますよ!$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "{JPN}‘ドードリオのきのみどり’は\n"
	.string "{JPN}ドードリオの 3つの あたまに\l"
	.string "{JPN}めいれいして うえから おちてくる\l"
	.string "{JPN}きのみを おとさないように\l"
	.string "{JPN}とりつづける ゲームです\p"
	.string "{JPN}じゅうじボタンの\n"
	.string "{JPN}うえ みぎ ひだりを つかいます\p"
	.string "{JPN}この ゲームを あそぶには\n"
	.string "{JPN}ドードリオが ひつようです$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "{JPN}ゲームを するなら\n"
	.string "{JPN}おとなりの おじいさんに いってね$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "{JPN}やあ いらっしゃい\n"
	.string "{JPN}ワイヤレスつうしんの ゲームかな?\l"
	.string "{JPN}ちょっと まってね$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "{JPN}また おいでね$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "{JPN}ワイヤレスアダプタを つなげて\n"
	.string "{JPN}あそびに おいで!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "{JPN}さて どの ゲームを\n"
	.string "{JPN}やりたいのかな?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "{JPN}どの ポケモンを\n"
	.string "{JPN}さんか させるのかな?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "{JPN}じゅんびが できたよ\n"
	.string "{JPN}げんきに あそんで おいで!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "{JPN}きょうは かえるのかい?\n"
	.string "{JPN}また おいでね$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "{JPN}ゲームに さんかできる\n"
	.string "{JPN}ポケモンを もって いないんだね\p"
	.string "{JPN}だれが さんか できるか\n"
	.string "{JPN}せつめいを しようか?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "{JPN}‘ミニポケモンでジャンプ’に\n"
	.string "{JPN}さんか できる ポケモンは\l"
	.string "{JPN}たかさ 70センチくらい までだよ\p"
	.string "{JPN}じめんに もぐったり\n"
	.string "{JPN}うかんでいる ポケモンは\l"
	.string "{JPN}ジャンプ できないから\l"
	.string "{JPN}でられないんだよ$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "{JPN}‘ドードリオのきのみどり’は\n"
	.string "{JPN}ドードリオ だけが\l"
	.string "{JPN}さんか できる ゲームなんだよ$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "{JPN}もういちど はじめから\n"
	.string "{JPN}やりなおして みて くれるかな?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "{JPN}ポケモン ワイヤレス クラブ\n"
	.string "{JPN}ダイレクト コーナーに ようこそ!\p"
	.string "{JPN}こちらでは ともだちと ちょくせつ\n"
	.string "{JPN}やりとり できます\p"
	.string "{JPN}どの へやに はいりますか?$"

CableClub_Text_TradePokemon:
	.string "{JPN}こうかんを しますか?$"

CableClub_Text_PlayWhichBattleMode:
	.string "{JPN}どちらの たいせんを しますか?$"

CableClub_Text_AccessRecordCorner:
	.string "{JPN}レコードコーナーを しますか?$"

CableClub_Text_UseBerryCrush:
	.string "{JPN}きのみクラッシュを しますか?$"

CableClub_Text_ExplainBattleModes:
	.string "{JPN}たいせんには 3しゅるいの\n"
	.string "{JPN}モードが あります\p"
	.string "{JPN}シングルバトルは たたかいの ばに\n"
	.string "{JPN}ポケモンを 1ひきだして\l"
	.string "{JPN}ふたりで たいせんします\p"
	.string "{JPN}ダブルバトルは たたかいの ばに\n"
	.string "{JPN}ポケモンを 2ひきずつ だして\l"
	.string "{JPN}ふたりで たいせんします\p"
	.string "{JPN}マルチバトルは たたかいの ばに\n"
	.string "{JPN}4にんで ポケモンを 1ひきずつ\l"
	.string "{JPN}だして 2たい2で たいせんします$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "{JPN}ふたりで はなしあって ひとりが\n"
	.string "{JPN}リーダーに なってください\p"
	.string "{JPN}もうひとりは グループにはいる を\n"
	.string "{JPN}えらんでください$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "{JPN}4にんで はなしあって ひとりが\n"
	.string "{JPN}グループリーダーに なってください\p"
	.string "{JPN}ほかの ひとは グループにはいる を\n"
	.string "{JPN}えらんで ください$"

CableClub_Text_ChooseGroupLeader:
	.string "{JPN}みんなで はなしあって ひとりが\n"
	.string "{JPN}グループリーダーに なってください\p"
	.string "{JPN}ほかの ひとは グループにはいる を\n"
	.string "{JPN}えらんでください$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "{JPN}ポケモン ワイヤレス クラブ\n"
	.string "{JPN}ユニオン ルームに ようこそ!\p"
	.string "{JPN}こちらでは みしらぬ ともだちと\n"
	.string "{JPN}やりとり できます\p"
	.string "{JPN}へやに はいりますか?$"

CableClub_Text_UnionRoomInfo:
	.string "{JPN}ユニオン ルーム は あなたの\n"
	.string "{JPN}ちかくで ユニオン ルームに\l"
	.string "{JPN}はいっている ひとが あらわれます\p"
	.string "{JPN}かんたんな あいさつをしたり\p"
	.string "{JPN}レベル30までの ポケモン2ひきで\n"
	.string "{JPN}1たい1の たいせん\p"
	.string "{JPN}2にんから 5にんまで どうじに\n"
	.string "{JPN}おしゃべりが できる チャット\p"
	.string "{JPN}そして とうろくしき\n"
	.string "{JPN}ポケモン こうかんが たのしめます\p"
	.string "{JPN}へやに はいりますか?$"

CableClub_Text_EnjoyUnionRoom:
	.string "{JPN}それでは ユニオン ルームで\n"
	.string "{JPN}おたのしみ ください$"

CableClub_Text_FirstTimeRightThisWay:
	.string "{JPN}こんにちは!\p"
	.string "{JPN}ワイヤレス つうしんが\n"
	.string "{JPN}はじめての かたですね?\p"
	.string "{JPN}わたくし あんないやくの\n"
	.string "{JPN}アオナと もうします\p"
	.string "{JPN}ポケモンセンター 2かいの\n"
	.string "{JPN}ごあんないを いたしますので\l"
	.string "{JPN}こちらへ どうぞ!$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "{JPN}こちら 2かいには\n"
	.string "{JPN}ふたつの おへやが ございます\p"
	.string "{JPN}ひとつめは ひだりがわの おへや\n"
	.string "{JPN}ユニオン ルーム!\p"
	.string "{JPN}あなたの ちかくで\n"
	.string "{JPN}ユニオン ルームに はいっている\l"
	.string "{JPN}みしらぬ おともだちと\l"
	.string "{JPN}いろいろな コミュニケーションが\l"
	.string "{JPN}たのしめます!\p"
	.string "{JPN}ふたつめは みぎがわの おへや\n"
	.string "{JPN}ダイレクト コーナー!\p"
	.string "{JPN}あなたの しっている おともだちと\n"
	.string "{JPN}ポケモンの こうかんや\l"
	.string "{JPN}たいせん などを\l"
	.string "{JPN}たのしむ ことが できます!\p"
	.string "{JPN}もし ワイヤレスアダプタが\n"
	.string "{JPN}つながって いない ばあいでも\p"
	.string "{JPN}みぎがわの おへやで\n"
	.string "{JPN}ケーブル つうしんが たのしめます\p"
	.string "{JPN}それでは\p"
	.string "{JPN}ワイヤレス つうしんを\n"
	.string "{JPN}たのしんで くださいね!$"

CableClub_Text_AskAboutLinking:
	.string "{JPN}こんにちは! {PLAYER}さん!\p"
	.string "{JPN}ポケモンセンター 2かいの\n"
	.string "{JPN}あんないやく アオナです\p"
	.string "{JPN}なにか つうしんで おこまりですか?$"

CableClub_Text_ExplainWirelessClub:
	.string "{JPN}ポケモン ワイヤレス クラブでの\n"
	.string "{JPN}あそびかたを せつめい します!\p"
	.string "{JPN}こちら 2かいには\n"
	.string "{JPN}ふたつの おへやが ございます\p"
	.string "{JPN}ひとつめは ひだりがわの おへや\n"
	.string "{JPN}ユニオン ルーム!\p"
	.string "{JPN}あなたの ちかくで\n"
	.string "{JPN}ユニオン ルームに はいっている\l"
	.string "{JPN}みしらぬ おともだちと\l"
	.string "{JPN}いろいろな コミュニケーションが\l"
	.string "{JPN}たのしめます!\p"
	.string "{JPN}ふたつめは みぎがわの おへや\n"
	.string "{JPN}ダイレクト コーナー!\p"
	.string "{JPN}あなたの しっている おともだちと\n"
	.string "{JPN}ポケモンの こうかんや\l"
	.string "{JPN}たいせん などを\l"
	.string "{JPN}たのしむ ことが できます!\p"
	.string "{JPN}もし ユニオン ルームや\n"
	.string "{JPN}ダイレクト コーナーで\l"
	.string "{JPN}おともだちが みつからない ときは\p"
	.string "{JPN}もうすこし おともだちと\n"
	.string "{JPN}ちかづいて みて ください\p"
	.string "{JPN}また ワイヤレスアダプタが\n"
	.string "{JPN}つながって いない ばあいでも\p"
	.string "{JPN}みぎがわの おへやで\n"
	.string "{JPN}ケーブル つうしんが たのしめます\p"
	.string "{JPN}それでは\p"
	.string "{JPN}ワイヤレス つうしんを\n"
	.string "{JPN}たのしんで くださいね!$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "{JPN}ポケモン ワイヤレス クラブで\n"
	.string "{JPN}おたのしみ ください$"
