Text_PictureBookShelf:
	.string "{JPN}ポケモンえほんが そろってる!$"

Text_BookShelf:
	.string "{JPN}いろんな ほんが いっぱいだ!$"

Text_PokemonCenterBookShelf:
	.string "{JPN}ポケモンざっしが ならんでる!\p"
	.string "{JPN}...‘ポケモンのとも’\n"
	.string "{JPN}...‘ポケモン てちょう’\l"
	.string "{JPN}...‘かわいい ポケモン’$"

Text_Vase:
	.string "{JPN}たかそうな つぼが ある!\n"
	.string "{JPN}のぞきこむと...\p"
	.string "{JPN}なかは からっぽ だ!$"

Text_EmptyTrashCan:
	.string "{JPN}なかは からっぽ だ!$"

Text_ShopShelf:
	.string "{JPN}たくさんの ポケモン グッズが\n"
	.string "{JPN}ところせましと ならべられてる!$"

Text_Blueprint:
	.string "{JPN}なにかの せっけいず...?\n"
	.string "{JPN}みても チンプンカンプン!$"
