gContestHallPaintingCaption::
	.string "{JPN}コンテスト$"

@ Unused
gContestPaintingContest::
	.string "{JPN}ノーマルランク$"

gContestRankNormal::
	.string "{JPN}スーパーランク$"

gContestRankSuper::
	.string "{JPN}ハイパーランク$"

gContestRankHyper::
	.string "{JPN}マスターランク$"

gContestRankMaster::
	.string "{JPN}つうしん$"

gContestLink::
	.string "{JPN}かっこよさ$"

gContestCoolness::
	.string "{JPN}うつくしさ$"

gContestBeauty::
	.string "{JPN}かわいさ$"

gContestCuteness::
	.string "{JPN}かしこさ$"

gContestSmartness::
	.string "{JPN}たくましさ$"

gContestToughness::
	.string "{JPN}スーパー クール\n"
	.string "{JPN}ノンストップ {STR_VAR_1}$"

gContestPaintingCool1::
	.string "{JPN}グッドルッキン ポケモン {STR_VAR_1}$"

gContestPaintingCool2::
	.string "{JPN}マーベラス ワンダフル\n"
	.string "{JPN}グレート {STR_VAR_1}$"

gContestPaintingCool3::
	.string "{JPN}こんせいき さいごの ビーナス\n"
	.string "{JPN}ビューティー {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "{JPN}{STR_VAR_1} クンの マブシイ\n"
	.string "{JPN}キラキラ スマイル$"

gContestPaintingBeauty2::
	.string "{JPN}ポケモンセンター の\n"
	.string "{JPN}スーパー アイドル {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "{JPN}ラブリー スウィート {STR_VAR_1} ちゃん$"

gContestPaintingCute1::
	.string "{JPN}プリティー {STR_VAR_1}たんの\n"
	.string "{JPN}おすまし ショット$"

gContestPaintingCute2::
	.string "{JPN}こっち むいて!\n"
	.string "{JPN}キュート ポケモン {STR_VAR_1} ちゃん$"

gContestPaintingCute3::
	.string "{JPN}かしこさ マエストロ\n"
	.string "{JPN}ワイズ ポケモン {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "{JPN}えらばれた ポケモン...\n"
	.string "{JPN}ポケモンの なかの ポケモン {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{JPN}エクセレント {STR_VAR_1} の\n"
	.string "{JPN}ゆうがな ひととき$"

gContestPaintingSmart3::
	.string "{JPN}パワフル マッスル\n"
	.string "{JPN}ハッスル {STR_VAR_1}$"

gContestPaintingTough1::
	.string "{JPN}ストロング ストロンガー\n"
	.string "{JPN}ストロンゲスト {STR_VAR_1}$"

gContestPaintingTough2::
	.string "{JPN}タフネス マイティー\n"
	.string "{JPN}ハイパーポケモン {STR_VAR_1}!$"

gContestPaintingTough3::
	.string "{JPN}ナゾノクサ$"
