@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "{JPN}たくさん アピール できる$"

gText_UserMoreEasilyStartled::
	.string "{JPN}この アピールの あと\n"
	.string "{JPN}びっくり しやすく なってしまう$"

gText_GreatAppealButNoMoreToEnd::
	.string "{JPN}すごいアピールに なるが このあと\n"
	.string "{JPN}さいごまで なにも できなくなる$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "{JPN}つづけて だしても しんさいんに\n"
	.string "{JPN}あきられずに アピール できる$"

gText_AvoidStartledByOthersOnce::
	.string "{JPN}ほかの ポケモンに おどかされても\n"
	.string "{JPN}1ど くらいは がまんできる$"

gText_AvoidStartledByOthers::
	.string "{JPN}ほかの ポケモンに おどかされても\n"
	.string "{JPN}がまんできる$"

gText_AvoidStartledByOthersLittle::
	.string "{JPN}ほかの ポケモンに おどかされても\n"
	.string "{JPN}すこし くらいなら がまんできる$"

gText_UserLessLikelyStartled::
	.string "{JPN}この わざを だした あとは\n"
	.string "{JPN}あまり びっくり しなくなる$"

gText_SlightlyStartleFrontMon::
	.string "{JPN}じぶんの まえに アピールした\n"
	.string "{JPN}ポケモンを ちょっと おどろかす$"

gText_SlightlyStartleAppealed::
	.string "{JPN}アピールが おわっている ポケモン\n"
	.string "{JPN}みんなを ちょっと おどろかす$"

gText_StartleAppealedBeforeUser::
	.string "{JPN}じぶんの まえに アピールした\n"
	.string "{JPN}ポケモンを おどろかす$"

gText_StartleAllAppealed::
	.string "{JPN}アピールが おわっている ポケモン\n"
	.string "{JPN}みんなを おどろかす$"

gText_BadlyStartleFrontMon::
	.string "{JPN}じぶんの まえに アピールした\n"
	.string "{JPN}ポケモンを かなり おどろかす$"

gText_BadlyStartleAppealed::
	.string "{JPN}アピールが おわっている ポケモン\n"
	.string "{JPN}みんなを かなり おどろかす$"

gText_StartleAppealedBeforeUser2::
	.string "{JPN}じぶんの まえに アピールした\n"
	.string "{JPN}ポケモンを おどろかす$"

gText_StartleAllAppealed2::
	.string "{JPN}アピールが おわっている ポケモン\n"
	.string "{JPN}みんなを おどろかす$"

gText_ShiftJudgesAttentionFromOthers::
	.string "{JPN}しんさいんの ほかの ポケモンへの\n"
	.string "{JPN}ちゅうもくを そらすことが できる$"

gText_StartleMonHasJudgesAttention::
	.string "{JPN}しんさいんに ちゅうもく されている\n"
	.string "{JPN}ポケモンを とくに おどろかす$"

gText_JamOthersMissesTurn::
	.string "{JPN}みんなの じゃまを しまくって\n"
	.string "{JPN}つぎの アピールは さんか しない$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "{JPN}おなじ タイプの アピールを した\n"
	.string "{JPN}ポケモンを とくに おどろかす$"

gText_BadlyStartleCoolAppeals::
	.string "{JPN}かっこいい アピールを した\n"
	.string "{JPN}ポケモンを かなり おどろかす$"

gText_BadlyStartleBeautyAppeals::
	.string "{JPN}うつくしい アピールを した\n"
	.string "{JPN}ポケモンを かなり おどろかす$"

gText_BadlyStartleCuteAppeals::
	.string "{JPN}かわいい アピールを した\n"
	.string "{JPN}ポケモンを かなり おどろかす$"

gText_BadlyStartleSmartAppeals::
	.string "{JPN}かしこい アピールを した\n"
	.string "{JPN}ポケモンを かなり おどろかす$"

gText_BadlyStartleToughAppeals::
	.string "{JPN}たくましい アピールを した\n"
	.string "{JPN}ポケモンを かなり おどろかす$"

gText_MakeMonAfterUserNervous::
	.string "{JPN}このあと アピールする ポケモン\n"
	.string "{JPN}1ひきを きんちょう させる$"

gText_MakeAllMonsAfterUserNervous::
	.string "{JPN}このあと アピールする ポケモン\n"
	.string "{JPN}みんなを きんちょう させる$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "{JPN}アピールが おわった ポケモンの\n"
	.string "{JPN}ちょうしを さげる$"

gText_BadlyStartleMonsGoodCondition::
	.string "{JPN}ちょうしの いい ポケモン\n"
	.string "{JPN}みんなを かなり おどろかす$"

gText_AppealGreatIfPerformedFirst::
	.string "{JPN}1ばん はじめに アピールすると\n"
	.string "{JPN}アピールが すごく うまくいく$"

gText_AppealGreatIfPerformedLast::
	.string "{JPN}1ばん さいごに アピールすると\n"
	.string "{JPN}アピールが すごく うまくいく$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "{JPN}それまでの ポケモンの アピールと\n"
	.string "{JPN}おなじくらいの アピールに みせる$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "{JPN}1つまえの ポケモンの アピールと\n"
	.string "{JPN}おなじくらい うまく できる$"

gText_AppealBetterLaterItsPerformed::
	.string "{JPN}みんなの あとで アピールするほど\n"
	.string "{JPN}すごい アピールに みせられる$"

gText_AppealVariesDependingOnTiming::
	.string "{JPN}だすときに よって アピールの\n"
	.string "{JPN}できぐあいが いろいろと かわる$"

gText_WorksWellIfSameTypeAsBefore::
	.string "{JPN}1つまえの ポケモンの アピールと\n"
	.string "{JPN}タイプが おなじなら きにいられる$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "{JPN}1つまえの ポケモンの アピールと\n"
	.string "{JPN}タイプが ちがうなら きにいられる$"

gText_AffectedByAppealInFront::
	.string "{JPN}1つまえの ポケモンの アピールの\n"
	.string "{JPN}うまさに えいきょう される$"

gText_UpsConditionHelpsPreventNervousness::
	.string "{JPN}アピールの ちょうしが あがる\n"
	.string "{JPN}きんちょうも しにくくなる$"

gText_AppealWorksWellIfConditionGood::
	.string "{JPN}ちょうしが いいときに だすと\n"
	.string "{JPN}アピールが とても うまくいく$"

gText_NextAppealMadeEarlier::
	.string "{JPN}このつぎの アピールを\n"
	.string "{JPN}はじめの ほうに だすことが できる$"

gText_NextAppealMadeLater::
	.string "{JPN}このつぎの アピールを\n"
	.string "{JPN}おわりの ほうに だすことが できる$"

gText_TurnOrderMoreEasilyScrambled::
	.string "{JPN}このつぎの アピールの\n"
	.string "{JPN}じゅんばんが かわりやすく なる$"

gText_ScrambleOrderOfNextAppeals::
	.string "{JPN}このつぎの アピールの\n"
	.string "{JPN}じゅんばんを めちゃくちゃに する$"

gText_AppealExcitesAudienceInAnyContest::
	.string "{JPN}どの コンテストで みせても\n"
	.string "{JPN}かならず もりあがる アピール$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "{JPN}アピールが うまくいった ポケモン\n"
	.string "{JPN}みんなを かなり おどろかす$"

gText_AppealBestMoreCrowdExcited::
	.string "{JPN}かいじょうが もりあがっている ほど\n"
	.string "{JPN}アピールが きにいられる$"

gText_TemporarilyStopCrowdExcited::
	.string "{JPN}このアピールのあと かいじょうが\n"
	.string "{JPN}しばらく もりあがらなく なる$"

gText_RainDance::
	.string "{JPN}あまごい$"

gText_Rage::
	.string "{JPN}いかり$"

gText_FocusEnergy::
	.string "{JPN}きあいだめ$"

gText_Hypnosis::
	.string "{JPN}さいみんじゅつ$"

gText_Softboiled::
	.string "{JPN}タマゴうみ$"

gText_HornAttack::
	.string "{JPN}つのでつく$"

gText_SwordsDance::
	.string "{JPN}つるぎのまい$"

gText_Conversion::
	.string "{JPN}テクスチャー$"

gText_SunnyDay::
	.string "{JPN}にほんばれ$"

gText_Rest2::
	.string "{JPN}ねむる$"

gText_Vicegrip::
	.string "{JPN}はさむ$"

gText_DefenseCurl::
	.string "{JPN}まるくなる$"

gText_LockOn::
	.string "{JPN}ロックオン$"

gContestMoveTypeCoolText::
	.string "{JPN}かっこいい$"

gContestMoveTypeBeautyText::
	.string "{JPN}うつくしい$"

gContestMoveTypeCuteText::
	.string "{JPN}かわいい$"

gContestMoveTypeSmartText::
	.string "{JPN}かしこい$"

gContestMoveTypeToughText::
	.string "{JPN}たくましい$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "{JPN}かいめの アピール!\n"
	.string "{JPN}どの わざを だす?$"

gText_AppealNumButItCantParticipate::
	.string "{JPN}かいめの アピール!\n"
	.string "{JPN}しかし さんか できない!$"

gText_MonAppealedWithMove::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}{STR_VAR_2}で アピール!$"

gText_MonWasWatchingOthers::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}みんなを みていた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "{JPN}アピールタイム しゅうりょう!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButAppealWasJammed::
	.string "{JPN}しかし じゃまを された!$"

gText_FollowedAnotherMonsLead::
	.string "{JPN}ほかの ポケモンに つられた!$"

gText_ButItMessedUp::
	.string "{JPN}しかし しっぱいして\n"
	.string "{JPN}しまった!$"

gText_WentBetterThanUsual::
	.string "{JPN}いつもより うまく いった!$"

gText_JudgeLookedAwayForSomeReason::
	.string "{JPN}しんさいんが なぜか\n"
	.string "{JPN}めを そらした!$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "{JPN}これまでの しっぱいを\n"
	.string "{JPN}いかして がんばってみた!$"

gText_CantMakeAnyMoreMoves::
	.string "{JPN}これいじょう わざを\n"
	.string "{JPN}だせなくなった!$"

gText_WorkedFrighteninglyWell::
	.string "{JPN}こわいくらい うまく いった!$"

gText_WorkedHardAsStandoutMon::
	.string "{JPN}めだっている ポケモンと\n"
	.string "{JPN}おなじくらい がんばった!$"

gText_JudgedLookedOnExpectantly::
	.string "{JPN}しんさいんが きたいを\n"
	.string "{JPN}こめた めで みつめた!$"

gText_WorkedRatherWell::
	.string "{JPN}かなり うまく いった!$"

gText_WorkedLittleBetterThanUsual::
	.string "{JPN}ふつうより ちょっと\n"
	.string "{JPN}うまく いった!$"

gText_MonFailedToStandOutAtAll::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}ぜんぜん めだたなかった...{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}あんまり めだたなかった...{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}まあまあ めだった!{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}かなり めだった!{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}ものすごく めだった!{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}アピール していない!{PAUSE_UNTIL_PRESS}$"

gText_AnticipationSwelledForMonsAppealNext2::
	.string "{JPN}つぎの {STR_VAR_1}の アピールに\n"
	.string "{JPN}きたいが たかまった!$"

gText_EmptyContestString::
	.string "{JPN}$"

gText_JudgesViewsOnMonHeldFirm::
	.string "{JPN}しんさいんの {STR_VAR_1}への\n"
	.string "{JPN}いんしょうは かわらない!$"

gText_MonsXChangedPerceptions::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}は\n"
	.string "{JPN}いんしょうを はねかえした!$"

gText_MonsAppealEffectWoreOff::
	.string "{JPN}{STR_VAR_1}の\n"
	.string "{JPN}アピールこうかが なくなった!$"

gText_SpecialAppealsEffectWoreOff::
	.string "{JPN}スペシャル アピールの\n"
	.string "{JPN}こうかが なくなった!$"

gText_EveryonesAppealsMadeToLookSame::
	.string "{JPN}ぜんいんの アピールを\n"
	.string "{JPN}おなじくらいに みせた!$"

gText_CheapenedMonsAppeal::
	.string "{JPN}{STR_VAR_2}の\n"
	.string "{JPN}アピールを ひくくみせた!$"

gText_CheapenedAppealOfThoseAhead::
	.string "{JPN}{STR_VAR_1}より めだつ\n"
	.string "{JPN}アピールを ひくくみせた!$"

gText_StoleAttentionAwayFromMon::
	.string "{JPN}{STR_VAR_2}の\n"
	.string "{JPN}ちゅうもくを うばった!$"

gText_CheapenedMonsAppeal2::
	.string "{JPN}{STR_VAR_2}の\n"
	.string "{JPN}アピールを ひくくみせた!$"

gText_SeverelyCheapenedOtherAppeals::
	.string "{JPN}みんなの アピールを\n"
	.string "{JPN}おおはばに ひくくみせた!$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "{JPN}つぎの {STR_VAR_1}の アピールに\n"
	.string "{JPN}きたいが たかまった!$"

gText_CheapenedAppealOfThoseAhead2::
	.string "{JPN}{STR_VAR_1}より めだっている\n"
	.string "{JPN}アピールを ひくくみせた!$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "{JPN}しんさいんの すきなアピールを\n"
	.string "{JPN}いつもより ひくくみせた!$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "{JPN}じぶんいがいの アピールを\n"
	.string "{JPN}はんぶんの できにみせた!$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "{JPN}いままで じゃまされた\n"
	.string "{JPN}うっぷんを はらして めだった!$"

gText_CantParticipateInAppealsAnyMore::
	.string "{JPN}もう アピールに\n"
	.string "{JPN}さんか できなくなった!$"

gText_TouchedJudgeForFantasticAppeal::
	.string "{JPN}しんさいんの こころに うったえ\n"
	.string "{JPN}すごい アピールになった!$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "{JPN}つぎからの アピールに\n"
	.string "{JPN}すこし きたいが たかまった!$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "{JPN}スペシャル アピールがある\n"
	.string "{JPN}かずだけ めだった!$"

gText_StoodOutAsMuchAsMon::
	.string "{JPN}{STR_VAR_1}と\n"
	.string "{JPN}おなじくらい めだった!$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "{JPN}じゃまされた アピールを\n"
	.string "{JPN}さらに めだたなくした!$"

gText_EveryonesAppealsMadeSame::
	.string "{JPN}ぜんいんの アピールと\n"
	.string "{JPN}おなじくらいに みせた!$"

gText_BecameMoreConsciousOfOtherMons::
	.string "{JPN}ほかの ポケモンが いつもより\n"
	.string "{JPN}きに なって きた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{JPN}{STR_VAR_1}は このあと\n"
	.string "{JPN}アピール できなく なった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "{JPN}ちょっと だけ\n"
	.string "{JPN}きもちが おちついた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "{JPN}ほかの ポケモンが ぜんぜん\n"
	.string "{JPN}きに ならなく なった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "{JPN}ほかの ポケモンが あまり\n"
	.string "{JPN}きに ならなく なった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "{JPN}ほかの ポケモンを あまり\n"
	.string "{JPN}きに しないように なった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "{JPN}ほかの ポケモンを\n"
	.string "{JPN}びっくり させようと した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "{JPN}みんなの めを\n"
	.string "{JPN}くらませようと した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "{JPN}しんさいんは {STR_VAR_1}から\n"
	.string "{JPN}めを そらして しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "{JPN}つぎに まっている ポケモンを\n"
	.string "{JPN}きんちょう させようと した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}きんちょう してしまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "{JPN}アピールが まだの ポケモンを\n"
	.string "{JPN}きんちょう させようと した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "{JPN}ちょうしが いい ポケモンを\n"
	.string "{JPN}からかってみた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{JPN}{STR_VAR_1}の ちょうしが\n"
	.string "{JPN}もとに もどって しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "{JPN}ちょうしが いい ポケモンの\n"
	.string "{JPN}じゃまを しようと した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{JPN}めだっている {STR_VAR_1}は\n"
	.string "{JPN}さらに はりきった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "{JPN}めだっていない {STR_VAR_1}は\n"
	.string "{JPN}がんばりまくった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "{JPN}まえの ポケモンたちに\n"
	.string "{JPN}まけないくらい はりきった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{JPN}{STR_VAR_1}は アピールを\n"
	.string "{JPN}うまく みせられなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "{JPN}まえの ポケモンと\n"
	.string "{JPN}おなじくらい はりきった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}うまく みせられなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}うまく みせられなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}すこし うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}まあまあ うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}とても うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}しっぱい して しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}あまり うまく いかなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}すこし うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}まあまあ うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}かなり うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{JPN}{STR_VAR_1}の アピールは\n"
	.string "{JPN}とても うまく いった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "{JPN}まえの ポケモンと\n"
	.string "{JPN}おなじタイプで きにいられた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "{JPN}まえの ポケモンと\n"
	.string "{JPN}ちがうタイプで きにいられた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "{JPN}まえの ポケモンより\n"
	.string "{JPN}だいぶ めだった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "{JPN}まえの ポケモンより\n"
	.string "{JPN}うまく できなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{JPN}{STR_VAR_1}の ちょうしが\n"
	.string "{JPN}いつもより あがった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{JPN}{STR_VAR_1}は ちょうしが よくて\n"
	.string "{JPN}ぜっこうの アピールに なった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "{JPN}つぎの アピールを はやく\n"
	.string "{JPN}しようと まえに でた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "{JPN}つぎの アピールを おそく\n"
	.string "{JPN}しようと 1ぽ さがった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "{JPN}つぎの ターンの じゅんばんを\n"
	.string "{JPN}おかしく した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "{JPN}しんさいんが きたいして\n"
	.string "{JPN}{STR_VAR_1}を みつめた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "{JPN}アピールの くみあわせが\n"
	.string "{JPN}きに いって もらえた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "{JPN}アピールの くみあわせが\n"
	.string "{JPN}かなり きに いられた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "{JPN}アピールの くみあわせが\n"
	.string "{JPN}ものすごく きに いられた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{JPN}{STR_VAR_1}は なんとか\n"
	.string "{JPN}めを そらした!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}そっちを みずに すんだ!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}このくらいは へいきだった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{JPN}{STR_VAR_1}は ちょっと\n"
	.string "{JPN}きを とられて しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "{JPN}ほかの ポケモンを\n"
	.string "{JPN}びっくり させようと した!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{JPN}{STR_VAR_1}は きを とられて\n"
	.string "{JPN}したを むいて しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{JPN}{STR_VAR_1}は きを とられて\n"
	.string "{JPN}ふりかえって しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{JPN}{STR_VAR_1}は おもわず\n"
	.string "{JPN}こえを あげて しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{JPN}{STR_VAR_1}は おもわず\n"
	.string "{JPN}とびあがって しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{JPN}{STR_VAR_1}は きを とられて\n"
	.string "{JPN}ひっくり かえって しまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{JPN}{STR_VAR_1}は きんちょうして\n"
	.string "{JPN}アピールが できなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "{JPN}でも しっぱい してしまった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "{JPN}でも きんちょう\n"
	.string "{JPN}させられなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "{JPN}でも だれも\n"
	.string "{JPN}きんちょう しなかった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "{JPN}でも むし されて しまった...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "{JPN}でも ちょうしは\n"
	.string "{JPN}あがらなかった...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "{JPN}ちょうしが よく なくて\n"
	.string "{JPN}あまり うまく できなかった...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{JPN}{STR_VAR_1}は\n"
	.string "{JPN}へいき だった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{JPN}{STR_VAR_1}は おなじアピールを\n"
	.string "{JPN}つづけて がっかり された!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}が\n"
	.string "{JPN}まわりに とても うけた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}は\n"
	.string "{JPN}ここでは うけなかった...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_3}に\n"
	.string "{JPN}まわりが もりあがった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{JPN}{STR_VAR_1}は つぎの アピールに\n"
	.string "{JPN}さんか できなくなった!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "{JPN}かんきゃくの\n"
	.string "{JPN}ちゅうもくを あつめた!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "{JPN}かんきゃくは\n"
	.string "{JPN}{STR_VAR_3}を みつづけている!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_2}は\n"
	.string "{JPN}めを むけられなかった...{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "{JPN}モジモジ$"

gText_Contest_Anxiety::
	.string "{JPN}ドキドキ$"

gText_Contest_Laziness::
	.string "{JPN}デレデレ$"

gText_Contest_Hesitancy::
	.string "{JPN}オロオロ$"

gText_Contest_Fear::
	.string "{JPN}ビクビク$"

gText_Contest_Coolness::
	.string "{JPN}かっこよさ$"

gText_Contest_Beauty::
	.string "{JPN}うつくしさ$"

gText_Contest_Cuteness::
	.string "{JPN}かわいさ$"

gText_Contest_Smartness::
	.string "{JPN}かしこさ$"

gText_Contest_Toughness::
	.string "{JPN}たくましさ$"

gText_Tension::
	.string "{JPN}テンション$"

gText_CoolMove::
	.string "{JPN}かっこいい わざ$"

gText_BeautyMove::
	.string "{JPN}うつくしい わざ$"

gText_CuteMove::
	.string "{JPN}かわいい わざ$"

gText_SmartMove::
	.string "{JPN}かしこい わざ$"

gText_ToughMove::
	.string "{JPN}たくましい わざ$"

gText_3QuestionMarks::
	.string "{JPN}???$"
