@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "{JPN}やすみ$"

gText_LinkStandby4::
	.string "{JPN}つうしん たいきちゅう!$"

gText_WinnerIsPlayersMonCongrats::
	.string "{JPN}ゆうしょうは {STR_VAR_1}の {STR_VAR_2}!\n"
	.string "{JPN}おめでとう!$"

gText_WinnerIsPlayersMon::
	.string "{JPN}ゆうしょうは {STR_VAR_1}の {STR_VAR_2}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "{JPN}いちじしんさ: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "{JPN}にじしんさ: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "{JPN}セットされたイベント: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "{JPN}いちばんおおくつかったわざ:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "{JPN}いんしょうにのこったのは\n"
	.string "{JPN}{STR_VAR_1}の {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "{JPN}セットされたイベント: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "{JPN}ゆうしょう しなかったので\n"
	.string "{JPN}つうしんテレビは つくられません{PAUSE_UNTIL_PRESS}$"
