EventTicket_Text_ShowOldSeaMap:
	.string "{JPN}アサギゆきの ふねは...\p"
	.string "{JPN}え? この ちずの ばしょに\n"
	.string "{JPN}いきたい ですって?\p"
	.string "{JPN}くわしい ものを よびますから\n"
	.string "{JPN}おまち ください$"

EventTicket_Text_ThatPass:
	.string "{JPN}アサギゆきの ふねは...\p"
	.string "{JPN}お?\n"
	.string "{JPN}その チケットは...$"

EventTicket_Text_ShowEonTicket:
	.string "{JPN}みょうな チケットを\n"
	.string "{JPN}もってきたのは おまえさんか?\p"
	.string "{JPN}おまえが いこうと しているのは\n"
	.string "{JPN}はるか みなみの ちいさな しま...\p"
	.string "{JPN}そこには なにが まっているのか\n"
	.string "{JPN}しっている やつは いねえ...\l"
	.string "{JPN}ううむ ふなのりの ちが さわぐぜ!\p"
	.string "{JPN}さあ のりな!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "{JPN}なーんにも ない しまだなあ\p"
	.string "{JPN}もう アサギへ かえるかい?$"

EventTicket_Text_SailHome:
	.string "{JPN}よし!\n"
	.string "{JPN}アサギに むけて しゅっこう!$"

EventTicket_Text_AsYouLike:
	.string "{JPN}そうか まだ いるんだな$"

SouthernIsland_Interior_Text_Sign:
	.string "{JPN}すべての ゆめは もうひとつの げんじつ\n"
	.string "{JPN}それを わすれるべからず...$"

SouthernIsland_Exterior_Text_Sign:
	.string "{JPN}きおく かすみし ものは\n"
	.string "{JPN}こころに きざみつける ことを のぞむ...$"
