EventTicket_Text_OldSeaMapTooFar:
	.string "{JPN}なんだ?\n"
	.string "{JPN}ボロっちい ちずを もってきたってのは\l"
	.string "{JPN}おまえさんか? みせてみな!\p"
	.string "... ... ...\p"
	.string "{JPN}こりゃ また ずいぶん とおいなあ\n"
	.string "{JPN}わりいが ほかを あたったほうが...$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "{JPN}ハギ: こら! わしの おんじんの\n"
	.string "{JPN}ねがいを ことわるとは なにごとだ!$"

EventTicket_Text_BrineyLetsSail:
	.string "{JPN}{PLAYER}{KUN} すまなかったね\n"
	.string "{JPN}このふねを たよって きて くれたのに...\l"
	.string "{JPN}もちろん いますぐに しゅっこうだ!\p"
	.string "{JPN}さあいくぞ!\n"
	.string "{JPN}かいずに ある しまへ しゅっぱつ!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "{JPN}みょうな チケットを\n"
	.string "{JPN}もってきたのは おまえさんか?\p"
	.string "{JPN}おまえが いこうと しているのは\n"
	.string "{JPN}とおく はなれた ちほうの しま...\l"
	.string "{JPN}そこには なにが まっているのか\l"
	.string "{JPN}しって いるやつは いねえ...\l"
	.string "{JPN}ううむ ふなのりの ちが さわぐぜ!\p"
	.string "{JPN}さあ のりな!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "{JPN}まったく ハギ せんちょうの\n"
	.string "{JPN}きまぐれにも まいるよなあ...\p"
	.string "{JPN}もう アサギへ かえるのかい?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "{JPN}ふしぎな かたちの しまだなあ\n"
	.string "{JPN}もう アサギへ かえるか?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "{JPN}ヘンテコな チケットを\n"
	.string "{JPN}いくつも もってきたのは おまえさんか?\p"
	.string "{JPN}... ... ...ふむ\p"
	.string "{JPN}こいつらで いける ところは\n"
	.string "{JPN}どこも ここから とおい しま\l"
	.string "{JPN}そこでは なにが おきるのか\l"
	.string "{JPN}なにが まっているのか\l"
	.string "{JPN}しっている やつは いねえ...\l"
	.string "{JPN}ううむ ふなのりの ちが さわぐぜ!\p"
	.string "{JPN}さあ のりな!\n"
	.string "{JPN}まずは どこから いってみるかい?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "{JPN}な... なんか おくふかくから\n"
	.string "{JPN}ひくい うなりが きこえたような...\p"
	.string "{JPN}だ だいじょうぶか?\n"
	.string "{JPN}もう かえった ほうが いいんじゃないか?$"

FarawayIsland_Entrance_Text_Sign:
	.string "{JPN}なんねんも まえに かかれたような\n"
	.string "{JPN}ふるい かきおきが ある...\p"
	.string "{JPN}...がつ 6か\n"
	.string "{JPN}ここに たちいる にんげ...が\l"
	.string "{JPN}ふたたび ...らわれると すれば\l"
	.string "{JPN}こころ やさし...で あらんことを\p"
	.string "{JPN}...こに その ねがいを しるし\n"
	.string "{JPN}この ...を あとにする\p"
	.string "{JPN}...ジ$"

FarawayIsland_Interior_Text_Mew:
	.string "{JPN}ミュー...$"
