@ Battle Tower
gText_AnabelWonSilver::
	.string "{JPN}ざんねん だよ...$"

gText_AnabelDefeatSilver::
	.string "{JPN}なるほどね...$"

gText_AnabelWonGold::
	.string "{JPN}ごめんね...$"

gText_AnabelDefeatGold::
	.string "{JPN}ありがとう...$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "{JPN}アッハッハッ!! はずかしく ないのっ!?\n"
	.string "{JPN}みんなが みてるよっ!!$"

gText_TuckerDefeatSilver::
	.string "{JPN}クッ... なんて こと...$"

gText_TuckerWonGold::
	.string "{JPN}ドームスーパースターの\n"
	.string "{JPN}なまえは かざりじゃ ないっ!!$"

gText_TuckerDefeatGold::
	.string "{JPN}アッハッハッ!! ステキっ!!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "{JPN}おつかれさん!\n"
	.string "{JPN}イイ べんきょうに なったろ?$"

gText_NolandDefeatSilver::
	.string "{JPN}イイねぇー!\n"
	.string "{JPN}おめえ わかってる ねぇー!$"

gText_NolandWonGold::
	.string "{JPN}おいおいおいーー!!\n"
	.string "{JPN}もう おしまいかー?$"

gText_NolandDefeatGold::
	.string "{JPN}なんだとぉ...$"

@ Battle Pike
gText_LucyWonSilver::
	.string "{JPN}フン...$"

gText_LucyDefeatSilver::
	.string "{JPN}くっ...$"

gText_LucyWonGold::
	.string "{JPN}ハッ!!$"

gText_LucyDefeatGold::
	.string "{JPN}ちくしょおぉぉぉっーーー!!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "{JPN}ちょっと ちょっとぉー!\n"
	.string "{JPN}もっと がんばってよねー!!$"

gText_GretaDefeatSilver::
	.string "{JPN}うっそ! やるじゃんー!!$"

gText_GretaWonGold::
	.string "{JPN}ウィーッス! とうぜん!!$"

gText_GretaDefeatGold::
	.string "{JPN}いーっ!? マジっ!?$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "{JPN}ポケモンが なんじゃく なのは\n"
	.string "{JPN}トレーナーが なんじゃく だからだ!!$"

gText_SpenserDefeatSilver::
	.string "{JPN}おまえの ポケモンたちは\n"
	.string "{JPN}まことに すんだ ひとみを しとる!\p"
	.string "{JPN}つぎの きかいを\n"
	.string "{JPN}たのしみに しとるぞ!$"

gText_SpenserWonGold::
	.string "{JPN}ほほぅ...\n"
	.string "{JPN}これは これは...$"

gText_SpenserDefeatGold::
	.string "{JPN}ぐわはっはっは!!\n"
	.string "{JPN}わが きょうだいの まえに てき なし!!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "{JPN}ぐわーーーはっはっは!!$"

gText_BrandonDefeatSilver::
	.string "{JPN}おい! なにを やってるんだ!\n"
	.string "{JPN}ほら がんばれ! たちあがるんだ!!$"

gText_BrandonWonGold::
	.string "{JPN}よおしっ! がんばった!\n"
	.string "{JPN}よく がんばったぞ!!$"

gText_BrandonDefeatGold::
	.string "{JPN}おい! あきらめるんじゃ ない!\n"
	.string "{JPN}さあ たつんだ! がんばるんだ!!$"
