LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "{JPN}こちらは ポケモンくじ\n"
	.string "{JPN}ちゅうせん コーナーです\p"
	.string "{JPN}とうデパートに おこし いただいた かたに\n"
	.string "{JPN}もれなく ポケモンくじを\l"
	.string "{JPN}ひいて いただいて います!\p"
	.string "{JPN}ひいた くじの ナンバーと\n"
	.string "{JPN}おきゃくさまの ポケモンの IDが\l"
	.string "{JPN}あっていましたら すてきな しょうひんを\l"
	.string "{JPN}プレゼント いたします!\p"
	.string "{JPN}ポケモンくじを ひかれますか?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "{JPN}また あした いこう\n"
	.string "{JPN}おこし ください$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "{JPN}それでは また おこし ください$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "{JPN}では くじを ひいて ください\n"
	.string "{JPN}...くそくそ...くそくそ...くそくそ$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "{JPN}くじの ナンバーは {STR_VAR_1}です!\p"
	.string "{JPN}ナンバーが あなたの ポケモンの IDと\n"
	.string "{JPN}いっちしているか おしらべ いたしますので\l"
	.string "{JPN}しょうしょう おまちください$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "{JPN}おめでとう ございます!\p"
	.string "{JPN}あなたが つれている\n"
	.string "{JPN}{STR_VAR_1}ちゃんの IDが みごとに\l"
	.string "{JPN}くじの ナンバーと いっち しました!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "{JPN}おめでとう ございます!\p"
	.string "{JPN}パソコンに あずけている\n"
	.string "{JPN}{STR_VAR_1}ちゃんの IDが みごとに\l"
	.string "{JPN}くじの ナンバーと いっち しました!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "{JPN}ざんねんでした\n"
	.string "{JPN}すべて はずれの ようです$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "{JPN}2ケタ あって いましたので\n"
	.string "{JPN}3とう です!\l"
	.string "{JPN}{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "{JPN}3ケタ あって いましたので\n"
	.string "{JPN}2とう です!\l"
	.string "{JPN}{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "{JPN}4ケタ あって いましたので\n"
	.string "{JPN}1とう です!\l"
	.string "{JPN}{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "{JPN}なんと 5ケタ すべて\n"
	.string "{JPN}あって いました!!\p"
	.string "{JPN}とくとうです!!\n"
	.string "{JPN}{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "{JPN}あら?\n"
	.string "{JPN}もちものが いっぱいの ようですね.\p"
	.string "{JPN}どうぐを せいりしてから\n"
	.string "{JPN}また きてくださいね.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{JPN}......あら?\n"
	.string "{JPN}どうぐが いっぱいの ようですね\p"
	.string "{JPN}どうぐを せいりしてから もういちど\n"
	.string "{JPN}おこし ください$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "{JPN}{PLAYER}さん ですね\n"
	.string "{JPN}おまちして おりました!\p"
	.string "{JPN}では しょうひんを\n"
	.string "{JPN}おわたし いたします$"
