MatchCall_WildBattleText1::
	.string "{JPN}あ! {PLAYER}{KUN} こんにちは!\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}このまえ {STR_VAR_2}を みつけたんだけど\n"
	.string "{JPN}つかまえられなかったよ\p"
	.string "{JPN}おしかったなー\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_WildBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}このまえ {STR_VAR_2} を\n"
	.string "{JPN}つかまえようと したんだけど\p"
	.string "{JPN}にげられちゃったの\n"
	.string "{JPN}ざんねん だったなあ\p"
	.string "{JPN}じゃあ またね!$"

MatchCall_WildBattleText3::
	.string "{JPN}おーっす {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1} だ!\p"
	.string "{JPN}このまえ {STR_VAR_2} を\n"
	.string "{JPN}つかまえようと したんだけど\l"
	.string "{JPN}あとすこしの ところで にげられたんだ!\p"
	.string "{JPN}くやしかった なあ...\n"
	.string "{JPN}じゃあ またなー$"

MatchCall_WildBattleText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}{STR_VAR_2}って ポケモン しってるかい?\n"
	.string "{JPN}このまえ あとすこしで\p"
	.string "{JPN}つかまえられそう だったんだけど\n"
	.string "{JPN}にげられて しまったよ\p"
	.string "{JPN}こんど みつけたら ぜったい\n"
	.string "{JPN}つかまえて みせるよ\p"
	.string "{JPN}じゃあ またな$"

MatchCall_WildBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だけど\l"
	.string "{JPN}ポケモン つかまえてる?\p"
	.string "{JPN}おれも このまえ もうすこしで\n"
	.string "{JPN}つかまえられそう だったけど\p"
	.string "{JPN}にげられちゃったよ\n"
	.string "{JPN}じゃあ またな$"

MatchCall_WildBattleText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だけど\l"
	.string "{JPN}ポケモン つかまえてる?\p"
	.string "{JPN}おれも このまえ もうすこしで\n"
	.string "{JPN}つかまえられそう だったけど\p"
	.string "{JPN}にげられちゃったよ\n"
	.string "{JPN}じゃあ またな$"

MatchCall_WildBattleText7::
	.string "{JPN}...あ {PLAYER}{KUN}?\n"
	.string "{JPN}{STR_VAR_1} だけど...\p"
	.string "{JPN}あ ちょっと まって!\n"
	.string "{JPN}いま {STR_VAR_2}を つかまえ...\p"
	.string "{JPN}ああああ にげられたー!\n"
	.string "{JPN}もうすこし だったのに!$"

MatchCall_WildBattleText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}あれから ポケモン つかまえた?\n"
	.string "{JPN}わたし このまえ もうすこしで\p"
	.string "{JPN}つかまえられそう だったのに\n"
	.string "{JPN}にげられちゃった\p"
	.string "{JPN}もっと がんばらなきゃ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_WildBattleText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n"
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}どう? ポケモン あつまってる?\n"
	.string "{JPN}わたしは にげられて ばっかりで\p"
	.string "{JPN}ぜんぜん うまく いかないの\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_WildBattleText10::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}もうすこしで {STR_VAR_2} を\n"
	.string "{JPN}つかまえられそう だったのに\l"
	.string "{JPN}にげられちゃった\p"
	.string "{JPN}もっと がんばらなきゃ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_WildBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だけど\l"
	.string "{JPN}ちょうしは どうだい?\p"
	.string "{JPN}おれは このまえ {STR_VAR_2} を\n"
	.string "{JPN}つかまえようと したんだけど\p"
	.string "{JPN}にげられちゃったよ\n"
	.string "{JPN}がっくり$"

MatchCall_WildBattleText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが\l"
	.string "{JPN}ポケモン つかまえとるかな?\p"
	.string "{JPN}わしも つかまえようと おもったが\n"
	.string "{JPN}なかなか うまくいかん\p"
	.string "{JPN}ポケモンの みちは\n"
	.string "{JPN}おくが ふかいのう$"

MatchCall_WildBattleText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが\l"
	.string "{JPN}ポケモン つかまえとるかな?\p"
	.string "{JPN}わしも つかまえようと おもったが\n"
	.string "{JPN}なかなか うまくいかん\p"
	.string "{JPN}ポケモンの みちは\n"
	.string "{JPN}おくが ふかいのう$"

MatchCall_WildBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}さっき {STR_VAR_2}ちゃんを\n"
	.string "{JPN}つかまえようと したんだけど\p"
	.string "{JPN}にげられちゃったのよ ざんねん!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_WildBattleText15::
	.string "{JPN}おーっす {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1} だ!\p"
	.string "{JPN}ポケモンを つかまえようと\n"
	.string "{JPN}おもってるんだが\l"
	.string "{JPN}みつからなくてさー\l"
	.string "{JPN}おじさん こまってる とこなのよ\p"
	.string "{JPN}まいったなー\n"
	.string "{JPN}じゃあ またなー$"

MatchCall_NegativeBattleText1::
	.string "{JPN}{PLAYER}{KUN} こんにちは!\n"
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}ほかのひとと しょうぶ したんだけど\n"
	.string "{JPN}まけちゃったよ がっくし\p"
	.string "{JPN}じゃあ またね$"

MatchCall_NegativeBattleText2::
	.string "{JPN}{PLAYER}{KUN} こんにちは!\n"
	.string "{JPN}{STR_VAR_1}よ!\p"
	.string "{JPN}わたし ね\n"
	.string "{JPN}あれから また しょうぶ してみたの\p"
	.string "{JPN}でも あとちょっとの ところで\n"
	.string "{JPN}まけちゃった あーあ$"

MatchCall_NegativeBattleText3::
	.string "{JPN}おーっす {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1} だ!\p"
	.string "{JPN}しょうぶ に まけたよー\n"
	.string "{JPN}もっと そだてないと だめだなー$"

MatchCall_NegativeBattleText4::
	.string "{JPN}やあ {PLAYER}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}きのう また しょうぶ してみたんだ\n"
	.string "{JPN}でも かてなかったよ\p"
	.string "{JPN}もっと そだてが ひつようだな\n"
	.string "{JPN}じゃあ またな$"

MatchCall_NegativeBattleText5::
	.string "{JPN}やあ {PLAYER}\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}ちょうしは どうだい?\n"
	.string "{JPN}おれは しょうぶ しても\l"
	.string "{JPN}あまり かてないんだよ\p"
	.string "{JPN}ちょうし わるいなあ\n"
	.string "{JPN}じゃあ またな$"

MatchCall_NegativeBattleText6::
	.string "{JPN}やあ {PLAYER}\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}ちょうしは どうだい?\n"
	.string "{JPN}おれは しょうぶ しても\l"
	.string "{JPN}あまり かてないんだよ\p"
	.string "{JPN}ちょうし わるいなあ\n"
	.string "{JPN}じゃあ またな$"

MatchCall_NegativeBattleText7::
	.string "{JPN}{STR_VAR_1} だけどー\n"
	.string "{JPN}さいきん どう?\p"
	.string "{JPN}きのう しょうぶに まけてさ\n"
	.string "{JPN}そのことで あたまが いっぱいなんだ\p"
	.string "{JPN}たいさく かんがえないと...\n"
	.string "{JPN}じゃあ また$"

MatchCall_NegativeBattleText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}ポケモンの ちょうしは どう?\n"
	.string "{JPN}わたしは このまえの しょうぶで\l"
	.string "{JPN}まけちゃった\p"
	.string "{JPN}もっと がんばらなきゃ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_NegativeBattleText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n"
	.string "{JPN}{STR_VAR_1} でーす\p"
	.string "{JPN}ねー きいて きいて!\n"
	.string "{JPN}このまえ ポケモン しょうぶ したんだけど\p"
	.string "{JPN}あとちょっとの ところで\n"
	.string "{JPN}まけちゃったのよー! くやしい!$"

MatchCall_NegativeBattleText10::
	.string "{JPN}あら {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}さっき しょうぶ したんだけど\n"
	.string "{JPN}まけちゃった\p"
	.string "{JPN}もっと ポケモン そだてないと だめね\n"
	.string "{JPN}じゃあ またね$"

MatchCall_NegativeBattleText11::
	.string "{JPN}やあ {PLAYER}{KUN} げんきかい?\n"
	.string "{JPN}{STR_VAR_1} だよ\l"
	.string "{JPN}ポケモンの ちょうしは どう?\p"
	.string "{JPN}こっちは また しょうぶに\n"
	.string "{JPN}まけちゃったよ\p"
	.string "{JPN}じゃあ また$"

MatchCall_NegativeBattleText12::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが\l"
	.string "{JPN}しょうぶ しておるのかな?\p"
	.string "{JPN}わしのほうは このまえ まけてしまって\n"
	.string "{JPN}また ポケモンを\l"
	.string "{JPN}そだてておる ところじゃよ\p"
	.string "{JPN}では またな$"

MatchCall_NegativeBattleText13::
	.string "{JPN}おお {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃ\p"
	.string "{JPN}げんき かのう?\n"
	.string "{JPN}さっきまで ポケモン しょうぶを\l"
	.string "{JPN}しておったよ\p"
	.string "{JPN}{PLAYER}{KUN}も がんばるんじゃぞ\n"
	.string "{JPN}では またの$"

MatchCall_NegativeBattleText14::
	.string "{JPN}あら {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}ちょうしは どうなの?\n"
	.string "{JPN}たまには いえに かえらないと だめよ\l"
	.string "{JPN}じゃあ またね$"

MatchCall_PositiveBattleText1::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n"
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}さっき しょうぶ したんだけど\n"
	.string "{JPN}かったよ! かったよ!\p"
	.string "{JPN}ぼくの {STR_VAR_2} が\n"
	.string "{JPN}すごく がんばったんだ! うれしいなー$"

MatchCall_PositiveBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n"
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}きのう しょうぶ したんだけど\n"
	.string "{JPN}かったのよ! うれしいー!$"

MatchCall_PositiveBattleText3::
	.string "{JPN}おーっす {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1} だぞ\p"
	.string "{JPN}ちょうしは どうだ?\n"
	.string "{JPN}おれも このまえ しょうぶ したんだけど\l"
	.string "{JPN}おれの {STR_VAR_2}が だいかつやく さ!\p"
	.string "{JPN}つぎ {PLAYER}と しょうぶ するときは\n"
	.string "{JPN}ぜったい まけない からなー!$"

MatchCall_PositiveBattleText4::
	.string "{JPN}やあ {PLAYER}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}さっき しょうぶ したんだけど\n"
	.string "{JPN}なんとか かつ ことが できたよ\p"
	.string "{JPN}ぼくの {STR_VAR_2}が\n"
	.string "{JPN}すごく がんばったんだ$"

MatchCall_PositiveBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}ちょうしは どうだい?\n"
	.string "{JPN}しょうぶ してる?\p"
	.string "{JPN}おれ このまえ かったよ!\n"
	.string "{JPN}{STR_VAR_2}が だいかつやく さ!\p"
	.string "{JPN}つぎこそ きみに かつからね!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_PositiveBattleText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}げんき かい?\n"
	.string "{JPN}おれは さいきん ちょうしが よくて\l"
	.string "{JPN}さっきも しょうぶに かったところだ\p"
	.string "{JPN}つぎに きみと しょうぶ するときは\n"
	.string "{JPN}ぜったいに まけないからな$"

MatchCall_PositiveBattleText7::
	.string "{JPN}{PLAYER}{KUN}?\n"
	.string "{JPN}{STR_VAR_1} だけど\p"
	.string "{JPN}ぼくの {STR_VAR_2} つよいわけよ!\n"
	.string "{JPN}さっきも しょうぶで かったわけよ!\p"
	.string "{JPN}つぎに きみと しょうぶ するのが\n"
	.string "{JPN}たのしみだなあ$"

MatchCall_PositiveBattleText8::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}げんき かしら?\n"
	.string "{JPN}わたしね さっき しょうぶ して かったの\p"
	.string "{JPN}{STR_VAR_2} が とっても がんばったのよ\n"
	.string "{JPN}じゃあ またね$"

MatchCall_PositiveBattleText9::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n"
	.string "{JPN}{STR_VAR_1} でーす!\p"
	.string "{JPN}ポケモンの ちょうしは どう?\n"
	.string "{JPN}わたしのほうは さっき しょうぶして\l"
	.string "{JPN}かった ところよ!\p"
	.string "{JPN}わたしの {STR_VAR_2} が\n"
	.string "{JPN}すごい かつやく だったのよ\p"
	.string "{JPN}みせたかったなー\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_PositiveBattleText10::
	.string "{JPN}あら こんにちは {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}ちょうしは どうかしら?\n"
	.string "{JPN}わたしの ポケモン ちょうし いいみたい\p"
	.string "{JPN}さっきも しょうぶで かてたのよ\n"
	.string "{JPN}じゃあ またね$"

MatchCall_PositiveBattleText11::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}ポケモン しょうぶ してるかい?\n"
	.string "{JPN}おじさん きょうも しょうぶに かってねー\p"
	.string "{JPN}ちょうし いいんだよ がははは\n"
	.string "{JPN}じゃあ またね$"

MatchCall_PositiveBattleText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃよ\p"
	.string "{JPN}げんきに してるかのう?\n"
	.string "{JPN}わしは げんき じゃぞ\p"
	.string "{JPN}さっきも しょうぶに かった ところじゃ\n"
	.string "{JPN}わかいもんには まだまだ まけんぞ$"

MatchCall_PositiveBattleText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃよ\p"
	.string "{JPN}げんきに してるかのう?\n"
	.string "{JPN}わしは げんき じゃぞ\p"
	.string "{JPN}さっきも しょうぶに かった ところじゃ\n"
	.string "{JPN}わかいもんには まだまだ まけんぞ\p"
	.string "{JPN}じゃあ またのう$"

MatchCall_PositiveBattleText14::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}このまえ しょうぶ したんだけど\n"
	.string "{JPN}わたしの {STR_VAR_2}が だいかつやく!\p"
	.string "{JPN}{PLAYER}{KUN}にも みせたかったな\n"
	.string "{JPN}じゃあ また$"

MatchCall_SameRouteBattleRequestText1::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}え! いま {STR_VAR_2} に いるの?\n"
	.string "{JPN}じゃあ いまから しょうぶ しようよ!\l"
	.string "{JPN}まってるよ! じゃあね!$"

MatchCall_SameRouteBattleRequestText2::
	.string "{JPN}{PLAYER}さん こんにちは!\n"
	.string "{JPN}{STR_VAR_1} でーす\p"
	.string "{JPN}え! いま {STR_VAR_2} に いるの?\n"
	.string "{JPN}じゃあ いまから しょうぶ しない?\l"
	.string "{JPN}まってるわよ! じゃあね!$"

MatchCall_SameRouteBattleRequestText3::
	.string "{JPN}おーっす {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1} だ!\p"
	.string "{JPN}お いま {STR_VAR_2}にいるのか?\n"
	.string "{JPN}じゃあ これから しょうぶ しないか?\p"
	.string "{JPN}こんどこそ まけない からな!\n"
	.string "{JPN}まってるぞー じゃあな$"

MatchCall_SameRouteBattleRequestText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}いま どこに いるんだい?\n"
	.string "{JPN}え {STR_VAR_2}?\p"
	.string "{JPN}じゃあ これから しょうぶ しないか?\n"
	.string "{JPN}まってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}ちょうしは どうだい?\n"
	.string "{JPN}え? いま {STR_VAR_2}に いるの?\p"
	.string "{JPN}それなら これから おれと\n"
	.string "{JPN}しょうぶ してみないかい?\p"
	.string "{JPN}まってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}ポケモンの ちょうしは どうだい?\n"
	.string "{JPN}へえ いま {STR_VAR_2}に いるのか\p"
	.string "{JPN}じゃあ これから おれと\n"
	.string "{JPN}しょうぶ しよう\p"
	.string "{JPN}まってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText7::
	.string "{JPN}...あ {PLAYER}{KUN}?\n"
	.string "{JPN}{STR_VAR_1} だけど...\p"
	.string "{JPN}へー いま {STR_VAR_2}に いるの?\n"
	.string "{JPN}じゃあ しょうぶ しよう これから\p"
	.string "{JPN}おれの ポケモンを みせてあげるよ\n"
	.string "{JPN}じゃあ まってるよ$"

MatchCall_SameRouteBattleRequestText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}げんき ですか?\n"
	.string "{JPN}あら いま {STR_VAR_2}に いるのね\p"
	.string "{JPN}じゃあ これから\n"
	.string "{JPN}わたしと しょうぶ しない?\p"
	.string "{JPN}まってるわよ じゃあね!$"

MatchCall_SameRouteBattleRequestText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n"
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}げんきに してる?\n"
	.string "{JPN}あら いま {STR_VAR_2}に いるの?\p"
	.string "{JPN}そっかー じゃあ これから\n"
	.string "{JPN}わたしと しょうぶ してみない?\p"
	.string "{JPN}じゃあね まってるわよ$"

MatchCall_SameRouteBattleRequestText10::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}げんき ですか?\n"
	.string "{JPN}あら いま {STR_VAR_2}に いるのね\p"
	.string "{JPN}じゃあ これから\n"
	.string "{JPN}わたしと しょうぶ しない?\p"
	.string "{JPN}まってるわよ じゃあね!$"

MatchCall_SameRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だけど\p"
	.string "{JPN}ほほう\n"
	.string "{JPN}いま {STR_VAR_2}に いるんだって?\p"
	.string "{JPN}じゃあ これから おじさんと\n"
	.string "{JPN}ポケモン しょうぶ しないかい?\p"
	.string "{JPN}まってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが\l"
	.string "{JPN}いま どこに いるのかな?\p"
	.string "{JPN}{STR_VAR_2} か! すぐ ちかく じゃな\n"
	.string "{JPN}これから わしと しょうぶ せんか?\p"
	.string "{JPN}まっておるぞ じゃあの$"

MatchCall_SameRouteBattleRequestText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかのう?\p"
	.string "{JPN}ほうほう いまは {STR_VAR_2}に おるのか\n"
	.string "{JPN}ちかいから こっちへ よって\p"
	.string "{JPN}いちど しょうぶ して いかんかの?\n"
	.string "{JPN}まっておるぞ じゃあの$"

MatchCall_SameRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}あら いま {STR_VAR_2}に いるの?\n"
	.string "{JPN}すぐちかくに いるのね\p"
	.string "{JPN}じゃあ これから おばさんと\n"
	.string "{JPN}ポケモンしょうぶ してみない?\p"
	.string "{JPN}まってるわよ じゃあね$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "{JPN}あ! {PLAYER}{KUN}!\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}これから ぼくと しょうぶ しない?\n"
	.string "{JPN}{STR_VAR_2} で まってるよ!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "{JPN}あ! {PLAYER}{KUN}!\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}これから わたしと しょうぶ してみない?\n"
	.string "{JPN}{STR_VAR_2} で まってるよ!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "{JPN}おーっす {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1} だ!\p"
	.string "{JPN}あれから おれの ポケモンも\n"
	.string "{JPN}たくましく なったぞ!\p"
	.string "{JPN}{PLAYER}の ポケモンで\n"
	.string "{JPN}うでだめし したいから\p"
	.string "{JPN}しょうぶ してみないか?\n"
	.string "{JPN}{STR_VAR_2} で まってるぞ$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}ちょうしは どうだい?\n"
	.string "{JPN}おれの ポケモンも\l"
	.string "{JPN}ずいぶん つよく なったよ\p"
	.string "{JPN}そうだ また おれと\n"
	.string "{JPN}しょうぶ しないかい?\p"
	.string "{JPN}じゃあ {STR_VAR_2}で あおう$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だけど\p"
	.string "{JPN}おれの ポケモン\n"
	.string "{JPN}けっこう いいかんじに そだってきたよ\p"
	.string "{JPN}きみと もういちど\n"
	.string "{JPN}しょうぶ してみたいなあ\p"
	.string "{JPN}{STR_VAR_2} で まってるよ\n"
	.string "{JPN}じゃあね$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だけど\l"
	.string "{JPN}げんきで やってるかい?\p"
	.string "{JPN}また きみと ポケモンしょうぶを\n"
	.string "{JPN}してみたいんだけど どうだい?\p"
	.string "{JPN}しょうぶ したくなったら\n"
	.string "{JPN}{STR_VAR_2}に きてくれよ\p"
	.string "{JPN}じゃあ また$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "{JPN}あ {PLAYER}{KUN}?\n"
	.string "{JPN}{STR_VAR_1} だけど...\p"
	.string "{JPN}どう? ポケモン そだってる?\n"
	.string "{JPN}ぼくの ポケモンも つよくなったから\l"
	.string "{JPN}きみに みせたいなあ\p"
	.string "{JPN}{STR_VAR_2}で まってるから\n"
	.string "{JPN}しょうぶ しに きてくれよ\p"
	.string "{JPN}じゃあ また$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}ちょうしは どうですか?\n"
	.string "{JPN}わたしの ポケモンは とても げんきですよ\p"
	.string "{JPN}こんど こちらに いらしたら\n"
	.string "{JPN}また わたしと\l"
	.string "{JPN}しょうぶ してくださいね\p"
	.string "{JPN}{STR_VAR_2}で まってます\n"
	.string "{JPN}では また$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n"
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}ポケモンの ちょうしは どうかな?\n"
	.string "{JPN}わたしの ポケモンも\p"
	.string "{JPN}どんどん つよく なってるのよ\n"
	.string "{JPN}{PLAYER}{KUN}にも みせてあげたいなあ\p"
	.string "{JPN}{STR_VAR_2}に いるから\n"
	.string "{JPN}ちかくに きたら しょうぶでも しようよ\p"
	.string "{JPN}じゃあ またね$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}どう? げんきで やってるかしら?\n"
	.string "{JPN}あれから わたしの ポケモンも\l"
	.string "{JPN}ずいぶん つよく なったのよ\p"
	.string "{JPN}また {PLAYER}{KUN}と\n"
	.string "{JPN}しょうぶ したいなあ\p"
	.string "{JPN}{STR_VAR_2}に いるから\n"
	.string "{JPN}ちかくに きたら あいに きてね$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だけど\l"
	.string "{JPN}いま どこに いるのかな?\p"
	.string "{JPN}わしの ポケモンは とても げんき だぞ\n"
	.string "{JPN}{PLAYER}{KUN}の ポケモンと あうのを\l"
	.string "{JPN}たのしみに しているみたいだ\p"
	.string "{JPN}{STR_VAR_2}に いるから\n"
	.string "{JPN}ぜひ あいに きてくれよ$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃ\p"
	.string "{JPN}わしの ポケモンも あれから\n"
	.string "{JPN}ずいぶんと たくましく なったぞ\p"
	.string "{JPN}{PLAYER}{KUN}の ポケモンと\n"
	.string "{JPN}もういちど てあわせ したいのう\p"
	.string "{JPN}{STR_VAR_2}に おるから\n"
	.string "{JPN}いつでも きてくれたまえ$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃ\p"
	.string "{JPN}ポケモンは げんきに しとるかね?\n"
	.string "{JPN}わしの ポケモンも\l"
	.string "{JPN}まけない ぐらい げんきに しておるよ\p"
	.string "{JPN}また しょうぶ してみたいので\n"
	.string "{JPN}{STR_VAR_2}の ちかくに きたら\p"
	.string "{JPN}あいに きてくれんかのう\n"
	.string "{JPN}では またの$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}げんきに してる?\n"
	.string "{JPN}あ そうそう\p"
	.string "{JPN}わたしの ポケモン\n"
	.string "{JPN}あれから けっこう つよく なったのよ\p"
	.string "{JPN}{PLAYER}{KUN}と もういちど\n"
	.string "{JPN}しょうぶ してみたいわねえ\p"
	.string "{JPN}{STR_VAR_2}で まってるから\n"
	.string "{JPN}いつでも あいに きてね$"

MatchCall_PersonalizedText1::
	.string "{JPN}やまを あいする {STR_VAR_1}だが\p"
	.string "{JPN}どうだね あれから\n"
	.string "{JPN}すこしは やまが すきに なったか?\l"
	.string "{JPN}あまり やまで きみを みかけないが...\p"
	.string "{JPN}よし つぎは {STR_VAR_2}で\n"
	.string "{JPN}あおう じゃないか またな!$"

MatchCall_PersonalizedText2::
	.string "{JPN}{STR_VAR_1}です\n"
	.string "{JPN}こんにちは\p"
	.string "{JPN}いまね トレーナーに なりたてのコに\n"
	.string "{JPN}あなたの ことを きかせて いたのよ!\l"
	.string "{JPN}ポケモンを たいせつに そだてている\l"
	.string "{JPN}つよい トレーナーが いるのよって...\p"
	.string "{JPN}みんなの あこがれに なるような\n"
	.string "{JPN}すばらしい トレーナーに なってね!\l"
	.string "{JPN}じゃあ また あいましょう!$"

MatchCall_PersonalizedText3::
	.string "{JPN}こんにちは! {STR_VAR_1}よ\n"
	.string "{JPN}この あたりは ほんとうに\l"
	.string "{JPN}いいかおりが して きもちがいいわ\p"
	.string "{JPN}だれかが きのみを うめて\n"
	.string "{JPN}はなを さかせて くれたのかしら? うふふ\p"
	.string "{JPN}それじゃ またね!$"

MatchCall_PersonalizedText4::
	.string "{JPN}はいはい! いせきを さがして 30ねん\n"
	.string "{JPN}わたし {STR_VAR_1}で ございます\p"
	.string "{JPN}きみは せっきょくてきに あちこちを\n"
	.string "{JPN}まわって いるよう だけど\l"
	.string "{JPN}なにか いせきを みつけたかい?\l"
	.string "{JPN}みつけたら おしえて くれよ!\p"
	.string "{JPN}では わたしは\n"
	.string "{JPN}いせきを さがすので これで$"

MatchCall_PersonalizedText5::
	.string "{JPN}{STR_VAR_1} でーす\n"
	.string "{JPN}きょうはね すなはま から\l"
	.string "{JPN}うみを ながめて いるんだ!\p"
	.string "{JPN}はー... キラキラ なみが ひかって\n"
	.string "{JPN}ここから みる うみが いちばん きれい!\l"
	.string "{JPN}あー おなかすいた じゃあまたね!$"

MatchCall_PersonalizedText6::
	.string "{JPN}もぐもぐ...\n"
	.string "{JPN}あ {STR_VAR_1}です\l"
	.string "{JPN}すなはまで たべる おにぎりは うまいなー\p"
	.string "{JPN}うーん ぼくも ポケモンも\n"
	.string "{JPN}げんきに なったぞ!\l"
	.string "{JPN}じゃ およいで くるね!$"

MatchCall_PersonalizedText7::
	.string "{JPN}やあ {STR_VAR_1} だけど...\p"
	.string "{JPN}エリートトレーナー の せいかつに\n"
	.string "{JPN}ちょっと つかれちゃってね...\p"
	.string "{JPN}みんな ぼくのことを\n"
	.string "{JPN}かんぺきな トレーナーだと おもうから\l"
	.string "{JPN}ぼくも それらしく しないと いけない\p"
	.string "{JPN}でも それも エリートトレーナーの\n"
	.string "{JPN}しゅくめいだと おもって\l"
	.string "{JPN}がんばる ことに するよ!\p"
	.string "{JPN}こんな ことが いえるのは キミだけだ\n"
	.string "{JPN}でも こんど あった ときは\l"
	.string "{JPN}よわねは はかないから あんしんして!\l"
	.string "{JPN}じゃ!$"

MatchCall_PersonalizedText8::
	.string "{JPN}ヤッホー {STR_VAR_1}よ\n"
	.string "{JPN}こんにちは!\p"
	.string "{JPN}いま あなたを めざして\n"
	.string "{JPN}ポケモンを そだてて いるの!\l"
	.string "{JPN}こんど たたかう ときは\l"
	.string "{JPN}ぜったい まけない つもり! ふふっ\p"
	.string "{JPN}トレーナー なかまが いるって いいよね\n"
	.string "{JPN}また あいましょう!$"

MatchCall_PersonalizedText9::
	.string "{JPN}{STR_VAR_1} ですけど...\n"
	.string "{JPN}いま あなたの うしろ...\l"
	.string "{JPN}なにかが いない...?\p"
	.string "{JPN}ここ おくりびやまで ねむっている\n"
	.string "{JPN}ポケモンたちの ちからが\l"
	.string "{JPN}わたしに おしえて くれるの...\l"
	.string "{JPN}ふりかえらないで そのまま\l"
	.string "{JPN}まっすぐ あるいたほうが いいわよ...\p"
	.string "{JPN}フフ...\n"
	.string "{JPN}それじゃあ さよなら...$"

MatchCall_PersonalizedText10::
	.string "{JPN}わたくし {STR_VAR_1}ですわ\n"
	.string "{JPN}ごきげんよう\p"
	.string "{JPN}はなれていても こうして\n"
	.string "{JPN}おはなし できるなんて べんりね\p"
	.string "{JPN}いままでは あいたい ひとが いたら\n"
	.string "{JPN}パパに おくってもらって いたもの...\p"
	.string "{JPN}それではまた...\n"
	.string "{JPN}おはなし できて うれしかった ですわ$"

MatchCall_PersonalizedText11::
	.string "{JPN}{STR_VAR_1}よ\n"
	.string "{JPN}ちょっと はなし ききなさいよ!\p"
	.string "{JPN}わたし サファリゾーンが すきなんだけど\n"
	.string "{JPN}あそこに いくと かならず まようのよ!\l"
	.string "{JPN}くさ ばっかり はえてて\l"
	.string "{JPN}ちょっと ひろすぎるのよねー! ぷんぷん!\p"
	.string "{JPN}あー おこったら きが すんだわ\n"
	.string "{JPN}ちょっと サファリゾーンでも いこっと!\l"
	.string "{JPN}またね!$"

MatchCall_PersonalizedText12::
	.string "{JPN}やあ\n"
	.string "{JPN}おかねもちの {STR_VAR_1} だけど\p"
	.string "{JPN}ボク あれから ますます\n"
	.string "{JPN}おかねもちに なっちゃったし\l"
	.string "{JPN}ポケモンも ますます つよく なったよ\p"
	.string "{JPN}この せかいって\n"
	.string "{JPN}ボクの ために あるんじゃない かな?\p"
	.string "{JPN}ああ へんじは しなくて いいよ\n"
	.string "{JPN}わかっている ことだからね!\l"
	.string "{JPN}おっと そろそろ ディナーのじかんだ\l"
	.string "{JPN}しつれい するよ!$"

MatchCall_PersonalizedText13::
	.string "{JPN}うふふふふふふ...\n"
	.string "{JPN}ボ ボク {STR_VAR_1}です\p"
	.string "{JPN}いま めのまえで\n"
	.string "{JPN}{STR_VAR_2} どうしが たたかってるんだ\l"
	.string "{JPN}かった ほうを つかまえよう かな?\l"
	.string "{JPN}うふふふふ...\p"
	.string "{JPN}じ じゃ いそがしいから\n"
	.string "{JPN}ボクは これで$"

MatchCall_PersonalizedText14::
	.string "{JPN}あ {STR_VAR_1}です!\n"
	.string "{JPN}そろそろ すてられぶね にも\l"
	.string "{JPN}あきて きちゃった のよね\p"
	.string "{JPN}でも せっかく だから\n"
	.string "{JPN}いちどは キミに かって みたいし\l"
	.string "{JPN}とうぶんは ここで さんぽ してるわ\l"
	.string "{JPN}きが むいたら あいに きてよね!\p"
	.string "{JPN}よし きょうは ついに\n"
	.string "{JPN}となりの へやの おじさんに\l"
	.string "{JPN}しょうぶを いどんで みようかな?\p"
	.string "{JPN}ではね!$"

MatchCall_PersonalizedText15::
	.string "{JPN}うみの おとこ\n"
	.string "{JPN}{STR_VAR_1}だぜ!\p"
	.string "{JPN}やっぱさ!\n"
	.string "{JPN}でっかい うみに いる トレーナーは\l"
	.string "{JPN}つよいやつ ばっかりだぜ!\p"
	.string "{JPN}おまえも オレらを みならって\n"
	.string "{JPN}うみで しゅぎょうすりゃ いいのによ...\l"
	.string "{JPN}...と おおなみが きそうだ!\p"
	.string "{JPN}しゅぎょうの チャンスだぜ!\n"
	.string "{JPN}わるいけど またなっ!$"

MatchCall_PersonalizedText16::
	.string "{JPN}{STR_VAR_1}だ!\n"
	.string "{JPN}ポケモンに カラテを おしえてたら\l"
	.string "{JPN}ほんとに おれより つよくなっちまって\l"
	.string "{JPN}おれ まけまくりだ!\p"
	.string "{JPN}だが おれは ポケモンに まけても\n"
	.string "{JPN}トレーナー には まけん!\l"
	.string "{JPN}いつか また おれと しょうぶだ!\l"
	.string "{JPN}うがー!$"

MatchCall_PersonalizedText17::
	.string "{JPN}{STR_VAR_1}だけど\n"
	.string "{JPN}そっちの たびは どんなカンジ?\p"
	.string "{JPN}...へえー なるほど なるほど\n"
	.string "{JPN}たのしそうじゃん!\l"
	.string "{JPN}きみの エピソードで\l"
	.string "{JPN}1きょく つくれそうだな!\p"
	.string "{JPN}...おッ うかんできた\n"
	.string "{JPN}いい フレーズ うかんできたよ!\p"
	.string "{JPN}じゃ オレ いまから\n"
	.string "{JPN}きょくづくりに はいるから またな!$"

MatchCall_PersonalizedText18::
	.string "{JPN}{STR_VAR_1}だけど...\n"
	.string "{JPN}ボクの しんきょく きいてくれ\p"
	.string "{JPN}ルル {STR_VAR_2} {STR_VAR_2}\n"
	.string "{JPN}どうして おまえは {STR_VAR_2}なんだ\l"
	.string "{JPN}どうして ボクは {STR_VAR_2}では ないんだ\l"
	.string "{JPN}あー ルルル {STR_VAR_2}と{STR_VAR_1}\l"
	.string "{JPN}{STR_VAR_1}と{STR_VAR_2} ルル...\p"
	.string "{JPN}フェードアウト...$"

MatchCall_PersonalizedText19::
	.string "{JPN}キャンプの たつじん\n"
	.string "{JPN}{STR_VAR_1} だ!\p"
	.string "{JPN}ま こないだ ぼくが まけちゃったのは\n"
	.string "{JPN}ぼくの せんもんが キャンプだからね\l"
	.string "{JPN}しかたが なかったのさ!\p"
	.string "{JPN}かっても まけても\n"
	.string "{JPN}キャンプで ポケモンしょうぶ するの\l"
	.string "{JPN}ぼく だいすき なんだ!\p"
	.string "{JPN}またこんど あいてを たのむよ\n"
	.string "{JPN}あ キャンプも いっしょに しようぜ!$"

MatchCall_PersonalizedText20::
	.string "{JPN}おれ おれ {STR_VAR_1}!\p"
	.string "{JPN}いやあ おれも ほかの やまにも\n"
	.string "{JPN}のぼって みても いいんだけどさー\l"
	.string "{JPN}えんとつやま みたいに\l"
	.string "{JPN}きれいな おねいさん たちが\l"
	.string "{JPN}いるか どうか わからんもんなー\p"
	.string "{JPN}きれいな おねいさんが いっぱいの\n"
	.string "{JPN}やまが あったら おしえて くれよ!\l"
	.string "{JPN}えへへへ またなあ!$"

MatchCall_PersonalizedText21::
	.string "{JPN}... ... ...\n"
	.string "... ... ...\l"
	.string "{JPN}{STR_VAR_1} です...\p"
	.string "... ... ...\n"
	.string "... ... ...\l"
	.string "{JPN}きょうは それだけ...$"

MatchCall_PersonalizedText22::
	.string "{JPN}{STR_VAR_1}だよ... きょうは\n"
	.string "{JPN}きみと はなす きが してたんだ\p"
	.string "{JPN}きみに かちたい きもちは\n"
	.string "{JPN}ひましに つよくなる ばかりだよ\l"
	.string "{JPN}きみ にも そんな あいてが いるだろ?\l"
	.string "{JPN}それが ぼくなら いいのにな\p"
	.string "{JPN}きいて くれて ありがと またな!$"

MatchCall_PersonalizedText23::
	.string "{JPN}{STR_VAR_1}です\p"
	.string "{JPN}つよい トレーナーが ちかくに いると\n"
	.string "{JPN}なんとなく その そんざいを\l"
	.string "{JPN}かんじる ことが あるの\p"
	.string "{JPN}もしかしたら {PLAYER}{KUN}が\n"
	.string "{JPN}わたしの そばを とおったの かもね?\p"
	.string "{JPN}あいに きて くれるのを\n"
	.string "{JPN}まっているわ! バーイ!$"

MatchCall_PersonalizedText24::
	.string "{JPN}{STR_VAR_1}です\n"
	.string "{JPN}{PLAYER}{KUN}は げんきそう ですな\p"
	.string "{JPN}せかい かっこくを まわった わたしですが\n"
	.string "{JPN}この ちほうを たいへん きにいりました\l"
	.string "{JPN}とうぶん いる つもりですよ\p"
	.string "{JPN}そういう わけ ですから\n"
	.string "{JPN}また あえるかも しれませんね\p"
	.string "{JPN}あなたの みごとな わざ\n"
	.string "{JPN}わすれては おりませんよ\l"
	.string "{JPN}また おあいてを おねがいしますね$"

MatchCall_PersonalizedText25::
	.string "{JPN}グスン {STR_VAR_1}...です\n"
	.string "{JPN}...グスン\p"
	.string "{JPN}きょう ツツジさんに\n"
	.string "{JPN}おこられ ちゃった\p"
	.string "{JPN}でも ツツジさんは\n"
	.string "{JPN}なんで ボクが わるいのか\l"
	.string "{JPN}ちゃんと おしえて くれるから\l"
	.string "{JPN}うらんだり しないよ!\p"
	.string "{JPN}あしたも また いくんだ\n"
	.string "{JPN}トレーナーズ スクール! えへ...\l"
	.string "{JPN}じゃ またね!$"

MatchCall_PersonalizedText26::
	.string "{JPN}{STR_VAR_1} です!\p"
	.string "{JPN}きのう ツツジさまに\n"
	.string "{JPN}しょうぶ してもらったの!\p"
	.string "{JPN}けっかは さんざん だったけど...\n"
	.string "{JPN}ツツジさまが あたしの あいてを\l"
	.string "{JPN}してくれた って いうことが\l"
	.string "{JPN}すごく うれしいの!\l"
	.string "{JPN}ますます あこがれちゃうわ!\p"
	.string "{JPN}いまから また もうべんきょうよ!\n"
	.string "{JPN}だから さよなら!$"

MatchCall_PersonalizedText27::
	.string "{JPN}ミホでーす!\n"
	.string "{JPN}きょうも こうはいの リコと いっしょだよ\p"
	.string "{JPN}もうね! リコも ポケモンも\n"
	.string "{JPN}かわいくて しかたないの\l"
	.string "{JPN}おとうとや いもうと みたいに\l"
	.string "{JPN}ずーっと めんどう みて あげたいな!\p"
	.string "{JPN}あ リコ!\n"
	.string "{JPN}パン かってきて くれた?\p"
	.string "{JPN}え? な なによ\n"
	.string "{JPN}つかいっぱしり なんて させてないわよ!\l"
	.string "{JPN}ポケモン しょうぶで まけたから\l"
	.string "{JPN}これは ばつゲームなの!\p"
	.string "{JPN}かわいい リコを\n"
	.string "{JPN}こきつかうわけ ないでしょ!\l"
	.string "{JPN}じゃ これから おやつだから バイバイ!$"

MatchCall_PersonalizedText28::
	.string "{JPN}ポケモン だいすき!\n"
	.string "{JPN}だいすきクラブの {STR_VAR_1}です!\p"
	.string "{JPN}きっ きいて くださいよ!\n"
	.string "{JPN}わたしの ポケモンちゃんが なんと...!\l"
	.string "{JPN}ぐふ ぐふふふ\l"
	.string "{JPN}これいじょうは ひみつ!\l"
	.string "{JPN}もー かわいすぎて くちに できない!\p"
	.string "{JPN}ああっ {STR_VAR_2}ちゃんが\n"
	.string "{JPN}ポロックを おねだりしてるー!\l"
	.string "{JPN}かわいいぞーーーっ!\p"
	.string "{JPN}わるいけど きみと\n"
	.string "{JPN}はなしている ばあいじゃ ないぞ!\l"
	.string "{JPN}また こんど つづきを きいてくれ$"

MatchCall_PersonalizedText29::
	.string "{JPN}おほほ!\p"
	.string "{JPN}ポケモンを じまん したくて しかたない\n"
	.string "{JPN}{STR_VAR_1} ですわ!\p"
	.string "{JPN}あなた おききに なって\n"
	.string "{JPN}あたくしの {STR_VAR_2}ちゃん...\l"
	.string "{JPN}ほかの ひとに だっこされると\l"
	.string "{JPN}ピョンと にげだして\l"
	.string "{JPN}あたくしの むねに とびこんでくるの!\p"
	.string "{JPN}もう... もう!\n"
	.string "{JPN}こんな しあわせって ほかに あるかしら!\p"
	.string "{JPN}ああ しあわせだわ\n"
	.string "{JPN}あなたにも しあわせを わけて あげられて\l"
	.string "{JPN}よかったわ!\l"
	.string "{JPN}では しつれい するわね$"

MatchCall_PersonalizedText30::
	.string "{JPN}わたしは... {STR_VAR_1}だ\p"
	.string "{JPN}ひとは わたしを たつじんと よぶ\n"
	.string "{JPN}だが わたしは わかっている\l"
	.string "{JPN}わたしだけの ちから では\l"
	.string "{JPN}たつじん には なれない ことを\p"
	.string "{JPN}ポケモンの ちからが あってこそ\n"
	.string "{JPN}トレーナーは たつじんに なれる!\p"
	.string "{JPN}うむ...! わたしは いま\n"
	.string "{JPN}すごく いいことを いった きがする!\l"
	.string "{JPN}きもちがよい ままに わかれよう!$"

MatchCall_PersonalizedText31::
	.string "{JPN}{STR_VAR_1} じゃよ\n"
	.string "{JPN}おんせんに つかって ごきげんだからねぇ\l"
	.string "{JPN}こうして おはなし できて うれしいよ!\p"
	.string "{JPN}あれから なんにんか\n"
	.string "{JPN}わかい トレーナーさんと たたかったが\l"
	.string "{JPN}おまえさんが いちばん つよかったよ!\p"
	.string "{JPN}きっと としを とったら\n"
	.string "{JPN}たつじんに なるじゃろうな!\l"
	.string "{JPN}おっほっほっほ...$"

MatchCall_PersonalizedText32::
	.string "{JPN}わーい! {STR_VAR_1}でーす!\n"
	.string "{JPN}げんきー?\p"
	.string "{JPN}ボクが ポケモン かてる ときって\n"
	.string "{JPN}きのせいかも しれないけど\l"
	.string "{JPN}たんパンの ちょうしが いいんだ!\p"
	.string "{JPN}え どういうこと かって?\n"
	.string "{JPN}うーん うまく せつめい できないけど\l"
	.string "{JPN}なんていう のかな...\l"
	.string "{JPN}はき ごこちが サラっと してるんだ!\p"
	.string "{JPN}で {PLAYER}{KUN}と しょうぶの ときは\n"
	.string "{JPN}だいたい ベタっと してるんだよね...\p"
	.string "... ... ...\n"
	.string "{JPN}ボクの はなし しんじた?\l"
	.string "{JPN}えへへへ じゃあね バイバーイ!$"

MatchCall_PersonalizedText33::
	.string "{JPN}うおーい!\n"
	.string "{JPN}{STR_VAR_1}だぞーっ!\l"
	.string "{JPN}きょうも ごうかいに\l"
	.string "{JPN}つりを たのしんで いるぞーっ!\p"
	.string "{JPN}うみ か かわ いがいに\n"
	.string "{JPN}つりが できる ばしょって ないかーっ?\l"
	.string "{JPN}どこでも つりが したくって\l"
	.string "{JPN}うずうずするんだーっ!\p"
	.string "{JPN}おっと つりいとが からまった!\n"
	.string "{JPN}じゃ つりが できるところ\l"
	.string "{JPN}さがしといてくれーっ! またなーっ!$"

MatchCall_PersonalizedText34::
	.string "{JPN}やあ! {STR_VAR_1} だけど\n"
	.string "{JPN}どう のんびり やっている かい?\p"
	.string "{JPN}ボクはさ むかしから\n"
	.string "{JPN}あせったり いそいだり するのが\l"
	.string "{JPN}にがて なんだよね\l"
	.string "{JPN}それでも なぜか いまは\l"
	.string "{JPN}トライアスリートを やっている...\p"
	.string "{JPN}じんせい なにが おこるか\n"
	.string "{JPN}わからないって ヤツだな! はは\p"
	.string "{JPN}キミも いまは トレーナーだけど\n"
	.string "{JPN}しょうらいは せんせい とか えかき とか\l"
	.string "{JPN}よそうも つかない ことを\l"
	.string "{JPN}やって いるの かもな!\p"
	.string "{JPN}まー のんびり やれよ!\n"
	.string "{JPN}じゃあなー$"

MatchCall_PersonalizedText35::
	.string "{JPN}{STR_VAR_1}よ!\n"
	.string "{JPN}いま じてんしゃに のっているわ!\p"
	.string "{JPN}わたし すいえいも はしるのも すきだけど\n"
	.string "{JPN}じてんしゃが いちばん すきなの!\l"
	.string "{JPN}だって からだに かぜを\l"
	.string "{JPN}たくさん かんじる ことが できるでしょ?\l"
	.string "{JPN}そらをとぶ みたいで きもちいいのよ!\p"
	.string "{JPN}よーし きょうこそ サイクリングロードで\n"
	.string "{JPN}しんきろくを だすわっ!\l"
	.string "{JPN}あなたも ちょうせん しに きなさいよ!\l"
	.string "{JPN}じゃあねーっ$"

MatchCall_PersonalizedText36::
	.string "{JPN}よお! トライアスロンの まっさいちゅうの\n"
	.string "{JPN}{STR_VAR_1}だけど\l"
	.string "{JPN}さくっと せけんばなし でも どうだい!\p"
	.string "{JPN}ポケモンと いっしょに あせを ながすと\n"
	.string "{JPN}すごく きもちいいぜ!\l"
	.string "{JPN}ことばに ださなくったって\l"
	.string "{JPN}ふたりの こころが つうじあうんだ\l"
	.string "{JPN}あれは ちょっと かんどう するなあ!\p"
	.string "{JPN}はあはあ... はしりながら はなしてたら\n"
	.string "{JPN}たいりょくが なくなった!\l"
	.string "{JPN}はあはあ わるいけど こんどな!$"

MatchCall_PersonalizedText37::
	.string "{JPN}こんにちは {STR_VAR_1}よ\n"
	.string "{JPN}じきゅうりょく を つけるには\l"
	.string "{JPN}やっぱり たかい ところが いいわね!\p"
	.string "{JPN}やまの てっぺん とかで\n"
	.string "{JPN}はしり まわると\l"
	.string "{JPN}すぐに いきが きれるのよ!\p"
	.string "{JPN}ああ わたしも いきが きれそう\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_PersonalizedText38::
	.string "{JPN}ああ {STR_VAR_1} です\n"
	.string "{JPN}あれから だいぶ およいだけど\l"
	.string "{JPN}サイユウシティには まだ つかないのかなあ\p"
	.string "{JPN}もしかして おなじ ところを\n"
	.string "{JPN}ぐるぐる まわってるだけ だったりして\p"
	.string "{JPN}いや まさか そんなこと ないよな\n"
	.string "{JPN}わはははは\l"
	.string "{JPN}じゃあ また!$"

MatchCall_PersonalizedText39::
	.string "{JPN}ああ {STR_VAR_1} ですけ...\p"
	.string "{JPN}ボチャン\p"
	.string "{JPN}ブクブクブク......\p"
	.string "{JPN}ザバー\p"
	.string "{JPN}ブンブン\p"
	.string "{JPN}...ごッ ごめん!\n"
	.string "{JPN}いま オイルを ぬった てで\l"
	.string "{JPN}ポケナビを もってたら\l"
	.string "{JPN}うみに おとして しまったんだ!\p"
	.string "{JPN}うみに おとしても こわれないなんて\n"
	.string "{JPN}デボンの ポケナビって すげーな!\l"
	.string "{JPN}じゃ にっこうよくの つづきを するんで\l"
	.string "{JPN}またこんど はなそうぜ!$"

MatchCall_PersonalizedText40::
	.string "{JPN}トライアスロンの なかでも\n"
	.string "{JPN}すいえいが だいすきな {STR_VAR_1} です\p"
	.string "{JPN}でも あんまり ながいこと\n"
	.string "{JPN}うみに いると\l"
	.string "{JPN}からだが ふやけちゃわないかなあ\p"
	.string "{JPN}やっぱり トライアスロンは\n"
	.string "{JPN}かこくな レースよね!\l"
	.string "{JPN}じゃ またね!$"

MatchCall_PersonalizedText41::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だ\p"
	.string "{JPN}きみの ポケモンの\n"
	.string "{JPN}ちょうしは どうだい?\p"
	.string "{JPN}ぼくの ドラゴンポケモンたちも\n"
	.string "{JPN}ちょうし よさそうだよ\l"
	.string "{JPN}じゃあ また$"

MatchCall_PersonalizedText42::
	.string "{JPN}{STR_VAR_1}だ\n"
	.string "{JPN}おれの {STR_VAR_2}\l"
	.string "{JPN}あれから いちだんと つよくなったぜ!\p"
	.string "{JPN}つぎ キミと しょうぶ するときは\n"
	.string "{JPN}まけない からな!\p"
	.string "{JPN}じゃあ またな!$"

MatchCall_PersonalizedText43::
	.string "{JPN}{STR_VAR_1}で ござる\n"
	.string "{JPN}かくれかたの けんきゅうを\l"
	.string "{JPN}つづけて いるんだけど\p"
	.string "{JPN}うまく かくれすぎると\n"
	.string "{JPN}だれにも みつけて もらえないで ござる\l"
	.string "{JPN}それは ちょっと さびしいで ござるなあ\p"
	.string "{JPN}それでは これにて どろん!$"

MatchCall_PersonalizedText44::
	.string "{JPN}{STR_VAR_1}よ\n"
	.string "{JPN}あれから しゅぎょうを かさねて\p"
	.string "{JPN}わたしの {STR_VAR_2}も\n"
	.string "{JPN}けっこう つよく なってきたわよ\p"
	.string "{JPN}やっぱり すなはまでの しゅぎょうは\n"
	.string "{JPN}こうかてき だわ!\l"
	.string "{JPN}じゃあ また!$"

MatchCall_PersonalizedText45::
	.string "{JPN}こんにちは {STR_VAR_1}です\n"
	.string "{JPN}かざんばい いつになったら\l"
	.string "{JPN}おさまるの かしら\p"
	.string "{JPN}あんまり つもっちゃうと\n"
	.string "{JPN}パラソルの がらが\l"
	.string "{JPN}みえなく なっちゃうのに...\p"
	.string "{JPN}それでは また\n"
	.string "{JPN}おあい しましょう$"

MatchCall_PersonalizedText46::
	.string "{JPN}{STR_VAR_1} でーす\p"
	.string "{JPN}ねえねえ!\n"
	.string "{JPN}うみって プールと くらべて\l"
	.string "{JPN}うかびやすいって しってた?\p"
	.string "{JPN}こうやって からだを よこに すれば\l"
	.string "{JPN}かってに うくのよ\p"
	.string "{JPN}でも あんまり ながく うかんでると\n"
	.string "{JPN}おきに ながされるから\l"
	.string "{JPN}きを つけないと だめよ\p"
	.string "{JPN}...あれ? ここ どこかしら...\n"
	.string "{JPN}じゃ じゃあ またね!$"

MatchCall_PersonalizedText47::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは!\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}ここって じめんが でこぼこ してるから\n"
	.string "{JPN}テント はれないのよね...\l"
	.string "{JPN}せっかく やまに きたのに...\p"
	.string "{JPN}あ! いいこと おもいついた!\n"
	.string "{JPN}ポケモンで ここを たいらに\l"
	.string "{JPN}できないかしら?\p"
	.string "{JPN}よーし がんばっちゃおう!\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_PersonalizedText48::
	.string "{JPN}あ こんにちは\n"
	.string "{JPN}{STR_VAR_1} でーす\p"
	.string "{JPN}ルミと いっしょに がんばって\n"
	.string "{JPN}ポケモン そだててるの!\p"
	.string "{JPN}もっと がんばったら\n"
	.string "{JPN}いちばんに なれるかなあ?\l"
	.string "{JPN}じゃあ またねー!$"

MatchCall_PersonalizedText49::
	.string "{JPN}{STR_VAR_1}だ!\p"
	.string "{JPN}オレさまは ふなのり だが\n"
	.string "{JPN}いまは ふねに のっていない\p"
	.string "{JPN}ふねに のっていない ふなのりは\n"
	.string "{JPN}なんと よべば いいだろうか!\p"
	.string "{JPN}うみを みながら\n"
	.string "{JPN}そんな ことを かんがえて いるのだ!\l"
	.string "{JPN}じゃあ またな!!$"

MatchCall_PersonalizedText50::
	.string "{JPN}{STR_VAR_1} だよ\n"
	.string "{JPN}どう? ポケモン ふえた?\p"
	.string "{JPN}あたらしい ポケモン つかまえたら\n"
	.string "{JPN}また みせに きてくれよ\p"
	.string "{JPN}ちょうだいって いわないからさ\n"
	.string "{JPN}まってるよ じゃあね$"

MatchCall_PersonalizedText51::
	.string "{JPN}{STR_VAR_1}だ\n"
	.string "{JPN}ポケモン ちゃんと そだててるか?\p"
	.string "{JPN}ここは くうきも きれいだし\n"
	.string "{JPN}ポケモンを そだてるには\l"
	.string "{JPN}ぜっこうの かんきょう なんだよな\p"
	.string "{JPN}きみも ポケモンを そだてる ことに\n"
	.string "{JPN}せんねん する ときは\l"
	.string "{JPN}{STR_VAR_2}に くると いいぞ\l"
	.string "{JPN}じゃあ またな$"

MatchCall_PersonalizedText52::
	.string "{JPN}{STR_VAR_1}です\n"
	.string "{JPN}わたしの {STR_VAR_2}に\p"
	.string "{JPN}ポロック あげたんですよ\n"
	.string "{JPN}とても よろこんでた みたい\p"
	.string "{JPN}ポケモンに よって\n"
	.string "{JPN}ポロックの すききらいが あるみたいなの\p"
	.string "{JPN}おもしろい ですよね\n"
	.string "{JPN}では ごきげんよう$"

MatchCall_PersonalizedText53::
	.string "{JPN}{STR_VAR_1}だ\n"
	.string "{JPN}ポケモンと きょうりょく すれば\l"
	.string "{JPN}しぜんの なかでも\l"
	.string "{JPN}かいてきに くらせる ものだよ\p"
	.string "{JPN}みんな それに きが ついて\n"
	.string "{JPN}もっと ポケモンと\l"
	.string "{JPN}きょうりょく できるように なれば\l"
	.string "{JPN}いいのにな!\p"
	.string "{JPN}きみは けっこう いいセン\n"
	.string "{JPN}いってると おもうよ!\l"
	.string "{JPN}じゃ またな!$"

MatchCall_PersonalizedText54::
	.string "{JPN}いつも ぼうけんの じゅんびを\n"
	.string "{JPN}おこたらない {STR_VAR_1}よ!\p"
	.string "{JPN}{PLAYER}{KUN} どうぐは たりてる?\n"
	.string "{JPN}ポケモンの たいちょうは バッチリ?\p"
	.string "{JPN}じぶんの みの まわりを\n"
	.string "{JPN}つねに かんぺきに しておくことが\l"
	.string "{JPN}たびを ながく つづける ひけつ よ!\p"
	.string "{JPN}わたしも じぶんの どうぐを\n"
	.string "{JPN}かくにん するわ! またね!$"

MatchCall_PersonalizedText55::
	.string "{JPN}{STR_VAR_1}だよ {STR_VAR_1}だよー!\p"
	.string "{JPN}{STR_VAR_2} って\n"
	.string "{JPN}ひとどおりが はげしいから\l"
	.string "{JPN}まいにち いろんな ひとに\l"
	.string "{JPN}しょうぶを もうしこまれるの!\p"
	.string "{JPN}きょうはねえ 5にんに かって\n"
	.string "{JPN}3にんに まけたわ!\l"
	.string "{JPN}あなたのほうは どうだった?\l"
	.string "{JPN}こんど きかせてねっ! じゃあね$"

MatchCall_PersonalizedText56::
	.string "{JPN}むしポケモンを いっぱい もってて\n"
	.string "{JPN}にんきものの {STR_VAR_1} だけど!\p"
	.string "{JPN}...きょう がっこうに\n"
	.string "{JPN}おきにいりの むしポケモンを\l"
	.string "{JPN}いっぱい つれて いったら\l"
	.string "{JPN}すきな おんなのこに なかれ ちゃった...\l"
	.string "{JPN}うう わらいたければ わらって くれよ\p"
	.string "{JPN}ぼくは むしポケモンの よさを\n"
	.string "{JPN}あのコに わかって もらえるまで\l"
	.string "{JPN}がんばるんだ からね!\p"
	.string "{JPN}グッスン じゃーな!$"

MatchCall_PersonalizedText57::
	.string "{JPN}はっ ほっ はっ ほっ\p"
	.string "{JPN}やあ! {STR_VAR_1}です! はっ ほっ\p"
	.string "{JPN}やま...のぼり しながらの おしゃべりも\n"
	.string "{JPN}なかなか どうして... はっ ほっ\l"
	.string "{JPN}トレーニングに なるなあ\p"
	.string "{JPN}ふっ くっ...\n"
	.string "{JPN}おっと のぼりが きつく なってきた\l"
	.string "{JPN}ま また こんど... ゆっくり はなそう!\l"
	.string "{JPN}はっ ほっ はっ...$"

MatchCall_PersonalizedText58::
	.string "{JPN}や や どうも!\n"
	.string "{JPN}いま ナツと おたから さがしててさ!\p"
	.string "{JPN}おたから なんて もしかしたら\n"
	.string "{JPN}ほんとうは ないのかも しれないけど...\p"
	.string "{JPN}ナツと おたからを ふたりで さがす\n"
	.string "{JPN}って ことが だいじ なんだよね\p"
	.string "{JPN}...て あれ ナツ?\n"
	.string "{JPN}な なんで おこってるの?\l"
	.string "{JPN}ほっといて ゴメンね\l"
	.string "{JPN}もちろん キミが いちばん だいじだよぉ\l"
	.string "{JPN}わかっている だろう?\p"
	.string "{JPN}じ じゃ... {PLAYER}さんさようなら$"

MatchCall_PersonalizedText59::
	.string "{JPN}じぶんは {STR_VAR_1}だ!\n"
	.string "{JPN}しゅぎょうの ために また\l"
	.string "{JPN}ムロの ポケモンジムに いってきた!\p"
	.string "{JPN}ジムリーダーの トウキは\n"
	.string "{JPN}あらなみに もまれ つよくなった!\l"
	.string "{JPN}なのに ちっとも あせくさく ないし\l"
	.string "{JPN}もてもてで しょうじき くやしい!\p"
	.string "{JPN}なかまの シバ という おとこも\n"
	.string "{JPN}きっと あせくさく なくて\l"
	.string "{JPN}ビッグウェーブ だとか ボク だとか\l"
	.string "{JPN}さわやかに いったり するのだろう!\p"
	.string "{JPN}...やきもちは みぐるしいな!\n"
	.string "{JPN}すまん わすれて くれ! オスっ!$"

MatchCall_PersonalizedText60::
	.string "{JPN}わかい トレーナーさんと\n"
	.string "{JPN}おはなし できて うれしい のう\p"
	.string "{JPN}きみも もちろん\n"
	.string "{JPN}なんさいに なっても ポケモンを\l"
	.string "{JPN}がんばる つもり じゃろう?\l"
	.string "{JPN}その ときには わしらのように\l"
	.string "{JPN}だれか あいてが いると いいのう!\p"
	.string "{JPN}まあ {PLAYER}{KUN}は いまだって\n"
	.string "{JPN}ポケモンに しんらい されて\l"
	.string "{JPN}ずっと がんばって おるからのう\p"
	.string "{JPN}りっぱな きんこんしきに なれる\n"
	.string "{JPN}そしつは バッチリじゃ!\l"
	.string "{JPN}はっはっはっ がんばるのじゃよ!$"

MatchCall_PersonalizedText61::
	.string "{JPN}{STR_VAR_1}です!\n"
	.string "{JPN}さっき ボクたち めずらしく\l"
	.string "{JPN}かいパンの おにいさんに かったんだ!\l"
	.string "{JPN}でも かっこいい ひとだった から...\p"
	.string "{JPN}せっかく かよわい ところを\n"
	.string "{JPN}みせようと したのに!\p"
	.string "{JPN}って ねえちゃんに おこられた...\p"
	.string "{JPN}どーせ かっても まけても\n"
	.string "{JPN}おこられるんだ ボクは!\l"
	.string "{JPN}{PLAYER}{KUN}も こんど\l"
	.string "{JPN}なんとか いって やって!\p"
	.string "{JPN}じゃ またねー!$"

MatchCall_PersonalizedText62::
	.string "{JPN}{STR_VAR_1}だよ うん...\n"
	.string "{JPN}きのうは いせきを もとめて\l"
	.string "{JPN}ちがう うみに でようと したら\l"
	.string "{JPN}みちに まよってしまったよ\p"
	.string "{JPN}うみを めぐり めぐって\n"
	.string "{JPN}きがついたら また もとの ばしょさ\p"
	.string "{JPN}あいかわらず しょうぶも よわいし\n"
	.string "{JPN}もう わらって くれよ...\p"
	.string "{JPN}まあ わしは あきらめんぞ\n"
	.string "{JPN}いつのひか いせきを みつけたら\l"
	.string "{JPN}わしの じだいが くるだろう からな!\p"
	.string "{JPN}そういった わけで\n"
	.string "{JPN}きょうは これで さらばだ!$"

MatchCall_PersonalizedText63::
	.string "{JPN}やあー きみーっ!\n"
	.string "{JPN}{STR_VAR_1}だー!\l"
	.string "{JPN}わたしは いまー\l"
	.string "{JPN}108ばんすいどうに きているーっ!\p"
	.string "{JPN}つまり いつもと おなじ ところだー!\p"
	.string "{JPN}きょうは めの まえを\n"
	.string "{JPN}ビキニのおねえさんが とおったからーっ\l"
	.string "{JPN}おおごえで おどかして みたーっ!\p"
	.string "{JPN}そしたら いやな かおを されたー!\p"
	.string "{JPN}いじょう 108ばんすいどう から\n"
	.string "{JPN}{STR_VAR_1}が おつたえ したー!$"

MatchCall_PersonalizedText64::
	.string "{JPN}{STR_VAR_1}よ!\n"
	.string "{JPN}いま いそがしいんだけど\l"
	.string "{JPN}きょうは もう\l"
	.string "{JPN}5にんの トレーナーを たおしたから\l"
	.string "{JPN}あなたにも いちおう ほうこく するわ!\p"
	.string "{JPN}この ちょうし だと\n"
	.string "{JPN}つぎは たぶん あなたに かてるわね!\l"
	.string "{JPN}わたしたち いい ライバルとして\l"
	.string "{JPN}やって いけそうね...\l"
	.string "{JPN}じゃあね バイ!$"

MatchCall_BattleFrontierStreakText1::
	.string "{JPN}こんにちは {STR_VAR_1} です!\n"
	.string "{JPN}きいたよ!\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}すごい かつやく したんだって?\p"
	.string "{JPN}{STR_VAR_3}れんしょう って すごいなあ\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_BattleFrontierStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす\n"
	.string "{JPN}{STR_VAR_2} で\l"
	.string "{JPN}{STR_VAR_3}れんしょう したって きいたわよ!\p"
	.string "{JPN}すっごーい! わたしも がんばろうっと!\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_BattleFrontierStreakText3::
	.string "{JPN}おう! {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1}だぞ!\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}おおあばれ したらしいな!\p"
	.string "{JPN}{STR_VAR_3}れんしょう って\n"
	.string "{JPN}すごい きろく なんだろ?\p"
	.string "{JPN}おれも まけられねーな!\n"
	.string "{JPN}じゃ またな!$"

MatchCall_BattleFrontierStreakText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だけど げんき かい?\p"
	.string "{JPN}うわさで きいたんだけど\n"
	.string "{JPN}きみ {STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんだって?\p"
	.string "{JPN}ぼくも がんばらなきゃな\n"
	.string "{JPN}じゃあ また$"

MatchCall_BattleFrontierStreakText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したんだってね!\l"
	.string "{JPN}すごいなあ\p"
	.string "{JPN}ぼくも ポケモン そだてなきゃ\n"
	.string "{JPN}じゃあ また$"

MatchCall_BattleFrontierStreakText6::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}こんにちは {STR_VAR_1} だ\p"
	.string "{JPN}そういえば きみ\n"
	.string "{JPN}{STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんだってね\p"
	.string "{JPN}おれも がんばって\n"
	.string "{JPN}ポケモンを そだてるよ$"

MatchCall_BattleFrontierStreakText7::
	.string "{JPN}えーと あ {PLAYER}{KUN}?\n"
	.string "{JPN}{STR_VAR_1} だ...\p"
	.string "{JPN}そういえば {STR_VAR_2} で\n"
	.string "{JPN}{STR_VAR_3}れんしょう したんだってね\p"
	.string "{JPN}あ! いま めずらしい ポケモンを\n"
	.string "{JPN}みつけたから じゃあ また!$"

MatchCall_BattleFrontierStreakText8::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}ちょうしは どうですか?\n"
	.string "{JPN}そういえば {STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいですね!\n"
	.string "{JPN}つぎも がんばってね$"

MatchCall_BattleFrontierStreakText9::
	.string "{JPN}あら {PLAYER}{KUN}!\n"
	.string "{JPN}こんにちは {STR_VAR_1}です!\p"
	.string "{JPN}きいたわよ! {STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したって!\p"
	.string "{JPN}すっごいねー\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattleFrontierStreakText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいわねえ\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattleFrontierStreakText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だ\p"
	.string "{JPN}{STR_VAR_2}で だいかつやく らしいなあ\n"
	.string "{JPN}{STR_VAR_3}れんしょう したんだって?\p"
	.string "{JPN}すげえなあ おれだったら\n"
	.string "{JPN}なんれんしょう できるのかな$"

MatchCall_BattleFrontierStreakText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}ひとづてに きいたのじゃが\n"
	.string "{JPN}{STR_VAR_2} とかいう ところで\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したらしいのう?\p"
	.string "{JPN}すごい はなし だのう\n"
	.string "{JPN}では またの$"

MatchCall_BattleFrontierStreakText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したそうじゃのう\p"
	.string "{JPN}げんきで いいことじゃ\n"
	.string "{JPN}では またのう$"

MatchCall_BattleFrontierStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}きいたわよ!\n"
	.string "{JPN}{STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいわねえ かんしん しちゃうわ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "{JPN}こんにちは {STR_VAR_1} です!\n"
	.string "{JPN}きいたよ!\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}すごい かつやく したんだって?\p"
	.string "{JPN}{STR_VAR_3}れんしょう って すごいなあ\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす\n"
	.string "{JPN}{STR_VAR_2} で\l"
	.string "{JPN}{STR_VAR_3}れんしょう したって きいたわよ!\p"
	.string "{JPN}すっごーい! わたしも がんばろうっと!\n"
	.string "{JPN}じゃあ またね!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "{JPN}おう! {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1}だぞ!\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}おおあばれ したらしいな!\p"
	.string "{JPN}{STR_VAR_3}れんしょう って\n"
	.string "{JPN}すごい きろく なんだろ?\p"
	.string "{JPN}おれも まけられねーな!\n"
	.string "{JPN}じゃ またな!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だけど げんき かい?\p"
	.string "{JPN}うわさで きいたんだけど\n"
	.string "{JPN}きみ {STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんだって?\p"
	.string "{JPN}ぼくも がんばらなきゃな\n"
	.string "{JPN}じゃあ また$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したんだってね!\l"
	.string "{JPN}すごいなあ\p"
	.string "{JPN}おれ? おれは まあ ぼちぼちかなー\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}こんにちは {STR_VAR_1} だ\p"
	.string "{JPN}そういえば きみ\n"
	.string "{JPN}{STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんだってね\p"
	.string "{JPN}おれも がんばらなきゃ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "{JPN}えーと あ {PLAYER}{KUN}?\n"
	.string "{JPN}{STR_VAR_1} だ...\p"
	.string "{JPN}そういえば {STR_VAR_2} で\n"
	.string "{JPN}{STR_VAR_3}れんしょう したんだってね\p"
	.string "{JPN}あ! いま めずらしい ポケモンを\n"
	.string "{JPN}みつけたから じゃあ また!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}ちょうしは どうですか?\n"
	.string "{JPN}そういえば {STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいですね! わたしも がんばって\n"
	.string "{JPN}ポケモンを そだてなきゃ$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "{JPN}あら {PLAYER}{KUN}!\n"
	.string "{JPN}こんにちは {STR_VAR_1}です!\p"
	.string "{JPN}きいたわよ! {STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したって!\p"
	.string "{JPN}すっごいねー\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいわねえ\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だ\p"
	.string "{JPN}{STR_VAR_2}で だいかつやく らしいなあ\n"
	.string "{JPN}{STR_VAR_3}れんしょう したんだって?\p"
	.string "{JPN}すげえなあ おれだったら\n"
	.string "{JPN}なんれんしょう できるのかな$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}ひとづてに きいたのじゃが\n"
	.string "{JPN}{STR_VAR_2} とかいう ところで\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したらしいのう?\p"
	.string "{JPN}すごい はなし だのう\n"
	.string "{JPN}では またの$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したそうじゃのう\p"
	.string "{JPN}げんきで いいことじゃ\n"
	.string "{JPN}では またのう$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}きいたわよ!\n"
	.string "{JPN}{STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいわねえ かんしん しちゃうわ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleDomeText1::
	.string "{JPN}あ! {PLAYER}?\n"
	.string "{JPN}こんにちは {STR_VAR_1} です!\p"
	.string "{JPN}きいたよ!\n"
	.string "{JPN}{STR_VAR_2} で\p"
	.string "{JPN}{STR_VAR_3}かい も\n"
	.string "{JPN}ゆうしょう したんだって?\p"
	.string "{JPN}すごいね! ぼくも がんばらなきゃ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleDomeText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす!\n"
	.string "{JPN}きいたわよ!\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}{STR_VAR_3}かい も\l"
	.string "{JPN}ゆうしょう したんですって?\p"
	.string "{JPN}すごいわねー\n"
	.string "{JPN}わたしも ゆうしょう できるのかな?$"

MatchCall_BattleDomeText3::
	.string "{JPN}よう {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1}だぞ げんきかー?\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}かいも\n"
	.string "{JPN}ゆうしょう したって きいたぞ\p"
	.string "{JPN}つぎも がんばれよなー\n"
	.string "{JPN}じゃあ またな$"

MatchCall_BattleDomeText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}かいも\n"
	.string "{JPN}ゆうしょう した らしいね\p"
	.string "{JPN}がんばってる みたいだね\n"
	.string "{JPN}ぼくも まけないように しなきゃ$"

MatchCall_BattleDomeText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}きいたよ {STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}かいも ゆうしょう したんだって?\p"
	.string "{JPN}ぼくも がんばらなきゃ\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleDomeText6::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}こんにちは {STR_VAR_1} だ\p"
	.string "{JPN}そういえば きみ\n"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}かいも\l"
	.string "{JPN}ゆうしょう したんだってね\p"
	.string "{JPN}おれも まけないように\n"
	.string "{JPN}ポケモンを そだてなきゃな$"

MatchCall_BattleDomeText7::
	.string "{JPN}{PLAYER}{KUN}?\n"
	.string "{JPN}ああ {STR_VAR_1} だけど\p"
	.string "{JPN}{STR_VAR_2}で ゆうしょうを\n"
	.string "{JPN}{STR_VAR_3}かいも したんだって?\p"
	.string "{JPN}へー ところで さいきん\n"
	.string "{JPN}めずらしい ポケモン つかまえた?\p"
	.string "{JPN}あ そう\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleDomeText8::
	.string "{JPN}こんにちは {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}げんき ですか?\n"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}かいも\l"
	.string "{JPN}ゆうしょう したんですって?\p"
	.string "{JPN}すごいですね!\n"
	.string "{JPN}わたしも がんばって\p"
	.string "{JPN}ポケモン そだてないと!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattleDomeText9::
	.string "{JPN}あら {PLAYER}{KUN}!\n"
	.string "{JPN}こんにちは {STR_VAR_1}です!\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}かいも ゆうしょう したんだって?\p"
	.string "{JPN}すっごいねー\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattleDomeText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}れんしょうも したんですって?\p"
	.string "{JPN}すごいわねえ\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattleDomeText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だ\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}だいかつやく らしいなあ\l"
	.string "{JPN}{STR_VAR_3}れんしょう したんだって?\p"
	.string "{JPN}すげえなあ おれでも\n"
	.string "{JPN}ゆうしょう できるのかな\p"
	.string "{JPN}... むりかな?\n"
	.string "{JPN}じゃあ またな$"

MatchCall_BattleDomeText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2} とかいう ところで\n"
	.string "{JPN}{STR_VAR_3}かい ゆうしょう したとな?\p"
	.string "{JPN}すごい はなし だのう\n"
	.string "{JPN}では またの$"

MatchCall_BattleDomeText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}{STR_VAR_3}かいも ゆうしょう とな?\p"
	.string "{JPN}げんきで いいことじゃ\n"
	.string "{JPN}では またのう$"

MatchCall_BattleDomeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}きいたわよ!\n"
	.string "{JPN}{STR_VAR_2} で\p"
	.string "{JPN}{STR_VAR_3}かいも\n"
	.string "{JPN}ゆうしょう したんですって?\p"
	.string "{JPN}すごいわねえ かんしん しちゃうわ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePikeText1::
	.string "{JPN}あ! {PLAYER}?\n"
	.string "{JPN}こんにちは {STR_VAR_1} です!\p"
	.string "{JPN}きいたよ!\n"
	.string "{JPN}{STR_VAR_2} で\p"
	.string "{JPN}{STR_VAR_3}も へやを\n"
	.string "{JPN}とっぱ したんだって?\p"
	.string "{JPN}すごいなあ\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePikeText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす!\n"
	.string "{JPN}きいたわよ!\p"
	.string "{JPN}{STR_VAR_2} で{STR_VAR_3}へやも\n"
	.string "{JPN}かちぬいたんですって?\p"
	.string "{JPN}わたしも がんばらなきゃ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePikeText3::
	.string "{JPN}よう {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1}だぞ げんきかー?\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}へやも\n"
	.string "{JPN}とっぱ したって きいたぞ\p"
	.string "{JPN}つぎも がんばれよなー\n"
	.string "{JPN}じゃあ またな$"

MatchCall_BattlePikeText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}へやも\n"
	.string "{JPN}とっぱ した らしいね\p"
	.string "{JPN}おれも まけないように\n"
	.string "{JPN}ポケモン そだてなきゃな$"

MatchCall_BattlePikeText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}きいたよ {STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}へやも とっぱ したんだって?\p"
	.string "{JPN}ぼくも がんばらなきゃ\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePikeText6::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}こんにちは {STR_VAR_1} だ\p"
	.string "{JPN}そういえば きみ\n"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}へやも\l"
	.string "{JPN}とっぱ したんだってね\p"
	.string "{JPN}おれも まけないように\n"
	.string "{JPN}ポケモンを そだてなきゃな$"

MatchCall_BattlePikeText7::
	.string "{JPN}{PLAYER}{KUN}?\n"
	.string "{JPN}ああ {STR_VAR_1} だけど\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}へやも\n"
	.string "{JPN}とっぱ したんだって?\p"
	.string "{JPN}すごいねえ\n"
	.string "{JPN}あ めずらしいポケモンを みつけたから\p"
	.string "{JPN}じゃあ また$"

MatchCall_BattlePikeText8::
	.string "{JPN}こんにちは {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}げんき ですか?\n"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}へやも\l"
	.string "{JPN}とっぱ したんですって?\p"
	.string "{JPN}すごいですね!\n"
	.string "{JPN}わたしも がんばって\p"
	.string "{JPN}ポケモン そだてないと!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePikeText9::
	.string "{JPN}あら {PLAYER}{KUN}!\n"
	.string "{JPN}こんにちは {STR_VAR_1}です!\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}へやも\n"
	.string "{JPN}とっぱ したんだって?\p"
	.string "{JPN}すっごいねー\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattlePikeText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}へやも とっぱ したんですって?\p"
	.string "{JPN}すごいわねえ\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattlePikeText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だ\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}だいかつやく らしいなあ\l"
	.string "{JPN}{STR_VAR_3}へやも とっぱ したんだって?\p"
	.string "{JPN}すげえなあ おれでも\n"
	.string "{JPN}ゆうしょう できるのかな\p"
	.string "{JPN}... むりかなあ?\n"
	.string "{JPN}じゃあ またな$"

MatchCall_BattlePikeText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2} とかいう ところで\n"
	.string "{JPN}{STR_VAR_3}へや とっぱ したとな?\p"
	.string "{JPN}すごい はなし だのう\n"
	.string "{JPN}では またの$"

MatchCall_BattlePikeText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}へやも とっぱした とな?\p"
	.string "{JPN}げんきで いいことじゃ\n"
	.string "{JPN}では またのう$"

MatchCall_BattlePikeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}きいたわよ!\n"
	.string "{JPN}{STR_VAR_2}で\p"
	.string "{JPN}{STR_VAR_3}へやも\n"
	.string "{JPN}とっぱ したんですって?\p"
	.string "{JPN}すごいわねえ かんしん しちゃうわ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePyramidText1::
	.string "{JPN}あ! {PLAYER}?\n"
	.string "{JPN}こんにちは {STR_VAR_1} です!\p"
	.string "{JPN}きいたよ!\n"
	.string "{JPN}{STR_VAR_2} で\p"
	.string "{JPN}{STR_VAR_3}だん も\n"
	.string "{JPN}のぼったんだって?\p"
	.string "{JPN}すごいねー ぼくも こんど\n"
	.string "{JPN}ちょうせん してみようかなー$"

MatchCall_BattlePyramidText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす!\n"
	.string "{JPN}きいたわよ!\p"
	.string "{JPN}{STR_VAR_2} で\n"
	.string "{JPN}{STR_VAR_3}だん も\l"
	.string "{JPN}かちぬいたんですって?\p"
	.string "{JPN}すごーい! わたしの ポケモンも\n"
	.string "{JPN}がんばって そだてなくちゃ$"

MatchCall_BattlePyramidText3::
	.string "{JPN}よう {PLAYER}!\n"
	.string "{JPN}{STR_VAR_1}だぞ げんきかー?\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}だんも\n"
	.string "{JPN}のぼったって きいたぞ\p"
	.string "{JPN}つぎも がんばれよなー\n"
	.string "{JPN}じゃあ またな$"

MatchCall_BattlePyramidText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} だ\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}だんも\n"
	.string "{JPN}のぼった らしいね\p"
	.string "{JPN}ぼくも きみに まけないように\n"
	.string "{JPN}がんばらなきゃな$"

MatchCall_BattlePyramidText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} だよ\p"
	.string "{JPN}きいたよ {STR_VAR_2} で\n"
	.string "{JPN}{STR_VAR_3}だんも のぼったんだって?\p"
	.string "{JPN}ぼくも がんばらなきゃ\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePyramidText6::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}こんにちは {STR_VAR_1} だ\p"
	.string "{JPN}そういえば きみ\n"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}だんも\l"
	.string "{JPN}かちぬいたんだってね\p"
	.string "{JPN}おれも まけないように\n"
	.string "{JPN}ポケモンを そだてなきゃな$"

MatchCall_BattlePyramidText7::
	.string "{JPN}{PLAYER}{KUN}?\n"
	.string "{JPN}ああ {STR_VAR_1} だけど\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}だんも\n"
	.string "{JPN}のぼったんだって?\p"
	.string "{JPN}へー... そこに\n"
	.string "{JPN}めずらしい ポケモン いなかった?\p"
	.string "{JPN}そうかー いないかー\n"
	.string "{JPN}じゃあ また$"

MatchCall_BattlePyramidText8::
	.string "{JPN}こんにちは {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}げんき ですか?\n"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}だんも\l"
	.string "{JPN}かちぬいたんですって?\p"
	.string "{JPN}すごいですね!\n"
	.string "{JPN}わたしも がんばって\p"
	.string "{JPN}ポケモン そだてないと!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_BattlePyramidText9::
	.string "{JPN}あら {PLAYER}{KUN}!\n"
	.string "{JPN}こんにちは {STR_VAR_1}です!\p"
	.string "{JPN}{STR_VAR_2}で {STR_VAR_3}だんも\n"
	.string "{JPN}かちぬいたんだって?\p"
	.string "{JPN}すっごいねー\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattlePyramidText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} です\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}だんも のぼったんですって?\p"
	.string "{JPN}すごいわねえ\n"
	.string "{JPN}わたしも がんばらなくちゃ$"

MatchCall_BattlePyramidText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1}だ\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}だいかつやく らしいなあ\l"
	.string "{JPN}{STR_VAR_3}だんも のぼったんだって?\p"
	.string "{JPN}すげえなあ おれでも\n"
	.string "{JPN}ゆうしょう できるのかな\p"
	.string "{JPN}... できない?\n"
	.string "{JPN}じゃあ またな$"

MatchCall_BattlePyramidText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2} とかいう ところで\n"
	.string "{JPN}{STR_VAR_3}だんも かちぬいたとな?\p"
	.string "{JPN}すごい はなし だのう\n"
	.string "{JPN}では またの$"

MatchCall_BattlePyramidText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n"
	.string "{JPN}{STR_VAR_1} じゃが げんきかの?\p"
	.string "{JPN}{STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}だんも のぼったとな?\p"
	.string "{JPN}げんきで いいことじゃ\n"
	.string "{JPN}では またのう$"

MatchCall_BattlePyramidText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n"
	.string "{JPN}{STR_VAR_1} よ\p"
	.string "{JPN}きいたわよ!\n"
	.string "{JPN}{STR_VAR_2}で\p"
	.string "{JPN}{STR_VAR_3}だんも\n"
	.string "{JPN}かちぬいたんですって?\p"
	.string "{JPN}すごいわねえ かんしん しちゃうわ!\n"
	.string "{JPN}じゃあ またね$"

MatchCall_Text_Mom1::
	.string "{JPN}ママ“パパも あなたも\n"
	.string "{JPN}みんな ポケモンに むちゅう なのね\p"
	.string "{JPN}ポケモンの みりょく って\n"
	.string "{JPN}なんなの かしら...\p"
	.string "{JPN}わたし?\n"
	.string "{JPN}わたしは いえの ようじを おてつだい\l"
	.string "{JPN}してくれる ポケモンが すきだわ$"

MatchCall_Text_Mom2::
	.string "{JPN}ママ“あら {PLAYER}\n"
	.string "{JPN}パパなら まいにち トウカシティの\l"
	.string "{JPN}ジムに こもってるわよ!\p"
	.string "{JPN}ときどき うちに かえってきては\n"
	.string "{JPN}たくさん ごはんを たべて\l"
	.string "{JPN}また でかけて いくの!\p"
	.string "{JPN}あなたに まけたのが\n"
	.string "{JPN}よっぽど くやしかった みたいね!$"

MatchCall_Text_Mom3::
	.string "{JPN}ママ“{PLAYER}...\p"
	.string "{JPN}おうちの ことなら きにしなくて いいから\n"
	.string "{JPN}ママが あげた ランニングシューズ\l"
	.string "{JPN}ボロボロに なるまで はいてちょうだいね!$"

MatchCall_Text_Baoba1::
	.string "{JPN}バオバ”{PLAYER}!\n"
	.string "{JPN}サファリゾーンが もうすぐ\n"
	.string "{JPN}かんせい するぞ!\p"
	.string "{JPN}できたら まっさきに\n"
	.string "{JPN}れんらく するからな!$"

MatchCall_Text_Baoba2::
	.string "{JPN}バオバ”{PLAYER}!\n"
	.string "{JPN}サファリゾーンが オープンしたぞ!\p"
	.string "{JPN}いつでも あそびに こい!$"

MatchCall_Text_Roxanne1::
	.string "{JPN}ツツジ“あら {PLAYER}さん!\p"
	.string "{JPN}あれから また トレーニングを\n"
	.string "{JPN}やりなおして いるところ なんですよ!\p"
	.string "{JPN}また ジムを さいかい するためには\n"
	.string "{JPN}もうすこし じかんが かかりますが\p"
	.string "{JPN}もし ジムを さいかい できたら\n"
	.string "{JPN}ぜひまた ちょうせん してくださいね...$"

MatchCall_Text_Roxanne2::
	.string "{JPN}ツツジ“{PLAYER}さん おめでとう!\n"
	.string "{JPN}うわさは ききましたよ!\p"
	.string "{JPN}こちらは ジムを さいかい するためには\n"
	.string "{JPN}もうすこし じかんが かかりますが\p"
	.string "{JPN}もし ジムを さいかい できたら\n"
	.string "{JPN}ぜひまた ちょうせん してくださいね...$"

MatchCall_Text_Roxanne3::
	.string "{JPN}ツツジ“{PLAYER}さん!\n"
	.string "{JPN}ジムの じゅんびが できました!\p"
	.string "{JPN}いつでも カナズミ シティまで\n"
	.string "{JPN}きてくださいな!$"

MatchCall_Text_Roxanne4::
	.string "{JPN}ツツジ“{PLAYER}さんと\n"
	.string "{JPN}しょうぶ できたことは\l"
	.string "{JPN}カナズミ ジムの ほこりですよ!$"

MatchCall_Text_Brawly1::
	.string "{JPN}トウキ“やあ {PLAYER}{KUN}!\p"
	.string "{JPN}キミとの しょうぶでは いろんなことを\n"
	.string "{JPN}まなばせて もらったよ!\p"
	.string "{JPN}また しゅぎょう しなおして\n"
	.string "{JPN}ジムを さいかいする つもりさ!\p"
	.string "{JPN}ジムの じゅんびが できるまでは\n"
	.string "{JPN}まだ じかんが かかりそう だけど\p"
	.string "{JPN}もし ジムを さいかい できたら\n"
	.string "{JPN}ぜひまた ちょうせん してくれよ...$"

MatchCall_Text_Brawly2::
	.string "{JPN}トウキ“{PLAYER}{KUN} おめでとう!\p"
	.string "{JPN}キミの うわさは しおかぜに のって\n"
	.string "{JPN}このまちにも とどいて いるよ!\p"
	.string "{JPN}ボクのほうは まだまだ しゅぎょうを\n"
	.string "{JPN}やりなおす ひつようが ありそうだ\p"
	.string "{JPN}ジムの じゅんびが できるまでは\n"
	.string "{JPN}まだ じかんが かかりそう だけど\p"
	.string "{JPN}もし ジムを さいかい できたら\n"
	.string "{JPN}ぜひまた ちょうせん してくれよ...$"

MatchCall_Text_Brawly3::
	.string "{JPN}トウキ“{PLAYER}{KUN}!\n"
	.string "{JPN}ジムの じゅんびが できたよ!\p"
	.string "{JPN}いつでも ムロ タウンまで\n"
	.string "{JPN}ちょうせんしに きてくれよな!$"

MatchCall_Text_Brawly4::
	.string "{JPN}トウキ“{PLAYER}{KUN} とは\n"
	.string "{JPN}なんど しょうぶ しても あきないよ!$"

MatchCall_Text_Wattson1::
	.string "{JPN}テッセン“おう おまえさんか!\p"
	.string "{JPN}わしは あれから また トレーニングを\n"
	.string "{JPN}やりなおして いるところ じゃよ!\p"
	.string "{JPN}わしの ジムを さいかいするには\n"
	.string "{JPN}まだ ちーと じかんが かかりそうじゃな!\p"
	.string "{JPN}それまで まっていて おくれ!\n"
	.string "{JPN}わっはははは!$"

MatchCall_Text_Wattson2::
	.string "{JPN}テッセン“わっははは!\p"
	.string "{JPN}おまえさん とうとう やったな!\n"
	.string "{JPN}うわさは わしの みみにも とどいとる!\p"
	.string "{JPN}こちらは まだまだ しゅぎょうを\n"
	.string "{JPN}やりなおす ひつようが ありそうじゃ\p"
	.string "{JPN}わしの ジムを さいかいするには\n"
	.string "{JPN}まだ ちーと じかんが かかりそうじゃな!\p"
	.string "{JPN}それまで まっていて おくれ!\n"
	.string "{JPN}わっはははは!$"

MatchCall_Text_Wattson3::
	.string "{JPN}テッセン“おう おまえさんか!\n"
	.string "{JPN}ジムの じゅんびが できたぞい!\p"
	.string "{JPN}いつでも キンセツ シティまで\n"
	.string "{JPN}くるがいいぞ! わっははは!$"

MatchCall_Text_Wattson4::
	.string "{JPN}テッセン“わっははは!\p"
	.string "{JPN}おまえさんとの ポケモン しょうぶは\n"
	.string "{JPN}ビリビリと しげきてきじゃな!$"

MatchCall_Text_Flannery1::
	.string "{JPN}アスナ“{PLAYER}さん...\p"
	.string "{JPN}あなたとの しょうぶで じぶんの\n"
	.string "{JPN}みじゅくさを おもいしらされた けど\l"
	.string "{JPN}わたしは これで おわったり しないよ!\p"
	.string "{JPN}もういちど しゅぎょうを しなおして\n"
	.string "{JPN}また ジムを さいかい するんだ!\p"
	.string "{JPN}そのときには {PLAYER}さん\n"
	.string "{JPN}ぜったい ちょうせんしに きてよね!$"

MatchCall_Text_Flannery2::
	.string "{JPN}アスナ“{PLAYER}さん おめでとう!\p"
	.string "{JPN}あなたの うわさは かざんの ねつのように\n"
	.string "{JPN}わたしにも つたわって きてるよ!\p"
	.string "{JPN}こちらも じゅんちょうに\n"
	.string "{JPN}トレーニングが すすんでるんだ!\p"
	.string "{JPN}ジムの じゅんびが できたら\n"
	.string "{JPN}エントリーコールの なまえの ところに\l"
	.string "{JPN}しるしが つくからね!$"

MatchCall_Text_Flannery3::
	.string "{JPN}アスナ“あっ {PLAYER}さん?\n"
	.string "{JPN}ジムの じゅんびは もうできてます!\p"
	.string "{JPN}おんせんに はいる ついでに\n"
	.string "{JPN}フエン タウンまで きてくださいね!$"

MatchCall_Text_Flannery4::
	.string "{JPN}アスナ“{PLAYER}さん...\n"
	.string "{JPN}ポケモンの あつかいかたが\l"
	.string "{JPN}どんどん うまくなってる きがするよ!$"

MatchCall_Text_Winona1::
	.string "{JPN}ナギ“こんにちは {PLAYER}さん!\p"
	.string "{JPN}あなたと しょうぶを したおかげで\n"
	.string "{JPN}じぶんの じゃくてんが よくわかったわ!\p"
	.string "{JPN}いつか また ジムを さいかい できたら\n"
	.string "{JPN}そのときは もう まけませんよ!$"

MatchCall_Text_Winona2::
	.string "{JPN}ナギ“やりましたね {PLAYER}さん!\p"
	.string "{JPN}しんチャンピオン たんじょうの うわさは\n"
	.string "{JPN}ヒワマキにも とどいて いますよ!\p"
	.string "{JPN}でも... つぎに しょうぶ するときは\n"
	.string "{JPN}このまえの ようには いきませんからね!$"

MatchCall_Text_Winona3::
	.string "{JPN}ナギ“ええと {PLAYER}さん?\n"
	.string "{JPN}ジムの じゅんびが できましたよ!\p"
	.string "{JPN}ヒワマキ タウンで まってます!$"

MatchCall_Text_Winona4::
	.string "{JPN}ナギ“{PLAYER}さん...\n"
	.string "{JPN}しょうぶに まけても わたしの つばさは\l"
	.string "{JPN}けっして おれることは ないのです!\p"
	.string "{JPN}そう {PLAYER}さんが\n"
	.string "{JPN}ゆめを あきらめなかった ように!$"

MatchCall_Text_TateLiza1::
	.string "{JPN}フウ“あっ あなたは\n"
	.string "{JPN}ラン“{PLAYER}さん ですね!\p"
	.string "{JPN}フウ“ぼくたち ジムを さいかい するため\n"
	.string "{JPN}ラン“しゅぎょう しなおして いるんです!\p"
	.string "{JPN}フウ“ジムの じゅんびが できたら\n"
	.string "{JPN}ラン“ジムの じゅんびが できたら\p"
	.string "{JPN}フウ“エントリーコールの なまえに\n"
	.string "{JPN}ラン“しるしが つくので わかるんです!$"

MatchCall_Text_TateLiza2::
	.string "{JPN}フウ“{PLAYER}さん おめでとう!\n"
	.string "{JPN}ラン“{PLAYER}さん おめでとう!\p"
	.string "{JPN}フウ“ぼくたち ふたりは\n"
	.string "{JPN}ラン“まだ しゅぎょうちゅう!\p"
	.string "{JPN}フウ“もうすこし じかんが かかるけど\n"
	.string "{JPN}ラン“もし ジムを さいかい できたら\p"
	.string "{JPN}フウ“エントリーコールの なまえに\n"
	.string "{JPN}ラン“しるしが つくから わかりますよ!$"

MatchCall_Text_TateLiza3::
	.string "{JPN}フウ“{PLAYER}さん!\n"
	.string "{JPN}ラン“{PLAYER}さん!\p"
	.string "{JPN}フウ“ジムの じゅんびが できました!\n"
	.string "{JPN}ラン“ジムの じゅんびが できました!\p"
	.string "{JPN}フウ“いつでも トクサネ シティまで\n"
	.string "{JPN}ラン“きてくださいね!$"

MatchCall_Text_TateLiza4::
	.string "{JPN}フウ“{PLAYER}さんとの しょうぶは\n"
	.string "{JPN}ラン“わたしたちの だいじな けいけん\p"
	.string "{JPN}フウ“いつか また 3にんで\n"
	.string "{JPN}ラン“しょうぶが できると いいですね$"

MatchCall_Text_Juan1::
	.string "{JPN}アダン“ほ...\n"
	.string "{JPN}{PLAYER}{KUN}... でしたね\p"
	.string "{JPN}ユーとの たたかいは\n"
	.string "{JPN}はじめて ミクリと であったときを\l"
	.string "{JPN}おもいださせて くれましたよ\p"
	.string "{JPN}もしかすると ユーは\n"
	.string "{JPN}ミクリを こえるほどの ジーニアス!\l"
	.string "{JPN}すなわち てんさい かもしれません$"

MatchCall_Text_Juan2::
	.string "{JPN}アダン“ふ... {PLAYER}{KUN}\n"
	.string "{JPN}ついに やりとげた ようですね\p"
	.string "{JPN}やはり わたくしの ひとを みるめは\n"
	.string "{JPN}まちがって いなかった...\p"
	.string "{JPN}つよさを きわめた ユーとは\n"
	.string "{JPN}ぜひ また しょうぶ したい ものです$"

MatchCall_Text_Juan3::
	.string "{JPN}アダン“ほっほ... {PLAYER}{KUN}\p"
	.string "{JPN}わが ルネシティ ジムが\n"
	.string "{JPN}ふたたび オープン したのですよ\p"
	.string "{JPN}わたくしの すがたを みたくなったら\n"
	.string "{JPN}まあ いつでも おいでなさい$"

MatchCall_Text_Juan4::
	.string "{JPN}アダン“{PLAYER}{KUN}...\p"
	.string "{JPN}ユーと かなでる ポケモン しょうぶは\n"
	.string "{JPN}せんれんされた おんがくにも にて\l"
	.string "{JPN}ハートに ふかく ひびいて きます...\p"
	.string "{JPN}めを とじれば メロディーに あわせて\n"
	.string "{JPN}ゆうがに まう ユーの すがたが...$"

MatchCall_Text_Sidney::
	.string "{JPN}カゲツ“よお {PLAYER}!\p"
	.string "{JPN}おれと ポケモン しょうぶ したけりゃ\n"
	.string "{JPN}いつでも ポケモン リーグに おいで!\p"
	.string "{JPN}おれは いつでも ここに いるからな\n"
	.string "{JPN}じゃあ まってるぜ!$"

MatchCall_Text_Phoebe::
	.string "{JPN}フヨウ“ハーイ {PLAYER}!\p"
	.string "{JPN}あなたと ポケモンの きずなが\n"
	.string "{JPN}どれぐらい ふかく なったか\l"
	.string "{JPN}たまには ここまで みせに きてよね!$"

MatchCall_Text_Glacia::
	.string "{JPN}プリム“こんにちは {PLAYER}\p"
	.string "{JPN}あなたは その つよさに\n"
	.string "{JPN}おぼれたり していない でしょうね\p"
	.string "{JPN}あつい きもちを すこしだけ\n"
	.string "{JPN}ひやしたいと おもったら\l"
	.string "{JPN}ポケモン リーグに いらっしゃい...$"

MatchCall_Text_Drake::
	.string "{JPN}ゲンジ“そのこえは {PLAYER}か\n"
	.string "{JPN}げんきそう だな...\p"
	.string "{JPN}さいきん ポケモン リーグとは べつに\n"
	.string "{JPN}トレーナーの うでを きそわせる\l"
	.string "{JPN}バトル フロンティア とかいう しせつが\l"
	.string "{JPN}あるらしいが...\p"
	.string "{JPN}ほんとうの しょうぶを したいのなら\n"
	.string "{JPN}やはり ポケモン リーグだ!\p"
	.string "{JPN}なあ {PLAYER}も そうおもう だろう?$"

MatchCall_Text_Wallace::
	.string "{JPN}ミクリ“やあ {PLAYER}{KUN}\n"
	.string "{JPN}きみは ダイゴには あったかな?\p"
	.string "{JPN}かれって...\n"
	.string "{JPN}ほんとうは ものすごく つよいのに\p"
	.string "{JPN}あまり ポケモン しょうぶを しないで\n"
	.string "{JPN}めずらしい いしを さがして ばかりいる\l"
	.string "{JPN}かわりもの なんだよ\p"
	.string "{JPN}どこかの どうくつか いわやまに\n"
	.string "{JPN}もぐってるんじゃ ないかな\p"
	.string "{JPN}めずらしい いし なんて\n"
	.string "{JPN}わたしには いんせき ぐらいしか\l"
	.string "{JPN}おもい うかばないんだけど...$"

MatchCall_Text_MayRayquazaCall:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ... ピッ!\p"
	.string "{JPN}ハルカ“あっ {PLAYER}{KUN}!?\p"
	.string "{JPN}あたしね さっきまで キナギ タウンに\n"
	.string "{JPN}いってたんだけど\l"
	.string "{JPN}おおきな みどりいろの ポケモンが\l"
	.string "{JPN}そらを とんで いくのを みたの!\p"
	.string "{JPN}あたし...\n"
	.string "{JPN}あんな ポケモン みたこと ない!\p"
	.string "{JPN}なんだろう もしかしたら これって\n"
	.string "{JPN}だいはっけん!?\p"
	.string "... ... ...\n"
	.string "{JPN}... ... ... ツー$"

MatchCall_Text_BrendanRayquazaCall:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ... ピッ!\p"
	.string "{JPN}ユウキ“おっ {PLAYER}!?\p"
	.string "{JPN}オレ さっきまで キナギ タウンに\n"
	.string "{JPN}いってたんだけどさ\l"
	.string "{JPN}でっかい みどりいろの ポケモンが\l"
	.string "{JPN}そらを とんで いくのを みたんだ!\p"
	.string "{JPN}あんな すごいの みたこと ないよ\n"
	.string "{JPN}{PLAYER}にも みせたかったなあ!\p"
	.string "... ... ...\n"
	.string "{JPN}... ... ... ツー$"

MatchCall_Text_May1::
	.string "{JPN}ハルカ“あっ {PLAYER}{KUN}!\p"
	.string "{JPN}ハギろうじんは\n"
	.string "{JPN}ふなのりを いんたい したけど\p"
	.string "{JPN}ときどき ピーコちゃんと いっしょに\n"
	.string "{JPN}うみに でてるのを みかけるよ\p"
	.string "{JPN}きっと いまも うみが すきなんだね!$"

MatchCall_Text_May2::
	.string "{JPN}ハルカ“ねえねえ {PLAYER}{KUN}!\p"
	.string "{JPN}トウカや ムロみたいな\n"
	.string "{JPN}ちいさい まちに ジムが あるのに\p"
	.string "{JPN}おおきな みなとまちの カイナには\n"
	.string "{JPN}なぜか ジムが ないのよね\p"
	.string "{JPN}いつか ジムが できたら あたし\n"
	.string "{JPN}ジムリーダーに りっこうほ しよっかなー$"

MatchCall_Text_May3::
	.string "{JPN}ハルカ“あっ {PLAYER}{KUN}!\p"
	.string "{JPN}そういえば カナズミシティに\n"
	.string "{JPN}いあいぎりオヤジ っていう ひとの\l"
	.string "{JPN}いえが あったでしょ?\p"
	.string "{JPN}キンセツシティには\n"
	.string "{JPN}その おとうとが すんでるんだって!\p"
	.string "{JPN}どんな なまえだと おもう?\p"
	.string "... ... ...\n"
	.string "... ... ...\p"
	.string "{JPN}いわくだきオヤジ っていうの!$"

MatchCall_Text_May4::
	.string "{JPN}ハルカ“{PLAYER}{KUN}?\p"
	.string "{JPN}カナシダトンネル って\n"
	.string "{JPN}カナズミと シダケを むすぶから\l"
	.string "{JPN}カナシダトンネル って いうのよね!$"

MatchCall_Text_May5::
	.string "{JPN}ハルカ“{PLAYER}{KUN} げんきー?\p"
	.string "{JPN}あたしは いま\n"
	.string "{JPN}111ばんどうろに きているの!\p"
	.string "{JPN}さばくの うえのほうに すんでる\n"
	.string "{JPN}おばあさんの ところで\l"
	.string "{JPN}ひとやすみ していく つもりよ!$"

MatchCall_Text_May6::
	.string "{JPN}ハルカ“あっ {PLAYER}{KUN}!\p"
	.string "{JPN}さばくに げんえいのとう っていうのが\n"
	.string "{JPN}たってるの しってる?\p"
	.string "{JPN}しんきろう みたいに\n"
	.string "{JPN}みえたり みえなかったり するんだって!\p"
	.string "{JPN}あたしも みてみたいなー$"

MatchCall_Text_May7::
	.string "{JPN}ハルカ“{PLAYER}{KUN} やっほー!\p"
	.string "{JPN}あたしは いま\n"
	.string "{JPN}119ばんどうろに きているの!\p"
	.string "{JPN}このあたりは おおきな かわが あるし\n"
	.string "{JPN}あめも しょっちゅう ふってるから\l"
	.string "{JPN}ずぶぬれに なっちゃったよ!$"

MatchCall_Text_May8::
	.string "{JPN}ハルカ“{PLAYER}{KUN}!\p"
	.string "{JPN}おくりびやまには じゅみょうを おえた\n"
	.string "{JPN}ポケモンが まつられてるの!\p"
	.string "{JPN}そのせいか しゅつげんする ポケモンも\n"
	.string "{JPN}ゴーストタイプが おおいのよ!$"

MatchCall_Text_May9::
	.string "{JPN}ハルカ“ねえねえ {PLAYER}{KUN}!\p"
	.string "{JPN}あたし また フエンタウンの\n"
	.string "{JPN}おんせんに いこうと おもったんだけど\p"
	.string "{JPN}デコボコさんどうに\n"
	.string "{JPN}にんそうの わるいのが うろついていて\l"
	.string "{JPN}なんか いやーな かんじ だったわ!$"

MatchCall_Text_May10::
	.string "{JPN}ハルカ“あっ {PLAYER}{KUN}!\p"
	.string "{JPN}クスノキかんちょうが せんすいていで\n"
	.string "{JPN}かいていどうくつを はっけんした って\l"
	.string "{JPN}ニュースで やってたけど みた?$"

MatchCall_Text_May11::
	.string "{JPN}ハルカ“ねえねえ {PLAYER}{KUN}!\p"
	.string "{JPN}ふねが なくても ポケモンの わざで\n"
	.string "{JPN}うみのうえを わたって いけるって\l"
	.string "{JPN}すごいよね!\p"
	.string "{JPN}でも それだけじゃなくて\n"
	.string "{JPN}ポケモンと いっしょに うみのそこに\l"
	.string "{JPN}もぐれちゃう わざも あるんだって!$"

MatchCall_Text_May12::
	.string "{JPN}ハルカ“{PLAYER}{KUN} おつかれ!\p"
	.string "{JPN}うみのうえで みえてるのに むこうがわへ\n"
	.string "{JPN}いけない ところ なんかは\p"
	.string "{JPN}どこかから いったん もぐって\n"
	.string "{JPN}かいていの みちを とおりぬけて\l"
	.string "{JPN}むこうの すいめんに でれば いいの!$"

MatchCall_Text_May13::
	.string "{JPN}ハルカ“はーい {PLAYER}{KUN}\p"
	.string "{JPN}どう? ずかんは じゅんちょうに\n"
	.string "{JPN}うまっていってる?\p"
	.string "{JPN}あのね うわさで きいたんだけど\n"
	.string "{JPN}どこかに ちょうこだいポケモン というのが\l"
	.string "{JPN}3しゅるいも いるらしいの!\p"
	.string "{JPN}うーん 1しゅるい だけでも いいから\n"
	.string "{JPN}みてみたいなあ...$"

MatchCall_Text_May14::
	.string "{JPN}ハルカ“{PLAYER}{KUN}!\n"
	.string "{JPN}うわさは きいたよ!\p"
	.string "{JPN}ルネの ジムリーダーにも かったって?\n"
	.string "{JPN}ということは もうひといき だね!$"

MatchCall_Text_May15::
	.string "{JPN}ハルカ“もう ホウエンちほうで\n"
	.string "{JPN}{PLAYER}{KUN}を しらない\l"
	.string "{JPN}トレーナー なんて いないんだよ!\p"
	.string "{JPN}あたしが {PLAYER}{KUN}と\n"
	.string "{JPN}ともだちだ っていうと\l"
	.string "{JPN}みんな ビックリ するんだから!$"

MatchCall_Text_Brendan1::
	.string "{JPN}ユウキ“おっ {PLAYER}!\p"
	.string "{JPN}ハギろうじんは\n"
	.string "{JPN}ふなのりを いんたい したけど\p"
	.string "{JPN}ときどき ピーコちゃんと いっしょに\n"
	.string "{JPN}うみに でてるのを みかけるんだ\p"
	.string "{JPN}きっと いまも うみが すきなんだろうな!$"

MatchCall_Text_Brendan2::
	.string "{JPN}ユウキ“やあ {PLAYER}!\p"
	.string "{JPN}トウカや ムロみたいな\n"
	.string "{JPN}ちいさい まちに ジムが あるのに\p"
	.string "{JPN}おおきな みなとまちの カイナには\n"
	.string "{JPN}なぜか ジムが ないんだよな\p"
	.string "{JPN}いつか ジムが できたら オレ\n"
	.string "{JPN}ジムリーダーに りっこうほ しようかな$"

MatchCall_Text_Brendan3::
	.string "{JPN}ユウキ“おっ {PLAYER}!\p"
	.string "{JPN}そういえば カナズミシティに\n"
	.string "{JPN}いあいぎりオヤジ っていう ひとの\l"
	.string "{JPN}いえが あっただろう?\p"
	.string "{JPN}キンセツシティには\n"
	.string "{JPN}その おとうとが すんでるんだって!\p"
	.string "{JPN}どんな なまえだと おもう?\p"
	.string "... ... ...\n"
	.string "... ... ...\p"
	.string "{JPN}いわくだきオヤジ だってさ!$"

MatchCall_Text_Brendan4::
	.string "{JPN}ユウキ“そのこえは {PLAYER}?\p"
	.string "{JPN}カナシダトンネル って\n"
	.string "{JPN}カナズミと シダケを むすぶから\l"
	.string "{JPN}カナシダトンネル なんだよ\p"
	.string "{JPN}おまえ... しってたか?$"

MatchCall_Text_Brendan5::
	.string "{JPN}ユウキ“{PLAYER} げんきか?\p"
	.string "{JPN}オレは いま\n"
	.string "{JPN}111ばんどうろに きてるんだ!\p"
	.string "{JPN}さばくの うえのほうに すんでる\n"
	.string "{JPN}ばあさんの ところで\l"
	.string "{JPN}ひとやすみ していく つもりさ!\p"
	.string "{JPN}ちかくまで きたら\n"
	.string "{JPN}おまえも よっていくと いいよ!$"

MatchCall_Text_Brendan6::
	.string "{JPN}ユウキ“あっ {PLAYER}!\p"
	.string "{JPN}さばくに げんえいのとう っていうのが\n"
	.string "{JPN}たってるの しってるか?\p"
	.string "{JPN}しんきろう みたいに\n"
	.string "{JPN}みえたり みえなかったり するんだよ!\p"
	.string "{JPN}オレも みてみたいなー$"

MatchCall_Text_Brendan7::
	.string "{JPN}ユウキ“だれ? {PLAYER}か?\p"
	.string "{JPN}オレは いま\n"
	.string "{JPN}119ばんどうろに きてるんだ!\p"
	.string "{JPN}このへんは でっかい かわが あるし\n"
	.string "{JPN}いっつも あめが ふってるから\l"
	.string "{JPN}ずぶぬれに なっちまったよ!$"

MatchCall_Text_Brendan8::
	.string "{JPN}ユウキ“{PLAYER}!\p"
	.string "{JPN}おくりびやまには じゅみょうを おえた\n"
	.string "{JPN}ポケモンが まつられてるんだ!\p"
	.string "{JPN}そのせいか しゅつげんする ポケモンも\n"
	.string "{JPN}ゴーストタイプが おおいんだよな!$"

MatchCall_Text_Brendan9::
	.string "{JPN}ユウキ“なあなあ {PLAYER}!\p"
	.string "{JPN}オレ また フエンタウンの\n"
	.string "{JPN}おんせんに いこうと おもったんだけど\p"
	.string "{JPN}デコボコさんどうの とちゅうに\n"
	.string "{JPN}にんそうの わるいのが いたんだよ!\p"
	.string "{JPN}あれって マグマだん... だよな!?$"

MatchCall_Text_Brendan10::
	.string "{JPN}ユウキ“おっ {PLAYER}!\p"
	.string "{JPN}クスノキかんちょうが せんすいていで\n"
	.string "{JPN}かいていどうくつを はっけんした って\l"
	.string "{JPN}ニュースで やってたけど みたか?$"

MatchCall_Text_Brendan11::
	.string "{JPN}ユウキ“なあなあ {PLAYER}!\p"
	.string "{JPN}ふねが なくても ポケモンの わざで\n"
	.string "{JPN}うみのうえを わたって いけるって\l"
	.string "{JPN}なんだか すごくないか!?\p"
	.string "{JPN}しかも ポケモンと いっしょに\n"
	.string "{JPN}うみのそこに もぐれる わざも あるって!\p"
	.string "{JPN}ポケモンって なんでも できるんだなー!$"

MatchCall_Text_Brendan12::
	.string "{JPN}ユウキ“{PLAYER} おつかれ!\p"
	.string "{JPN}うみのうえで みえてるのに むこうがわへ\n"
	.string "{JPN}いけない ところ なんかは\p"
	.string "{JPN}どこかから いったん もぐって\n"
	.string "{JPN}かいていの みちを とおりぬけて\l"
	.string "{JPN}むこうの すいめんに でれば いいんだ!$"

MatchCall_Text_Brendan13::
	.string "{JPN}ユウキ“おーす {PLAYER}!\p"
	.string "{JPN}どうだ? ずかんは じゅんちょうに\n"
	.string "{JPN}うまっていってるか?\p"
	.string "{JPN}あのな うわさで きいたんだけど\n"
	.string "{JPN}どこかに ちょうこだいポケモン ってのが\l"
	.string "{JPN}3しゅるいも いるらしいんだよ!\p"
	.string "{JPN}うーん 1しゅるい だけでも いいから\n"
	.string "{JPN}つかまえて みたいよなあ...$"

MatchCall_Text_Brendan14::
	.string "{JPN}ユウキ“{PLAYER}!\n"
	.string "{JPN}うわさは きいたよ!\p"
	.string "{JPN}ルネの ジムリーダーにも かったって?\n"
	.string "{JPN}すげえなあ もうひといき だな!$"

MatchCall_Text_Brendan15::
	.string "{JPN}ユウキ“もう ホウエンちほうで\n"
	.string "{JPN}{PLAYER}のこと しらない\l"
	.string "{JPN}トレーナー なんて いないんだ!\p"
	.string "{JPN}オレが {PLAYER}と\n"
	.string "{JPN}ともだちだ っていうと\l"
	.string "{JPN}みんな うらやましそうに するよ!$"

MatchCall_Text_Wally1::
	.string "{JPN}ミツル“あっ {PLAYER}さん!\p"
	.string "{JPN}さいきんは からだの ぐあいも\n"
	.string "{JPN}ずいぶん よくなって きたし\p"
	.string "{JPN}ぼくも はやく {PLAYER}さん みたいな\n"
	.string "{JPN}トレーナーに なりたいな!$"

MatchCall_Text_Wally2::
	.string "{JPN}ミツル“{PLAYER}さん こんにちは!\p"
	.string "{JPN}カナシダトンネルが かいつう したせいで\n"
	.string "{JPN}ミチルおねえちゃんも\l"
	.string "{JPN}すっごく うれしそう ですよ!$"

MatchCall_Text_Wally3::
	.string "{JPN}ミツル“あっ {PLAYER}さん!\p"
	.string "{JPN}ぼく... シダケの おじさんに\n"
	.string "{JPN}なにも いわずに でてきちゃった けど\l"
	.string "{JPN}おじさん おこってないかな...\p"
	.string "{JPN}{PLAYER}さん なら\n"
	.string "{JPN}ぼくの きもち わかって くれますよね?$"

MatchCall_Text_Wally4::
	.string "{JPN}ミツル“{PLAYER}さん?\n"
	.string "{JPN}ぼくです ミツルです!\p"
	.string "{JPN}トレーナーの せかいって すごいですね!\n"
	.string "{JPN}ポケモンを つれて あるいていると\l"
	.string "{JPN}みんなが こえを かけて くれるんです!\p"
	.string "{JPN}まるで ポケモンを つうじて\n"
	.string "{JPN}みんなが つながっている みたいに!$"

MatchCall_Text_Wally5::
	.string "{JPN}ミツル“{PLAYER}さん? すごいですよ!\n"
	.string "{JPN}{PLAYER}さんと いっしょに つかまえた\l"
	.string "{JPN}ラルトスが しんか したんです!\p"
	.string "{JPN}ぼくって さいのう あるのかなあ...\p"
	.string "{JPN}なーんて ちょうしに のったら\n"
	.string "{JPN}いけませんよね\p"
	.string "{JPN}えらいのは ポケモン ですもん!$"

MatchCall_Text_Wally6::
	.string "{JPN}... ... ...\n"
	.string "... ... ...\p"
	.string "{JPN}ミツルは ポケナビの よびだしが\n"
	.string "{JPN}とどかない ところに いるようだ...$"

MatchCall_Text_Wally7::
	.string "{JPN}ミツル“あっ {PLAYER}さん!\p"
	.string "{JPN}いままで ほとんど いえから\n"
	.string "{JPN}でたことの ない ぼくが\p"
	.string "{JPN}こうして ポケモンと いっしょに\n"
	.string "{JPN}ぼうけんを している なんて...\p"
	.string "{JPN}{PLAYER}さん... ありがとう$"

MatchCall_Text_Scott1::
	.string "{JPN}エニシダ“どーも どーも {PLAYER}{KUN}\p"
	.string "{JPN}やまでも うみでも くさむらでも\n"
	.string "{JPN}どこにだって ポケモンが いるように\l"
	.string "{JPN}トレーナーさん というのも\l"
	.string "{JPN}いろんな ところに いるもんだねえ\p"
	.string "{JPN}おかげで わたしも\n"
	.string "{JPN}アッチいったり コッチいったり\l"
	.string "{JPN}いそがしくて しょうがないよ!$"

MatchCall_Text_Scott2::
	.string "{JPN}エニシダ“わたしは いま\n"
	.string "{JPN}119ばん どうろに きてるんだけど\l"
	.string "{JPN}たくさんの トレーナーが いるねえ!\p"
	.string "{JPN}でも このあたりは せのたかい くさが\n"
	.string "{JPN}いっぱい はえてるから\p"
	.string "{JPN}はんズボンで あるきまわると\n"
	.string "{JPN}あしが くすぐったくて こまるよ!$"

MatchCall_Text_Scott3::
	.string "{JPN}エニシダ“やあやあ {PLAYER}{KUN}!\p"
	.string "{JPN}きみは おくりびやま って\n"
	.string "{JPN}のぼったこと ある?\p"
	.string "{JPN}あそこは ポケモンの たましいが\n"
	.string "{JPN}まつられている ばしょ だからねえ\p"
	.string "{JPN}トレーナー ならば いちど ぐらいは\n"
	.string "{JPN}てっぺんまで のぼって みないとね!$"

MatchCall_Text_Scott4::
	.string "{JPN}エニシダ“んー {PLAYER}{KUN}!\p"
	.string "{JPN}どうも ちかごろは\n"
	.string "{JPN}マグマだん とか アクアだん とか\l"
	.string "{JPN}おかしな れんちゅうが あばれてるね\p"
	.string "{JPN}かれらの なかには\n"
	.string "{JPN}すぐれた トレーナーも いるんだろうけど\l"
	.string "{JPN}でも わるもの じゃあなあ...$"

MatchCall_Text_Scott5::
	.string "{JPN}エニシダ“おおー {PLAYER}{KUN}\p"
	.string "{JPN}あのね うみのそこにも すごうでの\n"
	.string "{JPN}トレーナーが いたり するのかな?\p"
	.string "{JPN}でも たしかめに いこうにも\n"
	.string "{JPN}わたしは およげないし\l"
	.string "{JPN}ポケモンも もってないし...$"

MatchCall_Text_Scott6::
	.string "{JPN}エニシダ“やあやあ {PLAYER}{KUN}!\p"
	.string "{JPN}ぜんぶの ジムバッジを あつめたら\n"
	.string "{JPN}ポケモンリーグに ちょうせん できる\l"
	.string "{JPN}というのは しってるよね?\p"
	.string "{JPN}きみほどの じつりょくが あるなら\n"
	.string "{JPN}チャンピオンも ゆめじゃない けど...\l"
	.string "{JPN}じつは もっと いいところが あるんだよ\p"
	.string "{JPN}まあ いまは それいじょう\n"
	.string "{JPN}いわないで おくよ\p"
	.string "{JPN}ポケモンリーグを かちぬいて\n"
	.string "{JPN}でんどういり してからの おたのしみだね!$"

MatchCall_Text_Scott7::
	.string "{JPN}... ... ...\n"
	.string "... ... ...\p"
	.string "{JPN}エニシダは ポケナビの よびだしが\n"
	.string "{JPN}とどかない ところに いるようだ...$"

MatchCall_Text_Norman1::
	.string "{JPN}パパ“カナズミの まちには\n"
	.string "{JPN}いあいぎりおやじ という\l"
	.string "{JPN}かわった なまえの ひとが すんでいる!\p"
	.string "{JPN}ちかくまで いったら\n"
	.string "{JPN}おまえも たずねて みると いいぞ!$"

MatchCall_Text_Norman2::
	.string "{JPN}パパ“ふむ... {PLAYER}は\n"
	.string "{JPN}すこしずつ しかし かくじつに\l"
	.string "{JPN}つよく なっているな\p"
	.string "{JPN}おまえが つよくなれば なるほど\n"
	.string "{JPN}わたしや ママの もとから\l"
	.string "{JPN}とおくへ はなれて いってしまう...\p"
	.string "{JPN}なんとも ふくざつな きぶんだよ$"

MatchCall_Text_Norman3::
	.string "{JPN}パパ“そうか...\n"
	.string "{JPN}ジムバッジを 4つ あつめたのか\p"
	.string "{JPN}では やくそく どおり\n"
	.string "{JPN}ポケモンしょうぶ だな...\p"
	.string "{JPN}いつでも おいで まってるぞ!$"

MatchCall_Text_Norman4::
	.string "{JPN}パパ“{PLAYER}! たまには ママにも\n"
	.string "{JPN}あいに いって あげるんだぞ!\p"
	.string "{JPN}わたしは ここで\n"
	.string "{JPN}じぶんを きたえなおす!\p"
	.string "{JPN}ポケモンしょうぶの みちは\n"
	.string "{JPN}おくが ふかい からな!$"

MatchCall_Text_Norman5::
	.string "{JPN}パパ“おお {PLAYER}!\p"
	.string "{JPN}なになに? マグマのしるし...?\n"
	.string "{JPN}なんのことか わたしには わからないが\p"
	.string "{JPN}マグマと いうぐらい だから\n"
	.string "{JPN}なにか かざんと かんけい ありそうだな!$"

MatchCall_Text_Norman6::
	.string "{JPN}パパ“せや! うりゃ! どりゃー!\p"
	.string "{JPN}...お {PLAYER}か!\p"
	.string "{JPN}わたしは いま ポケモンと いっしょに\n"
	.string "{JPN}トレーニングの まっさいちゅうだ!$"

MatchCall_Text_Norman7::
	.string "{JPN}パパ“{PLAYER}!\p"
	.string "{JPN}まさか おまえが でんどういりを\n"
	.string "{JPN}はたして しまうとは...\p"
	.string "{JPN}よし!\n"
	.string "{JPN}わたしも まけては いられないぞ!$"

MatchCall_Text_Norman8::
	.string "{JPN}パパ“...ん? {PLAYER}か?\n"
	.string "{JPN}これは ちょうど よかった!\p"
	.string "{JPN}こんどは パパから おまえに\n"
	.string "{JPN}しょうぶを もうしこんで やろう\p"
	.string "{JPN}トウカの ジムで まってるから\n"
	.string "{JPN}いつでも ちょうせんしに おいで!$"

MatchCall_Text_Norman9::
	.string "{JPN}パパ“...すごいなあ {PLAYER}\n"
	.string "{JPN}どこまで つよく なっちゃうんだろう$"

MatchCall_Text_Steven1::
	.string "{JPN}ダイゴ“やあ {PLAYER}{KUN}!\p"
	.string "{JPN}もう キンセツシティには いったかな?\p"
	.string "{JPN}まちの サイクルショップで\n"
	.string "{JPN}マッハじてんしゃを てにいれたら\p"
	.string "{JPN}もういちど いしのどうくつの おくに\n"
	.string "{JPN}いってみるのも いいね!\p"
	.string "{JPN}なにか あたらしい はっけんが\n"
	.string "{JPN}あるかも しれないよ!$"

MatchCall_Text_Steven2::
	.string "{JPN}ダイゴ“やあ {PLAYER}{KUN}!\p"
	.string "{JPN}ボクは これまでに ずいぶん いろいろな\n"
	.string "{JPN}トレーナーを みてきた けれど\p"
	.string "{JPN}キミは だれにも にていない\n"
	.string "{JPN}はじめて みる タイプの ひとだよ!$"

MatchCall_Text_Steven3::
	.string "{JPN}ダイゴ“やあ {PLAYER}{KUN}!\p"
	.string "{JPN}キミは ポケモンと ぼうけんを していて\n"
	.string "{JPN}どんな きぶんに なる?\p"
	.string "{JPN}つよいみかた だと おもうかい?\n"
	.string "{JPN}たのしいなかま だと おもうかい?\p"
	.string "{JPN}キミが どう かんじるかに よって\n"
	.string "{JPN}その ぼうけんの いみは かわるんだ!$"

MatchCall_Text_Steven4::
	.string "{JPN}ダイゴ“ああ {PLAYER}{KUN} かい?\p"
	.string "{JPN}ちょっと いま うちゅうセンターで\n"
	.string "{JPN}めんどうな ことが おきてるんだ\p"
	.string "{JPN}わるいけど また あとでね!$"

MatchCall_Text_Steven5::
	.string "{JPN}ダイゴ“あっ {PLAYER}{KUN}!\p"
	.string "{JPN}なにも いわなくて いいよ!\n"
	.string "{JPN}とにかく いまは...\p"
	.string "{JPN}キミが おもうように すすむんだ!$"

MatchCall_Text_Steven6::
	.string "{JPN}... ... ...\p"
	.string "{JPN}ダイゴには よびだしが\n"
	.string "{JPN}つうじていない ようだ...$"

MatchCall_Text_Steven7::
	.string "{JPN}ダイゴ“{PLAYER}{KUN}...\n"
	.string "{JPN}でんどういり おめでとう\p"
	.string "... ... ...\n"
	.string "... ... ...\p"
	.string "{JPN}また いつか あえると いいね!$"

MatchCall_Text_BirchRegisterCall:
	.string "{JPN}オダマキ“おお {PLAYER}{KUN}!\n"
	.string "{JPN}はなしは すでに きいて いるよ!\p"
	.string "{JPN}きみの ポケナビに エントリーコールが\n"
	.string "{JPN}セットされた らしいな!\p"
	.string "{JPN}ならば わたしも とうろく しておこう!\p"
	.string "{JPN}これで きみと はなれていても\n"
	.string "{JPN}すぐに ポケモンずかんの ひょうかを\l"
	.string "{JPN}してあげられる からね!\p"
	.string "... ... ...$"

MatchCall_Text_RegisteredBirch:
	.string "{JPN}オダマキはかせを\n"
	.string "{JPN}ポケナビに とうろく した!$"

MatchCall_Text_UnusedProfBirch:
	.string "{JPN}オダマキ“ずかんと ポケナビが あれば\n"
	.string "{JPN}ポケモンの ちょうさも\l"
	.string "{JPN}より いっそう たのしくなるな!$"

MatchCall_Text_MrStone1::
	.string "{JPN}ツワブキ“おっ! {PLAYER}{KUN}か?\p"
	.string "{JPN}こうして わしを よびだした ってことは\n"
	.string "{JPN}ポケナビの ちょうしは よさそうだな!\p"
	.string "{JPN}わしの ほかにも いろんな ひとが\n"
	.string "{JPN}とうろく されて いくから どんどん\l"
	.string "{JPN}よびだして はなしを すると いいぞ!\p"
	.string "{JPN}けっこう! けっこう!\n"
	.string "{JPN}うれしそうに しとる ようだな!\p"
	.string "{JPN}...ん? なんで わかるのかって?\p"
	.string "{JPN}それは... しゃちょうしつの まどから\n"
	.string "{JPN}きみを みおろして いるからだよ!\p"
	.string "{JPN}わははは! じゃあ またな!$"

MatchCall_Text_MrStone2::
	.string "{JPN}ツワブキ“おっ! {PLAYER}{KUN}か?\p"
	.string "{JPN}どうした! わしが たのんだ しごと\n"
	.string "{JPN}わすれちゃったの かな?\p"
	.string "{JPN}まずは ムロタウンで ダイゴに\n"
	.string "{JPN}てがみを わたしてくれ!\p"
	.string "{JPN}そのあと カイナシティの クスノキくんに\n"
	.string "{JPN}わがしゃの にもつを とどけるんだ!\p"
	.string "{JPN}な? おぼえたかな?\n"
	.string "{JPN}わしは いそがしい しゃちょう だからね\l"
	.string "{JPN}これで しつれい するよ!$"

MatchCall_Text_MrStone3::
	.string "{JPN}ツワブキ“おっ! {PLAYER}{KUN}!\p"
	.string "{JPN}そうか ダイゴに あえたのか!\n"
	.string "{JPN}よーし おれいに プレゼントを やろう!\p"
	.string "{JPN}カナズミに くることが あったら\n"
	.string "{JPN}わしの へやに よっていって おくれ!\p"
	.string "{JPN}じゃあな まっとるぞ!$"

MatchCall_Text_MrStone4::
	.string "{JPN}ツワブキ“おお! {PLAYER}{KUN}!\p"
	.string "{JPN}そうそう カナシダトンネルは\n"
	.string "{JPN}わがしゃが ほって いたんだけどね\p"
	.string "{JPN}あの あたりに せいそく している\n"
	.string "{JPN}ポケモンを ほご するために\l"
	.string "{JPN}こうじは ちゅうし したんだよ\p"
	.string "{JPN}まあ にんげんの べんりさ よりは\n"
	.string "{JPN}ポケモンが しずかに くらせる\l"
	.string "{JPN}そのほうが だいじな ことだからね!$"

MatchCall_Text_MrStone5::
	.string "{JPN}ツワブキ“やあやあ {PLAYER}{KUN}!\p"
	.string "{JPN}トウカシティの ひとから きいたんだけど\n"
	.string "{JPN}きみは センリさんの こども なんだね\p"
	.string "{JPN}どうりで たのもしいと おもったよ!$"

MatchCall_Text_MrStone6::
	.string "{JPN}ツワブキ“ええっ!\n"
	.string "{JPN}きみは じぶんの おとうさんと\l"
	.string "{JPN}ポケモンしょうぶを して かったのかい?\p"
	.string "{JPN}こりゃ びっくりだ!\n"
	.string "{JPN}わしは すごい ひとと ともだちに\l"
	.string "{JPN}なっちゃったんだなあ! わはは!$"

MatchCall_Text_MrStone7::
	.string "{JPN}もしもし!\n"
	.string "{JPN}デボンコーポレーションで ございま...\l"
	.string "{JPN}ああ {PLAYER}さん ですね!\p"
	.string "{JPN}しゃちょうは さっきまで いたんですけど\n"
	.string "{JPN}いまは るすに してるんですよ!\p"
	.string "{JPN}うちの しゃちょうも いそがしいけど\n"
	.string "{JPN}{PLAYER}さんも いそがしそう ですね!$"

MatchCall_Text_MrStone8::
	.string "{JPN}...え ...なにかね?\p"
	.string "{JPN}グラ... はい? ...ドン?\p"
	.string "{JPN}なんだか... きこえな...\p"
	.string "{JPN}ザザザザザ... ... ...$"

MatchCall_Text_MrStone9::
	.string "{JPN}...え ...なにかね?\p"
	.string "{JPN}かいて... はい? ...どうくつ?\p"
	.string "{JPN}なんだか... きこえな...\p"
	.string "{JPN}ザザザザザ... ... ...$"

MatchCall_Text_MrStone10::
	.string "{JPN}ツワブキ“{PLAYER}{KUN}! わしだ!\p"
	.string "{JPN}なんだか いろいろ あった らしいが\n"
	.string "{JPN}いそがしい わしには\l"
	.string "{JPN}なんの ことだか サッパリ わからん!\p"
	.string "{JPN}とにかく キミは じぶんの しんじた\n"
	.string "{JPN}みちを あゆんで いきたまえ!\p"
	.string "{JPN}わしも カゲながら おうえん しとるぞ!\n"
	.string "{JPN}じゃあな!$"

MatchCall_Text_MrStone11::
	.string "{JPN}ツワブキ“... ... ...\n"
	.string "{JPN}もしかして {PLAYER}{KUN} か?\p"
	.string "{JPN}こえに じしんが みなぎっていて\n"
	.string "{JPN}いっしゅん ちがうひとかと おもったぞ!\p"
	.string "{JPN}うむ! たまには わがしゃにも\n"
	.string "{JPN}あそびに きておくれ!$"
