@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "{JPN} きれい だよねー$"

GiddyText_SoDarling::
	.string "{JPN} かわいい よねー$"

GiddyText_SoRelaxed::
	.string "{JPN} のんびり だよねー$"

GiddyText_SoSunny::
	.string "{JPN} ぽっかぽか だよねー$"

GiddyText_SoDesirable::
	.string "{JPN} あこがれる よねー$"

GiddyText_SoExciting::
	.string "{JPN} ドキドキ するよねー$"

GiddyText_SoAmusing::
	.string "{JPN} おもしろい よねー$"

GiddyText_SoMagical::
	.string "{JPN} ふしぎ だよねー$"

GiddyText_Is::
	.string "{JPN}って$"

GiddyText_DontYouAgree::
	.string "{JPN}\n"
	.string "{JPN}そう おもわない?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "{JPN}って$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "{JPN}\n"
	.string "{JPN}そう おもわない?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "{JPN}たびに でたいなー\n"
	.string "{JPN}どこか いい ところ しらない?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "{JPN}120しょくの クレヨン かったんだー\n"
	.string "{JPN}いいでしょう?$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "{JPN}しゃぼんだまに のって とべるように\n"
	.string "{JPN}ならないかなー$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "{JPN}すなはまに かいた もじは\n"
	.string "{JPN}すぐに きえちゃうのが かなしいよねー$"

GiddyText_LyingBackInTheGreenGrass::
	.string "{JPN}うみの そこって どうなってるのかなー\n"
	.string "{JPN}いちどで いいから みて みたいなー$"

GiddyText_SecretBasesAreSoWonderful::
	.string "{JPN}ゆうやけを みると\n"
	.string "{JPN}ウチに かえりたく ならない?$"
