MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "{JPN}この わざを おぼえますか?\n"
	.string "{JPN}5000えん かかります$"

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnceFinite:
	.string "{JPN}この わざは いちどだけしか\n"
	.string "{JPN}おぼえられません いいですか?$"

MoveTutor_Text_SwaggerTeach:
	.string "{JPN}ふふーん\n"
	.string "{JPN}おれの ポケモンは すごいのさ!\l"
	.string "{JPN}どの ポケモンよりも かっこいいのさ!\p"
	.string "{JPN}...って いばってたら\n"
	.string "{JPN}かいちょうに おこられちゃった\p"
	.string "{JPN}もう いばらない ことに したから\n"
	.string "{JPN}かわりに おまえの ポケモンに\l"
	.string "{JPN}いばる わざを おしえて やってもいいぜ$"

MoveTutor_Text_SwaggerDeclined:
	.string "{JPN}えー\n"
	.string "{JPN}なんだよ つきあい わるいな$"

MoveTutor_Text_SwaggerWhichMon:
	.string "{JPN}おう!\n"
	.string "{JPN}どの ポケモンが いばりたいんだ?$"

MoveTutor_Text_SwaggerTaught:
	.string "{JPN}こんどっから いばる かわりに\n"
	.string "{JPN}じまん するだけに しておくよ...$"

MoveTutor_Text_RolloutTeach:
	.string "{JPN}ねえ ここから あっちに むかって\n"
	.string "{JPN}いちども まがらずに ずーっと\l"
	.string "{JPN}あるいて いけるって しってた?\l"
	.string "{JPN}ぼく なら ころがって いけるかも...!\p"
	.string "{JPN}きみの ポケモンも ころがって みる?\n"
	.string "{JPN}ころがる なら おしえて あげられるよ$"

MoveTutor_Text_RolloutDeclined:
	.string "{JPN}えんりょ いらないのに!\n"
	.string "{JPN}ごろ ごろ$"

MoveTutor_Text_RolloutWhichMon:
	.string "{JPN}えへへ いいよ!\n"
	.string "{JPN}ぼく そっくりの ポケモンだと いいな$"

MoveTutor_Text_RolloutTaught:
	.string "{JPN}くさに ねころがると しあわせだなー\n"
	.string "{JPN}ごろ ごろ$"

MoveTutor_Text_FuryCutterTeach:
	.string "{JPN}おなじ わざをさ\n"
	.string "{JPN}つづけて なんども だすと\l"
	.string "{JPN}どんどん つよくなる わざが あるの!\l"
	.string "{JPN}しかも むしタイプで かっこいいの!\p"
	.string "{JPN}れんぞくぎりって いうんだけど\n"
	.string "{JPN}おぼえて みたい?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "{JPN}きが あわないねぇ$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "{JPN}わーい!\n"
	.string "{JPN}じゃ おぼえさせる ポケモンを おしえてね$"

MoveTutor_Text_FuryCutterTaught:
	.string "{JPN}れんぞくして あたるか どうかの\n"
	.string "{JPN}スリルが たのしいんだよねぇ$"

MoveTutor_MimicTeach:
	.string "{JPN}おお おわかいの!\n"
	.string "{JPN}わしは こども じゃが\l"
	.string "{JPN}このまちの じいちゃんや ばあちゃんの\l"
	.string "{JPN}はなしかたを ものまね しておるのじゃ!\p"
	.string "{JPN}どうかね? おわかいの\n"
	.string "{JPN}おぬしの ポケモンに わしが\l"
	.string "{JPN}ものまねを おしえて やろうかね?$"

MoveTutor_MimicDeclined:
	.string "{JPN}ちぇっ なーんだ!\n"
	.string "{JPN}ボク ものまね おしえたいのにな!$"

MoveTutor_Text_MimicWhichMon:
	.string "{JPN}ふぉっ ふぉっ! よかろう!\n"
	.string "{JPN}おしえさせる ポケモンを みせてみぃ$"

MoveTutor_Text_MimicTaught:
	.string "{JPN}ものまねは おくの ふかい わざじゃ!\n"
	.string "{JPN}ボ... わしの ように\l"
	.string "{JPN}うまく できるかな?$"

MoveTutor_Text_MetronomeTeach:
	.string "{JPN}あーん ほしいものが いっぱい!\n"
	.string "{JPN}でも おこづかいは なくなっちゃったし...\p"
	.string "{JPN}ゆびを ふれば まほうで\n"
	.string "{JPN}おこづかい でてくれば いーのにな!\l"
	.string "{JPN}なんてね エヘヘ...\p"
	.string "{JPN}しかたが ないから\n"
	.string "{JPN}あなたの ポケモンに\l"
	.string "{JPN}ゆびをふる でも おしえて あげよっか?$"

MoveTutor_Text_MetronomeDeclined:
	.string "{JPN}そっか\n"
	.string "{JPN}きが むいたら またおいでよ!$"

MoveTutor_Text_MetronomeWhichMon:
	.string "{JPN}うん! じゃ おしえるね\n"
	.string "{JPN}どのコが いいのかな?$"

MoveTutor_Text_MetronomeTaught:
	.string "{JPN}ゆびをふると ステキな ことが\n"
	.string "{JPN}いっぱい おきるんだよー!\p"
	.string "{JPN}わたしたちも つかえたら いーのにね!$"

MoveTutor_Text_SleepTalkTeach:
	.string "{JPN}ふん... ばあさんめ\n"
	.string "{JPN}めざめるパワー などに\l"
	.string "{JPN}たより おって...\p"
	.string "{JPN}ワシと いっしょに おひるね して\n"
	.string "{JPN}ねごとでも いってたほうが たのしいのに\p"
	.string "{JPN}もう あんたの ポケモンでも ええわ\n"
	.string "{JPN}ねごとを おぼえて つかってみんか?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "{JPN}そうかい そうかい...\n"
	.string "{JPN}みんな めざめるパワーが だいすきかい$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "{JPN}むぉう! ものわかりの いい こどもよ!\n"
	.string "{JPN}さて ポケモンは どいつが いいかな?$"

MoveTutor_Text_SleepTalkTaught:
	.string "{JPN}ワシ ばあさんの コイン\n"
	.string "{JPN}いちども あてたことが なくてな...\l"
	.string "{JPN}ねごとでも ええから あたらんかな$"

MoveTutor_Text_SubstituteTeach:
	.string "{JPN}ふう\n"
	.string "{JPN}こうやって おくじょうから\l"
	.string "{JPN}ひろい せかいを みていると...\p"
	.string "{JPN}なんにんもの じぶんが いて\n"
	.string "{JPN}いくつもの じんせいを たのしめたらなー\l"
	.string "{JPN}って おもうの!\l"
	.string "{JPN}ムリな はなしだけどね うふふ\p"
	.string "{JPN}そうだわ あなたの ポケモンちゃん!\n"
	.string "{JPN}みがわりの わざ おぼえてみない?$"

MoveTutor_Text_SubstituteDeclined:
	.string "{JPN}あら そう?\n"
	.string "{JPN}ポケモンなら じぶんの ぶんしんを\l"
	.string "{JPN}つくる ことが できるのに$"

MoveTutor_Text_SubstituteWhichMon:
	.string "{JPN}うふふ\n"
	.string "{JPN}どの ポケモンちゃんが いいかしら?$"

MoveTutor_Text_SubstituteTaught:
	.string "{JPN}わたしたち にんげんは\n"
	.string "{JPN}じぶんの じんせいを\l"
	.string "{JPN}おもいきり たのしまなきゃ ね!\l"
	.string "{JPN}あなたも そうなるように いのってる!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "{JPN}もう できんわ!\p"
	.string "{JPN}ぜったい ムリだわ!\p"
	.string "{JPN}かくとうタイプの オレは\n"
	.string "{JPN}トクサネの ジムでは\l"
	.string "{JPN}ぜんぜん かてんわ!\p"
	.string "{JPN}ちきしょーっ! ボカ ボカ!\n"
	.string "{JPN}ボカ ボカ! ボカ ボカ!\p"
	.string "{JPN}なんだよ\n"
	.string "{JPN}そんな めで みるなよ!\l"
	.string "{JPN}じめんを なぐってる だけだろ!\p"
	.string "{JPN}それとも おまえの ポケモンに\n"
	.string "{JPN}ばくれつパンチを おしえて ほしいのかよ?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "{JPN}ちきしょー おまえまで\n"
	.string "{JPN}オレを ばかに するかっ!?\l"
	.string "{JPN}ボカ ボカ!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "{JPN}うぉー! ほんとか! いいやつだな!\n"
	.string "{JPN}どのポケモンに おしえれば いい?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "{JPN}なあ ばくれつパンチ つかって\n"
	.string "{JPN}トクサネジムで かって きてくれよ!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "{JPN}あーあ\n"
	.string "{JPN}ルネシティの ジムリーダーって\l"
	.string "{JPN}すっごく すてきだから\l"
	.string "{JPN}ライバルが いっぱい なのよねー\p"
	.string "{JPN}この あたしが すてみで ぶつかっても\n"
	.string "{JPN}ダメだったわ!\p"
	.string "{JPN}ねえ あなた!\n"
	.string "{JPN}せっかく だから この あたしの\l"
	.string "{JPN}じきでんの すてみタックル!\l"
	.string "{JPN}あなたの ポケモンに おしえさせてよ!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "{JPN}うん もう!\n"
	.string "{JPN}あなたに まで ふられちゃったわ$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "{JPN}ん じゃあ\n"
	.string "{JPN}どの ポケモンが いいか きめてよ$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "{JPN}もう いいわっ!\n"
	.string "{JPN}あたしも こいを すてて\l"
	.string "{JPN}つよい オンナに なってやるっ!$"

MoveTutor_Text_ExplosionTeach:
	.string "{JPN}ぼかぁ こんな イナカで\n"
	.string "{JPN}いつまでも くすぶっとる つもりは\l"
	.string "{JPN}まったく ないんじゃあー!\p"
	.string "{JPN}みとれよ いつか トカイに でて\n"
	.string "{JPN}ドッカーンと はでに やって やるわい!\p"
	.string "{JPN}おいっ! おまえ きいとったん なら\n"
	.string "{JPN}けいきよく だいばくはつを おしえさせろ!$"

MoveTutor_Text_ExplosionDeclined:
	.string "{JPN}がーっ!\n"
	.string "{JPN}イナカもん だからって ことわるなあ!$"

MoveTutor_Text_ExplosionWhichMon:
	.string "{JPN}ぃよーし ドッカーンと おぼえさせるか!\n"
	.string "{JPN}どの ポケモンが ぶちかますんか?$"

MoveTutor_Text_ExplosionTaught:
	.string "{JPN}いつも ポケモンに ばっか\n"
	.string "{JPN}だいばくはつを おしえとって\l"
	.string "{JPN}かんじんの ぼくは いつまでも\l"
	.string "{JPN}ばくはつ できん...\p"
	.string "{JPN}でも ほんとは\n"
	.string "{JPN}このまちに いつまでも いたいから\l"
	.string "{JPN}かも しれん...$"
