gText_ObtainedTheItem::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_TheBagIsFull::
	.string "{JPN}バッグが いっぱいだ!$"

gText_PutItemInPocket::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}{STR_VAR_3}ポケットに しまった!$"

gText_PlayerFoundOneItem::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\nみつけた!$"

gText_TooBadBagIsFull::
	.string "{JPN}ざんねん!\n"
	.string "{JPN}バッグが いっぱいだ...$"

gText_PlayerPutItemInBag::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}バッグに しまった!$"

gText_ObtainedTheDecor::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_NoRoomLeftForAnother::
	.string "{JPN}ざんねん! {STR_VAR_2}を\n"
	.string "{JPN}いれる ばしょが いっぱいだ...$"

gText_TheDecorWasTransferredToThePC::
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}パソコンに てんそうされた!$"

gText_PutItemInPC::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}パソコンに しまった!$"

gText_TooBadBagAndPCAreFull::
	.string "{JPN}ざんねん!\n"
	.string "{JPN}バッグも パソコンも いっぱいだ...$"
