gText_PkmnTransferredSomeonesPC::
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}だれかのパソコンに おくられた.\p"
	.string "{JPN}ボックス {STR_VAR_1}に\n"
	.string "{JPN}あずけられた.$"

gText_PkmnTransferredBillsPC::
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}マサキのパソコンに おくられた.\p"
	.string "{JPN}ボックス {STR_VAR_1}に\n"
	.string "{JPN}あずけられた.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{JPN}ボックス {STR_VAR_3}が\n"
	.string "{JPN}いっぱいだったので\p"
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}ボックス {STR_VAR_1}に おくられた.$"

gText_PkmnTransferredBillsPCBoxFull::
	.string "{JPN}ボックス {STR_VAR_3}が\n"
	.string "{JPN}いっぱいだったので\p"
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}ボックス {STR_VAR_1}に おくられた.$"

gText_NoMoreRoomForPokemon::
	.string "{JPN}ポケモンを あずける\nばしょが ありません!\p"
	.string "{JPN}ボックスが すべて\n"
	.string "{JPN}いっぱいです!$"

gText_NicknameThisPokemon::
	.string "{JPN}この {STR_VAR_1}に\n"
	.string "{JPN}ニックネームを つけますか?$"
