gText_WouldYouLikeToRestYourPkmn::
	.string "{JPN}おつかれさまです!\n"
	.string "{JPN}ポケモン センター です\p"
	.string "{JPN}ここでは ポケモンの\n"
	.string "{JPN}たいりょく かいふくを します\p"
	.string "{JPN}あなたの ポケモンを\n"
	.string "{JPN}やすませて あげますか?$"

gText_IllTakeYourPkmn::
	.string "{JPN}それでは\n"
	.string "{JPN}おあずかり いたします!$"

gText_RestoredPkmnToFullHealth::
	.string "{JPN}おまちどおさま!\p"
	.string "{JPN}おあずかり した ポケモンは\n"
	.string "{JPN}みんな げんきに なりましたよ!$"

gText_WeHopeToSeeYouAgain::
	.string "{JPN}またの\nごりようを おまち してます!$"

gText_WelcomeCutShort::
	.string "{JPN}おつかれさまです!\n"
	.string "{JPN}ポケモン センター です\p"
	.string "{JPN}ここでは ポケモンの\n"
	.string "{JPN}たいりょく かいふくを します\p"
	.string "{JPN}あなたの ポケモンを...$"

gText_NoticesGoldCard::
	.string "{JPN}そ それは...\n"
	.string "{JPN}ひょっとして ゴールドカード!?\p"
	.string "{JPN}ああ... きんいろが まぶしい!\n"
	.string "{JPN}4つの ほしが かがやかしい!\p"
	.string "{JPN}わたしも これまでに\n"
	.string "{JPN}シルバーカードの トレーナーさんなら\l"
	.string "{JPN}なんにんか みてきましたが\l"
	.string "{JPN}ゴールドカードを おもちの かたは\l"
	.string "{JPN}{PLAYER}さんが はじめて ですよ!\p"
	.string "{JPN}さあ {PLAYER}さんの\n"
	.string "{JPN}ポケモンを やすませて あげましょう!$"

gText_YouWantTheUsual::
	.string "{JPN}{PLAYER}さん おつかれさまです!\n"
	.string "{JPN}いつもので よろしい ですね!$"

gText_IllTakeYourPkmn2::
	.string "{JPN}では おあずかりさせて いただきます!$"

gText_ThankYouForWaiting::
	.string "{JPN}たいへん おまたせ いたしました!$"

gText_WeHopeToSeeYouAgain2::
	.string "{JPN}また いつでも おこしください!$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "{JPN}すみません ポケセンチャレンジ\n"
    .string "{JPN}ちゅうですね!\p"
    .string "{JPN}がんばってください!{PAUSE_UNTIL_PRESS}$"
