gBirchDexRatingText_GoFindMrPokemon::
	.string "{JPN}エルムはかせ: おお {PLAYER}{KUN}!\p"
	.string "{JPN}ポケモンじいさんの いえは\n"
	.string "{JPN}みつけたかい? 30ばんどうろ\p"
	.string "{JPN}にあるから すぐわかるよ!$"

gBirchDexRatingText_Robbery::
	.string "{JPN}エルムはかせ: {PLAYER}{KUN}!\p"
	.string "{JPN}すぐ きてくれ! たいへんな\n"
	.string "{JPN}ことが おきたんだ!$"

gBirchDexRatingText_AreYouCurious::
	.string "{JPN}エルムはかせ: おお {PLAYER}{KUN}!\p"
	.string "{JPN}ポケモンずかんの ちょうしは\n"
	.string "{JPN}どうだい?$"

gBirchDexRatingText_Cancel::
	.string "{JPN}ん? まだ つかまえた\n"
	.string "{JPN}ポケモンが すくないね.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "{JPN}ふむふむ...\p"
	.string "{JPN}{STR_VAR_1}しゅるいの ポケモンを みて\n"
	.string "{JPN}{STR_VAR_2}しゅるいを つかまえたか...$"

gBirchDexRatingText_LessThan10::
	.string "{JPN}くさむらに もっと はいって\n"
	.string "{JPN}ポケモンを さがしてみよう!$"

gBirchDexRatingText_LessThan20::
	.string "{JPN}コツを つかんできたね.\n"
	.string "{JPN}でも ここからが たいへんだよ.$"

gBirchDexRatingText_LessThan30::
	.string "{JPN}ある ばしょにしか いない\n"
	.string "{JPN}ポケモンも いるんだ.\l"
	.string "{JPN}こんきよく さがそう!$"

gBirchDexRatingText_LessThan40::
	.string "{JPN}かずは まだだけど\n"
	.string "{JPN}ポケモンずかんらしく\l"
	.string "{JPN}なってきたね.$"

gBirchDexRatingText_LessThan50::
	.string "{JPN}じゅんちょうだね.\n"
	.string "{JPN}このちょうしで がんばろう!$"

gBirchDexRatingText_LessThan60::
	.string "{JPN}つりざおは つかってるかい?\n"
	.string "{JPN}うみにも たくさん ポケモンが いるよ.$"

gBirchDexRatingText_LessThan70::
	.string "{JPN}つかまえるだけじゃなくて\n"
	.string "{JPN}しんかさせるのも だいじだよ!$"

gBirchDexRatingText_LessThan80::
	.string "{JPN}すばらしい ポケモンずかんに\n"
	.string "{JPN}なりそうだ.\l"
	.string "{JPN}そんな よかんが するよ!$"

gBirchDexRatingText_LessThan90::
	.string "{JPN}こんなに あつめるなんて...\n"
	.string "{JPN}きみの さいのうは すごいね!$"

gBirchDexRatingText_LessThan100::
	.string "{JPN}サファリゾーンには いったかい?\p"
	.string "{JPN}あそこでしか つかまえられない\n"
	.string "{JPN}ポケモンも いるらしいよ.$"

gBirchDexRatingText_LessThan110::
	.string "{JPN}ついに 100しゅるいを\n"
	.string "{JPN}こえたんだね.\p"
	.string "{JPN}りっぱな ポケモンずかんだ!$"

gBirchDexRatingText_LessThan120::
	.string "{JPN}いわくだきで みつかる\n"
	.string "{JPN}ポケモンも いるかもしれないよ.$"

gBirchDexRatingText_LessThan130::
	.string "{JPN}トレーナーに なつくと\n"
	.string "{JPN}しんかする ポケモンも\l"
	.string "{JPN}いるらしいよ.$"

gBirchDexRatingText_LessThan140::
	.string "{JPN}トレーナーに なつくと\n"
	.string "{JPN}しんかする ポケモンも\l"
	.string "{JPN}いるらしいよ.$"

gBirchDexRatingText_LessThan150::
	.string "{JPN}ジョウトちほうに こんなにも\n"
	.string "{JPN}たくさんの しゅるいの\l"
	.string "{JPN}ポケモンが いるとはね.$"

gBirchDexRatingText_LessThan160::
	.string "{JPN}ときどき たいりょうはっせい\n"
	.string "{JPN}する ポケモンが いるよ.\p"
	.string "{JPN}そんな チャンスを\n"
	.string "{JPN}のがさないようにね!$"

gBirchDexRatingText_LessThan170::
	.string "{JPN}きみの ポケモンずかんを みれば\n"
	.string "{JPN}ジョウトちほうの ポケモンが\l"
	.string "{JPN}よく わかるね!$"

gBirchDexRatingText_LessThan180::
	.string "{JPN}きみは もう りっぱな\n"
	.string "{JPN}ポケモンはかせだよ.\l"
	.string "{JPN}それも すごうでの!$"

gBirchDexRatingText_LessThan190::
	.string "{JPN}ここまで そろえるとは\n"
	.string "{JPN}ほんとうに プロだね!$"

gBirchDexRatingText_LessThan200::
	.string "{JPN}かんせいまで あと すこし.\n"
	.string "{JPN}わたしには わかるよ!$"

gBirchDexRatingText_DexCompleted::
	.string "{JPN}おめでとう!\n"
	.string "{JPN}ポケモンずかんが かんせいだ!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "{JPN}ふむふむ...\n"
	.string "{JPN}ぜんこくてきに みると...\p"
	.string "{JPN}{STR_VAR_1}しゅるいの ポケモンを みて\n"
	.string "{JPN}{STR_VAR_2}しゅるいを つかまえたか...$"

gBirchDexRatingText_CaughtAllNational::
	.string "{JPN}ふむふむ...\n"
	.string "{JPN}ぜんこくてきに みると...\p"
	.string "{JPN}{STR_VAR_1}しゅるいの ポケモンを みて\n"
	.string "{JPN}{STR_VAR_2}しゅるいを つかまえたか...\p"
	.string "{JPN}すごいぞ {PLAYER}!\p"
	.string "{JPN}ぜんこくずかんが かんせいだ!\n"
	.string "{JPN}おめでとう!$"
