Questionnaire_Text_FillOut::
	.string "{JPN}アンケートようの メモようしが ある\n"
	.string "{JPN}アンケートに なにか かきますか?$"

Questionnaire_Text_ThankYou::
	.string "{JPN}アンケートに ごきょうりょく\n"
	.string "{JPN}いただき ありがとう ございます!\p"
	.string "{JPN}この アンケートは こんごの\n"
	.string "{JPN}さんこうに させて いただきます!$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "{JPN}... おきゃくさま!\n"
	.string "{JPN}そのことばを しってるの ですか!\p"
	.string "{JPN}ということは ふしぎなおくりもの を\n"
	.string "{JPN}しって いらっしゃるの ですね!\p"
	.string "{JPN}これからは あなたにも\n"
	.string "{JPN}ふしぎなおくりもの が\l"
	.string "{JPN}とどくように なるでしょう!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "{JPN}レポートをかくと ふしぎなおくりもの が\n"
	.string "{JPN}つかえるように なります$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "{JPN}... おきゃくさま!\n"
	.string "{JPN}そのことばを しってるの ですか!\p"
	.string "{JPN}ということは ふしぎなできごと を\n"
	.string "{JPN}しって いらっしゃるの ですね!$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "{JPN}レポートをかくと ふしぎなできごと が\n"
	.string "{JPN}つかえるように なります$"

MysteryGift_Text_TheresATicketForYou::
	.string "{JPN}ふしぎなできごと を ごりよう\n"
	.string "{JPN}いただき ありがとう ございます!\l"
	.string "{JPN}{PLAYER}さま ですね\p"
	.string "{JPN}あなたさま あてに\n"
	.string "{JPN}この チケットが\l"
	.string "{JPN}おくられて きました$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "{JPN}ミナモシティの ふなつきば で\n"
	.string "{JPN}つかえる ようですね\p"
	.string "{JPN}ぜひ ごりよう してみては\n"
	.string "{JPN}いかがでしょうか?$"
