	.align 2
gText_ConfirmSave::
	.string "{JPN}レポートを かきますか?$"

gText_AlreadySavedFile::
	.string "{JPN}まえの レポートに\n"
	.string "{JPN}うわがきしますが いいですか?$"

gText_SavingDontTurnOff::
	.string "{JPN}レポートを かいています...\n"
	.string "{JPN}でんげんを きらないでください.$"

gText_PlayerSavedGame::
	.string "{JPN}{PLAYER}は レポートを かいた.$"

gText_DifferentSaveFile::
	.string "{JPN}ちゅうい!\p"
	.string "{JPN}べつの セーブデータが\n"
	.string "{JPN}すでに あります.\p"
	.string "{JPN}いま セーブすると まえの\n"
	.string "{JPN}ぼうけんの きろくは\l"
	.string "{JPN}すべて きえてしまいます.\p"
	.string "{JPN}それでも セーブしますか?$"

gText_SaveError::
	.string "{JPN}セーブエラー.\p"
	.string "{JPN}バックアップメモリを\n"
	.string "{JPN}こうかんしてください.$"

gText_SavingDontTurnOffPower::
	.string "{JPN}レポートを かいています...\n"
	.string "{JPN}でんげんを きらないでください.$"
