SecretBase_Text_Trainer0Intro:
	.string "{JPN}きみは もう ひみつきちを つくったかい?\p"
	.string "{JPN}ぼくは あっち こっち まわって\n"
	.string "{JPN}やっと この ばしょに きめたんだ!\p"
	.string "{JPN}せっかく きたんだから\n"
	.string "{JPN}ポケモン しょうぶ しない?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "{JPN}それじゃ いくよ!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "{JPN}えっ いまは むりなんだ...$"

SecretBase_Text_Trainer0Defeated::
	.string "{JPN}うわっ きみって つよいなー\n"
	.string "{JPN}ぼくが まけたこと ひみつに してね!$"

SecretBase_Text_Trainer0PostBattle:
	.string "{JPN}ぼくの ひみつきち どうかなー\n"
	.string "{JPN}また あしたも あそびに きてね!$"

SecretBase_Text_Trainer0PreChampion:
	.string "{JPN}きみは もう ひみつきちを つくったかい?\p"
	.string "{JPN}ぼくは あっち こっち まわって\n"
	.string "{JPN}やっと この ばしょに きめたんだ!\p"
	.string "{JPN}ゆっくり して いってね!$"

SecretBase_Text_Trainer5Intro:
	.string "{JPN}ひみつきちを つくれる ばしょは\n"
	.string "{JPN}ほかにも たくさん あるけど\l"
	.string "{JPN}ここが いちばん きにいったの!\p"
	.string "{JPN}ねっ! すてきでしょ!\p"
	.string "{JPN}あっ もし よかったら\n"
	.string "{JPN}ポケモン しょうぶ しない?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "{JPN}それじゃ いくわよ!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "{JPN}そう いまは むりなのね...$"

SecretBase_Text_Trainer5Defeated::
	.string "{JPN}そう いまは むりなのね...$"

SecretBase_Text_Trainer5PostBattle:
	.string "{JPN}うーん わたしの まけね...\n"
	.string "{JPN}わたしが まけたのは ないしょの ひみつね!$"

SecretBase_Text_Trainer5PreChampion:
	.string "{JPN}このちかくに くることが あったら\n"
	.string "{JPN}また あそびに よってね!$"

SecretBase_Text_Trainer1Intro:
	.string "{JPN}ひみつきちを つくれる ばしょは\n"
	.string "{JPN}ほかにも たくさん あるけど\l"
	.string "{JPN}ここが いちばん きにいったの!\p"
	.string "{JPN}ねっ! すてきでしょ!$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "{JPN}この ばしょは にんきが あるから\n"
	.string "{JPN}いつも うまって いるんだー\p"
	.string "{JPN}あっ もしかして\n"
	.string "{JPN}きみも ここを つかいたい?\p"
	.string "{JPN}うーん ぼくに かてたら\n"
	.string "{JPN}このばしょ あげても いいよ!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "{JPN}よしっ! ぼくの きちを まもるぞー!$"

SecretBase_Text_Trainer1Defeated::
	.string "{JPN}えっ この ばしょに きょうみが ないの?\n"
	.string "{JPN}そっかー$"

SecretBase_Text_Trainer1PostBattle:
	.string "{JPN}もう ダメだ!\n"
	.string "{JPN}こうさーん!$"

SecretBase_Text_Trainer1PreChampion:
	.string "{JPN}よしっ ぼくが いつか ひっこしたら\n"
	.string "{JPN}この ばしょは きみの ものさ!$"

SecretBase_Text_Trainer6Intro:
	.string "{JPN}この ばしょは にんきが あるから\n"
	.string "{JPN}いつも うまって いるんだよー\p"
	.string "{JPN}ぼくは ずっと まっていて\n"
	.string "{JPN}やっと つかえる ように なったんだ!$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "{JPN}わたしの ポケモン けんきゅうじょへ\n"
	.string "{JPN}ようこそ!\p"
	.string "{JPN}ここで ポケモン しょうぶに ついて\n"
	.string "{JPN}こっそり べんきょう してるのよ\p"
	.string "{JPN}どう わたしの じつりょく みてみる?$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "{JPN}それじゃ また こんどね!$"

SecretBase_Text_Trainer6Defeated::
	.string "{JPN}ほんきで いくわよ!$"

SecretBase_Text_Trainer6PostBattle:
	.string "{JPN}それじゃ また こんどね!$"

SecretBase_Text_Trainer6PreChampion:
	.string "{JPN}うーん わたしも まだまだねー\n"
	.string "{JPN}もっと  べんきょう しないと!$"

SecretBase_Text_Trainer2Intro:
	.string "{JPN}しょうぶ してくれて どうも ありがとう!\n"
	.string "{JPN}また あしたも きてねー$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "{JPN}わたしの ポケモン けんきゅうじょへ\n"
	.string "{JPN}ようこそ!\p"
	.string "{JPN}ここで ポケモン しょうぶに ついて\n"
	.string "{JPN}こっそり べんきょう してるのよ$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "{JPN}おおきな いえも いいけど\n"
	.string "{JPN}ぼくは こういう ばしょが すきなんだ\p"
	.string "{JPN}だって いろいろな ひとが\n"
	.string "{JPN}あそびに きてくれる からねー!\p"
	.string "{JPN}どう ポケモン しょうぶでも するかい?$"

SecretBase_Text_Trainer2Defeated::
	.string "{JPN}そう こなくっちゃ!$"

SecretBase_Text_Trainer2PostBattle:
	.string "{JPN}よういが できたら\n"
	.string "{JPN}いつでも こえを かけてね!$"

SecretBase_Text_Trainer2PreChampion:
	.string "{JPN}やられたー!\n"
	.string "{JPN}だけど ポケモン しょうぶは たのしいー!$"

SecretBase_Text_Trainer7Intro:
	.string "{JPN}さてと グッズでも かいに いこうかな\p"
	.string "{JPN}ぼくの ひみつきちを\n"
	.string "{JPN}みんなに たのしんで ほしい からね!$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "{JPN}おおきな いえも いいけど\n"
	.string "{JPN}ぼくは こういう ばしょが すきなんだ\p"
	.string "{JPN}だって いろいろな ひとが\n"
	.string "{JPN}あそびに きてくれる からねー!$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "{JPN}そう それは ざんねん です...$"

SecretBase_Text_Trainer7Defeated::
	.string "{JPN}わたし グッズの おかいものが\n"
	.string "{JPN}だいすき です!\p"
	.string "{JPN}それと おなじくらい ポケモンを そだてるの\n"
	.string "{JPN}だいすき です!\p"
	.string "{JPN}もし よかったら わたしの ポケモンちゃんと\n"
	.string "{JPN}しょうぶして くれますか?$"

SecretBase_Text_Trainer7PostBattle:
	.string "{JPN}それでは おねがいします$"

SecretBase_Text_Trainer7PreChampion:
	.string "{JPN}そう それは ざんねん です...$"

SecretBase_Text_Trainer3Intro:
	.string "{JPN}まいりました...$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "{JPN}ああ たのしかった!\n"
	.string "{JPN}つぎは おかいものを たのしもう かしら$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "{JPN}わたし グッズの おかいものが\n"
	.string "{JPN}だいすき です\p"
	.string "{JPN}それと おなじくらい ポケモンを そだてるの\n"
	.string "{JPN}だいすき です$"

SecretBase_Text_Trainer3Defeated::
	.string "{JPN}みつかり にくい ばしょに\n"
	.string "{JPN}ひみつきちを つくる ひとが いるけど\l"
	.string "{JPN}こっそりと かくれて いたいのかなぁ...\p"
	.string "{JPN}うん せっかく みつけて くれたんだから\n"
	.string "{JPN}ポケモン しょうぶ しようか?$"

SecretBase_Text_Trainer3PostBattle:
	.string "{JPN}かんたんには おわらせ ないよ!$"

SecretBase_Text_Trainer3PreChampion:
	.string "{JPN}もしかして さがすのに つかれちゃった?$"

SecretBase_Text_Trainer8Intro:
	.string "{JPN}おわっちゃった...$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "{JPN}きみの ひみつきちは どこなんだい!\n"
	.string "{JPN}こんど あそびに いこうかなー$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "{JPN}みつかり にくい ばしょに\n"
	.string "{JPN}ひみつきちを つくる ひとが いるけど\l"
	.string "{JPN}こっそりと かくれて いたいのかなぁ$"

SecretBase_Text_Trainer8Defeated::
	.string "{JPN}グッズを てにいれる ほうほうは\n"
	.string "{JPN}いろいろ あるって はなしよ\p"
	.string "{JPN}どっちが すてきな グッズを\n"
	.string "{JPN}てにいれるか きょうそうね!\p"
	.string "{JPN}ついでに ポケモン しょうぶも しない?$"

SecretBase_Text_Trainer8PostBattle:
	.string "{JPN}じぶんの ひみつきちで まけられないわ!$"

SecretBase_Text_Trainer8PreChampion:
	.string "{JPN}いつでも しょうぶ まってるわ!$"

SecretBase_Text_Trainer4Intro:
	.string "{JPN}えっ もしかして わたしの まけ?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "{JPN}グッズあつめ まけないわよ!\n"
	.string "{JPN}また あそびに きてね!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "{JPN}グッズを てにいれる ほうほうは\n"
	.string "{JPN}いろいろ あるって はなしよ\p"
	.string "{JPN}どっちが すてきな グッズを\n"
	.string "{JPN}てにいれるか きょうそうね!$"

SecretBase_Text_Trainer4Defeated::
	.string "{JPN}すきな ばしょを さがして\n"
	.string "{JPN}すきな グッズを おく!\p"
	.string "{JPN}すきな ポケモンを そだてて\n"
	.string "{JPN}ぼくも いっしょに つよくなる\p"
	.string "{JPN}そんな ぼくと しょうぶ しよう!$"

SecretBase_Text_Trainer4PostBattle:
	.string "{JPN}きみの じつりょくを みせてくれ!$"

SecretBase_Text_Trainer4PreChampion:
	.string "{JPN}まぁ そんな ときも あるよね!$"

SecretBase_Text_Trainer9Intro:
	.string "{JPN}きみの じつりょくは じゅうぶん わかった!$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "{JPN}きみも ぼくも もっと つよく なれる!\n"
	.string "{JPN}おたがいに がんばろうね!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "{JPN}すきな ばしょを さがして\n"
	.string "{JPN}すきな ものを おく!\p"
	.string "{JPN}すきな ポケモンを そだてて\n"
	.string "{JPN}ぼくも いっしょに つよくなる\p"
	.string "{JPN}まいにち たのしいねー$"

SecretBase_Text_Trainer9Defeated::
	.string "{JPN}グッズの しゅるいや おきかたを みれば\n"
	.string "{JPN}そのひとが どんな センスの もちぬしか\l"
	.string "{JPN}よーく わかるわね!\p"
	.string "{JPN}わたしの センスは どうかしら?\n"
	.string "{JPN}うふふっ なにも いえないって かんじね!\p"
	.string "{JPN}しょうぶの センスも ためして みる?$"

SecretBase_Text_Trainer9PostBattle:
	.string "{JPN}おもいっきり いくわよ!$"

SecretBase_Text_Trainer9PreChampion:
	.string "{JPN}いつでも わたしの センスを みせるわよ!$"
