ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "{JPN}よかったら\n"
	.string "{JPN}あさせのしおと あさせのかいがらを\l"
	.string "{JPN}あつめてきて くれないか\p"
	.string "{JPN}ざいりょうが あつまったら\n"
	.string "{JPN}わたしが いいもの つくるんだがね$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "{JPN}あさせのしおと あさせのかいがら\n"
	.string "{JPN}それぞれ 4つ あれば\l"
	.string "{JPN}かいがらのすずが つくれるんだが...\p"
	.string "{JPN}かいがらのすずの ざいりょう なら\n"
	.string "{JPN}まいにち とれるよ$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "{JPN}お! あさせのしおと あさせのかいがら!\n"
	.string "{JPN}りょうも じゅうぶんだ!\p"
	.string "{JPN}これで かいがらのすず\n"
	.string "{JPN}つくっても いいかね?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "{JPN}かいがらのすず\n"
	.string "{JPN}さっそく つくらせて もらうよ\p"
	.string "... ... ...\n"
	.string "... ... ...\p"
	.string "{JPN}よし できたっ!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "{JPN}ポケモンに もたせてあげると よろこぶよ\p"
	.string "{JPN}なんたって かいがらのすずの ねいろは\n"
	.string "{JPN}てんか いっぴん だからね\p"
	.string "{JPN}かいがらのすずの ざいりょう なら\n"
	.string "{JPN}まいにち とれるから\l"
	.string "{JPN}そろえば また つくらせて もらうよ$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "{JPN}そうかね...\n"
	.string "{JPN}かいがらのすず つくりたかった...$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "{JPN}つくっても バッグが いっぱいで\n"
	.string "{JPN}もてない ようだね...\p"
	.string "{JPN}せいりして また くると いいよ$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "{JPN}あさせのしおを とった あと...\n"
	.string "{JPN}いまは なにも ない...$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "{JPN}あさせのかいがらを みつけた あと...\n"
	.string "{JPN}いまは なにも ない...$"
