Route102_Text_CalvinIntro:
	.string "{JPN}ポケモン つれていれば\n"
	.string "{JPN}キミも りっぱな ポケモントレーナー!\p"
	.string "{JPN}ボクの ちょうせん うけるよね!$"

Route102_Text_CalvinDefeated:
	.string "{JPN}ああ まけた……\n"
	.string "{JPN}もっと そだてておけば よかったよ$"

Route102_Text_CalvinPostBattle:
	.string "{JPN}キミ つよいなら つよいって\n"
	.string "{JPN}さいしょから いって くれよな!$"

Route102_Text_CalvinRegister:
	.string "{JPN}ボク あれから がんばってるよ!\n"
	.string "{JPN}こんど たたかいたい から\l"
	.string "{JPN}ポケナビ とうろく してよ!$"
	@ TODO: needs JP translation

Route102_Text_CalvinRegisterShort:
	.string "{JPN}こんど また たたかいたい から\n"
	.string "{JPN}ポケナビ とうろく してよ!$"
	@ TODO: needs JP translation

Route102_Text_CalvinRematchIntro:
	.string "{JPN}キミに まけてから ひっしに\n"
	.string "{JPN}ポケモン そだてたんだ! もちろん\p"
	.string "{JPN}ボクの ちょうせん うけるよね!$"

Route102_Text_CalvinRematchDefeated:
	.string "{JPN}ああ まけた……\n"
	.string "{JPN}そだてかた わるいのかな$"

Route102_Text_CalvinRematchPostBattle:
	.string "{JPN}キミが つよくなるなら\n"
	.string "{JPN}ボクも もっと つよくなって みせるよ!$"

Route102_Text_AllenIntro:
	.string "{JPN}きみ トレーナーに なったばかり?\n"
	.string "{JPN}おたがい しょしんしゃ だね!$"

Route102_Text_AllenDefeated:
	.string "{JPN}かてると おもったから\n"
	.string "{JPN}こえを かけたのに!$"

Route102_Text_AllenPostBattle:
	.string "{JPN}まだ 1かいも かってない……\n"
	.string "{JPN}はやく かちたいなあ……$"

Route102_Text_RickIntro:
	.string "{JPN}おっと! めが あったな!\n"
	.string "{JPN}むしポケモンで あいてを するぜ!$"

Route102_Text_RickDefeated:
	.string "{JPN}まけてしまった!$"

Route102_Text_RickPostBattle:
	.string "{JPN}めが あった トレーナーには\n"
	.string "{JPN}しょうぶを いどむのが きまりさ!$"

Route102_Text_TianaIntro:
	.string "{JPN}わたしは どんどん かちぬいて\n"
	.string "{JPN}さいきょうの トレーナーを めざすのよ!\l"
	.string "{JPN}あなたも きょうりょく してね!$"

Route102_Text_TianaDefeated:
	.string "{JPN}わたしが あなたに\n"
	.string "{JPN}きょうりょく しちゃった みたいね……$"

Route102_Text_TianaPostBattle:
	.string "{JPN}どんどん かちぬくには\n"
	.string "{JPN}もっと たくさん ポケモンを\p"
	.string "{JPN}つかまえないと いけない みたいね!$"

Route103_Text_DaisyIntro:
	.string "{JPN}こころ やすらぐ かおりに\n"
	.string "{JPN}あなたも さそわれたのですね……$"

Route103_Text_DaisyDefeated:
	.string "{JPN}わたくしの かおりに\n"
	.string "{JPN}まどわされませんでしたね……$"

Route103_Text_DaisyPostBattle:
	.string "{JPN}アロマとは かおりのこと……\n"
	.string "{JPN}かおりは こころと からだを いやすのです$"

Route103_Text_AmyIntro:
	.string "{JPN}クミ: あたしは クミ!\n"
	.string "{JPN}こっちは いもうとの ルミ!\p"
	.string "{JPN}ふたりで いっしょに たたかうのよ!$"

Route103_Text_AmyDefeated:
	.string "{JPN}クミ: まけっちゃったよぉ……$"

Route103_Text_AmyPostBattle:
	.string "{JPN}クミ: ふたりを あいてに するのって\n"
	.string "{JPN}いろんな ことを かんがえるよね!$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{JPN}クミ”あら?\n"
	.string "{JPN}ポケモン 1ひきしか つれてないんだね!\l"
	.string "{JPN}それじゃあ あたしたちと たたかえないわ!$"
	@ TODO: needs JP translation

Route103_Text_LivIntro:
	.string "{JPN}ルミ: あたしたちは ふたりで ひとり\n"
	.string "{JPN}いっしょに たたかうんだよ!$"

Route103_Text_LivDefeated:
	.string "{JPN}ルミ: まけちゃったよぉ おねえちゃぁん……$"

Route103_Text_LivPostBattle:
	.string "{JPN}ルミ: おねえちゃんと あたしは\n"
	.string "{JPN}いきが ぴったり あってるのに……\l"
	.string "{JPN}まけちゃったよぉ……$"

Route103_Text_AmyLivRegister:
	.string "{JPN}ルミ”あたしたち ほんとは\n"
	.string "{JPN}もっと つよいんだもん...\l"
	.string "{JPN}ほんとうだから! こんど みせるから!$"
	@ TODO: needs JP translation

Route103_Text_LivNotEnoughPokemon:
	.string "{JPN}ルミ”あたしたちと たたかいたいなら\n"
	.string "{JPN}ポケモンを 2ひき つれてないと ダメよ!\l"
	.string "{JPN}じゃないと しょうぶに ならないんだから!$"
	@ TODO: needs JP translation

Route103_Text_AmyRematchIntro:
	.string "{JPN}クミ: あたしは クミ!\n"
	.string "{JPN}こっちは いもうとの ルミ!\p"
	.string "{JPN}ふたりで いっしょに たたかうのよ!$"

Route103_Text_AmyRematchDefeated:
	.string "{JPN}クミ: くやしい……\n"
	.string "{JPN}また かてなかったよぉ……$"

Route103_Text_AmyRematchPostBattle:
	.string "{JPN}クミ: ふたりを あいてに するのって\n"
	.string "{JPN}いろんな ことを かんがえるよね!$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{JPN}クミ”あら?\n"
	.string "{JPN}ポケモン 1ひきしか つれてないんだね!\l"
	.string "{JPN}それじゃあ あたしたちと たたかえないわ!$"
	@ TODO: needs JP translation

Route103_Text_LivRematchIntro:
	.string "{JPN}ルミ: あたしたちは ふたりで ひとり\n"
	.string "{JPN}いつも いっしょに たたかうんだよ!$"

Route103_Text_LivRematchDefeated:
	.string "{JPN}ルミ: また まけちゃったよぉ\n"
	.string "{JPN}おねえちゃぁん……$"

Route103_Text_LivRematchPostBattle:
	.string "{JPN}ルミ: おねえちゃんと あたしは\n"
	.string "{JPN}いきが ぴったり あってるのに……\l"
	.string "{JPN}どうして また まけちゃったの?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{JPN}ルミ”あたしたちと たたかいたいなら\n"
	.string "{JPN}ポケモンを 2ひき つれてないと ダメよ!\l"
	.string "{JPN}じゃないと しょうぶに ならないんだから!$"
	@ TODO: needs JP translation

Route103_Text_AndrewIntro:
	.string "{JPN}つりいとが からまって イライラするーっ!\n"
	.string "{JPN}ええいっ しょうぶだっ!$"

Route103_Text_AndrewDefeated:
	.string "{JPN}まけたっ!\n"
	.string "{JPN}よけいに イライラするぞーっ!$"

Route103_Text_AndrewPostBattle:
	.string "{JPN}ええい はらだたしい……!\n"
	.string "{JPN}イライライライラ……$"

Route103_Text_MiguelIntro:
	.string "{JPN}わたしの ポケモンちゃん\n"
	.string "{JPN}すごく かわいいから みていきたまえ!$"

Route103_Text_MiguelDefeated:
	.string "{JPN}あわわ……\n"
	.string "{JPN}わたしの ポケモンちゃん!$"

Route103_Text_MiguelPostBattle:
	.string "{JPN}かわいい ポケモンちゃんは\n"
	.string "{JPN}やられた すがたも かわいいな……$"

Route103_Text_MiguelRegister:
	.string "{JPN}なんどでも かわいい ポケモンちゃんを\n"
	.string "{JPN}みにきて もらうんだからね!$"
	@ TODO: needs JP translation

Route103_Text_MiguelRematchIntro:
	.string "{JPN}きみ! わたしの ポケモンちゃん\n"
	.string "{JPN}さらに かわいく なったのだ!$"

Route103_Text_MiguelRematchDefeated:
	.string "{JPN}ああ!\n"
	.string "{JPN}わたしの ポケモンちゃん!$"

Route103_Text_MiguelRematchPostBattle:
	.string "{JPN}いっしょに いれば いるほど\n"
	.string "{JPN}ポケモンが かわいくなって たまらん!$"

Route103_Text_PeteIntro:
	.string "{JPN}この くらいの きょり\n"
	.string "{JPN}およいで わたれば いーのにさ!$"

Route103_Text_PeteDefeated:
	.string "{JPN}おお やるじゃん$"

Route103_Text_PetePostBattle:
	.string "{JPN}なーるほど\l"
	.string "{JPN}それ ほど たよれる ポケモンなら\n"
	.string "{JPN}おもわず なみのり したくなる ってもんだ$"

Route103_Text_IsabelleIntro:
	.string "{JPN}きゃあ ぶつかるわ!\n"
	.string "{JPN}あぶないっ!$"

Route103_Text_IsabelleDefeated:
	.string "{JPN}んん……$"

Route103_Text_IsabellePostBattle:
	.string "{JPN}わたし およぎが へたで\n"
	.string "{JPN}れんしゅう してたのよ……\p"
	.string "{JPN}ぶつかりそうに なって ゴメンね$"

Route103_Text_RhettIntro:
	.string "{JPN}うぉっ!\n"
	.string "{JPN}なぜ こんな せまいところに!?$"

Route103_Text_RhettDefeated:
	.string "{JPN}うぉっ できる!$"

Route103_Text_RhettPostBattle:
	.string "{JPN}せまい ところが\n"
	.string "{JPN}すき なのかい きみは?$"

Route103_Text_MarcosIntro:
	.string "{JPN}おれっちの ギターに さそわれて\n"
	.string "{JPN}やって きたのかーい?$"

Route103_Text_MarcosDefeated:
	.string "{JPN}おれっちの ひとりショーが だいなしだよ$"

Route103_Text_MarcosPostBattle:
	.string "{JPN}ひとの すくない ところで\n"
	.string "{JPN}ギターを ひいていたのに\p"
	.string "{JPN}こんなにも あつまって きたぜ!\l"
	.string "{JPN}ぷ プロを めざして みるか!$"

Route104_Text_GinaIntro:
	.string "{JPN}ナオ: よーし!\n"
	.string "{JPN}あたしたちの ポケモンと たたかうです!$"

Route104_Text_GinaDefeat:
	.string "{JPN}ナオ: まけて すごく くやしいです$"

Route104_Text_GinaPostBattle:
	.string "{JPN}ナオ: うわー {STR_VAR_1} つよいです!\n"
	.string "{JPN}あたしたち もっと しゅぎょう するです$"

Route104_Text_GinaNotEnoughMons:
	.string "{JPN}ナオ”あら? ポケモン 1ひき だけですか!\n"
	.string "{JPN}じゃあ あたしたち たたかわない です!\p"
	.string "{JPN}だって ポケモン 1ひき だけだと\n"
	.string "{JPN}ポケモンが さびしそうで かわいそう です!$"
	@ TODO: needs JP translation

Route104_Text_MiaIntro:
	.string "{JPN}ミオ: あたしたち ふたご だから\n"
	.string "{JPN}ポケモンしょうぶも いっしょに するです!$"

Route104_Text_MiaDefeat:
	.string "{JPN}ミオ: ふたりで しょうぶ したのに\n"
	.string "{JPN}まけちゃったです……$"

Route104_Text_MiaPostBattle:
	.string "{JPN}ミオ: もっと ポケモン そだてて\n"
	.string "{JPN}{STR_VAR_1} みたいに つよく なるです!$"

Route104_Text_MiaNotEnoughMons:
	.string "{JPN}ミオ”あたしたちと たたかうですか?\p"
	.string "{JPN}じゃあ ポケモンを\n"
	.string "{JPN}2ひき つれてないと ダメですよ!\l"
	.string "{JPN}だって あたしたち つよいもん!$"
	@ TODO: needs JP translation

Route104_Text_IvanIntro:
	.string "{JPN}みずポケモンの エキスパートとは\n"
	.string "{JPN}なにを かくそう オレのこと!\l"
	.string "{JPN}……え?\n"
	.string "{JPN}しらないの?$"

Route104_Text_IvanDefeat:
	.string "{JPN}けっこう つよいと おもってたんだけどな\n"
	.string "{JPN}じぶんのこと…… がっかり……$"

Route104_Text_IvanPostBattle:
	.string "{JPN}つりに むちゅうに なってて\n"
	.string "{JPN}ポケモン そだてるのを わすれてたよ……$"

Route104_Text_BillyIntro:
	.string "{JPN}すなはまに あしあと つけるのって\n"
	.string "{JPN}たのしーよねー!$"

Route104_Text_BillyDefeat:
	.string "{JPN}うへーっ!\n"
	.string "{JPN}クツに すなが はいって ジャリジャリする!$"

Route104_Text_BillyPostBattle:
	.string "{JPN}すなはまを ボクの あしあとで\n"
	.string "{JPN}いっぱいに したいんだけど\p"
	.string "{JPN}すぐに きえちゃうんだよなぁ$"

Route104_Text_HaleyIntro:
	.string "{JPN}しょうぶ しようかな……\n"
	.string "{JPN}やめとこうかな……\l"
	.string "{JPN}えーい! たたかっちゃえ!$"

Route104_Text_HaleyDefeat:
	.string "{JPN}たたかわなければ よかったかな……$"

Route104_Text_HaleyPostBattle:
	.string "{JPN}どっちに しようか まよってる とき\n"
	.string "{JPN}じぶんで きめないで たにんに まかせると\p"
	.string "{JPN}どっちに なっても こうかいするね……$"

Route104_Text_HaleyRegister1:
	.string "{JPN}あなた つよいけど\n"
	.string "{JPN}ポケナビに とうろく しようかな...\l"
	.string "{JPN}やめとこうかな...\p"
	.string "{JPN}えーい! とうろくしちゃえ!$"
	@ TODO: needs JP translation

Route104_Text_HaleyRegister2:
	.string "{JPN}あなた つよいけど\n"
	.string "{JPN}ポケナビに とうろく しようかな...\l"
	.string "{JPN}やめとこうかな...\p"
	.string "{JPN}えーい! とうろくしちゃえ!$"
	@ TODO: needs JP translation

Route104_Text_HaleyRematchIntro:
	.string "{JPN}あたしと しょうぶ してもらうわよ!$"

Route104_Text_HaleyRematchDefeat:
	.string "{JPN}うーん……\n"
	.string "{JPN}かてると おもったのにな$"

Route104_Text_HaleyPostRematch:
	.string "{JPN}たたかうって じぶんで きめたから\n"
	.string "{JPN}まけても すっきり してるわ!\l"
	.string "{JPN}……もちろん まけて くやしいけどね$"

Route104_Text_WinstonIntro:
	.string "{JPN}ボクが あいてして あげるよ\n"
	.string "{JPN}この おかねもちの ボクがね$"

Route104_Text_WinstonDefeat:
	.string "{JPN}どうして かてないんだ……!?$"

Route104_Text_WinstonPostBattle:
	.string "{JPN}おかねじゃ かてない ものが ある……\n"
	.string "{JPN}それが ポケモンなんだね……$"

Route104_Text_WinstonRegister1:
	.string "{JPN}ん? きみ ポケナビを てにいれたね!\p"
	.string "{JPN}ボクが とうろくして あげよう\n"
	.string "{JPN}この おかねもちの ボクがね$"
	@ TODO: needs JP translation

Route104_Text_WinstonRegister2:
	.string "{JPN}ん? きみ ポケナビを てにいれたね!\p"
	.string "{JPN}ボクが とうろくして あげよう\n"
	.string "{JPN}この おかねもちの ボクがね$"
	@ TODO: needs JP translation

Route104_Text_WinstonRematchIntro:
	.string "{JPN}きみに まけてから いろいろ\n"
	.string "{JPN}ポケモンのこと べんきょう したんだ!$"

Route104_Text_WinstonRematchDefeat:
	.string "{JPN}また まけた……\n"
	.string "{JPN}どうして かてないんだ……!?$"

Route104_Text_WinstonPostRematch:
	.string "{JPN}おかねもちの ボク なのに\n"
	.string "{JPN}なかなか ポケモンに かてない……\l"
	.string "{JPN}なんて おくが ふかいんだろう\n"
	.string "{JPN}ポケモンって……$"

Route104_Text_CindyIntro:
	.string "{JPN}あなたと であったのも なにかの ごえん\n"
	.string "{JPN}おてあわせを おねがい できるかしら$"

Route104_Text_CindyDefeat:
	.string "{JPN}まあ!$"

Route104_Text_CindyPostBattle:
	.string "{JPN}であいは わかれの はじまり……\n"
	.string "{JPN}また どこかで おあいしましょう$"

Route104_Text_CindyRegister1:
	.string "{JPN}あら... また おあい しましたわね\p"
	.string "{JPN}こんなに ごえんが あるんですもの\n"
	.string "{JPN}ポケナビに とうろく して くださいませ$"
	@ TODO: needs JP translation

Route104_Text_CindyRegister2:
	.string "{JPN}この ごえんを きねんして\n"
	.string "{JPN}ポケナビに とうろく して くださいませ$"
	@ TODO: needs JP translation

Route104_Text_CindyRematchIntro:
	.string "{JPN}また おあい しましたわね\n"
	.string "{JPN}おてあわせ おねがい できるかしら$"

Route104_Text_CindyRematchDefeat:
	.string "{JPN}あら……\n"
	.string "{JPN}わたくし ベストを つくしましたのに……$"

Route104_Text_CindyPostRematch:
	.string "{JPN}であいは わかれの はじまり……\n"
	.string "{JPN}また どこかで おあいしましょう$"

Route104_Text_DarianIntro:
	.string "{JPN}つよそうな ポケモンが つれたっ!\n"
	.string "{JPN}さかなの おうさま って かんじだ!\p"
	.string "{JPN}これは つよそうだぞっ!$"

Route104_Text_DarianDefeat:
	.string "{JPN}なっにい$"

Route104_Text_DarianPostBattle:
	.string "{JPN}おい なまえ まけ してるじゃないか\n"
	.string "{JPN}おれの コイキングよ!$"

Route105_Text_FosterIntro:
	.string "{JPN}この あたりに\n"
	.string "{JPN}ふしぎな いわが あるらしいが\p"
	.string "{JPN}きみ しらないかい?$"

Route105_Text_FosterDefeated:
	.string "{JPN}いわのこと ばかり かんがえて\n"
	.string "{JPN}ポケモン よわいまま だったか……$"

Route105_Text_FosterPostBattle:
	.string "{JPN}すてきな いわ だったら\n"
	.string "{JPN}なんじかん みていても あきないよ……$"

Route105_Text_LuisIntro:
	.string "{JPN}よかった! こどもが\n"
	.string "{JPN}おぼれているのかと しんぱい したよ!\l"
	.string "{JPN}だいじょうぶ そうだから しょうぶ だな!$"

Route105_Text_LuisDefeated:
	.string "{JPN}ゴボゴボ……$"

Route105_Text_LuisPostBattle:
	.string "{JPN}すなはまに むかって かたてを ふるのが\n"
	.string "{JPN}おぼれたときの サインだぜ!$"

Route105_Text_DominikIntro:
	.string "{JPN}あおい うみで およいでいると\n"
	.string "{JPN}さいこうの きぶん だな!$"

Route105_Text_DominikDefeated:
	.string "{JPN}まけた……\n"
	.string "{JPN}ブルーな きぶん……$"

Route105_Text_DominikPostBattle:
	.string "{JPN}うみが あおい りゆう!?\l"
	.string "{JPN}カイナの はくぶつかんで きいたけど\n"
	.string "{JPN}そんなの わすれちまったよ!$"

Route105_Text_BeverlyIntro:
	.string "{JPN}みずに はいると からだが かるくなるわね\n"
	.string "{JPN}なんだか スリムに なったみたい!$"

Route105_Text_BeverlyDefeated:
	.string "{JPN}ぷかぷか……$"

Route105_Text_PostBattle:
	.string "{JPN}みずの なかでは たいじゅうが\n"
	.string "{JPN}10ぶんの1 くらいに なるのよ\l"
	.string "{JPN}と すると いま わたしは……\n"
	.string "{JPN}いけない! たいじゅうが バレちゃうわ!$"

Route105_Text_ImaniIntro:
	.string "{JPN}あおい そら……\n"
	.string "{JPN}ひろい うみ……\p"
	.string "{JPN}のどか よねー……$"

Route105_Text_ImaniDefeated:
	.string "{JPN}なごんでいる うちに\n"
	.string "{JPN}まけちゃったわーっ!$"

Route105_Text_ImaniPostBattle:
	.string "{JPN}あたしと いると なごむって いわれたいの\n"
	.string "{JPN}うふふふふ!$"

Route105_Text_AndresIntro:
	.string "{JPN}うみに こそ なにかが あると\n"
	.string "{JPN}かくしんが ある!$"

Route105_Text_AndresDefeated:
	.string "{JPN}うん…… わし\n"
	.string "{JPN}しょうぶは よわいんだよ$"

Route105_Text_AndresPostBattle:
	.string "{JPN}せかいじゅうの うみには\n"
	.string "{JPN}まだまだ ひみつが あるはずだ!\p"
	.string "{JPN}ぜんぶ さがしまくるぞ!$"

Route105_Text_AndresRegister:
	.string "{JPN}ん? こんな よわい わしでも\n"
	.string "{JPN}ポケナビ とうろくして くれるのか?$"
	@ TODO: needs JP translation

Route105_Text_AndresRematchIntro:
	.string "{JPN}しょうぶは よわいと いっているのに……\n"
	.string "{JPN}わし なんかで いいのか?$"

Route105_Text_AndresRematchDefeated:
	.string "{JPN}うん…… やっぱり かてないな$"

Route105_Text_AndresRematchPostBattle:
	.string "{JPN}しょうぶは よわいが\n"
	.string "{JPN}たんきゅうしんは きみにも まけん!\p"
	.string "{JPN}せかいじゅうの うみを たび するぞ!$"

Route105_Text_JosueIntro:
	.string "{JPN}なれない およぎで つかれたー\n"
	.string "{JPN}きばらしに ポケモンしょうぶ じゃい!$"

Route105_Text_JosueDefeated:
	.string "{JPN}うみで たたかった から まけたんだ$"

Route105_Text_JosuePostBattle:
	.string "{JPN}やっぱりさ おれには\n"
	.string "{JPN}うみより そらが にあってるんだよ$"

Route106_Text_ElliotIntro:
	.string "{JPN}うみづりと かわづり\n"
	.string "{JPN}キミは どっちが すき?$"

Route106_Text_ElliotDefeated:
	.string "{JPN}まるで うみづりの ように\n"
	.string "{JPN}ごうかいに まけたぞーっ!$"

Route106_Text_ElliotPostBattle:
	.string "{JPN}うみでも かわでも つりは サイコーだ!\n"
	.string "{JPN}キミも そう おもうだろ!?$"

Route106_Text_ElliotRegister:
	.string "{JPN}つりも いいけど しょうぶも いいな!\n"
	.string "{JPN}キミ よかったら また たのむよ!$"
	@ TODO: needs JP translation

Route106_Text_ElliotRematchIntro:
	.string "{JPN}ポケモン つりまくったからね\n"
	.string "{JPN}すごい しょうぶを してみせるぞー!$"

Route106_Text_ElliotRematchDefeated:
	.string "{JPN}また ごうかいに まけたぞーっ!$"

Route106_Text_ElliotRematchPostBattle:
	.string "{JPN}かっても まけても ポケモンは サイコーだ!\n"
	.string "{JPN}キミも そう おもうだろ!?$"

Route106_Text_NedIntro:
	.string "{JPN}トイレに いきたくなったとき\n"
	.string "{JPN}みんなは どうしてるんだろう……?\l"
	.string "{JPN}トイレに いっている あいだに\n"
	.string "{JPN}もし おおものが かかったらと おもうと……$"

Route106_Text_NedDefeated:
	.string "{JPN}トイレを がまん してたから\n"
	.string "{JPN}まけたんだよ きっと……$"

Route106_Text_NedPostBattle:
	.string "{JPN}ああっ!\n"
	.string "{JPN}おおものが つれそうな よかん……!$"

Route106_Text_DouglasIntro:
	.string "{JPN}はっはっはっ!\n"
	.string "{JPN}りくでは はやく はしれないが\p"
	.string "{JPN}みずの なかなら まけないぞ!$"

Route106_Text_DouglasDefeated:
	.string "{JPN}まいりましたーっ!$"

Route106_Text_DouglasPostBattle:
	.string "{JPN}すいえいの きょうそうなら まけないのに……$"

Route106_Text_KylaIntro:
	.string "{JPN}うみは わたしの にわ\n"
	.string "{JPN}こども だからって てかげん しないわよ!$"

Route106_Text_KylaDefeated:
	.string "{JPN}ひょっとして\n"
	.string "{JPN}てかげん してないよね?$"

Route106_Text_KylaPostBattle:
	.string "{JPN}なみに ゆられて ただようのが だいすき\n"
	.string "{JPN}あなたも やってみない?$"

Route107_Text_DarrinIntro:
	.string "{JPN}むにゃむにゃ……\l"
	.string "{JPN}なみに ゆられてたら きもちよくなって\n"
	.string "{JPN}うっかり ねてしまった!$"

Route107_Text_DarrinDefeated:
	.string "{JPN}あはは まけた……\n"
	.string "{JPN}また ねますか……$"

Route107_Text_DarrinPostBattle:
	.string "{JPN}うみに うかんで なみに ゆられてると\n"
	.string "{JPN}ふかふかの ベッドで ねてる みたいだよ!$"

Route107_Text_TonyIntro:
	.string "{JPN}うみは オレの にわ みたいな もの!\n"
	.string "{JPN}しょうぶ しようぜ!$"

Route107_Text_TonyDefeated:
	.string "{JPN}ホームグラウンドで まけた……\n"
	.string "{JPN}ショック!$"

Route107_Text_TonyPostBattle:
	.string "{JPN}おおきな ユメを いっぱい つめてー\n"
	.string "{JPN}でっかい うみを ひとおよぎー\l"
	.string "{JPN}さぁて まだまだ およぐぞー!$"

Route107_Text_TonyRegister:
	.string "{JPN}ショックを うけたオレを\n"
	.string "{JPN}きみが わすれない ために...!$"
	@ TODO: needs JP translation

Route107_Text_TonyRematchIntro:
	.string "{JPN}でっかい うみを およいでいたら\n"
	.string "{JPN}ポケモンが すっごく つよくなったぞー!$"

Route107_Text_TonyRematchDefeated:
	.string "{JPN}ショック!!\l"
	.string "{JPN}ポケモンは つよくなったが\n"
	.string "{JPN}トレーナーの おれが よわいまま!?$"

Route107_Text_TonyRematchPostBattle:
	.string "{JPN}たたかいの なかで おぼえたことが\n"
	.string "{JPN}トレーナーとしての つよさに つながる!\p"
	.string "{JPN}でっかい うみが そう いっていたぞー!$"

Route107_Text_DeniseIntro:
	.string "{JPN}ムロタウン っていう\n"
	.string "{JPN}ちいさな まちを しってる?$"

Route107_Text_DeniseDefeated:
	.string "{JPN}ヤダ もーっ!$"

Route107_Text_DenisePostBattle:
	.string "{JPN}ムロタウンの しゅうかいじょで\n"
	.string "{JPN}ふしぎな ことばが はやって いるのよ!$"

Route107_Text_BethIntro:
	.string "{JPN}わたしと しょうぶが したいの?\n"
	.string "{JPN}いいわ! あいてに なって あげる!$"

Route107_Text_BethDefeated:
	.string "{JPN}わたしじゃ あいてに ならなかったわ!$"

Route107_Text_BethPostBattle:
	.string "{JPN}あなた まだまだ つよく なりそうね\n"
	.string "{JPN}わたしも がんばろうっと!$"

Route107_Text_LisaIntro:
	.string "{JPN}ユミ: あたしたち きょうだい ふたりで\n"
	.string "{JPN}しょうぶを させてもらうわ!$"

Route107_Text_LisaDefeated:
	.string "{JPN}ユミ: すごいわ\n"
	.string "{JPN}つよさの レベルが ちがうのね$"

Route107_Text_LisaPostBattle:
	.string "{JPN}ユミ: あなたは いっしょに\n"
	.string "{JPN}うみに あそびに いくような\p"
	.string "{JPN}おともだち いるのかしら?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{JPN}ユミ”アタシたちと たたかうなら\n"
	.string "{JPN}ポケモン もっと つれてきなさいな$"
	@ TODO: needs JP translation

Route107_Text_RayIntro:
	.string "{JPN}シン: いつも きょうだいで\n"
	.string "{JPN}ポケモンしょうぶ してるんだ!\l"
	.string "{JPN}……いっつも おれが まけるけど\n"
	.string "{JPN}2たい2なら きみに かてるよ!$"

Route107_Text_RayDefeated:
	.string "{JPN}シン: ひゃー\n"
	.string "{JPN}つよさの レベルが ちがいすぎるや$"

Route107_Text_RayPostBattle:
	.string "{JPN}シン: おれの ポケモン\n"
	.string "{JPN}ねえちゃんから もらって そだてた\p"
	.string "{JPN}だいじな あいぼう なんだぜ!$"

Route107_Text_RayNotEnoughPokemon:
	.string "{JPN}シン”オレらと たたかうなら\n"
	.string "{JPN}もっと ポケモン つれてきてよ!$"
	@ TODO: needs JP translation

Route107_Text_CamronIntro:
	.string "{JPN}トライアスロンの とちゅう だが\n"
	.string "{JPN}ぜんぜん つかれて いないぜ!$"

Route107_Text_CamronDefeated:
	.string "{JPN}いまので つかれて しまった$"

Route107_Text_CamronPostBattle:
	.string "{JPN}こ このあと まだ\n"
	.string "{JPN}すいえい ランニングが のこっているぜ\p"
	.string "{JPN}だいじょうぶか おれ……?$"

Route108_Text_JeromeIntro:
	.string "{JPN}オレの ユメは せかいに ある\n"
	.string "{JPN}7つのうみ すべてで およぐこと!$"

Route108_Text_JeromeDefeated:
	.string "{JPN}これじゃ\n"
	.string "{JPN}7つのうみ すべてで およげない……$"

Route108_Text_JeromePostBattle:
	.string "{JPN}うみの ポケモンと あそぶことも\n"
	.string "{JPN}およいでいる ときの たのしみだね!$"

Route108_Text_MatthewIntro:
	.string "{JPN}なあ キミ!\n"
	.string "{JPN}キミも すてられた ふねに いくのかい?$"

Route108_Text_MatthewDefeated:
	.string "{JPN}ああ ぼくが しずむ……\n"
	.string "{JPN}ぶくぶく……$"

Route108_Text_MatthewPostBattle:
	.string "{JPN}すてられぶねの なかに\n"
	.string "{JPN}はいっていく やつらが いるんだよ!$"

Route108_Text_TaraIntro:
	.string "{JPN}ウソつきな カレに いわれたのよ\n"
	.string "{JPN}ビキニが にあってて カワイイって……$"

Route108_Text_TaraDefeated:
	.string "{JPN}いやん まけたわーっ!$"

Route108_Text_TaraPostBattle:
	.string "{JPN}ウソでも いいから カワイイって いわれたい\n"
	.string "{JPN}ふくざつな おんなごころ……$"

Route108_Text_MissyIntro:
	.string "{JPN}うみって だいすき!\n"
	.string "{JPN}およいでいれば イヤなことも わすれるわ!$"

Route108_Text_MissyDefeated:
	.string "{JPN}しょうぶに まけると\n"
	.string "{JPN}ストレスが たまるーっ!$"

Route108_Text_MissyPostBattle:
	.string "{JPN}ストレスは およいで はっさん!\n"
	.string "{JPN}けんこうてき よねー!$"

Route108_Text_CoryIntro:
	.string "{JPN}みずポケモンが だいすきだー!\n"
	.string "{JPN}ほかの ポケモンも だいすきだー!$"

Route108_Text_CoryDefeated:
	.string "{JPN}わー まけたー!\n"
	.string "{JPN}わーわー!$"

Route108_Text_CoryPostBattle:
	.string "{JPN}おおごえで さけべば\n"
	.string "{JPN}スッキリ するなあーっ!$"

Route108_Text_CoryRegister:
	.string "{JPN}つよい トレーナーも だいすきだー!\n"
	.string "{JPN}ポケナビの とうろくを してくれー!$"
	@ TODO: needs JP translation

Route108_Text_CoryRematchIntro:
	.string "{JPN}かっても まけても\n"
	.string "{JPN}うみ での しょうぶが だいすきだー!$"

Route108_Text_CoryRematchDefeated:
	.string "{JPN}わーっ また まけた!\n"
	.string "{JPN}わー わー!$"

Route108_Text_CoryRematchPostBattle:
	.string "{JPN}きみも いきづまった ときは\n"
	.string "{JPN}なにかを うみに むかって さけべーっ!$"

Route108_Text_CarolinaIntro:
	.string "{JPN}じまんの ポケモンたちで\n"
	.string "{JPN}スピーディに たたかうわよ!$"

Route108_Text_CarolinaDefeated:
	.string "{JPN}あら かわいくないわね!$"

Route108_Text_CarolinaPostBattle:
	.string "{JPN}せっかくの うみ だし\n"
	.string "{JPN}ピンクの フリフリの ビキニも\p"
	.string "{JPN}ちょっと きてみたい……$"

Route109_Text_DavidIntro:
	.string "{JPN}うりゃーっ!!\n"
	.string "{JPN}みごとに われた ふっきんを みろーっ!!$"

Route109_Text_DavidDefeated:
	.string "{JPN}うりゃーっ!!\n"
	.string "{JPN}まけたーっ!!$"

Route109_Text_DavidPostBattle:
	.string "{JPN}うりゃーっ!!\l"
	.string "{JPN}ふっきんと ポケモンの しょうぶは\n"
	.string "{JPN}かんけい ないぞーっ!!$"

Route109_Text_AliceIntro:
	.string "{JPN}ひやけ たいさく\n"
	.string "{JPN}あなたは してる?$"

Route109_Text_AliceDefeated:
	.string "{JPN}あちちちちっ!$"

Route109_Text_AlicePostBattle:
	.string "{JPN}ほっぺの あたりが いちばん\n"
	.string "{JPN}ひやけ しやすい ばしょ なのよ!$"

Route109_Text_HueyIntro:
	.string "{JPN}せかいじゅうの みなとを おとずれたが\n"
	.string "{JPN}カイナは さいこーの みなとまち だぜ!$"

Route109_Text_HueyDefeated:
	.string "{JPN}あんた さいこー だぜ……$"

Route109_Text_HueyPostBattle:
	.string "{JPN}さいこーの みなとまちには\n"
	.string "{JPN}さいこーの トレーナーが いたぜ……$"

Route109_Text_EdmondIntro:
	.string "{JPN}ううう……\n"
	.string "{JPN}しょうぶ するの? オレと?$"

Route109_Text_EdmondDefeated:
	.string "{JPN}げろげろ……$"

Route109_Text_EdmondPostBattle:
	.string "{JPN}いつもは もっと つよいんだぞ!\n"
	.string "{JPN}ふなよいで ちょうしが わるいだけだ!\l"
	.string "{JPN}ふなのり だけど……$"

Route109_Text_RickyIntro:
	.string "{JPN}のどが かわいたよ……\n"
	.string "{JPN}うみのいえで サイコソーダ のみたいな……$"

Route109_Text_RickyDefeated:
	.string "{JPN}うーん……$"

Route109_Text_RickyPostBattle:
	.string "{JPN}おなかも へってきた……\n"
	.string "{JPN}うきわが おっきな ドーナッツに みえるよ$"

Route109_Text_RickyRegister:
	.string "{JPN}こんど のどが かわいて ないときに\n"
	.string "{JPN}もういっかい しょうぶ してくれる?$"
	@ TODO: needs JP translation

Route109_Text_RickyRematchIntro:
	.string "{JPN}おなか へってるけど\n"
	.string "{JPN}しょうぶ するなら げんき だよ!$"

Route109_Text_RickyRematchDefeated:
	.string "{JPN}まけた……\n"
	.string "{JPN}おなかが へってるからだ$"

Route109_Text_RickyRematchPostBattle:
	.string "{JPN}すなはまで たべると\n"
	.string "{JPN}なんでも おいしく おもえるよね$"

Route109_Text_LolaIntro:
	.string "{JPN}ビーチパラソルって\n"
	.string "{JPN}おおきな おはな みたいよねー!$"

Route109_Text_LolaDefeated:
	.string "{JPN}ママーっ!$"

Route109_Text_LolaPostBattle:
	.string "{JPN}おそらの うえから すなはまを みたら\n"
	.string "{JPN}おはなばたけ みたいに みえるのよ!$"

Route109_Text_LolaRegister:
	.string "{JPN}わたし だったら\n"
	.string "{JPN}まいにち ここに きているよ!$"
	@ TODO: needs JP translation

Route109_Text_LolaRematchIntro:
	.string "{JPN}もう あなたには まけません!\n"
	.string "{JPN}そのために うきわ してるんだから!$"

Route109_Text_LolaRematchDefeated:
	.string "{JPN}ママーっ!$"

Route109_Text_LolaRematchPostBattle:
	.string "{JPN}うきわ もってると あたしと ポケモンの\n"
	.string "{JPN}かわいさが ぐぐーんと アップするの!$"

Route109_Text_AustinaIntro:
	.string "{JPN}うきわが ないと およげないけど\n"
	.string "{JPN}ポケモンなら だれにも まけないよ!$"

Route109_Text_AustinaDefeated:
	.string "{JPN}うきわが あるから まけちゃったのかな?$"

Route109_Text_AustinaPostBattle:
	.string "{JPN}あたしの うきわ\n"
	.string "{JPN}オシャレだから てばなせないの$"

Route109_Text_GwenIntro:
	.string "{JPN}そこの トレーナーさん\n"
	.string "{JPN}あたしと たたかう でちゅ!$"

Route109_Text_GwenDefeated:
	.string "{JPN}つよいでちゅね……$"

Route109_Text_GwenPostBattle:
	.string "{JPN}どうしたら そんなに\n"
	.string "{JPN}つよくなれる でちゅか……?$"

Route109_Text_CarterIntro:
	.string "{JPN}わはは!\n"
	.string "{JPN}おじさん おおもの つっちゃうぞ!$"

Route109_Text_CarterDefeated:
	.string "{JPN}おじさん まけちゃったな……$"

Route109_Text_CarterPostBattle:
	.string "{JPN}たしかに きみは おおもの だな!\n"
	.string "{JPN}いや きっと おおものに なるぞ!$"

Route109_Text_PaulIntro:
	.string "{JPN}リキ: やあ こまったなあ\l"
	.string "{JPN}ふたりっきりの じかん\n"
	.string "{JPN}じゃま して ほしくないなあ$"

Route109_Text_PaulDefeated:
	.string "{JPN}リキ: やあ まいったな……$"

Route109_Text_PaulPostBattle:
	.string "{JPN}リキ: やあ ぼくたちが ここに いること\n"
	.string "{JPN}だれにも いわないで くれよ!\p"
	.string "{JPN}ふたりっきりの せかい なんだからさ!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{JPN}リキ”ぼくたち ラブラブ だからね\n"
	.string "{JPN}ぼくたちの ポケモンも\l"
	.string "{JPN}2ひき いっしょに たたかわせるんだ!$"
	@ TODO: needs JP translation

Route109_Text_MelIntro:
	.string "{JPN}シキ: あたしたちが ラブラブだから\n"
	.string "{JPN}ホウエンは あっついのよお!$"

Route109_Text_MelDefeated:
	.string "{JPN}シキ: あたしの せいで まけたんだわ……\n"
	.string "{JPN}こんなんじゃ リキに きらわれちゃう!$"

Route109_Text_MelPostBattle:
	.string "{JPN}シキ: ねえ リキ\n"
	.string "{JPN}あたしのこと おこってない?\p"
	.string "{JPN}おこっちゃ いやよ$"

Route109_Text_MelNotEnoughPokemon:
	.string "{JPN}シキ”あたしたち ラブラブ だからね\n"
	.string "{JPN}あたしたちの ポケモンも\l"
	.string "{JPN}2ひき いっしょに たたかわせるんだ!$"
	@ TODO: needs JP translation

Route109_Text_ChandlerIntro:
	.string "{JPN}じゃーん!\n"
	.string "{JPN}ボクの うきわ まるいでしょーっ!$"

Route109_Text_ChandlerDefeated:
	.string "{JPN}あーあ! ざんねん$"

Route109_Text_ChandlerPostBattle:
	.string "{JPN}せっかく まるい うきわを\n"
	.string "{JPN}みせて あげたのにさ$"

Route109_Text_HaileyIntro:
	.string "{JPN}およげない から\n"
	.string "{JPN}およぐ ふりを してるの!$"

Route109_Text_HaileyDefeated:
	.string "{JPN}やっぱね!\n"
	.string "{JPN}かてないって おもってたんだ$"

Route109_Text_HaileyPostBattle:
	.string "{JPN}およげるように なったら\n"
	.string "{JPN}ポケモンも つよく なると おもう!$"

Route109_Text_ElijahIntro:
	.string "{JPN}こうはの おれさまには\n"
	.string "{JPN}こんな ポケモンが おにあいだぜ!$"

Route109_Text_ElijahDefeated:
	.string "{JPN}まけても カッコ いいだろ?$"

Route109_Text_ElijahPostBattle:
	.string "{JPN}こうはの おれさまには\n"
	.string "{JPN}みなとまちが おにあいだぜ!\p"
	.string "{JPN}カイナシティに いってくるか$"

Route110_Text_JacobIntro:
	.string "{JPN}おっと あぶない!\n"
	.string "{JPN}バイク レースに なれてない ようだな!$"

Route110_Text_JacobDefeated:
	.string "{JPN}キキーッ!\n"
	.string "{JPN}ブレーキが こしょうした!$"

Route110_Text_JacobPostBattle:
	.string "{JPN}タイヤの パンクや\n"
	.string "{JPN}ブレーキの こしょうは ケガのもと\p"
	.string "{JPN}ちゃんと てんけん しないとな$"

Route110_Text_AnthonyIntro:
	.string "{JPN}ヘイ ユー!\n"
	.string "{JPN}ワタシの スピードに ついてこれるかな!?$"

Route110_Text_AnthonyDefeated:
	.string "{JPN}オー マイ ガッ!$"

Route110_Text_AnthonyPostBattle:
	.string "{JPN}スピードだけじゃ ポケモンしょうぶ\n"
	.string "{JPN}かてませーん! ハンセイしまーす!$"

Route110_Text_BenjaminIntro:
	.string "{JPN}じてんしゃの スピード でても\n"
	.string "{JPN}あせっちゃ いけないよ!$"

Route110_Text_BenjaminDefeated:
	.string "{JPN}ポケモンしょうぶも\n"
	.string "{JPN}あせっちゃ いけないな……$"

Route110_Text_BenjaminPostBattle:
	.string "{JPN}あせらず のんびり いこうよ\n"
	.string "{JPN}じかんは たっぷり あるからね!$"

Route110_Text_BenjaminRegister:
	.string "{JPN}あせらずに また がんばるか!\n"
	.string "{JPN}よかったらさ れんらく くれよな$"
	@ TODO: needs JP translation

Route110_Text_BenjaminRematchIntro:
	.string "{JPN}おっ! スピード だしすぎ じゃない?\n"
	.string "{JPN}ちょっと のんびり しょうぶ しようよ!$"

Route110_Text_BenjaminRematchDefeated:
	.string "{JPN}べつに あせってないけど\n"
	.string "{JPN}なぜだか まけて しまうな……$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{JPN}あせらず のんびり いこうよ\n"
	.string "{JPN}じかんは たっぷり あるからね!$"

Route110_Text_AbigailIntro:
	.string "{JPN}トライアスロンは ハードな スポーツ\n"
	.string "{JPN}すいえい じてんしゃ マラソンの\p"
	.string "{JPN}3しゅもくを こなすのよ!$"

Route110_Text_AbigailDefeated:
	.string "{JPN}ポケモン しょうぶも ハードだわ!$"

Route110_Text_AbigailPostBattle:
	.string "{JPN}つかれたから ひとやすみ\n"
	.string "{JPN}きゅうけいは たいせつ なのよ$"

Route110_Text_AbigailRegister:
	.string "{JPN}あなた きにいったわ!\n"
	.string "{JPN}また サイクリングロードで たたかいましょ$"
	@ TODO: needs JP translation

Route110_Text_AbigailRematchIntro:
	.string "{JPN}じてんしゃに のりながら\n"
	.string "{JPN}ポケモンしょうぶ ってのも いいものよね!$"

Route110_Text_AbigailRematchDefeated:
	.string "{JPN}うわー\n"
	.string "{JPN}どうして そんなに つよいの?$"

Route110_Text_AbigailRematchPostBattle:
	.string "{JPN}ひょっとして きろくに\n"
	.string "{JPN}ちょうせん していたのかしら?\l"
	.string "{JPN}だったら ジャマして ゴメンねー$"

Route110_Text_JasmineIntro:
	.string "{JPN}じてんしゃを こぎつづけて\n"
	.string "{JPN}ふとももが パンパンに なっちゃった$"

Route110_Text_JasmineDefeated:
	.string "{JPN}きんにくつうが しんぱいだわ……$"

Route110_Text_JasminePostBattle:
	.string "{JPN}ジムの バッチを もってるの?\n"
	.string "{JPN}どうりで つよい はずだわ!$"

Route110_Text_EdwardIntro:
	.string "{JPN}おまえの さくせんは すべて みえた!\n"
	.string "{JPN}わたしが まけるはず ない!$"

Route110_Text_EdwardDefeated:
	.string "{JPN}じぶんの はいぼくは みえなかった……!$"

Route110_Text_EdwardPostBattle:
	.string "{JPN}おまえの みらいが みえる……\l"
	.string "{JPN}ふうむ……\n"
	.string "{JPN}あかるい ひかりが みえるぞ……!$"

Route110_Text_JaclynIntro:
	.string "{JPN}おほほほほっ!\n"
	.string "{JPN}わたくしの ミラクルを みせてあげるわ!$"

Route110_Text_JaclynDefeated:
	.string "{JPN}ミラクルに まけたーっ!$"

Route110_Text_JaclynPostBattle:
	.string "{JPN}わたくしに かったことが ミラクル……\n"
	.string "{JPN}そう きせき なのよ!\p"
	.string "{JPN}いつでも かてるなんて おもわないことね!$"

Route110_Text_EdwinIntro:
	.string "{JPN}キミの ポケモン みせてくれない?\n"
	.string "{JPN}ひとめで いいから おねがい!$"

Route110_Text_EdwinDefeated:
	.string "{JPN}コンプリート したかった……!$"

Route110_Text_EdwinPostBattle:
	.string "{JPN}みたことのない ポケモンに であうと\n"
	.string "{JPN}ボクの コレクターだましいが もえるなぁ!$"

Route110_Text_EdwinRegister:
	.string "{JPN}ぼく エントリーコールも\n"
	.string "{JPN}たくさん あつめたいんだよねぇ$"
	@ TODO: needs JP translation

Route110_Text_EdwinRematchIntro:
	.string "{JPN}ねえ キミ\n"
	.string "{JPN}あたらしい ポケモン つかまえた?\l"
	.string "{JPN}よかったら ポケモン みせてくれない?\n"
	.string "{JPN}ひとめで いいから おねがい!$"

Route110_Text_EdwinRematchDefeated:
	.string "{JPN}キミの ポケモン\n"
	.string "{JPN}うらやましいな……$"

Route110_Text_EdwinRematchPostBattle:
	.string "{JPN}ああ! とにかく めずらしい ポケモン\n"
	.string "{JPN}ぜんぶ ボクの ものに したいよー!$"

Route110_Text_DaleIntro:
	.string "{JPN}ええーい!\n"
	.string "{JPN}うしろから はなしかけるなー!$"

Route110_Text_DaleDefeated:
	.string "{JPN}まけたっ!\n"
	.string "{JPN}くやしいっ!!$"

Route110_Text_DalePostBattle:
	.string "{JPN}すいめんに うかぶ うきを じっと みる……\n"
	.string "{JPN}しゅうちゅうりょくが たいせつ なんだ$"

Route110_Text_IsabelIntro:
	.string "{JPN}おほほ! だいじな ポケモンを\n"
	.string "{JPN}じまん するためなら どこにでも いきますわ$"

Route110_Text_IsabelDefeated:
	.string "{JPN}あら まあ イヤですわ$"

Route110_Text_IsabelPostBattle:
	.string "{JPN}しょうぶ させるよりも\n"
	.string "{JPN}だいすきクラブで じまんして こようかしら$"

Route110_Text_IsabelRegister:
	.string "{JPN}わたしの じまんは こんなんじゃ\n"
	.string "{JPN}おわりませんわ!\l"
	.string "{JPN}なんかいも つきあって もらいますわよ!$"
	@ TODO: needs JP translation

Route110_Text_IsabelRematchIntro:
	.string "{JPN}おほほ! だいじな ポケモンなら\n"
	.string "{JPN}なんどだって じまん しますわ!$"

Route110_Text_IsabelRematchDefeated:
	.string "{JPN}あら まあ イヤですわ$"

Route110_Text_IsabelRematchPostBattle:
	.string "{JPN}ポケモンじまんも やめられないけど\n"
	.string "{JPN}しょうぶ するのも すきなのよ!$"

Route110_Text_TimmyIntro:
	.string "{JPN}この あたりの くさむらで\n"
	.string "{JPN}かっこいい ポケモン みつけたんだぜ!$"

Route110_Text_TimmyDefeated:
	.string "{JPN}かっこいい だけじゃ だめかぁ……$"

Route110_Text_TimmyPostBattle:
	.string "{JPN}つかまえた ばかりの ポケモンじゃ\n"
	.string "{JPN}うまく たたかえないや!$"

Route110_Text_AlyssaIntro:
	.string "{JPN}サイクリングロード から おちちゃった!\n"
	.string "{JPN}はずかしい…… しょうぶで まぎらわすわ!$"

Route110_Text_AlyssaDefeated:
	.string "{JPN}ひぇ まけて しまったわ!$"

Route110_Text_AlyssaPostBattle:
	.string "{JPN}おっこちるは まけるはで\n"
	.string "{JPN}はずかし すぎます! わたし!$"

Route110_Text_JosephIntro:
	.string "{JPN}よぉぉし とばして いくぜえェ!\n"
	.string "{JPN}ノリの わるいやつは おいてくぜェ!$"

Route110_Text_JosephDefeated:
	.string "{JPN}ノリが いいね あんた……$"

Route110_Text_JosephPostBattle:
	.string "{JPN}こんなこと では へこたれないぜェ!\n"
	.string "{JPN}おれは まけて またひとつ\p"
	.string "{JPN}いいオトコに なったぜェ!$"

Route110_Text_KalebIntro:
	.string "{JPN}かわいい ポケモンたちが\n"
	.string "{JPN}たすけあう ところは かわいいぞーーっ!$"

Route110_Text_KalebDefeated:
	.string "{JPN}きみは ちも なみだも ないんだな$"

Route110_Text_KalebPostBattle:
	.string "{JPN}おう よしよし\n"
	.string "{JPN}よくやったよ かわいい おまえたち$"

Route111_Text_DrewIntro:
	.string "{JPN}おっ! ゴーゴーゴーグル にあってるね!\n"
	.string "{JPN}でも ぼくの ほうが にあってるだろ?\p"
	.string "{JPN}どっちが にあうか しょうぶだよ!$"

Route111_Text_DrewDefeat:
	.string "{JPN}ゴーゴーゴーグルで まわりが\n"
	.string "{JPN}よく わからなかったよ$"

Route111_Text_DrewPostBattle:
	.string "{JPN}ゴーゴーゴーグルが あると\n"
	.string "{JPN}さばくの すなあらしも へいき だから\p"
	.string "{JPN}それだけで うれしくなるよ!$"

Route111_Text_HeidiIntro:
	.string "{JPN}さばくの なかでも ピクニック!\l"
	.string "{JPN}どんな ところでも トレーナー いるから\n"
	.string "{JPN}しょうぶも できるもんね!$"

Route111_Text_HeidiDefeat:
	.string "{JPN}いやーん いじわるー!$"

Route111_Text_HeidiPostBattle:
	.string "{JPN}すなあらしの なかで たたかうなら\n"
	.string "{JPN}ポケモンの たいりょくに きを つけないと\p"
	.string "{JPN}すぐに きぜつ しちゃうわよ!$"

Route111_Text_BeauIntro:
	.string "{JPN}ゴーゴーゴーグルを つけてると\n"
	.string "{JPN}なんとなく ヒーローきぶん!\p"
	.string "{JPN}いまの ぼくなら だれにだって かてるさ!$"

Route111_Text_BeauDefeat:
	.string "{JPN}きぶん だけじゃ かてないか……$"

Route111_Text_BeauPostBattle:
	.string "{JPN}いつかは ほんものの ヒーローに なる!\n"
	.string "{JPN}そのために もっと がんばって\p"
	.string "{JPN}ポケモンと じぶんを きたえてみせるよ$"

Route111_Text_BeckyIntro:
	.string "{JPN}さばくで カセキが みつかるって きいたけど\n"
	.string "{JPN}どこに あるのかなあ?$"

Route111_Text_BeckyDefeat:
	.string "{JPN}いまいち だわ……$"

Route111_Text_BeckyPostBattle:
	.string "{JPN}さばくで カセキが みつかると いうことは\n"
	.string "{JPN}むかし ここは うみ だったのね!$"

Route111_Text_DustyIntro:
	.string "{JPN}いせきを さがして 30ねん!\n"
	.string "{JPN}そんな わたしと たたかうのかね?$"

Route111_Text_DustyDefeat:
	.string "{JPN}いせきを さがしてるけど\n"
	.string "{JPN}つよい ポケモンは さがしてないんだ$"

Route111_Text_DustyPostBattle:
	.string "{JPN}いせきを さがして 30ねん!\l"
	.string "{JPN}いや もう 40ねん さがしているか?\n"
	.string "{JPN}あれ どうだったかな?$"

Route111_Text_DustyRegister:
	.string "{JPN}つよい ポケモンは さがしてないけど\n"
	.string "{JPN}なぜだか ポケナビは おきにいり なんだ!$"
	@ TODO: needs JP translation

Route111_Text_DustyRematchIntro:
	.string "{JPN}いせきを さがして 30ねん!\l"
	.string "{JPN}いや いせきを さがして 40ねん!\n"
	.string "{JPN}そんな わたしと たたかうのかね?$"

Route111_Text_DustyRematchDefeat:
	.string "{JPN}いせきは みつからない\n"
	.string "{JPN}つよい ポケモンも みつからない$"

Route111_Text_DustyPostRematch:
	.string "{JPN}いせきを さがして 30ねん!\l"
	.string "{JPN}いや もう 40ねん さがしているか?\l"
	.string "{JPN}うーん 50ねん だった きもする……\n"
	.string "{JPN}あれ どうだったかな?$"

Route111_Text_TravisIntro:
	.string "{JPN}ぼくも げんき いっぱい!\n"
	.string "{JPN}ポケモンも げんき いっぱい だよ!$"

Route111_Text_TravisDefeat:
	.string "{JPN}ポケモンの げんき なくなったよ$"

Route111_Text_TravisPostBattle:
	.string "{JPN}げんき いっぱいに はしりまわる\n"
	.string "{JPN}トレーナーが いると\p"
	.string "{JPN}つい そっちを みちゃうよね!$"

Route111_Text_IreneIntro:
	.string "{JPN}どこに いくのか しらないけど\n"
	.string "{JPN}ちょっと しょうぶ してみない?$"

Route111_Text_IreneDefeat:
	.string "{JPN}にくらしいほど つよいのね!$"

Route111_Text_IrenePostBattle:
	.string "{JPN}えんとつやまに いこうかな? って\n"
	.string "{JPN}おもって いるんだけど\p"
	.string "{JPN}このあたりの けしきも いいのよね!$"

Route111_Text_DaisukeIntro:
	.string "{JPN}おのれを きたえるため\n"
	.string "{JPN}であう にんげん すべてに\p"
	.string "{JPN}しょうぶを もうしこんでるッス!$"

Route111_Text_DaisukeDefeat:
	.string "{JPN}まいったッス……!$"

Route111_Text_DaisukePostBattle:
	.string "{JPN}おぬしの ように\n"
	.string "{JPN}つよい トレーナーに かてるまで\p"
	.string "{JPN}しゅぎょう あるのみッス!$"

Route111_Text_WiltonIntro:
	.string "{JPN}きみが ポケモンを どこまで\n"
	.string "{JPN}きたえているか みせて もらおう!$"

Route111_Text_WiltonDefeat:
	.string "{JPN}なるほど\n"
	.string "{JPN}かなり きたえてるね!$"

Route111_Text_WiltonPostBattle:
	.string "{JPN}ポケモンも トレーナーも\n"
	.string "{JPN}たたかうことで いろんなことを まなぶ!\l"
	.string "{JPN}だいじ なのは\n"
	.string "{JPN}まけても あきらめないことさ!$"

Route111_Text_WiltonRegister:
	.string "{JPN}きみの きたえかた さんこうに なるな!\n"
	.string "{JPN}きが むいたら さいど たたかってほしい$"
	@ TODO: needs JP translation

Route111_Text_WiltonRematchIntro:
	.string "{JPN}ぼくたちは さらなる たかみを めざして\n"
	.string "{JPN}ここで ポケモンを きたえている\p"
	.string "{JPN}きみも いっしょに しゅぎょう しよう!$"

Route111_Text_WiltonRematchDefeat:
	.string "{JPN}なかなか やるな!$"

Route111_Text_WiltonPostRematch:
	.string "{JPN}そんなに つよいなら\n"
	.string "{JPN}ポケモンリーグを めざすと いいよ!$"

Route111_Text_BrookeIntro:
	.string "{JPN}あら あなたの ポケモン\n"
	.string "{JPN}かなり つよそうだわ!\p"
	.string "{JPN}ぜひ おてあわせ してくれない?$"

Route111_Text_BrookeDefeat:
	.string "{JPN}つよそう じゃなくて\n"
	.string "{JPN}つよいのね!$"

Route111_Text_BrookePostBattle:
	.string "{JPN}あたしも がんばって\n"
	.string "{JPN}ポケモン そだてた つもりだけど\p"
	.string "{JPN}まだ やること いっぱい あるわね!$"

Route111_Text_BrookeRegister:
	.string "{JPN}あなた みたいな つよいひとと\n"
	.string "{JPN}おともだちに なりたいわ!$"
	@ TODO: needs JP translation

Route111_Text_BrookeRematchIntro:
	.string "{JPN}ポケモンは つかう わざによって\n"
	.string "{JPN}つよくなったり よわくなったりも するわ!\l"
	.string "{JPN}あなたの ポケモン\n"
	.string "{JPN}どんな わざを おぼえているの?$"

Route111_Text_BrookeRematchDefeat:
	.string "{JPN}いい わざを おぼえているのね!$"

Route111_Text_BrookePostRematch:
	.string "{JPN}あたしの ポケモン しんか させずに\n"
	.string "{JPN}さきに わざを おぼえさせてから\p"
	.string "{JPN}そだてた ほうが よかったかな?$"

Route111_Text_CeliaIntro:
	.string "{JPN}こんな ところで\n"
	.string "{JPN}ピクニックを するんじゃ なかった!$"

Route111_Text_CeliaDefeat:
	.string "{JPN}もー\n"
	.string "{JPN}ほんとに くるんじゃ なかった!$"

Route111_Text_CeliaPostBattle:
	.string "{JPN}この すなあらし じゃ\n"
	.string "{JPN}ゴーゴーゴーグルを つけて いても\p"
	.string "{JPN}おべんとうが ひろげられないんだもん……$"

Route111_Text_BryanIntro:
	.string "{JPN}きみの つよさは どのくらいか?\n"
	.string "{JPN}その ナゾを ときあかそう!$"

Route111_Text_BryanDefeat:
	.string "{JPN}おお そのつよさ\n"
	.string "{JPN}ナゾに みちておる!$"

Route111_Text_BryanPostBattle:
	.string "{JPN}この さばくには\n"
	.string "{JPN}ナゾが おおい ですぞーっ!$"

Route111_Text_BrandenIntro:
	.string "{JPN}ぼくに まけて くれたら\n"
	.string "{JPN}サンドイッチ わけて あげるよ!$"

Route111_Text_BrandenDefeat:
	.string "{JPN}ちぇっ!\n"
	.string "{JPN}サンドイッチに つられると おもったのに$"

Route111_Text_BrandenPostBattle:
	.string "{JPN}ぼくの サンドも\n"
	.string "{JPN}サンドイッチ だいすき なんだ$"

Route111_Text_TyronIntro:
	.string "{JPN}ぼくは こんな ポケモンが すきなんだ!$"

Route111_Text_TyronDefeat:
	.string "{JPN}ちょっと! ぼくの ポケモン\n"
	.string "{JPN}ちゃんと みてくれてた!?$"

Route111_Text_TyronPostBattle:
	.string "{JPN}しょうぶを する ときって\n"
	.string "{JPN}じぶんの ポケモンを みせびらかす\p"
	.string "{JPN}たのしみが ゼッタイ あるよねー$"

Route111_Text_CelinaIntro:
	.string "{JPN}うふん……\n"
	.string "{JPN}わたくしを ドキドキ させてね!$"

Route111_Text_CelinaDefeat:
	.string "{JPN}す ……ごい\n"
	.string "{JPN}なんて つよいの$"

Route111_Text_CelinaPostBattle:
	.string "{JPN}ま まだ ドキドキ しているわ\n"
	.string "{JPN}あなたって…… ステキな トレーナーね$"

Route111_Text_HaydenIntro:
	.string "{JPN}おいらは いま はらが へっている\n"
	.string "{JPN}だから ようしゃは しないぞ!$"

Route111_Text_HaydenDefeat:
	.string "{JPN}ぐうぅ……$"

Route111_Text_HaydenPostBattle:
	.string "{JPN}はらが なった!\n"
	.string "{JPN}きのみでも やいて たべようかナ?$"

Route111_Text_BiancaIntro:
	.string "{JPN}あなたは キンセツの ほうから きたの?\n"
	.string "{JPN}じゃ たいりょくも バッチリね!$"

Route111_Text_BiancaDefeat:
	.string "{JPN}あらら すごいんだー$"

Route111_Text_BiancaPostBattle:
	.string "{JPN}この さきの みちのりは\n"
	.string "{JPN}けっこう ながいわよ!$"

Route112_Text_BriceIntro:
	.string "{JPN}わっはっはっ!\n"
	.string "{JPN}どうだ?\p"
	.string "{JPN}オレと しょうぶ しないか?\p"
	.string "{JPN}わっはっはっ!$"

Route112_Text_BriceDefeat:
	.string "{JPN}まけた……\n"
	.string "{JPN}わっはっはっ!$"

Route112_Text_BricePostBattle:
	.string "{JPN}いろあざやかな キノコを たべたら……\n"
	.string "{JPN}わ わらいが とまらない!\p"
	.string "{JPN}わっはっはっ!$"

Route112_Text_TrentIntro:
	.string "{JPN}やまのぼりで きたえた オレの あしこし\n"
	.string "{JPN}ちょっとや そっとじゃ くじけないぜ!$"

Route112_Text_TrentDefeat:
	.string "{JPN}あ……\n"
	.string "{JPN}あしが つった……$"

Route112_Text_TrentPostBattle:
	.string "{JPN}なんじゅっキロも ある にもつを せおって\n"
	.string "{JPN}やまみちを あるき つづけるんだ\p"
	.string "{JPN}からだが じょうぶに なるぞ!$"

Route112_Text_TrentRegister:
	.string "{JPN}つった あしが いたい...\n"
	.string "{JPN}ちょっと オレの リュックから\l"
	.string "{JPN}ほうたいを だしてくれ\p"
	.string "{JPN}って ちがうよ それは ポケナビだろ!\n"
	.string "{JPN}もういいよ とうろく するから$"
	@ TODO: needs JP translation

Route112_Text_TrentRematchIntro:
	.string "{JPN}やまのぼりで きたえてるからな\n"
	.string "{JPN}かなり パワフルだぞ!$"

Route112_Text_TrentRematchDefeat:
	.string "{JPN}パワーで まけたか?$"

Route112_Text_TrentRematchPostBattle:
	.string "{JPN}えんとつやまの うえには\n"
	.string "{JPN}すごい トレーナーが いるらしいぞ!\p"
	.string "{JPN}こんど しょうぶに いくつもりだ!$"

Route112_Text_LarryIntro:
	.string "{JPN}ぼくは つよいんだ……\n"
	.string "{JPN}まけても ないたり しないぞ……!$"

Route112_Text_LarryDefeat:
	.string "{JPN}うわーーーん!$"

Route112_Text_LarryPostBattle:
	.string "{JPN}おかあさんに あえなくて\n"
	.string "{JPN}さみしいから ないてるんじゃ ないよ!\p"
	.string "{JPN}ぐすん……$"

Route112_Text_CarolIntro:
	.string "{JPN}ピクニックと いえば うた!\n"
	.string "{JPN}さあ いっしょに うたいましょ!$"

Route112_Text_CarolDefeat:
	.string "{JPN}こんなに つよいなんて……!$"

Route112_Text_CarolPostBattle:
	.string "{JPN}うたも ポケモンしょうぶも\n"
	.string "{JPN}うまい へた なんて かんけい ないよ!\p"
	.string "{JPN}たのしんだ ほうが かち なのよ!$"

Route112_Text_BryantIntro:
	.string "{JPN}ほのおの ぬけみちで つかまえた\n"
	.string "{JPN}ホカホカの ポケモン みせてやろー!$"

Route112_Text_BryantDefeat:
	.string "{JPN}おお ボコボコだ$"

Route112_Text_BryantPostBattle:
	.string "{JPN}ナカナカ すてきな\n"
	.string "{JPN}たたかいかたじゃ ないか きみぃ!$"

Route112_Text_ShaylaIntro:
	.string "{JPN}アラ! すてきな トレーナーさん\n"
	.string "{JPN}ロマンチックな しょうぶを おねがいね!\p"
	.string "{JPN}マアマア つよいわよ わたし!$"

Route112_Text_ShaylaDefeat:
	.string "{JPN}なんて つよいのかしら\n"
	.string "{JPN}おねえさん おどろいちゃった!$"

Route112_Text_ShaylaPostBattle:
	.string "{JPN}ねえ いま いそがしいの?\n"
	.string "{JPN}えっと もし よかったら\p"
	.string "{JPN}さっそく 2かいせん と おもって……\p"
	.string "{JPN}ん? いそがしいなら いいわ$"

Route113_Text_JaylenIntro:
	.string "{JPN}この あたりが わりと すずしいの\n"
	.string "{JPN}なんでか しってるかい?$"

Route113_Text_JaylenDefeat:
	.string "{JPN}ぴゅーっ!\n"
	.string "{JPN}まけたーっ!$"

Route113_Text_JaylenPostBattle:
	.string "{JPN}かざんばいが たいようの ひかりを\n"
	.string "{JPN}さえぎってるから ひえるんだね!\p"
	.string "{JPN}あつがりの オレには たすかるよ!$"

Route113_Text_DillonIntro:
	.string "{JPN}やまの ふんかは\n"
	.string "{JPN}ちきゅうが いきている しょうこ!$"

Route113_Text_DillonDefeat:
	.string "{JPN}つよいな おまえーっ!$"

Route113_Text_DillonPostBattle:
	.string "{JPN}ごほ がへっ!\n"
	.string "{JPN}はいが はいに はいった……\l"
	.string "{JPN}うけなかった……\n"
	.string "{JPN}さむい…… ブルブル……$"

Route113_Text_MadelineIntro:
	.string "{JPN}あたしの ドンメルちゃんに\n"
	.string "{JPN}かざんばいが かからないように\p"
	.string "{JPN}パラソルを さしているの$"

Route113_Text_MadelineDefeat:
	.string "{JPN}はあ はあ……\n"
	.string "{JPN}つかれましたわ……$"

Route113_Text_MadelinePostBattle:
	.string "{JPN}とても おつよいのね\n"
	.string "{JPN}おねえさん かんしん しちゃったわ$"

Route113_Text_MadelineRegister:
	.string "{JPN}ね ちょっと パラソルに はいって\n"
	.string "{JPN}ポケナビを とうろく していって!$"
	@ TODO: needs JP translation

Route113_Text_MadelineRematchIntro:
	.string "{JPN}おひさしぶりね\n"
	.string "{JPN}よろしかったら しょうぶ しません?$"

Route113_Text_MadelineRematchDefeat:
	.string "{JPN}おみごと ですわ$"

Route113_Text_MadelinePostRematch:
	.string "{JPN}あいかわらず おつよいのね\n"
	.string "{JPN}おねえさん かんしん しちゃったわ$"

Route113_Text_LaoIntro:
	.string "{JPN}はいの なかから ドロロンッ!!\n"
	.string "{JPN}しょうぶで ござる!$"

Route113_Text_LaoDefeat:
	.string "{JPN}まいったで ござる$"

Route113_Text_LaoPostBattle:
	.string "{JPN}もっと かくれかたを けんきゅう しよう\n"
	.string "{JPN}それでは しつれいするで ござる$"

Route113_Text_LaoRegister:
	.string "{JPN}やあ! にんぽう\n"
	.string "{JPN}ポケナビ とうろくのじゅつで ござる!$"
	@ TODO: needs JP translation

Route113_Text_LaoRematchIntro:
	.string "{JPN}はいの なかから ドロロロンッ!!\n"
	.string "{JPN}しょうぶで ござる!$"

Route113_Text_LaoRematchDefeat:
	.string "{JPN}まいったで ござる$"

Route113_Text_LaoPostRematch:
	.string "{JPN}かくれかたは よかったが\n"
	.string "{JPN}しょうぶが いまいち だった……\l"
	.string "{JPN}それでは しつれいするで ござる$"

Route113_Text_LungIntro:
	.string "{JPN}みつけてくれて ありがとう!\n"
	.string "{JPN}でも しょうぶは べつだよ!$"

Route113_Text_LungDefeat:
	.string "{JPN}にんぽう かざんばい がくれ!\l"
	.string "{JPN}…… って もう おわり?$"

Route113_Text_LungPostBattle:
	.string "{JPN}かくれていて なにが しんぱいって\n"
	.string "{JPN}だれも とおらないと さびしいんだよね$"

Route113_Text_ToriIntro:
	.string "{JPN}ナナ: ふたりで かざんばい あつめてるよ\n"
	.string "{JPN}でも ポケモンしょうぶも するんだよ!$"

Route113_Text_ToriDefeat:
	.string "{JPN}ナナ: まけちゃった\n"
	.string "{JPN}つまんないから かざんばい あつめよ!$"

Route113_Text_ToriPostBattle:
	.string "{JPN}ナナ: かざんばい どれくらい たまったかな?\n"
	.string "{JPN}しろいビードロ つくれると いいのにね!$"

Route113_Text_ToriNotEnoughMons:
	.string "{JPN}ナナ”あたしたち 2たい2で たたかいたいの\n"
	.string "{JPN}そうしないと まけちゃうもん!$"
	@ TODO: needs JP translation

Route113_Text_TiaIntro:
	.string "{JPN}ネネ: ふたりで かざんばい あつめてるよ\n"
	.string "{JPN}でも ポケモンしょうぶも するんだよ!$"

Route113_Text_TiaDefeat:
	.string "{JPN}ネネ: かてなかった\n"
	.string "{JPN}つまんないから かざんばい あつめよ!$"

Route113_Text_TiaPostBattle:
	.string "{JPN}ネネ: かざんばい けっこう たまったよ!\n"
	.string "{JPN}もう しろいビードロ つくれるよ きっと!$"

Route113_Text_TiaNotEnoughMons:
	.string "{JPN}ネネ”あたしたち 2たい2で たたかいたいの\n"
	.string "{JPN}そうしないと かてないもん!$"
	@ TODO: needs JP translation

Route113_Text_CobyIntro:
	.string "{JPN}おまえ なんか この つばさで\n"
	.string "{JPN}ふきとばして やるぜっ!$"

Route113_Text_CobyDefeat:
	.string "{JPN}え あれ?$"

Route113_Text_CobyPostBattle:
	.string "{JPN}そんなに あっさり かたれると\n"
	.string "{JPN}なにを いって いいか わからない……$"

Route113_Text_SophieIntro:
	.string "{JPN}あったかくて ねむく なっちゃう\n"
	.string "{JPN}ねむけ ざましに あいてを してよ!$"

Route113_Text_SophieDefeat:
	.string "{JPN}きっと これは ユメなのよ……$"

Route113_Text_SophiePostBattle:
	.string "{JPN}まけて くやしい から\n"
	.string "{JPN}もう ここで フテね しちゃうわ!\p"
	.string "{JPN}ぐーぐー$"

Route113_Text_LawrenceIntro:
	.string "{JPN}もしかして かざんばい あつめの\n"
	.string "{JPN}とちゅう だった?$"

Route113_Text_LawrenceDefeat:
	.string "{JPN}えへへ まけちゃったね$"

Route113_Text_LawrencePostBattle:
	.string "{JPN}ぼくも はいに もぐっちゃおう かしら$"

Route113_Text_WyattIntro:
	.string "{JPN}ぼ ボクと たたかうって いうんですか!\n"
	.string "{JPN}まだ つかまえた ばかりなのに!$"

Route113_Text_WyattDefeat:
	.string "{JPN}か かって うれしい ですか!\n"
	.string "{JPN}こんな ボクに かって うれしいですか!$"

Route113_Text_WyattPostBattle:
	.string "{JPN}はいしゃに こえを かけて くれるって\n"
	.string "{JPN}いうんですか!\p"
	.string "{JPN}か カッコいい ですね! ふん!$"

Route114_Text_LennyIntro:
	.string "{JPN}やっほーっ!\l"
	.string "{JPN}……\l"
	.string "{JPN}こだまの かわりに\n"
	.string "{JPN}やっほー! って いってくれよ!$"

Route114_Text_LennyDefeat:
	.string "{JPN}やっほーっ!$"

Route114_Text_LennyPostBattle:
	.string "{JPN}こどものころ こだま って\n"
	.string "{JPN}むこうの やまにいる モノマネさんが\p"
	.string "{JPN}やっほー! って いってると おもってた$"

Route114_Text_LucasIntro:
	.string "{JPN}じゅんびを おこたる もの\n"
	.string "{JPN}やまに のぼるべからず!$"

Route114_Text_LucasDefeat:
	.string "{JPN}やまは こわい ところだ……$"

Route114_Text_LucasPostBattle:
	.string "{JPN}ふゆの やまは なだれや ふぶきで\n"
	.string "{JPN}そうなんする きけんが おおいぞ!$"

Route114_Text_ShaneIntro:
	.string "{JPN}キャンプの たのしみと いえば\n"
	.string "{JPN}つりに はなびに きもだめし!\l"
	.string "{JPN}だけど いちばんは\n"
	.string "{JPN}ポケモンしょうぶ だね!$"

Route114_Text_ShaneDefeat:
	.string "{JPN}つよすぎるーっ!$"

Route114_Text_ShanePostBattle:
	.string "{JPN}ぼくね ポケモンと いっしょに\n"
	.string "{JPN}キャンプ できるだけで しあわせ だよ$"

Route114_Text_NancyIntro:
	.string "{JPN}しょくごの うんどう!\n"
	.string "{JPN}わたしと しょうぶ しましょうよ!$"

Route114_Text_NancyDefeat:
	.string "{JPN}まけちゃったー!$"

Route114_Text_NancyPostBattle:
	.string "{JPN}おいしい ごはんも たべたし\n"
	.string "{JPN}なんだか ねむくなって きたわ……$"

Route114_Text_SteveIntro:
	.string "{JPN}うふふふふふ……\n"
	.string "{JPN}ボクの ポケモンと しょうぶしない?$"

Route114_Text_SteveDefeat:
	.string "{JPN}ボ ボクの ポケモン……$"

Route114_Text_StevePostBattle:
	.string "{JPN}からだが おおきくて ゴツゴツ かたくて\n"
	.string "{JPN}おおきな ツノと するどい キバ……\p"
	.string "{JPN}うふふふふ……\p"
	.string "{JPN}そんな ポケモンが ほしいなぁ……$"

Route114_Text_SteveRegister:
	.string "{JPN}お おぼえてろっ! ...いや\n"
	.string "{JPN}わすれられない ように こうしてやる!$"
	@ TODO: needs JP translation

Route114_Text_SteveRematchIntro:
	.string "{JPN}うふふふふふ……\n"
	.string "{JPN}ボクの ポケモンと しょうぶ しようよ$"

Route114_Text_SteveRematchDefeat:
	.string "{JPN}ああ ポケモン みることが できて\n"
	.string "{JPN}しあわせ だ……$"

Route114_Text_StevePostRematch:
	.string "{JPN}うふふふふふ……\l"
	.string "{JPN}ポケモンの たたかっている すがたに\n"
	.string "{JPN}ぞくぞく するんだ ボク$"

Route114_Text_BernieIntro:
	.string "{JPN}キャンプファイヤー するとき\n"
	.string "{JPN}はなびを するとき\p"
	.string "{JPN}みずを ようい しておけよ!$"

Route114_Text_BernieDefeat:
	.string "{JPN}しょうか かつどう\n"
	.string "{JPN}ありがとう! ってか$"

Route114_Text_BerniePostBattle:
	.string "{JPN}ほんと ひのようじん だけは おこたるな!\n"
	.string "{JPN}ひを あまく みるんじゃないぜ!$"

Route114_Text_BernieRegister:
	.string "{JPN}もえあがった きもちの まま\n"
	.string "{JPN}ポケナビに とうろく しあおう!$"
	@ TODO: needs JP translation

Route114_Text_BernieRematchIntro:
	.string "{JPN}キャンプファイヤー するとき\n"
	.string "{JPN}はなびを するとき\p"
	.string "{JPN}みずを ようい するように なったか!?$"

Route114_Text_BernieRematchDefeat:
	.string "{JPN}もえあがる まえに\n"
	.string "{JPN}けされた! ってか$"

Route114_Text_BerniePostRematch:
	.string "{JPN}ほんと ひのようじん だけは おこたるな!\n"
	.string "{JPN}ひを あまく みるんじゃないぜ!$"

Route114_Text_ClaudeIntro:
	.string "{JPN}つりで しょうぶ すると\n"
	.string "{JPN}きみには かちめが ないだろう\p"
	.string "{JPN}ポケモンで かかってきなさい!$"

Route114_Text_ClaudeDefeat:
	.string "{JPN}つりの しょうぶなら かってた……$"

Route114_Text_ClaudePostBattle:
	.string "{JPN}りゅうせいのたきで\n"
	.string "{JPN}おおものでも つると しようかな\p"
	.string "{JPN}あそこの たきには なにか いそうだからね$"

Route114_Text_NolanIntro:
	.string "{JPN}つりも すき だが\n"
	.string "{JPN}しょうぶも すき!\l"
	.string "{JPN}しょうぶを いどまれたら\n"
	.string "{JPN}つりの さいちゅうでも ことわらないよ!$"

Route114_Text_NolanDefeat:
	.string "{JPN}しょうぶは すき だが\n"
	.string "{JPN}つよい わけじゃ ないんだ……$"

Route114_Text_NolanPostBattle:
	.string "{JPN}こんどこそ!\l"
	.string "{JPN}と おもっちゃうから\n"
	.string "{JPN}つりも しょうぶも やめられない$"

Route114_Text_TyraIntro:
	.string "{JPN}カヨ: そうね\n"
	.string "{JPN}なんとなく そんな きぶん だから\p"
	.string "{JPN}あなたにも ポケモン おしえたげよっか$"

Route114_Text_TyraDefeat:
	.string "{JPN}カヨ: すごい たたかいかた!$"

Route114_Text_TyraPostBattle:
	.string "{JPN}カヨ: コウハイの イヨに あたしが\n"
	.string "{JPN}ポケモンを おしえて あげたの!$"

Route114_Text_TyraNotEnoughMons:
	.string "{JPN}カヨ”うふふ!\n"
	.string "{JPN}あたしたちと しょうぶ するなら\l"
	.string "{JPN}ポケモン いっぴきじゃ ダメなのよ!$"
	@ TODO: needs JP translation

Route114_Text_IvyIntro:
	.string "{JPN}イヨ: あなた\n"
	.string "{JPN}だれに ポケモン おそわったの?$"

Route114_Text_IvyDefeat:
	.string "{JPN}イヨ: すごい たたかいかた!$"

Route114_Text_IvyPostBattle:
	.string "{JPN}イヨ: あたしが\n"
	.string "{JPN}ポケモン はじめた きっかけは\p"
	.string "{JPN}センパイが おしえてくれた からなの!$"

Route114_Text_IvyNotEnoughMons:
	.string "{JPN}イヨ”ポケモン いっぴき だけなの?\n"
	.string "{JPN}なんだか さみしい かんじ しちゃうね$"
	@ TODO: needs JP translation

Route114_Text_KaiIntro:
	.string "{JPN}でっかいの つれたっ でっかいの!$"

Route114_Text_KaiDefeat:
	.string "{JPN}あれー\n"
	.string "{JPN}おおきさで まけたんかな$"

Route114_Text_KaiPostBattle:
	.string "{JPN}よっしゃー!\n"
	.string "{JPN}もっと おおきいの つるもんね!$"

Route114_Text_CharlotteIntro:
	.string "{JPN}あたし!\n"
	.string "{JPN}かわいい だけじゃ ないんだから!$"

Route114_Text_CharlotteDefeat:
	.string "{JPN}かわいく なーいっ!$"

Route114_Text_CharlottePostBattle:
	.string "{JPN}かわいい だけの ポケモンなんて いや!\n"
	.string "{JPN}かわいくて ひとクセ あるコが すき!$"

Route114_Text_AngelinaIntro:
	.string "{JPN}あなたの ポケモンって\n"
	.string "{JPN}どの くらい しんか させてる?$"

Route114_Text_AngelinaDefeat:
	.string "{JPN}ふーん\n"
	.string "{JPN}なるほどね$"

Route114_Text_AngelinaPostBattle:
	.string "{JPN}しんか させると\n"
	.string "{JPN}みためが ものすごく かわって\p"
	.string "{JPN}ビックリする ポケモンが いるよね!$"

Route115_Text_TimothyIntro:
	.string "{JPN}ふむ……\n"
	.string "{JPN}なかなか できそうだな……\p"
	.string "{JPN}わたしが あいてを してあげよう!$"

Route115_Text_TimothyDefeat:
	.string "{JPN}そうぞう いじょうの つよさだ……!$"

Route115_Text_TimothyPostBattle:
	.string "{JPN}てんさい など いない\n"
	.string "{JPN}すべては どりょく!\p"
	.string "{JPN}わたしは そう しんじている……$"

Route115_Text_TimothyRegister:
	.string "{JPN}ふむ...\n"
	.string "{JPN}こんな まけかたも ひさかたぶりだ\l"
	.string "{JPN}できれば また あいてを してほしい$"
	@ TODO: needs JP translation

Route115_Text_TimothyRematchIntro:
	.string "{JPN}ふむ……\n"
	.string "{JPN}あいかわらずの みのこなし\p"
	.string "{JPN}わたしの あいてを してもらおう!$"

Route115_Text_TimothyRematchDefeat:
	.string "{JPN}あいかわらずの つよさだ……!$"

Route115_Text_TimothyPostRematch:
	.string "{JPN}どりょく あるのみ!\l"
	.string "{JPN}まけたのは まだまだ\n"
	.string "{JPN}どりょくが たりないからだ!$"

Route115_Text_KoichiIntro:
	.string "{JPN}おれのッ!\l"
	.string "{JPN}ワンリキーがッ!\l"
	.string "{JPN}たたかいを のぞんでいるッ!$"

Route115_Text_KoichiDefeat:
	.string "{JPN}いててててっ!$"

Route115_Text_KoichiPostBattle:
	.string "{JPN}おれの ワンリキー たちがッ!\l"
	.string "{JPN}つよさを のぞむかぎり\l"
	.string "{JPN}おれたちは どこまでも つよくなるぜッ!$"

Route115_Text_NobIntro:
	.string "{JPN}オレの とくいわざは\n"
	.string "{JPN}ずつきで レンガを くだく ことだ!$"

Route115_Text_NobDefeat:
	.string "{JPN}うがーっ!\n"
	.string "{JPN}あたまが くだけたーっ!$"

Route115_Text_NobPostBattle:
	.string "{JPN}ポケモンに カラテを おしえてるんだが\n"
	.string "{JPN}オレより つよく なりそうで\p"
	.string "{JPN}ちょっと たのしみ なんだ!$"

Route115_Text_NobRegister:
	.string "{JPN}きみは すげえな!\n"
	.string "{JPN}きたえなおして もういちど しょうぶだ!$"
	@ TODO: needs JP translation

Route115_Text_NobRematchIntro:
	.string "{JPN}きみに まけてから がんばって\n"
	.string "{JPN}ポケモンと おのれを きたえなおしたぞ!\p"
	.string "{JPN}さあ もういちど しょうぶ!$"

Route115_Text_NobRematchDefeat:
	.string "{JPN}うがーっ!\n"
	.string "{JPN}また まけたーっ!$"

Route115_Text_NobPostRematch:
	.string "{JPN}おれの ポケモンは まだまだ つよくなる!\n"
	.string "{JPN}がんばって きたえるぞ!$"

Route115_Text_CyndyIntro:
	.string "{JPN}この すなはまは わたしの\n"
	.string "{JPN}ヒミツの しゅぎょう ばしょ!\l"
	.string "{JPN}かってに はいって こないでよ!$"
	@ TODO: needs JP translation

Route115_Text_CyndyDefeat:
	.string "{JPN}しゅぎょうが たりないわ...!$"
	@ TODO: needs JP translation

Route115_Text_CyndyPostBattle:
	.string "{JPN}すなが クッションに なるから\n"
	.string "{JPN}からだを いためないの\l"
	.string "{JPN}さいこうの しゅぎょう ばしょね!$"
	@ TODO: needs JP translation

Route115_Text_CyndyRegister:
	.string "{JPN}いいわ あなたが ここに はいるの\n"
	.string "{JPN}みとめてあげる!\l"
	.string "{JPN}そのかわり また あいてを たのむわよ!$"
	@ TODO: needs JP translation

Route115_Text_CyndyRematchIntro:
	.string "{JPN}さあ ポケモンしょうぶ いくわよ!$"
	@ TODO: needs JP translation

Route115_Text_CyndyRematchDefeat:
	.string "{JPN}わたしは たたかえるけど\n"
	.string "{JPN}ポケモンが...$"
	@ TODO: needs JP translation

Route115_Text_CyndyPostRematch:
	.string "{JPN}まけても ちょっと たのしいのは\n"
	.string "{JPN}ほんとうに ポケモンが すき だからかな?$"
	@ TODO: needs JP translation

Route115_Text_HectorIntro:
	.string "{JPN}ぼく めずらしい ポケモン もってるんだ!\n"
	.string "{JPN}よかったら みせて あげようか$"

Route115_Text_HectorDefeat:
	.string "{JPN}きみ……\n"
	.string "{JPN}ぼくの ポケモン ほしいでしょ?$"

Route115_Text_HectorPostBattle:
	.string "{JPN}こんなに めずらしい ポケモン もってるんだ\n"
	.string "{JPN}それだけで ぼくは まんぞく なのさ!$"

Route115_Text_KyraIntro:
	.string "{JPN}はしりながら しょうぶを するわよッ!\n"
	.string "{JPN}あなたも ついて きなさーい!$"

Route115_Text_KyraDefeat:
	.string "{JPN}はぁ はぁ……$"

Route115_Text_KyraPostBattle:
	.string "{JPN}はしりながら たたかおうと したのが\n"
	.string "{JPN}まちがい だったわよ!\p"
	.string "{JPN}ひとっぱしり して アタマ ひやすかな$"

Route115_Text_JaidenIntro:
	.string "{JPN}くらえーっ\n"
	.string "{JPN}にんぽう すごポケモンの じゅつ!$"

Route115_Text_JaidenDefeat:
	.string "{JPN}わーん しっぱいだ!$"

Route115_Text_JaidenPostBattle:
	.string "{JPN}でも ぼくの ポケモン\n"
	.string "{JPN}すごポケモン だった でしょ?$"

Route115_Text_HeleneIntro:
	.string "{JPN}ふふっ あたしの ポケモンたちは\n"
	.string "{JPN}くろおび クラスの つよさよ!$"

Route115_Text_HeleneDefeat:
	.string "{JPN}くやしすぎるわ!$"

Route115_Text_HelenePostBattle:
	.string "{JPN}あたしより つよい ひとなんて\n"
	.string "{JPN}めったに あわないのに……\l"
	.string "{JPN}わかった!\n"
	.string "{JPN}あなた ジムリーダー でしょ!$"

Route115_Text_AlixIntro:
	.string "{JPN}めが あったからには にがさないわよ!$"

Route115_Text_AlixDefeat:
	.string "{JPN}くっ…… なかなか!$"

Route115_Text_AlixPostBattle:
	.string "{JPN}あーあ!\n"
	.string "{JPN}テレポートで おうちに かえろうかしら$"

Route115_Text_MarleneIntro:
	.string "{JPN}めいそうの じゃまを したわね……\n"
	.string "{JPN}おしおき させて もらうわ!$"

Route115_Text_MarleneDefeat:
	.string "{JPN}こころが みだれて しまう!$"

Route115_Text_MarlenePostBattle:
	.string "{JPN}ここで ポケモンたちと\n"
	.string "{JPN}めいそうを していたの!\p"
	.string "{JPN}でも あまり おちつかない ところね$"

Route116_Text_ClarkIntro:
	.string "{JPN}トンネルが つうじて いないなら\n"
	.string "{JPN}やまを こえて いけば いいのだ!$"

Route116_Text_ClarkDefeat:
	.string "{JPN}ぜえ…… ぜえ……\n"
	.string "{JPN}まけて つかれて しまった$"

Route116_Text_ClarkPostBattle:
	.string "{JPN}トンネルなど なくても かまわん\n"
	.string "{JPN}やまおとこは やまが みち なのだ!$"

Route116_Text_JoeyIntro:
	.string "{JPN}おれの ポケモン つえーぞ!\n"
	.string "{JPN}ちょっと みてみろよ!$"

Route116_Text_JoeyDefeat:
	.string "{JPN}あいたたたたっ! キズが できた!\n"
	.string "{JPN}バンソーコー はらなきゃ!$"

Route116_Text_JoeyPostBattle:
	.string "{JPN}バンソーコーは おとこの くんしょう!\n"
	.string "{JPN}また ひとつ ふえたぜ!$"

Route116_Text_JoseIntro:
	.string "{JPN}ぼくの むしポケモンは つよいよ!\n"
	.string "{JPN}しょうぶ しようよ!$"

Route116_Text_JoseDefeat:
	.string "{JPN}まけた……!\n"
	.string "{JPN}かてると おもったのに……!$"

Route116_Text_JosePostBattle:
	.string "{JPN}むしポケモンは しんかが はやいから\n"
	.string "{JPN}つよく なるのも はやい!$"

Route116_Text_JaniceIntro:
	.string "{JPN}わたしの かわいい ポケモンの つよさ\n"
	.string "{JPN}じっくりと おしえて あげるわ!$"

Route116_Text_JaniceDefeat:
	.string "{JPN}キミの ほうが いちまい うわてね……$"

Route116_Text_JanicePostBattle:
	.string "{JPN}かわいさと つよさを かねそなえた ポケモン\n"
	.string "{JPN}それが わたしの りそうなの!$"

Route116_Text_JerryIntro:
	.string "{JPN}トレーナーズ スクールで\n"
	.string "{JPN}いろいろ べんきょう したからね\p"
	.string "{JPN}じっせんで たしかめるよ!$"

Route116_Text_JerryDefeat:
	.string "{JPN}べんきょう さぼってたから\n"
	.string "{JPN}まけちゃったよ$"

Route116_Text_JerryPostBattle:
	.string "{JPN}トレーナーズ スクールで\n"
	.string "{JPN}もういちど べんきょう しなおさなきゃ\p"
	.string "{JPN}ツツジさんに おこられちゃうよ$"

Route116_Text_JerryRegister1:
	.string "{JPN}ポケナビには トレーナーが\n"
	.string "{JPN}とうろく できるん だって\l"
	.string "{JPN}トレーナーズ スクールで ならったんだ!\p"
	.string "{JPN}よく わからないから やってみてよ!$"
	@ TODO: needs JP translation

Route116_Text_JerryRegister2:
	.string "{JPN}ポケナビには トレーナーが\n"
	.string "{JPN}とうろく できるん だって\l"
	.string "{JPN}トレーナーズ スクールで ならったんだ!\p"
	.string "{JPN}よく わからないから やってみてよ!$"
	@ TODO: needs JP translation

Route116_Text_JerryRematchIntro:
	.string "{JPN}あれから トレーナーズ スクールで\n"
	.string "{JPN}まじめに べんきょう したからね\p"
	.string "{JPN}このまえ みたいに まけたりしないよ!$"

Route116_Text_JerryRematchDefeat:
	.string "{JPN}あれー?\n"
	.string "{JPN}きちんと べんきょう したのに$"

Route116_Text_JerryPostRematch:
	.string "{JPN}トレーナーズ スクールで\n"
	.string "{JPN}もういちど べんきょう しなおさなきゃ\p"
	.string "{JPN}ツツジさんに おこられちゃうよ$"

Route116_Text_KarenIntro:
	.string "{JPN}スクールでも べんきょう\n"
	.string "{JPN}かえりみち でも べんきょうよ!$"
	@ TODO: needs JP translation

Route116_Text_KarenDefeat:
	.string "{JPN}ショック\n"
	.string "{JPN}まけちゃったよ$"
	@ TODO: needs JP translation

Route116_Text_KarenPostBattle:
	.string "{JPN}ああん! これじゃ ツツジさまのように\n"
	.string "{JPN}エレガントな トレーナーに なれないわ!$"
	@ TODO: needs JP translation

Route116_Text_KarenRegister1:
	.string "{JPN}あーっ それ ポケナビね!\n"
	.string "{JPN}あたしも もってるから とうろくして!$"
	@ TODO: needs JP translation

Route116_Text_KarenRegister2:
	.string "{JPN}あーっ それ ポケナビね!\n"
	.string "{JPN}あたしも もってるから とうろくして!$"
	@ TODO: needs JP translation

Route116_Text_KarenRematchIntro:
	.string "{JPN}あれから ものすっごく べんきょう したの!\n"
	.string "{JPN}その せいか みてもらうからね!$"
	@ TODO: needs JP translation

Route116_Text_KarenRematchDefeat:
	.string "{JPN}ショック\n"
	.string "{JPN}また まけちゃったよ$"
	@ TODO: needs JP translation

Route116_Text_KarenPostRematch:
	.string "{JPN}ツツジさまに かったことが あるの?\n"
	.string "{JPN}それじゃ いまの あたしには かてないわ$"
	@ TODO: needs JP translation

Route116_Text_SarahIntro:
	.string "{JPN}わたくし いままで\n"
	.string "{JPN}ひとに なにかで まけた ことって\p"
	.string "{JPN}ありませんの!$"

Route116_Text_SarahDefeat:
	.string "{JPN}まあ\n"
	.string "{JPN}こんなの はじめてですわ!$"

Route116_Text_SarahPostBattle:
	.string "{JPN}なにふじゆう ない くらし ですけど\n"
	.string "{JPN}ポケモンの ことだけは\p"
	.string "{JPN}おもいどおりに なりません のね$"

Route116_Text_DawsonIntro:
	.string "{JPN}ぼくの ポケモンの\n"
	.string "{JPN}うつくしい けなみに みとれて\p"
	.string "{JPN}キミは なにも できない!$"

Route116_Text_DawsonDefeat:
	.string "{JPN}そりゃないぜ ベイビー$"

Route116_Text_DawsonPostBattle:
	.string "{JPN}ああっ\n"
	.string "{JPN}ポケモンの けなみと\p"
	.string "{JPN}ぼくの ヘアーが みだれた!\p"
	.string "{JPN}びよういん よやく しなきゃ$"

Route116_Text_DevanIntro:
	.string "{JPN}ガツンと いってみようかあ!$"

Route116_Text_DevanDefeat:
	.string "{JPN}あああ\n"
	.string "{JPN}しょうぶに ならんな こりゃ$"

Route116_Text_DevanPostBattle:
	.string "{JPN}たまには ほかの タイプの\n"
	.string "{JPN}ポケモンも つかって みるかなあ?$"

Route116_Text_JohnsonIntro:
	.string "{JPN}この さきって いきどまりなんだ\n"
	.string "{JPN}つまんない から しょうぶ してね$"

Route116_Text_JohnsonDefeat:
	.string "{JPN}まけた けど おもしろかったよ!$"

Route116_Text_JohnsonPostBattle:
	.string "{JPN}まけちゃった から\n"
	.string "{JPN}ぼくの たんパン かしてあげても いーよ!$"

Route117_Text_IsaacIntro:
	.string "{JPN}オレが そだてている ポケモンと\n"
	.string "{JPN}しょうぶ してくれないか?$"

Route117_Text_IsaacDefeat:
	.string "{JPN}みごとに そだててるね……$"

Route117_Text_IsaacPostBattle:
	.string "{JPN}つよさ だけが ポケモンじゃないよ!\n"
	.string "{JPN}ポケモンの こせいを みがきあげるのも\p"
	.string "{JPN}たのしみかたの ひとつ だね!$"

Route117_Text_IsaacRegister:
	.string "{JPN}よーし ますます がんばって そだてるぞ!\n"
	.string "{JPN}きみ そしたら みにきて くれるだろ?$"
	@ TODO: needs JP translation

Route117_Text_IsaacRematchIntro:
	.string "{JPN}オレが そだてている ポケモン\n"
	.string "{JPN}あいかわらず いい かんじ だよ!$"

Route117_Text_IsaacRematchDefeat:
	.string "{JPN}いい そだてかた してるね……\n"
	.string "{JPN}きみには そだてやの さいのう あるかも$"

Route117_Text_IsaacPostRematch:
	.string "{JPN}いい ぐあいに そだってるね!\n"
	.string "{JPN}ミナモシティの ポケモンコンテストに\p"
	.string "{JPN}でることを おすすめ するよ!$"

Route117_Text_LydiaIntro:
	.string "{JPN}ポケモンを ちゃんと そだててるか\n"
	.string "{JPN}わたしが たしかめて あげますね$"

Route117_Text_LydiaDefeat:
	.string "{JPN}ちゃんと そだってますね$"

Route117_Text_LydiaPostBattle:
	.string "{JPN}ポケモンの こせいにも きをくばって\n"
	.string "{JPN}そだてて みて くださいね$"

Route117_Text_LydiaRegister:
	.string "{JPN}よい トレーナーさんに あえて よかった!\n"
	.string "{JPN}これからも よろしく おねがいしますね$"
	@ TODO: needs JP translation

Route117_Text_LydiaRematchIntro:
	.string "{JPN}ポケモンを ちゃんと そだててるか\n"
	.string "{JPN}また わたしが たしかめて あげますね$"

Route117_Text_LydiaRematchDefeat:
	.string "{JPN}みごとに そだってますね$"

Route117_Text_LydiaPostRematch:
	.string "{JPN}ポケモンの せいかくに よって\n"
	.string "{JPN}すきな ポロックが あるみたいなの$"

Route117_Text_DylanIntro:
	.string "{JPN}トライアスロンの まっさいちゅう だけど\n"
	.string "{JPN}さくっと しょうぶ しようじゃ ないか!$"

Route117_Text_DylanDefeat:
	.string "{JPN}たいりょく なくなった!$"

Route117_Text_DylanPostBattle:
	.string "{JPN}まいったな……\l"
	.string "{JPN}いまの しょうぶの あいだに\n"
	.string "{JPN}ビリに なっちゃったかも……?$"

Route117_Text_DylanRegister:
	.string "{JPN}ポケモンも つよく なくちゃ ダメか?\n"
	.string "{JPN}きみさ たまに ぼくを きたえてよ!$"
	@ TODO: needs JP translation

Route117_Text_DylanRematchIntro:
	.string "{JPN}トライアスロンの まっさいちゅう だけど\n"
	.string "{JPN}ぼくには よゆうが あるからね\p"
	.string "{JPN}さくっと しょうぶ しようじゃ ないか!$"

Route117_Text_DylanRematchDefeat:
	.string "{JPN}また たいりょく なくなった!$"

Route117_Text_DylanPostRematch:
	.string "{JPN}およぎと じてんしゃでは トップだったけど\n"
	.string "{JPN}ポケモンは いまいち じしんが ないよ$"

Route117_Text_MariaIntro:
	.string "{JPN}トライアスロンの れんしゅう\n"
	.string "{JPN}ポケモンと いっしょに してるからさ\p"
	.string "{JPN}スピードに じしん あるよ!$"

Route117_Text_MariaDefeat:
	.string "{JPN}れんしゅうが たりなかったかな?$"

Route117_Text_MariaPostBattle:
	.string "{JPN}れんしゅうは つづけてこそ\n"
	.string "{JPN}いみが あるのよね\l"
	.string "{JPN}よーし! また れんしゅうよ\n"
	.string "{JPN}あしたから!$"

Route117_Text_MariaRegister:
	.string "{JPN}あなたは れんしゅう してる?\n"
	.string "{JPN}よかったら わたしが あいてになるわ!$"
	@ TODO: needs JP translation

Route117_Text_MariaRematchIntro:
	.string "{JPN}どう れんしゅう つづけてる?\n"
	.string "{JPN}あたしは もちろん つづけてるわ\p"
	.string "{JPN}その しょうこ みせちゃうから!$"

Route117_Text_MariaRematchDefeat:
	.string "{JPN}れんしゅうが たりなかったかな?$"

Route117_Text_MariaPostRematch:
	.string "{JPN}あしたから また れんしゅう するから\n"
	.string "{JPN}よかったら また しょうぶ してね!$"

Route117_Text_DerekIntro:
	.string "{JPN}むかしは むしとりしょうねん!\n"
	.string "{JPN}いまは こんちゅうマニア!\l"
	.string "{JPN}でも ポケモンを あいする きもちは\n"
	.string "{JPN}ずっと かわらないぜ!$"

Route117_Text_DerekDefeat:
	.string "{JPN}ポケモンの よわさも かわらない……$"

Route117_Text_DerekPostBattle:
	.string "{JPN}すきな ことばかり していたら\n"
	.string "{JPN}いつのまにか マニアって よばれてるよ!\l"
	.string "{JPN}まあ むしポケモンに くわしいからね\n"
	.string "{JPN}マニアと よばれて とうぜん なのさっ!$"

Route117_Text_AnnaIntro:
	.string "{JPN}ミホ: かわいい コウハイの まえ だもん\n"
	.string "{JPN}いいところ みせちゃうんだから!$"

Route117_Text_AnnaDefeat:
	.string "{JPN}ミホ: もう!\n"
	.string "{JPN}コウハイの まえ だから かたせてよ!$"

Route117_Text_AnnaPostBattle:
	.string "{JPN}ミホ: あなたの ポケモン\n"
	.string "{JPN}なかなかの コンビネーション してる!\l"
	.string "{JPN}そうね あたしたちの\n"
	.string "{JPN}つぎ ぐらいに すごいんじゃない?$"

Route117_Text_AnnaAndMegRegister:
	.string "{JPN}ミホ”まけっぱなしでは\n"
	.string "{JPN}ひきさがれない わたしたち!\l"
	.string "{JPN}また きて くれるわよね?$"
	@ TODO: needs JP translation

Route117_Text_AnnaNotEnoughMons:
	.string "{JPN}ミホ”あたしたちと しょうぶ したいなら\n"
	.string "{JPN}ポケモンを 2ひきは もってきてね!$"
	@ TODO: needs JP translation

Route117_Text_MegIntro:
	.string "{JPN}リコ: すてきな センパイとの タッグで\n"
	.string "{JPN}あなたを まかしちゃうから!$"

Route117_Text_MegDefeat:
	.string "{JPN}リコ: やーん\n"
	.string "{JPN}センパイ ごめんなさい!$"

Route117_Text_MegPostBattle:
	.string "{JPN}リコ: あたしが センパイの\n"
	.string "{JPN}あしを ひっぱっちゃったの……\l"
	.string "{JPN}そうでなきゃ あんた かってないわよ!$"

Route117_Text_MegNotEnoughMons:
	.string "{JPN}リコ”ポケモン 1ぴき しか いないの?\n"
	.string "{JPN}じゃあ しょうぶは できないわね\p"
	.string "{JPN}あたしたち 2たい2の\n"
	.string "{JPN}しょうぶを たのしみたいの!$"
	@ TODO: needs JP translation

Route117_Text_AnnaRematchIntro:
	.string "{JPN}ミホ: コウハイの まえで\n"
	.string "{JPN}なんども まけてられないのよね$"

Route117_Text_AnnaRematchDefeat:
	.string "{JPN}ミホ: ちょうしが でなかったのよ$"

Route117_Text_AnnaPostRematch:
	.string "{JPN}ミホ: あなたの ポケモン\n"
	.string "{JPN}なかなかの コンビネーションしてる!\l"
	.string "{JPN}そうね あたしたちの\n"
	.string "{JPN}つぎ ぐらいに すごいんじゃない?$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "{JPN}ミホ”あたしたちと しょうぶ したいなら\n"
	.string "{JPN}ポケモンを 2ひきは もってきてね!$"
	@ TODO: needs JP translation

Route117_Text_MegRematchIntro:
	.string "{JPN}リコ: センパイとの タッグで\n"
	.string "{JPN}こんどこそ あなたを まかしちゃうから!$"

Route117_Text_MegRematchDefeat:
	.string "{JPN}リコ: つよすぎるわ$"

Route117_Text_MegPostRematch:
	.string "{JPN}リコ: センパイと いっしょに たたかったのに\n"
	.string "{JPN}まけるだなんて…… おちこんじゃう!$"

Route117_Text_MegRematchNotEnoughMons:
	.string "{JPN}リコ”ポケモン 1ぴき しか いないの?\n"
	.string "{JPN}じゃあ しょうぶは できないわね\p"
	.string "{JPN}あたしたち 2たい2の\n"
	.string "{JPN}しょうぶを たのしみたいの!$"
	@ TODO: needs JP translation

Route117_Text_MelinaIntro:
	.string "{JPN}すてきな おはなを みながら\n"
	.string "{JPN}しょうぶする なんて すてきよね!$"

Route117_Text_MelinaDefeat:
	.string "{JPN}へーえ いいカンジね あんた!$"

Route117_Text_MelinaPostBattle:
	.string "{JPN}おはなを みながら はしると\n"
	.string "{JPN}きもちいいわよ!$"

Route117_Text_BrandiIntro:
	.string "{JPN}エスパーポケモンに\n"
	.string "{JPN}ひめられた ちからを おみせするわ!$"

Route117_Text_BrandiDefeat:
	.string "{JPN}おどろいたわ$"

Route117_Text_BrandiPostBattle:
	.string "{JPN}エスパーポケモンは おくが ふかいの\n"
	.string "{JPN}あなたも つかまえて ごらんなさい$"

Route117_Text_AishaIntro:
	.string "{JPN}かつこと だけを かんがえて たたかうわ!$"

Route117_Text_AishaDefeat:
	.string "{JPN}まけても くやしがったり しない!\n"
	.string "{JPN}そんなひまが あったら とっくんよ$"

Route117_Text_AishaPostBattle:
	.string "{JPN}まけるかな?と しんぱい すると\n"
	.string "{JPN}よけいに まけちゃうと おもうのよね$"

Route118_Text_RoseIntro:
	.string "{JPN}はなの かおりは ふしぎな ちから\n"
	.string "{JPN}からだも こころも きれいに なるわ$"

Route118_Text_RoseDefeat:
	.string "{JPN}あらら\n"
	.string "{JPN}まけちゃったわね$"

Route118_Text_RosePostBattle:
	.string "{JPN}はなも ポケモンも\n"
	.string "{JPN}いい かおりの ものが だいすき!\p"
	.string "{JPN}クサイにおいは…… かんべんね$"

Route118_Text_RoseRegister:
	.string "{JPN}あら その においは ポケナビね\n"
	.string "{JPN}ぜひとも とうろく しあいましょう!$"
	@ TODO: needs JP translation

Route118_Text_RoseRematchIntro:
	.string "{JPN}いい かおりに さそわれて\n"
	.string "{JPN}いらしたのかしら?$"

Route118_Text_RoseRematchDefeat:
	.string "{JPN}においの こうか……\n"
	.string "{JPN}あんまり きかなかったわね$"

Route118_Text_RosePostRematch:
	.string "{JPN}あまいかおりを うまく つかうと\n"
	.string "{JPN}ポケモンが さそわれて やってくるわね$"

Route118_Text_PerryIntro:
	.string "{JPN}かれいに おおぞらを まう\n"
	.string "{JPN}とりポケモンが さいこう だぜ!$"

Route118_Text_PerryDefeat:
	.string "{JPN}うう…… まけた……$"

Route118_Text_PerryPostBattle:
	.string "{JPN}きみも いい ポケモンを もってるね!\n"
	.string "{JPN}ぼくも まけずに そだてよっと!$"

Route118_Text_ChesterIntro:
	.string "{JPN}はばたけ!\n"
	.string "{JPN}おいらの とりポケモン!$"

Route118_Text_ChesterDefeat:
	.string "{JPN}はばたいたけど……$"

Route118_Text_ChesterPostBattle:
	.string "{JPN}もっと つよくなると\n"
	.string "{JPN}じゆうに とべるように なるのにな!$"

Route118_Text_BarnyIntro:
	.string "{JPN}あたしゃ つりびとだが トレーナーでもある\n"
	.string "{JPN}つった ポケモン ちゃんと そだててるよ!$"

Route118_Text_BarnyDefeat:
	.string "{JPN}そだてたはず なんだが……?$"

Route118_Text_BarnyPostBattle:
	.string "{JPN}つりを しながら\n"
	.string "{JPN}ポケモン そだてても かてなかった……\p"
	.string "{JPN}どっちも はんぱ だったのか!?$"

Route118_Text_WadeIntro:
	.string "{JPN}つりびとに だいじ なのは どうぐ!\n"
	.string "{JPN}トレーナーに だいじ なのは\p"
	.string "{JPN}もちろん ポケモンと ハートだな!$"

Route118_Text_WadeDefeat:
	.string "{JPN}ハートの しょうぶで まけたのか?$"

Route118_Text_WadePostBattle:
	.string "{JPN}つり というのも\n"
	.string "{JPN}ひとと ポケモンとの\p"
	.string "{JPN}しんけん しょうぶ だな!$"

Route118_Text_DaltonIntro:
	.string "{JPN}ぼくの メロディ\n"
	.string "{JPN}あなたの こころに とどけるよ$"

Route118_Text_DaltonDefeat:
	.string "{JPN}ルー ルルルー$"

Route118_Text_DaltonPostBattle:
	.string "{JPN}エレキギターって\n"
	.string "{JPN}ただ うるさい だけじゃ ないんだ……\l"
	.string "{JPN}こうして こころに しみる\n"
	.string "{JPN}メロディも かなでられるのさ……$"

Route118_Text_DaltonRegister:
	.string "{JPN}もっと いい メロディが できたら\n"
	.string "{JPN}ききにおいでよ!$"
	@ TODO: needs JP translation

Route118_Text_DaltonRematchIntro:
	.string "{JPN}ぼくと ポケモンの メロディ\n"
	.string "{JPN}あなたの こころに とどけるよ$"

Route118_Text_DaltonRematchDefeat:
	.string "{JPN}ルー ルルルー$"

Route118_Text_DaltonPostRematch:
	.string "{JPN}ひいてるときの ぼくの きもちが\n"
	.string "{JPN}エレキギターを とおして\p"
	.string "{JPN}あなたに とどく はずなのさ……$"

Route118_Text_DeandreIntro:
	.string "{JPN}いけいけー!\n"
	.string "{JPN}ボクの ポケモン 1ごう 2ごう 3ごう!$"

Route118_Text_DeandreDefeat:
	.string "{JPN}ああ だいじょうぶか!?\n"
	.string "{JPN}ボクの ポケモン 1ごう 2ごう 3ごう!$"

Route118_Text_DeandrePostBattle:
	.string "{JPN}ボクの ポケモン せんたい\n"
	.string "{JPN}カッコいい だろー!\p"
	.string "{JPN}まね しても いーぜー!$"

Route119_Text_BrentIntro:
	.string "{JPN}ボクらは モノマネサークル!\n"
	.string "{JPN}キミの うごきを マネするよ!$"

Route119_Text_BrentDefeat:
	.string "{JPN}うわあ まけたーっ!$"

Route119_Text_BrentPostBattle:
	.string "{JPN}マネを して なにが たのしいか……\l"
	.string "{JPN}ふふふ……\n"
	.string "{JPN}キミには わからない だろうよ$"

Route119_Text_DonaldIntro:
	.string "{JPN}ようやく であえたね!\n"
	.string "{JPN}ぼくの むしポケモンが あいて するよ!$"

Route119_Text_DonaldDefeat:
	.string "{JPN}であわなければ よかった……$"

Route119_Text_DonaldPostBattle:
	.string "{JPN}もっと キミの マネを したい!\n"
	.string "{JPN}ほら はやく うごいてよ!$"

Route119_Text_TaylorIntro:
	.string "{JPN}きみが まえに すすんだら\n"
	.string "{JPN}ぼくらも すすむ\l"
	.string "{JPN}きみが みぎへ まがれば\n"
	.string "{JPN}ぼくらも まがる……$"

Route119_Text_TaylorDefeat:
	.string "{JPN}キミが かっても\n"
	.string "{JPN}ぼくは まける……$"

Route119_Text_TaylorPostBattle:
	.string "{JPN}うーん しょうぶの しょうはい だけは\n"
	.string "{JPN}マネ できないよなあ……\p"
	.string "{JPN}なんか くやしい……$"

Route119_Text_DougIntro:
	.string "{JPN}やっと ボクを つかまえられたね!\n"
	.string "{JPN}それとも にげようと していたのかな?$"

Route119_Text_DougDefeat:
	.string "{JPN}すばらしい たたかい だったな!$"

Route119_Text_DougPostBattle:
	.string "{JPN}ボクらは モノマネサークル!\n"
	.string "{JPN}たのしんで もらえたかな?$"

Route119_Text_GregIntro:
	.string "{JPN}ボクが だれなのか わからないだろう?\l"
	.string "{JPN}……まあ ボクも キミのこと しらないから\n"
	.string "{JPN}こうして たたかうんだけどね!$"

Route119_Text_GregDefeat:
	.string "{JPN}けっこう つよい じゃんか!$"

Route119_Text_GregPostBattle:
	.string "{JPN}キミが どこかに いくまで\n"
	.string "{JPN}ボクらは マネを つづけるよ!$"

Route119_Text_KentIntro:
	.string "{JPN}モノマネ だいすきな ひとが\n"
	.string "{JPN}あつまって つくった モノマネサークル!\l"
	.string "{JPN}であった そのとき\n"
	.string "{JPN}しょうぶが はじまる!$"

Route119_Text_KentDefeat:
	.string "{JPN}まいりましたーっ!$"

Route119_Text_KentPostBattle:
	.string "{JPN}キミも モノマネサークルに はいらない?$"

Route119_Text_JacksonIntro:
	.string "{JPN}サバイバルに ひつような\n"
	.string "{JPN}ちしきと ぎじゅつを もつ もの!\p"
	.string "{JPN}それが ポケモンレンジャーさ!$"

Route119_Text_JacksonDefeat:
	.string "{JPN}ポケモンの ちしきは たらなかった……$"

Route119_Text_JacksonPostBattle:
	.string "{JPN}ぶんめい から はなれて\n"
	.string "{JPN}にんげんの やせいを めざめさせる!\p"
	.string "{JPN}それが オレたちの テーマさ!$"

Route119_Text_JacksonRegister:
	.string "{JPN}ちしきぶそくと わらわずに\n"
	.string "{JPN}こんど また あいてを してやってくれよな$"
	@ TODO: needs JP translation

Route119_Text_JacksonRematchIntro:
	.string "{JPN}ポケモンと いることで\n"
	.string "{JPN}やせいを とりもどすのさ!$"

Route119_Text_JacksonRematchDefeat:
	.string "{JPN}あいかわらず つよいな!$"

Route119_Text_JacksonPostRematch:
	.string "{JPN}とにかく ポケモンを しんじろ!\n"
	.string "{JPN}じぶんを しんじろ!\p"
	.string "{JPN}そうすれば みちは ひらける!$"

Route119_Text_CatherineIntro:
	.string "{JPN}あら あなた……\n"
	.string "{JPN}ぼうけんを している わりには\p"
	.string "{JPN}ずいぶん みがるな かっこうね!$"

Route119_Text_CatherineDefeat:
	.string "{JPN}じゅんび ぶそくは じこの もと……$"

Route119_Text_CatherinePostBattle:
	.string "{JPN}ずいぶん みがるな かっこう だけど\n"
	.string "{JPN}ひつような どうぐは もってるし\p"
	.string "{JPN}きりょく たいりょく じゅうぶんね!$"

Route119_Text_CatherineRegister:
	.string "{JPN}トレーナーの ひつじゅひん ポケナビは\n"
	.string "{JPN}ちゃんと もってる?\p"
	.string "{JPN}あっ もってるわね! とうろくしましょ$"
	@ TODO: needs JP translation

Route119_Text_CatherineRematchIntro:
	.string "{JPN}ポケモンと いっしょの ぼうけんは\n"
	.string "{JPN}うまく いってるかしら?$"

Route119_Text_CatherineRematchDefeat:
	.string "{JPN}まだ なにかが\n"
	.string "{JPN}たりなかったわね……$"

Route119_Text_CatherinePostRematch:
	.string "{JPN}トレーナーの あなたが\n"
	.string "{JPN}ポケモンを たよって いるように\p"
	.string "{JPN}ポケモンも あなたを たよっているのよ!$"

Route119_Text_HughIntro:
	.string "{JPN}おおぞらは おとこの ロマン!\l"
	.string "{JPN}じゆうに そらを とぶ きもちよさは\n"
	.string "{JPN}なにごとにも かえがたい!$"

Route119_Text_HughDefeat:
	.string "{JPN}まけたーっ!$"

Route119_Text_HughPostBattle:
	.string "{JPN}そらを とびまわる ユメは\n"
	.string "{JPN}とりポケモンの おかげで かなえられたよ!$"

Route119_Text_PhilIntro:
	.string "{JPN}ぼくの とりポケモンの じつりょくを\n"
	.string "{JPN}みせて あげるよ!$"

Route119_Text_PhilDefeat:
	.string "{JPN}じつりょく ぶそく だった……$"

Route119_Text_PhilPostBattle:
	.string "{JPN}ぼくは ちいさい ころから\n"
	.string "{JPN}とりポケモンに あこがれて いたんだ!$"

Route119_Text_YasuIntro:
	.string "{JPN}かげに ひそみ やみに いきる\n"
	.string "{JPN}それが オレの さだめ……!\p"
	.string "{JPN}いざ ポケモンしょうぶ!$"

Route119_Text_YasuDefeat:
	.string "{JPN}まいった……!$"

Route119_Text_YasuPostBattle:
	.string "{JPN}しょうぶに やぶれた ものは\n"
	.string "{JPN}いさぎよく かげに もどる……\p"
	.string "{JPN}それも さだめ……$"

Route119_Text_TakashiIntro:
	.string "{JPN}ゆだん してると\n"
	.string "{JPN}いたい めに あうぜ!$"

Route119_Text_TakashiDefeat:
	.string "{JPN}つよいな きみーっ!$"

Route119_Text_TakashiPostBattle:
	.string "{JPN}きしゅう さくせんは シッパイだった……$"

Route119_Text_HideoIntro:
	.string "{JPN}きを かくすなら もりのなか!$"

Route119_Text_HideoDefeat:
	.string "{JPN}つわもので ござるな$"

Route119_Text_HideoPostBattle:
	.string "{JPN}きを かくすなら もりのなか!\n"
	.string "{JPN}ポケモンを かくすなら ポケモンのなか!\l"
	.string "{JPN}とくに いみは ないでござる$"

Route119_Text_ChrisIntro:
	.string "{JPN}わたしに はなしかけた……\n"
	.string "{JPN}つまり しょうぶを いどむ つもりだな!\l"
	.string "{JPN}よーし! なみのり しながら\n"
	.string "{JPN}つりあげた ポケモンで たたかうぞ!$"

Route119_Text_ChrisDefeat:
	.string "{JPN}かつための ポイントが\n"
	.string "{JPN}ちっとも わからん!$"

Route119_Text_ChrisPostBattle:
	.string "{JPN}なみのりを つかう!\l"
	.string "{JPN}ポケモンの せなかに のって\n"
	.string "{JPN}つりを たのしむ!\l"
	.string "{JPN}なんて ゆうがな ひととき だろう!$"

Route119_Text_FabianIntro:
	.string "{JPN}デケデケデケデケ\n"
	.string "{JPN}かつぜーヘ おれたちーヒ かつぜーヘ$"

Route119_Text_FabianDefeat:
	.string "{JPN}まけたぜーヘ あっさりーヒ まけたぜーヘ$"

Route119_Text_FabianPostBattle:
	.string "{JPN}デケデケデケデケ\n"
	.string "{JPN}にどとーホ おれにーヒ かまうなよーホ$"

Route119_Text_DaytonIntro:
	.string "{JPN}ホッホッホー!\n"
	.string "{JPN}こども トレーナーは だいすきだぞ!\p"
	.string "{JPN}おじちゃんと たたかおうっ!$"

Route119_Text_DaytonDefeat:
	.string "{JPN}やるなー ホッホッホ!$"

Route119_Text_DaytonPostBattle:
	.string "{JPN}ホッホッホー!\n"
	.string "{JPN}こども トレーナーの げんきを\p"
	.string "{JPN}みならって おじちゃん がんばるぞ!$"

Route119_Text_RachelIntro:
	.string "{JPN}いつでも どこでも\n"
	.string "{JPN}パラソルを てばなさないの!$"

Route119_Text_RachelDefeat:
	.string "{JPN}いやん そんなあ$"

Route119_Text_RachelPostBattle:
	.string "{JPN}パラソルが おもく ないかって?\n"
	.string "{JPN}キミの バッグの ほうが\p"
	.string "{JPN}いっぱい はいってるじゃない$"

Route120_Text_ColinIntro:
	.string "{JPN}そらを とんでいる ポケモンに\n"
	.string "{JPN}ダメージを あたえる ワザを もってる?$"

Route120_Text_ColinDefeat:
	.string "{JPN}キミの ほうが\n"
	.string "{JPN}いちまい うわて だった!$"

Route120_Text_ColinPostBattle:
	.string "{JPN}そらをとぶ って ワザは べんりだな!\l"
	.string "{JPN}そらを とんでいる あいだは\n"
	.string "{JPN}ほとんどの ワザが あたらないだろ?$"

Route120_Text_RobertIntro:
	.string "{JPN}ボクの ポケモンは つよいぜ!\n"
	.string "{JPN}キミの ポケモンは どうかな?$"

Route120_Text_RobertDefeat:
	.string "{JPN}キミの ポケモンの ほうが\n"
	.string "{JPN}つよかった……!$"

Route120_Text_RobertPostBattle:
	.string "{JPN}どんどん つよくなる ポケモンは\n"
	.string "{JPN}ほんと たよりに なるよなー!$"

Route120_Text_RobertRegister:
	.string "{JPN}キミって きたい できそうだなー!\n"
	.string "{JPN}ポケナビに とうろく しておきたい!$"
	@ TODO: needs JP translation

Route120_Text_RobertRematchIntro:
	.string "{JPN}どんどん つよくなる ポケモンは\n"
	.string "{JPN}ほんと たよりに なるよなー!$"

Route120_Text_RobertRematchDefeat:
	.string "{JPN}キミの ポケモン\n"
	.string "{JPN}ほんとうに つよいんだな……$"

Route120_Text_RobertPostRematch:
	.string "{JPN}ポケモンが つよくなるのと いっしょに\n"
	.string "{JPN}おれも つよくならないとなー!$"

Route120_Text_LorenzoIntro:
	.string "{JPN}きみの ポケモン\n"
	.string "{JPN}そうなん しないか みてあげよう!$"

Route120_Text_LorenzoDefeat:
	.string "{JPN}そんなに つよい ポケモンと いっしょなら\n"
	.string "{JPN}そうなんの おそれは ないな!$"

Route120_Text_LorenzoPostBattle:
	.string "{JPN}ポケモンと いっしょに どこまでもいく\n"
	.string "{JPN}トレーナーの よろこびと いえるだろう!$"

Route120_Text_JennaIntro:
	.string "{JPN}あなたの たいりょく どう?\n"
	.string "{JPN}たいりょく ぶそくだと\p"
	.string "{JPN}いざと いうとき こまるわよ!$"

Route120_Text_JennaDefeat:
	.string "{JPN}たいりょく だけは あったのに……$"

Route120_Text_JennaPostBattle:
	.string "{JPN}たいりょく づくりが わたしの にっか\n"
	.string "{JPN}まいにち ポケモンと ランニングよ!$"

Route120_Text_JeffreyIntro:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ...\l"
	.string "{JPN}しょうぶ する...?$"
	@ TODO: needs JP translation

Route120_Text_JeffreyDefeat:
	.string "{JPN}... ... ...\n"
	.string "{JPN}まけた...$"
	@ TODO: needs JP translation

Route120_Text_JeffreyPostBattle:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ...\l"
	.string "{JPN}がんばろう...$"
	@ TODO: needs JP translation

Route120_Text_JeffreyRegister:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ...\l"
	.string "{JPN}ポケナビ もってる...?$"
	@ TODO: needs JP translation

Route120_Text_JeffreyRematchIntro:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ...\l"
	.string "{JPN}また しょうぶ する...?$"
	@ TODO: needs JP translation

Route120_Text_JeffreyRematchDefeat:
	.string "{JPN}... ... ...\n"
	.string "{JPN}また まけた...$"
	@ TODO: needs JP translation

Route120_Text_JeffreyPostRematch:
	.string "{JPN}... ... ...\n"
	.string "{JPN}... ... ...\l"
	.string "{JPN}また がんばろう...\l"
	.string "{JPN}だいじな むしポケモンの ために...$"
	@ TODO: needs JP translation

Route120_Text_JenniferIntro:
	.string "{JPN}ポケモンには いろんな とくせいが ある\n"
	.string "{JPN}それを かんがえてこそ\p"
	.string "{JPN}いちりゅうの トレーナーに なれるのよ!$"

Route120_Text_JenniferDefeat:
	.string "{JPN}なかなか かんがえてるのね$"

Route120_Text_JenniferPostBattle:
	.string "{JPN}そう ポケモンの とくせいに よって\n"
	.string "{JPN}たたかいかたも いろいろ かわってくるわ!$"

Route120_Text_ChipIntro:
	.string "{JPN}なんだね きみは?\l"
	.string "{JPN}もしかして ひょっとすると\n"
	.string "{JPN}あるかもしれない といわれる\p"
	.string "{JPN}こだいの いせきを さがしに きたのかね!?$"

Route120_Text_ChipDefeat:
	.string "{JPN}まいったね こりゃ$"

Route120_Text_ChipPostBattle:
	.string "{JPN}あの おおきな いわ\n"
	.string "{JPN}わたしは いせき だと おもいたいが\p"
	.string "{JPN}それにしては いりぐちが ないね……$"

Route120_Text_ClarissaIntro:
	.string "{JPN}あたしが パラソルを もってる りゆう?\l"
	.string "{JPN}うふふ あたしに かてたら\n"
	.string "{JPN}おしえて あげても いいかな?$"

Route120_Text_ClarissaDefeat:
	.string "{JPN}パラソルで ポケモンの こうげきは\n"
	.string "{JPN}しのげないのね……$"

Route120_Text_ClarissaPostBattle:
	.string "{JPN}あたしの ポケモンたちも\n"
	.string "{JPN}あつい ひざしは にがてだと おもうの\p"
	.string "{JPN}だから こうして パラソルを もってるのよ$"

Route120_Text_AngelicaIntro:
	.string "{JPN}あたしと ポケモンと パラソル\n"
	.string "{JPN}どれか ひとつ かけていても\p"
	.string "{JPN}うつくしさが そこなわれるんだわ$"

Route120_Text_AngelicaDefeat:
	.string "{JPN}うつくしさが\n"
	.string "{JPN}だいなしに なっちゃったわ$"

Route120_Text_AngelicaPostBattle:
	.string "{JPN}あなたに パラソルは にあわないわ!\l"
	.string "{JPN}だって こんなの もっていたら\n"
	.string "{JPN}すっごく ジャマに なりそう なんだもの$"

Route120_Text_KeigoIntro:
	.string "{JPN}ポケモンの うごきを とりいれて\n"
	.string "{JPN}あたらしい にんぽうを あみだすんだ!$"

Route120_Text_KeigoDefeat:
	.string "{JPN}あたらしい にんぽう\n"
	.string "{JPN}かんせいまで まだまだ かかりそうだ$"

Route120_Text_KeigoPostBattle:
	.string "{JPN}ニンジャの せんせいを さがして\n"
	.string "{JPN}でしいり しようかな?$"

Route120_Text_RileyIntro:
	.string "{JPN}ぼくたち ニンジャごっこの かくれぬの!\n"
	.string "{JPN}どこに いるのか わからなかっただろ!$"

Route120_Text_RileyDefeat:
	.string "{JPN}まけた!\n"
	.string "{JPN}かくれぬので かくれるか?$"

Route120_Text_RileyPostBattle:
	.string "{JPN}ぼくたち ニンジャごっこの かくれぬの!\n"
	.string "{JPN}これって てづくり なんだぜ!$"

Route120_Text_CallieIntro:
	.string "{JPN}よそみ してると ケガするよ!$"

Route120_Text_CallieDefeat:
	.string "{JPN}いたいめに あったのは あたしのほうか$"

Route120_Text_CalliePostBattle:
	.string "{JPN}やっぱり しんか させようかな?\n"
	.string "{JPN}このままでも かわいい けど$"

Route120_Text_LeonelIntro:
	.string "{JPN}きみの てもち ポケモン\n"
	.string "{JPN}いろんな タイプが そろって いるか?$"

Route120_Text_LeonelDefeat:
	.string "{JPN}きみの こだわり みせてもらったよ!$"

Route120_Text_LeonelPostBattle:
	.string "{JPN}すきな ポケモン だけで\n"
	.string "{JPN}つよいって いうのが さいこうだね$"

Route121_Text_VanessaIntro:
	.string "{JPN}あたしの とっても プリティな\n"
	.string "{JPN}ポケモンを かわいがってよ!$"

Route121_Text_VanessaDefeat:
	.string "{JPN}かわいがるの いみが ちがうわ!$"

Route121_Text_VanessaPostBattle:
	.string "{JPN}ミナモの コンテストに いくのよ\n"
	.string "{JPN}あたしの ポケモンなら\p"
	.string "{JPN}マスター ランクでも らくしょうよ!$"

Route121_Text_WalterIntro:
	.string "{JPN}せかい かっこくを\n"
	.string "{JPN}ポケモンと いっしょに まわってきた\l"
	.string "{JPN}すこしは うでに じしんが ありますよ!$"

Route121_Text_WalterDefeat:
	.string "{JPN}おみごと ですな$"

Route121_Text_WalterPostBattle:
	.string "{JPN}また ポケモンと いっしょに\n"
	.string "{JPN}せかいを まわってみたい ものです$"

Route121_Text_WalterRegister:
	.string "{JPN}あなたの うでまえは たいしたものだ\n"
	.string "{JPN}ぜひ きねんに とうろくを...$"
	@ TODO: needs JP translation

Route121_Text_WalterRematchIntro:
	.string "{JPN}せかい かっこくを\n"
	.string "{JPN}ポケモンと いっしょに まわってきた\l"
	.string "{JPN}すこしは うでに じしんが ありますよ!$"

Route121_Text_WalterRematchDefeat:
	.string "{JPN}おみごと ですな!$"

Route121_Text_WalterPostRematch:
	.string "{JPN}あなたと その ポケモンなら\n"
	.string "{JPN}がいこくでも つよいと いわれるでしょう!$"

Route121_Text_TammyIntro:
	.string "{JPN}よの なかには ふしぎな ちからが\n"
	.string "{JPN}いっぱい あるの……$"

Route121_Text_TammyDefeat:
	.string "{JPN}あたし まけたのね……$"

Route121_Text_TammyPostBattle:
	.string "{JPN}おくりびやま……\n"
	.string "{JPN}あそこに ふしぎな ちからが あるの……$"

Route121_Text_KateIntro:
	.string "{JPN}マナ: ふたり そろえば こわいもの なし!\n"
	.string "{JPN}あたしたちの つよさ みせつけちゃうから!$"

Route121_Text_KateDefeat:
	.string "{JPN}マナ: コウハイの まえで かっこわるいわ……$"

Route121_Text_KatePostBattle:
	.string "{JPN}マナ: あたしって たよられちゃうと\n"
	.string "{JPN}つい かっこいい ところ\p"
	.string "{JPN}みせたく なっちゃうのよね……$"

Route121_Text_KateNotEnoughMons:
	.string "{JPN}マナ”ポケモン 1ぴき しか いないのね\n"
	.string "{JPN}じゃあ しょうぶは できないわ!\p"
	.string "{JPN}だって よわいもの いじめに なるもの$"
	@ TODO: needs JP translation

Route121_Text_JoyIntro:
	.string "{JPN}ユイ: ふたり そろえば こわいもの なし!\n"
	.string "{JPN}あたしたちの つよさ みせつけちゃうから!$"

Route121_Text_JoyDefeat:
	.string "{JPN}ユイ: センパイ ごめんなさーい$"

Route121_Text_JoyPostBattle:
	.string "{JPN}ユイ: えへっ!\n"
	.string "{JPN}また センパイと いっしょに とっくんね!$"

Route121_Text_JoyNotEnoughMons:
	.string "{JPN}ユイ”あたしたちに しょうぶを いどむなら\n"
	.string "{JPN}ポケモン 2ひきは ひつよう だからね!$"
	@ TODO: needs JP translation

Route121_Text_JessicaIntro:
	.string "{JPN}あたくしの だいじな ポケモン\n"
	.string "{JPN}ちょっと みなさいよ!$"

Route121_Text_JessicaDefeat:
	.string "{JPN}ぷんぷん!\n"
	.string "{JPN}なによ ほんき だしちゃって!$"

Route121_Text_JessicaPostBattle:
	.string "{JPN}サファリで あたらしい ポケモン\n"
	.string "{JPN}つかまえようかな?$"

Route121_Text_JessicaRegister:
	.string "{JPN}きょうは てかげん してあげたのよ\n"
	.string "{JPN}つぎは こうは いかないからね!$"
	@ TODO: needs JP translation

Route121_Text_JessicaRematchIntro:
	.string "{JPN}だいじな ポケモン そだったのよ!\n"
	.string "{JPN}ちょっと みていきなさいよ!$"

Route121_Text_JessicaRematchDefeat:
	.string "{JPN}ぷんぷん!\n"
	.string "{JPN}また てかげん してくれないのね!$"

Route121_Text_JessicaPostRematch:
	.string "{JPN}サファリで あたらしい ポケモン\n"
	.string "{JPN}つかまえようかな?$"

Route121_Text_CristinIntro:
	.string "{JPN}1にちに 5にんずつ\n"
	.string "{JPN}たおす ことが にっかよ!\l"
	.string "{JPN}あなたが その 5にんめ!$"
	@ TODO: needs JP translation

Route121_Text_CristinDefeat:
	.string "{JPN}いやっ ひどいわ!$"
	@ TODO: needs JP translation

Route121_Text_CristinPostBattle:
	.string "{JPN}こんなに あっさり まけるなんて...\n"
	.string "{JPN}つぎは わたしが かつから!$"
	@ TODO: needs JP translation

Route121_Text_CristinRegister:
	.string "{JPN}くつじょく てき だわ!\n"
	.string "{JPN}あなたの こと わすれないんだから...\l"
	.string "{JPN}ポケナビを かしなさい!$"
	@ TODO: needs JP translation

Route121_Text_CristinRematchIntro:
	.string "{JPN}1にちに 10にんずつ\n"
	.string "{JPN}たおす ことが にっかよ!\l"
	.string "{JPN}あなたが その 10にんめ!$"
	@ TODO: needs JP translation

Route121_Text_CristinRematchDefeat:
	.string "{JPN}ちょっ...\n"
	.string "{JPN}ひどい やりなおしてよ!$"
	@ TODO: needs JP translation

Route121_Text_CristinPostRematch:
	.string "{JPN}こんなに かてない あいてが いるなんて...\n"
	.string "{JPN}グスっ しんじられない$"
	@ TODO: needs JP translation

Route121_Text_CaleIntro:
	.string "{JPN}いま にもつが いっぱい なんですけど!\n"
	.string "{JPN}こんな じょうたいで たたかえと?$"

Route121_Text_CaleDefeat:
	.string "{JPN}そりゃ まけますよ\n"
	.string "{JPN}りょうてが ふさがってるんだもん$"

Route121_Text_CalePostBattle:
	.string "{JPN}この さきの ミナモデパートで\n"
	.string "{JPN}かいもの しすぎたんだ!\p"
	.string "{JPN}きみの みたいな バッグが ほしいな$"

Route121_Text_MylesIntro:
	.string "{JPN}みんなの そだてた ポケモンが\n"
	.string "{JPN}みてみたーーい!$"

Route121_Text_MylesDefeat:
	.string "{JPN}すごーーい!$"

Route121_Text_MylesPostBattle:
	.string "{JPN}いいなーー! きみの ポケモン!\n"
	.string "{JPN}どうやって そだてているの?$"

Route121_Text_PatIntro:
	.string "{JPN}わたしの そだてた ポケモンたち\n"
	.string "{JPN}みんなに みてほしいの!$"

Route121_Text_PatDefeat:
	.string "{JPN}すごいなァ!$"

Route121_Text_PatPostBattle:
	.string "{JPN}どんな ポケモンでも おなじように\n"
	.string "{JPN}かわいがって そだてているの!$"

Route121_Text_MarcelIntro:
	.string "{JPN}わたしの ポケモンは まけしらず!\n"
	.string "{JPN}こんど かったら つぎは コンテストだ!$"

Route121_Text_MarcelDefeat:
	.string "{JPN}あっと どうしたことだ?$"

Route121_Text_MarcelPostBattle:
	.string "{JPN}コンテストの まえに\n"
	.string "{JPN}もうすこし きたえないと ダメかな$"

Route123_Text_WendyIntro:
	.string "{JPN}あなたの じつりょくが\n"
	.string "{JPN}どれほどの ものか……\p"
	.string "{JPN}わたしが たしかめて あげる!$"

Route123_Text_WendyDefeat:
	.string "{JPN}すばらしいわ……!$"

Route123_Text_WendyPostBattle:
	.string "{JPN}わたしに かつなんて……\n"
	.string "{JPN}あなたの じつりょくも そうとうな もの!$"

Route123_Text_BraxtonIntro:
	.string "{JPN}たくさん ジムの バッジを\n"
	.string "{JPN}もっている みたいだね!\l"
	.string "{JPN}ほんとうに それだけの ちからが あるか\n"
	.string "{JPN}たしかめさせて もらうよ!$"

Route123_Text_BraxtonDefeat:
	.string "{JPN}たしかに ちからは ある!$"

Route123_Text_BraxtonPostBattle:
	.string "{JPN}ジムバッジに はじない\n"
	.string "{JPN}たたかい だったよ!$"

Route123_Text_VioletIntro:
	.string "{JPN}たのしい ことが あるとき って\n"
	.string "{JPN}いい においで いっぱいに なってるのね$"

Route123_Text_VioletDefeat:
	.string "{JPN}あぁ\n"
	.string "{JPN}かなしみの におい だわ……$"

Route123_Text_VioletPostBattle:
	.string "{JPN}きのみ めいじんの はなばたけ\n"
	.string "{JPN}すっごく いいかんじの においで いっぱい!$"

Route123_Text_CameronIntro:
	.string "{JPN}サイキックとは きもちの つよさ……\l"
	.string "{JPN}そう ぼくは だれにも まけないと\n"
	.string "{JPN}おもっているから つよいよ!$"

Route123_Text_CameronDefeat:
	.string "{JPN}しょんぼり……$"

Route123_Text_CameronPostBattle:
	.string "{JPN}サイキックとは きもちの つよさ\n"
	.string "{JPN}きみには まけないと おもっていたのに……$"

Route123_Text_CameronRegister:
	.string "{JPN}ぼくには わかる!\n"
	.string "{JPN}ぼくと きみとは また しょうぶする!\l"
	.string "{JPN}かてるか わかんない けど...\p"
	.string "{JPN}ポケナビを だして!$"
	@ TODO: needs JP translation

Route123_Text_CameronRematchIntro:
	.string "{JPN}ぼくは もう だれにも まけないと\n"
	.string "{JPN}おもっているから つよいよ!!$"

Route123_Text_CameronRematchDefeat:
	.string "{JPN}しょんぼり……$"

Route123_Text_CameronPostRematch:
	.string "{JPN}おくりびやまで しゅぎょうでも しようかな\n"
	.string "{JPN}このままじゃ ずっと きみに かてないよ$"

Route123_Text_JackiIntro:
	.string "{JPN}ポケモンも ちょうのうりょくも\n"
	.string "{JPN}つかえるだけじゃ いみ ないわ\p"
	.string "{JPN}きたえてこそ ほんものに なるのよ$"

Route123_Text_JackiDefeat:
	.string "{JPN}すごい!$"

Route123_Text_JackiPostBattle:
	.string "{JPN}だれでも ちょうのうりょくを もっているの\n"
	.string "{JPN}ただ つかいかたを わすれている だけよ$"

Route123_Text_JackiRegister:
	.string "{JPN}もういちど しょうぶして みたいわ!\n"
	.string "{JPN}いいでしょう?$"
	@ TODO: needs JP translation

Route123_Text_JackiRematchIntro:
	.string "{JPN}どう? あなたの なかの\n"
	.string "{JPN}ちょうのうりょく めばえたり した?$"

Route123_Text_JackiRematchDefeat:
	.string "{JPN}すごいわ!$"

Route123_Text_JackiPostRematch:
	.string "{JPN}あなたの つよさ\n"
	.string "{JPN}それも ちょうのうりょく かもね$"

Route123_Text_MiuIntro:
	.string "{JPN}ミウ: トレーナーさんの ポケモン\n"
	.string "{JPN}まけても なかないで くださいね!$"

Route123_Text_MiuDefeat:
	.string "{JPN}ミウ: まけちゃったね……$"

Route123_Text_MiuPostBattle:
	.string "{JPN}ミウ: トレーナーさんの ポケモン\n"
	.string "{JPN}なかが いいから つよいんですね!$"

Route123_Text_MiuNotEnoughMons:
	.string "{JPN}ミウ”ポケモンさん 2ひきは いないと\n"
	.string "{JPN}たたかっても つまらないもん!$"
	@ TODO: needs JP translation

Route123_Text_YukiIntro:
	.string "{JPN}ユキ: よーし!\n"
	.string "{JPN}トレーナーさんの ポケモン やっつけます!$"

Route123_Text_YukiDefeat:
	.string "{JPN}ユキ: まけちゃったね……$"

Route123_Text_YukiPostBattle:
	.string "{JPN}ユキ: どーして そんなに つよいの?\n"
	.string "{JPN}あたちたち たたかって まけたの はじめて!$"

Route123_Text_YukiNotEnoughMons:
	.string "{JPN}ユキ”ポケモンさん 2ひきは いないと\n"
	.string "{JPN}たたかっても つまらないもん!$"
	@ TODO: needs JP translation

Route123_Text_KindraIntro:
	.string "{JPN}おくりびやまは……\n"
	.string "{JPN}ポケモンの たましいが ねむるところ……\p"
	.string "{JPN}あなたの ポケモンも ねむる……?$"

Route123_Text_KindraDefeat:
	.string "{JPN}げんき いっぱいね……$"

Route123_Text_KindraPostBattle:
	.string "{JPN}おくりびやまは……\n"
	.string "{JPN}ポケモンの たましいが ねむるところ……\l"
	.string "{JPN}きっと たましいを なぐさめる\n"
	.string "{JPN}ちからに あふれてるのよ……$"

Route123_Text_FernandoIntro:
	.string "{JPN}いっきょく かなでる あいだに\n"
	.string "{JPN}パッと たおしちゃうゼ!$"

Route123_Text_FernandoDefeat:
	.string "{JPN}おいおい まだ イントロだゼ!$"

Route123_Text_FernandoPostBattle:
	.string "{JPN}きみ やるじゃん\n"
	.string "{JPN}きみの きょくを つくって みたいよ$"

Route123_Text_FernandoRegister:
	.string "{JPN}こんど あった ときには\n"
	.string "{JPN}フルコーラス きいて くれヨ!$"
	@ TODO: needs JP translation

Route123_Text_FernandoRematchIntro:
	.string "{JPN}よし きょうこそ!\n"
	.string "{JPN}1ばんを うたっている あいだに\p"
	.string "{JPN}サッと たおしちゃうゼ!$"

Route123_Text_FernandoRematchDefeat:
	.string "{JPN}おいおい まだ サビまで いってないゼ!$"

Route123_Text_FernandoPostRematch:
	.string "{JPN}オレの うたに ききほれて\n"
	.string "{JPN}まけちゃう って おもってたんだけど$"

Route123_Text_DavisIntro:
	.string "{JPN}ぼくの おにいちゃんに とってもらった\n"
	.string "{JPN}じまんの むしポケモンだよ!$"

Route123_Text_DavisDefeat:
	.string "{JPN}わーん バカーっ!$"

Route123_Text_DavisPostBattle:
	.string "{JPN}まけちゃった こと\n"
	.string "{JPN}ぼくの おにいちゃんには ひみつ だよ!$"

Route123_Text_JazmynIntro:
	.string "{JPN}みるからに つよそうな あなたを\n"
	.string "{JPN}たおせば じしんが つくわね!$"

Route123_Text_JazmynDefeat:
	.string "{JPN}じしん なくしました……$"

Route123_Text_JazmynPostBattle:
	.string "{JPN}ヒトは みためには よらないと いうけど\n"
	.string "{JPN}けっこう みためどおりの ことも あるわね$"

Route123_Text_FrederickIntro:
	.string "{JPN}おい きみきみ\n"
	.string "{JPN}じいちゃんと ちょっと あそぼうか$"

Route123_Text_FrederickDefeat:
	.string "{JPN}つよいこ じゃな\n"
	.string "{JPN}こづかいを やるか$"

Route123_Text_FrederickPostBattle:
	.string "{JPN}え こづかい?\n"
	.string "{JPN}しょうきんを もらったから いいじゃろ!$"

Route123_Text_AlbertoIntro:
	.string "{JPN}オレ マジ とりポケモンが すき!\n"
	.string "{JPN}とりイカス! とりサイコー!$"

Route123_Text_AlbertoDefeat:
	.string "{JPN}まけた とりポケモンも イカス!$"

Route123_Text_AlbertoPostBattle:
	.string "{JPN}しょうぶの あいだに ちらばった\n"
	.string "{JPN}とりポケモンの ハネを あつめて\p"
	.string "{JPN}ぼうしを つくる つもりなんだ!$"

Route123_Text_EdIntro:
	.string "{JPN}トレーナーが いない ときは\n"
	.string "{JPN}じぶんの ポケモンどうしを\p"
	.string "{JPN}たたかわせて ながめて いるぞぅ$"

Route123_Text_EdDefeat:
	.string "{JPN}きみの ポケモンも いいねぃ$"

Route123_Text_EdPostBattle:
	.string "{JPN}へへへ きみの たたかいかたの\n"
	.string "{JPN}アイディア いただき!\p"
	.string "{JPN}つよく なれそう だよぅ$"

Route123_Text_JonasIntro:
	.string "{JPN}まちぶせ していたら\n"
	.string "{JPN}トレーナーが かかったで ござる!$"

Route123_Text_JonasDefeat:
	.string "{JPN}まけて くれなきゃ\n"
	.string "{JPN}ニンジャごっこ できないよ$"

Route123_Text_JonasPostBattle:
	.string "{JPN}つぎは もっと よわそうな トレーナーを\n"
	.string "{JPN}まちぶせ してみるで ござるよ$"

Route123_Text_KayleyIntro:
	.string "{JPN}かった ばかりの パラソルで\n"
	.string "{JPN}わたしも 3わりましで かわいい はず!$"

Route123_Text_KayleyDefeat:
	.string "{JPN}わたしの 5ばい くらい つよいわね$"

Route123_Text_KayleyPostBattle:
	.string "{JPN}こもの づかいも おしゃれの ひけつよ!$"

Route124_Text_SpencerIntro:
	.string "{JPN}おっと みちに まよったのか?\l"
	.string "{JPN}わたしの ポケモンに かてたら\n"
	.string "{JPN}みずさき あんないにんに なってあげようか?$"

Route124_Text_SpencerDefeat:
	.string "{JPN}たたかいかたを まよってしまった……$"

Route124_Text_SpencerPostBattle:
	.string "{JPN}うみで まよってしまう ひとは おおい!\l"
	.string "{JPN}そんな ひとは ポケナビで\n"
	.string "{JPN}マップを たしかめながら すすむと いい!$"

Route124_Text_RolandIntro:
	.string "{JPN}むっ! じぶんで およがずに\n"
	.string "{JPN}ポケモンに のっている……\l"
	.string "{JPN}なんて うらやましいんだ!$"

Route124_Text_RolandDefeat:
	.string "{JPN}ああ!\n"
	.string "{JPN}ダメだ……!$"

Route124_Text_RolandPostBattle:
	.string "{JPN}からだが ひえてきた……\n"
	.string "{JPN}ながいこと みずの なかに いるからだ\l"
	.string "{JPN}きみのように ポケモンに のりたいよ$"

Route124_Text_JennyIntro:
	.string "{JPN}こうして うみに うかんでいると\n"
	.string "{JPN}ポケモンたちが あそびに くるのよ!$"
	@ TODO: needs JP translation

Route124_Text_JennyDefeat:
	.string "{JPN}あーあ\n"
	.string "{JPN}まけちゃった...$"
	@ TODO: needs JP translation

Route124_Text_JennyPostBattle:
	.string "{JPN}うみを およいでいると\n"
	.string "{JPN}おそってくる ポケモンと\l"
	.string "{JPN}ただ みているだけの ポケモンが いるの\p"
	.string "{JPN}ポケモンにも こせいが あるのね!$"
	@ TODO: needs JP translation

Route124_Text_JennyRegister:
	.string "{JPN}なんとなく だけど\n"
	.string "{JPN}ポケナビ とうろく してもらおうかな...$"
	@ TODO: needs JP translation

Route124_Text_JennyRematchIntro:
	.string "{JPN}こうして うみに うかんでいると\n"
	.string "{JPN}トレーナーが いどんで くるのよね!$"
	@ TODO: needs JP translation

Route124_Text_JennyRematchDefeat:
	.string "{JPN}おかしいなあ\n"
	.string "{JPN}また まけちゃった...$"
	@ TODO: needs JP translation

Route124_Text_JennyPostRematch:
	.string "{JPN}なんとなく だけど\n"
	.string "{JPN}カラクリやしきに いってみようかな...$"
	@ TODO: needs JP translation

Route124_Text_GraceIntro:
	.string "{JPN}およぐのにも あきた ところだし……\n"
	.string "{JPN}わたしと しょうぶ しようよ!$"

Route124_Text_GraceDefeat:
	.string "{JPN}こんなに つよいなんて\n"
	.string "{JPN}おもいも しなかったわ!$"

Route124_Text_GracePostBattle:
	.string "{JPN}ずっと がんばって きたことが\n"
	.string "{JPN}あなたの つよさなのね……!$"

Route124_Text_ChadIntro:
	.string "{JPN}うふふふふ\n"
	.string "{JPN}オレは モグリの スイマー\p"
	.string "{JPN}もぐりは とくいちゅうの とくいだぜ!$"

Route124_Text_ChadDefeat:
	.string "{JPN}ゴボゴボゴボ……\n"
	.string "{JPN}しずんでいく……$"

Route124_Text_ChadPostBattle:
	.string "{JPN}うみの そこに もぐれる ポイントが\n"
	.string "{JPN}この あたりには あるらしいぜ!\p"
	.string "{JPN}モグリの ちが さわぐなあ……$"

Route124_Text_LilaIntro:
	.string "{JPN}カコ: はーあ\l"
	.string "{JPN}せっかくの うみ なのに\n"
	.string "{JPN}いっしょに いるのが おとうと なんて……\l"
	.string "{JPN}あなた きばらしに ポケモン しようか!?$"

Route124_Text_LilaDefeat:
	.string "{JPN}カコ: コウの せいで まけたのよ!\n"
	.string "{JPN}あとで おしおき だかんね!!$"

Route124_Text_LilaPostBattle:
	.string "{JPN}カコ: はーあ\l"
	.string "{JPN}となりに いるのが おとうと じゃなくて\n"
	.string "{JPN}すてきな かれし だったら いいのに……$"

Route124_Text_LilaNotEnoughMons:
	.string "{JPN}カコ”あたしたちと たたかう つもり?\n"
	.string "{JPN}ポケモン 2ひき いないと ダメよ$"
	@ TODO: needs JP translation

Route124_Text_RoyIntro:
	.string "{JPN}コウ: オレの ねえちゃん\n"
	.string "{JPN}ポケモン つよいぞ!\p"
	.string "{JPN}まけて ないたり するなよ!$"

Route124_Text_RoyDefeat:
	.string "{JPN}コウ: うわぁ……\n"
	.string "{JPN}あとで ねえちゃんに おこられる……$"

Route124_Text_RoyPostBattle:
	.string "{JPN}コウ: オレの ねえちゃん\n"
	.string "{JPN}おこると むちゃくちゃ こわいんだ……\l"
	.string "{JPN}だから こいびと いないんだぜ……$"

Route124_Text_LilaRoyRegister:
	.string "{JPN}コウ”また こんど しょうぶしてよ\n"
	.string "{JPN}...そのときは てかげんして くれよ!$"
	@ TODO: needs JP translation

Route124_Text_RoyNotEnoughMons:
	.string "{JPN}コウ”オレらと たたかう つもり?\n"
	.string "{JPN}ポケモン 2ひき つれてきなよ!$"
	@ TODO: needs JP translation

Route124_Text_LilaRematchIntro:
	.string "{JPN}カコ: はーあ\l"
	.string "{JPN}せっかくの うみ なのに\n"
	.string "{JPN}いっしょに いるのが おとうと なんて……\l"
	.string "{JPN}あら あなた ひさしぶりね\n"
	.string "{JPN}きばらしに ポケモン しようか!?$"

Route124_Text_LilaRematchDefeat:
	.string "{JPN}カコ: コウったら!\n"
	.string "{JPN}あんたの せいで また まけたでしょ!\p"
	.string "{JPN}あとで とっくん だかんね!!$"

Route124_Text_LilaPostRematch:
	.string "{JPN}カコ: はーあ\l"
	.string "{JPN}あたしに すてきな かれしが いたらなぁ\n"
	.string "{JPN}すてきな コンビネーションで\p"
	.string "{JPN}どんな あいてにでも かっちゃうのに$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "{JPN}カコ”あたしたちと たたかう つもり?\n"
	.string "{JPN}ポケモン 2ひき いないと ダメよ$"
	@ TODO: needs JP translation

Route124_Text_RoyRematchIntro:
	.string "{JPN}コウ: まけたら オレが おこられるから\n"
	.string "{JPN}むちゃくちゃ ほんきで がんばるぞ!$"

Route124_Text_RoyRematchDefeat:
	.string "{JPN}コウ: うわぁ……\n"
	.string "{JPN}また ねえちゃんに おこられる……$"

Route124_Text_RoyPostRematch:
	.string "{JPN}コウ: オレの ねえちゃん\n"
	.string "{JPN}おこると むちゃくちゃ こわいんだ……\l"
	.string "{JPN}あとで オレと ポケモン\n"
	.string "{JPN}もうとっくん だよ……$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "{JPN}コウ”オレらと たたかう つもり?\n"
	.string "{JPN}ポケモン 2ひき つれてきなよ!$"
	@ TODO: needs JP translation

Route124_Text_DeclanIntro:
	.string "{JPN}こんな きれいな うみで\n"
	.string "{JPN}ひとりで およいでいる オレ!\p"
	.string "{JPN}はっきりいって かなしすぎます!$"

Route124_Text_DeclanDefeat:
	.string "{JPN}かなしい\n"
	.string "{JPN}そらの あおさが かなしい$"

Route124_Text_DeclanPostBattle:
	.string "{JPN}ビキニのおねえさんを さそって\n"
	.string "{JPN}えんえいと しゃれこんで みようかな?$"

Route124_Text_IsabellaIntro:
	.string "{JPN}なみのりトレーナー なんかに まけないわ!$"

Route124_Text_IsabellaDefeat:
	.string "{JPN}ううっ ポタポタ\n"
	.string "{JPN}こ これは すいてきよ! ないてないわよ!$"

Route124_Text_IsabellaPostBattle:
	.string "{JPN}きれいな いろの カケラが\n"
	.string "{JPN}この あたりで みつかることが あるわよ$"

Route125_Text_NolenIntro:
	.string "{JPN}キミが やってくる おとが\n"
	.string "{JPN}きこえて いたから まってたよ!$"

Route125_Text_NolenDefeat:
	.string "{JPN}まいりました……!$"

Route125_Text_NolenPostBattle:
	.string "{JPN}くうきちゅう よりも\n"
	.string "{JPN}すいちゅうの ほうが おとの つたわる\p"
	.string "{JPN}スピードが はやいんだよ!$"

Route125_Text_StanIntro:
	.string "{JPN}おらーっ!!\n"
	.string "{JPN}おれの かわいい ポケモンだー!!$"

Route125_Text_StanDefeat:
	.string "{JPN}まいったぜ……!$"

Route125_Text_StanPostBattle:
	.string "{JPN}タッツーの みりょくに まいって\n"
	.string "{JPN}おれも およぐように なったんだー!$"

Route125_Text_TanyaIntro:
	.string "{JPN}およぎ つかれちゃった!\n"
	.string "{JPN}わたしと ひとしょうぶ どう?$"

Route125_Text_TanyaDefeat:
	.string "{JPN}あんた つよすぎ!$"

Route125_Text_TanyaPostBattle:
	.string "{JPN}ふう ふう……\n"
	.string "{JPN}トクサネシティは どっち だったっけ?$"

Route125_Text_SharonIntro:
	.string "{JPN}わたしの そだてた みずポケモンと\n"
	.string "{JPN}たたかって みない?$"

Route125_Text_SharonDefeat:
	.string "{JPN}まけた……$"

Route125_Text_SharonPostBattle:
	.string "{JPN}あなたの つよさは ホンモノね!\n"
	.string "{JPN}おどろいたわ!$"

Route125_Text_ErnestIntro:
	.string "{JPN}オレさまは たくましい ふなのり!\n"
	.string "{JPN}せかいの うみを わたりあるく おとこ!$"

Route125_Text_ErnestDefeat:
	.string "{JPN}ぐおおおーっ!\n"
	.string "{JPN}かてねえ……!$"

Route125_Text_ErnestPostBattle:
	.string "{JPN}あさせのほらあな は じかんによって\n"
	.string "{JPN}しおが みちたり ひいたり するんだ!\l"
	.string "{JPN}ちなみに みちしお から ひきしお まで\n"
	.string "{JPN}およそ 6じかんだぞ! しっていたか?$"

Route125_Text_ErnestRegister:
	.string "{JPN}ポケナビ とうろく して くれたら\n"
	.string "{JPN}いいことを おしえて やるよ!$"
	@ TODO: needs JP translation

Route125_Text_ErnestRematchIntro:
	.string "{JPN}おっと ここで あったが 100ねんめ!\n"
	.string "{JPN}とにかく ポケモンしょうぶ だっ!$"

Route125_Text_ErnestRematchDefeat:
	.string "{JPN}かてねえ\n"
	.string "{JPN}ちっとも かてねえよ!$"

Route125_Text_ErnestRematchPostBattle:
	.string "{JPN}あさせのほらあな……\l"
	.string "{JPN}しおの みちひきに よって\n"
	.string "{JPN}いけたり いけなかったり する\p"
	.string "{JPN}ばしょが あるんだよな\l"
	.string "{JPN}ちなみに みちしお から ひきしお まで\n"
	.string "{JPN}およそ 6じかんだぞ! おぼえておけよ!$"

Route125_Text_KimIntro:
	.string "{JPN}マホ: あさせのほらあなに\n"
	.string "{JPN}へんな じいさんが いるんだって!\p"
	.string "{JPN}あなたも あいにいく とちゅう?$"

Route125_Text_KimDefeat:
	.string "{JPN}マホ: かてると おもったのに$"

Route125_Text_KimPostBattle:
	.string "{JPN}マホ: あさせのほらあなに\n"
	.string "{JPN}へんな じいさんが いるんでしょ?\l"
	.string "{JPN}さっ ナホちゃん あいに いくよ!$"

Route125_Text_KimNotEnoughMons:
	.string "{JPN}マホ”ダメだって!\n"
	.string "{JPN}ポケモン 2ひき いないと ダメだって!$"
	@ TODO: needs JP translation

Route125_Text_IrisIntro:
	.string "{JPN}ナホ: センパイ\n"
	.string "{JPN}こんな ところに なにが あるんですかぁ?$"

Route125_Text_IrisDefeat:
	.string "{JPN}ナホ: とちゅう おしいところ あったのに$"

Route125_Text_IrisPostBattle:
	.string "{JPN}ナホ: センパイ…… ほんとに\n"
	.string "{JPN}あさせのほらあなに はいりますぅ?\p"
	.string "{JPN}ぬれちゃいますよぉ?$"

Route125_Text_IrisNotEnoughMons:
	.string "{JPN}ナホ”2たい1で しょうぶ なんて\n"
	.string "{JPN}そんな まね あたしたちに できないわ$"
	@ TODO: needs JP translation

Route125_Text_PresleyIntro:
	.string "{JPN}とりつかいの ボクが\n"
	.string "{JPN}なぜ うみにまで きているかと いうと……$"

Route125_Text_PresleyDefeat:
	.string "{JPN}わかった\n"
	.string "{JPN}なんで ここに いるか おしえてやるよ$"

Route125_Text_PresleyPostBattle:
	.string "{JPN}あきビンに メールを いれて\n"
	.string "{JPN}さっき うみに ながしたんだ!\l"
	.string "{JPN}きっと かわいい ビキニの おんなのコが\n"
	.string "{JPN}ひろって くれるぜ!$"

Route125_Text_AuronIntro:
	.string "{JPN}こらーッ! おぬしかッ\n"
	.string "{JPN}うみに ゴミを すてたのは!$"

Route125_Text_AuronDefeat:
	.string "{JPN}おぬしでは なかったか$"

Route125_Text_AuronPostBattle:
	.string "{JPN}さっき この あたりで\n"
	.string "{JPN}こきたない ビンを ひろったんじゃ!\p"
	.string "{JPN}うみに ゴミを すてるとは なっとらん!$"

Route126_Text_BarryIntro:
	.string "{JPN}すいえいは ぜんしん うんどう!\n"
	.string "{JPN}たいりょくが つくぞー!$"

Route126_Text_BarryDefeat:
	.string "{JPN}まけましたーっ!$"

Route126_Text_BarryPostBattle:
	.string "{JPN}まいにち およいでる おかげで\n"
	.string "{JPN}みよ! この きんにくっ!!$"

Route126_Text_DeanIntro:
	.string "{JPN}この しろく そびえる いわやまが\n"
	.string "{JPN}ルネシティ なんだぜー!$"

Route126_Text_DeanDefeat:
	.string "{JPN}やられたか!?$"

Route126_Text_DeanPostBattle:
	.string "{JPN}ルネシティの いりぐちが みつからん!\n"
	.string "{JPN}どこに あるんだ?$"

Route126_Text_NikkiIntro:
	.string "{JPN}おほほほっ\n"
	.string "{JPN}わたしは にんぎょ!$"

Route126_Text_NikkiDefeat:
	.string "{JPN}アワと なって きえていく……\n"
	.string "{JPN}ぶくぶくぶく……$"

Route126_Text_NikkiPostBattle:
	.string "{JPN}こっぴどく やられちゃったわ……\n"
	.string "{JPN}アワくって にげだしたい きぶん……$"

Route126_Text_BrendaIntro:
	.string "{JPN}ねえ ねえ\n"
	.string "{JPN}おねえさんと しょうぶ しない?$"

Route126_Text_BrendaDefeat:
	.string "{JPN}いやーんっ!$"

Route126_Text_BrendaPostBattle:
	.string "{JPN}こうして ポケモンと\n"
	.string "{JPN}うみで あそぶのが だいすきなの!$"

Route126_Text_PabloIntro:
	.string "{JPN}からておう より たくましい\n"
	.string "{JPN}この にくたいびを みよ!$"

Route126_Text_PabloDefeat:
	.string "{JPN}おわっ つよいな\n"
	.string "{JPN}いいね! いいね!$"

Route126_Text_PabloPostBattle:
	.string "{JPN}まけて いい しげきに なったよ!\n"
	.string "{JPN}からだも ポケモンも もっと きたえるぜ$"

Route126_Text_PabloRegister:
	.string "{JPN}いやー いいね!\n"
	.string "{JPN}ぜひとも おちかづきに なっておきたいね!$"
	@ TODO: needs JP translation

Route126_Text_PabloRematchIntro:
	.string "{JPN}ビキニのおねえさん より うつくしい\n"
	.string "{JPN}この にくたいびを みよ!$"

Route126_Text_PabloRematchDefeat:
	.string "{JPN}おわっ ほんと つよいな\n"
	.string "{JPN}いいね! いいね!$"

Route126_Text_PabloPostRematch:
	.string "{JPN}よし もっともっと きたえるぜ!\n"
	.string "{JPN}きみは いい しげきに なるから\p"
	.string "{JPN}また きてくれよ!$"

Route126_Text_LeonardoIntro:
	.string "{JPN}きょねん まで およげなかった オレも\n"
	.string "{JPN}かいパンやろうに なれたんだ\p"
	.string "{JPN}いまなら なんでも できる きがする!$"

Route126_Text_LeonardoDefeat:
	.string "{JPN}てへっ よくばりすぎちゃ ダメだよな$"

Route126_Text_LeonardoPostBattle:
	.string "{JPN}なんでも れんしゅう すれば\n"
	.string "{JPN}うまく なるんだ!\l"
	.string "{JPN}キミも わかい うちから\n"
	.string "{JPN}いろいろ やっておけよ!$"

Route126_Text_IsobelIntro:
	.string "{JPN}はなに かいすいが はいると\n"
	.string "{JPN}すっごく つらいよね?$"

Route126_Text_IsobelDefeat:
	.string "{JPN}ああっ!\n"
	.string "{JPN}く くやし……ごほッ!$"

Route126_Text_IsobelPostBattle:
	.string "{JPN}かいすいを ちょっと のんじゃった……!\n"
	.string "{JPN}からいーッ にがいーッ!$"

Route126_Text_SiennaIntro:
	.string "{JPN}わたしの ハートを ぶつけるわ!$"

Route126_Text_SiennaDefeat:
	.string "{JPN}ハートで まけたわ!$"

Route126_Text_SiennaPostBattle:
	.string "{JPN}あつく なっちゃった\n"
	.string "{JPN}ちょっと もぐって こようかな$"

Route127_Text_CamdenIntro:
	.string "{JPN}オレと しょうぶ したいって\n"
	.string "{JPN}かおに かいてあるぜ!$"

Route127_Text_CamdenDefeat:
	.string "{JPN}あわわわわ……$"

Route127_Text_CamdenPostBattle:
	.string "{JPN}いい しょうぶを した あとは\n"
	.string "{JPN}すがすがしい きもちに なるなー$"

Route127_Text_DonnyIntro:
	.string "{JPN}あいつには まけたくない って\n"
	.string "{JPN}ライバル きみには いるの?$"

Route127_Text_DonnyDefeat:
	.string "{JPN}あぁ すっごく くやしい!$"

Route127_Text_DonnyPostBattle:
	.string "{JPN}ライバルが いると\n"
	.string "{JPN}つよくなりたい って きもちが\p"
	.string "{JPN}どんどん あふれて くるよね$"

Route127_Text_JonahIntro:
	.string "{JPN}つりを することで てにいれた\n"
	.string "{JPN}おだやかな こころ...\l"
	.string "{JPN}それを みせて あげましょう...$"
	@ TODO: needs JP translation

Route127_Text_JonahDefeat:
	.string "{JPN}... まけても\n"
	.string "{JPN}こころは おだやかです$"
	@ TODO: needs JP translation

Route127_Text_JonahPostBattle:
	.string "{JPN}つれなくても かまいません\n"
	.string "{JPN}ずっと いとを たらしているのです...$"
	@ TODO: needs JP translation

Route127_Text_HenryIntro:
	.string "{JPN}おっと!? なみのり している\n"
	.string "{JPN}ポケモンを つりあげて しまったか?$"

Route127_Text_HenryDefeat:
	.string "{JPN}かなわん!$"

Route127_Text_HenryPostBattle:
	.string "{JPN}きみの ポケモン つよそうだから\n"
	.string "{JPN}つりあげたら かなりの てごたえ だろうな!$"

Route127_Text_RogerIntro:
	.string "{JPN}よーし!\n"
	.string "{JPN}ポケモンずきと つりずきの たいけつだ!$"

Route127_Text_RogerDefeat:
	.string "{JPN}わあ! いとが からまった!\n"
	.string "{JPN}まさに あとの まつり$"

Route127_Text_RogerPostBattle:
	.string "{JPN}つりでは いとが からまることを\n"
	.string "{JPN}マツリ と いうんだよ$"

Route127_Text_AidanIntro:
	.string "{JPN}とりポケモンは すごく めが いい!\n"
	.string "{JPN}おおぞら たかくから えものを みつけるぜ!$"

Route127_Text_AidanDefeat:
	.string "{JPN}ふぅ…… まいったぜ$"

Route127_Text_AidanPostBattle:
	.string "{JPN}この ちかくには いっぱい\n"
	.string "{JPN}もぐれそうな ところが あるな!\l"
	.string "{JPN}そらから みてると\n"
	.string "{JPN}うみの いろが ちがうから よくわかる!$"

Route127_Text_KojiIntro:
	.string "{JPN}はだしで かけまわると\n"
	.string "{JPN}あしの うらが きたえられるぞ!$"

Route127_Text_KojiDefeat:
	.string "{JPN}いってェ!\n"
	.string "{JPN}ツメの あいだに こいしが……$"

Route127_Text_KojiPostBattle:
	.string "{JPN}はだし さいこう!\n"
	.string "{JPN}だが おまえの その ズックも いいな!$"

Route127_Text_KojiRegister:
	.string "{JPN}おれに かったり するやつは こうだーっ!\n"
	.string "{JPN}また よろしくおねがいします!$"
	@ TODO: needs JP translation

Route127_Text_KojiRematchIntro:
	.string "{JPN}きょうも はだしで かけまわって\n"
	.string "{JPN}あしの うらを きたえまくりだ!$"

Route127_Text_KojiRematchDefeat:
	.string "{JPN}いってェ!\n"
	.string "{JPN}つちふまずに ジャリが……$"

Route127_Text_KojiPostRematch:
	.string "{JPN}しばらく おまえの ズックと\n"
	.string "{JPN}おれの はだし こうかん してみないか?$"

Route127_Text_AthenaIntro:
	.string "{JPN}じっくり ゆっくり しょうぶしましょう\n"
	.string "{JPN}よろしくね!$"

Route127_Text_AthenaDefeat:
	.string "{JPN}せんりゃくを ねる ひまも なかったわ$"

Route127_Text_AthenaPostBattle:
	.string "{JPN}あおい いろに かこまれていると\n"
	.string "{JPN}じかんが すぎるのが\p"
	.string "{JPN}ゆっくりに かんじられる のよ$"

Route128_Text_IsaiahIntro:
	.string "{JPN}サイユウシティは まだ とおい……$"

Route128_Text_IsaiahDefeat:
	.string "{JPN}ボクの はつしょうりも とおい……$"

Route128_Text_IsaiahPostBattle:
	.string "{JPN}まけつづけている じんせい ですが\n"
	.string "{JPN}けっして あきらめませんよ……!$"

Route128_Text_IsaiahRegister:
	.string "{JPN}こんな ボク ですけど\n"
	.string "{JPN}いつかは かてると おもうんです\l"
	.string "{JPN}ポケナビの とうろくを してください...!$"
	@ TODO: needs JP translation

Route128_Text_IsaiahRematchIntro:
	.string "{JPN}まだまだ げんき ですからね\n"
	.string "{JPN}サイユウシティ めざして およぎますよ!$"

Route128_Text_IsaiahRematchDefeat:
	.string "{JPN}また はつしょうり ならず……$"

Route128_Text_IsaiahPostRematch:
	.string "{JPN}あきらめなきゃ いつかは かてる\n"
	.string "{JPN}サイユウシティにも たどりつく……!$"

Route128_Text_KatelynIntro:
	.string "{JPN}トライアスロンは\n"
	.string "{JPN}すいえい じてんしゃ マラソン\l"
	.string "{JPN}3つの しゅもくを つづけて こなす\n"
	.string "{JPN}かこくな レースなの!$"

Route128_Text_KatelynDefeat:
	.string "{JPN}ポケモンしょうぶも かこく よね……$"

Route128_Text_KatelynPostBattle:
	.string "{JPN}つぎは じてんしゃ だけど……\n"
	.string "{JPN}くじけそうだわ……$"

Route128_Text_KatelynRegister:
	.string "{JPN}まあ せっかく だし\n"
	.string "{JPN}またいつか しょうぶを しましょうよ!$"
	@ TODO: needs JP translation

Route128_Text_KatelynRematchIntro:
	.string "{JPN}トライアスロンも ながいけど\n"
	.string "{JPN}ポケモン チャンピオンを めざすのも\p"
	.string "{JPN}ながい みちのり なのね!$"

Route128_Text_KatelynRematchDefeat:
	.string "{JPN}ほんとっ\n"
	.string "{JPN}ポケモンしょうぶ って きびしい……$"

Route128_Text_KatelynPostRematch:
	.string "{JPN}そろそろ チャンピオンロードに\n"
	.string "{JPN}ちょうせん してみるのも あり かな?$"

Route128_Text_AlexaIntro:
	.string "{JPN}ポケモンリーグに ちょうせん するため\n"
	.string "{JPN}いままで がんばって きた……\l"
	.string "{JPN}ここで まけるわけには いかないわ!$"

Route128_Text_AlexaDefeat:
	.string "{JPN}ああっ!\n"
	.string "{JPN}なんてこと$"

Route128_Text_AlexaPostBattle:
	.string "{JPN}ここまで きたんですもの\n"
	.string "{JPN}いちど まけたからって あきらめない$"

Route128_Text_RubenIntro:
	.string "{JPN}わたしの ように つよい\n"
	.string "{JPN}ポケモントレーナーは ほかに いない!$"

Route128_Text_RubenDefeat:
	.string "{JPN}なんて ことだ……!$"

Route128_Text_RubenPostBattle:
	.string "{JPN}きみの ように つよい\n"
	.string "{JPN}ポケモントレーナーは ほかに いないだろう!$"

Route128_Text_WayneIntro:
	.string "{JPN}サイユウに いってみたいから\n"
	.string "{JPN}たきのぼりを おぼえた\p"
	.string "{JPN}ポケモンを つりあげたんだよ!$"

Route128_Text_WayneDefeat:
	.string "{JPN}その いきおい\n"
	.string "{JPN}まさに たきのぼり!$"

Route128_Text_WaynePostBattle:
	.string "{JPN}しまった!\l"
	.string "{JPN}たきのぼりを おぼえた ポケモン つっても\n"
	.string "{JPN}ルネの ジムバッジ もってない!$"

Route128_Text_HarrisonIntro:
	.string "{JPN}きみが また つよそーだもんね!\n"
	.string "{JPN}オレ かてっかな?$"

Route128_Text_HarrisonDefeat:
	.string "{JPN}あっひゃ\n"
	.string "{JPN}やっぱ かてんわな$"

Route128_Text_HarrisonPostBattle:
	.string "{JPN}サイユウシティの まわりは\n"
	.string "{JPN}つよそーな トレーナーが いっぱいだぜ!\p"
	.string "{JPN}オレ ばちがいじゃ ないよな?$"

Route128_Text_CarleeIntro:
	.string "{JPN}この へんは ひざしが\n"
	.string "{JPN}いちだんと つよいわねえ!$"

Route128_Text_CarleeDefeat:
	.string "{JPN}まぶしくて よく みえなかったの!$"

Route128_Text_CarleePostBattle:
	.string "{JPN}そろそろ もどって\n"
	.string "{JPN}ひやけどめ ぬりなおさなきゃ$"

Route129_Text_ChaseIntro:
	.string "{JPN}オレは しょしんしゃ トライアスリート\n"
	.string "{JPN}はじめての レースで きんちょう!$"

Route129_Text_ChaseDefeat:
	.string "{JPN}うおー!\n"
	.string "{JPN}まけてしまったーっ!$"

Route129_Text_ChasePostBattle:
	.string "{JPN}きんちょう していたら\n"
	.string "{JPN}じつりょくが だせないよな!$"

Route129_Text_AllisonIntro:
	.string "{JPN}トライアスロンの とちゅう だけど……\n"
	.string "{JPN}ポケモンしょうぶを しようよ!$"

Route129_Text_AllisonDefeat:
	.string "{JPN}かてると おもったのにーっ!$"

Route129_Text_AllisonPostBattle:
	.string "{JPN}だいしぜんを あいてに\n"
	.string "{JPN}じぶんの ちからを ためす ことも\p"
	.string "{JPN}トライアスロンの だいごみ!$"

Route129_Text_ReedIntro:
	.string "{JPN}ホラホラ!\n"
	.string "{JPN}とっとと しょうぶ しようぜ!$"

Route129_Text_ReedDefeat:
	.string "{JPN}まけた まけたよ\n"
	.string "{JPN}とっとと おわろうぜ!$"

Route129_Text_ReedPostBattle:
	.string "{JPN}まけたら なにも ないさ\n"
	.string "{JPN}とっとと かえると するか!$"

Route129_Text_TishaIntro:
	.string "{JPN}のーんびり のーんびり やりましょうか?$"

Route129_Text_TishaDefeat:
	.string "{JPN}あらら\n"
	.string "{JPN}もっと のんびり したかったなあ$"

Route129_Text_TishaPostBattle:
	.string "{JPN}あせって ミスを するのって イヤでしょ?\n"
	.string "{JPN}のんびり やることに してるのよ$"

Route129_Text_ClarenceIntro:
	.string "{JPN}なみのりも けっこう たいへんだろ?$"

Route129_Text_ClarenceDefeat:
	.string "{JPN}かつのって むずかしいなあ$"

Route129_Text_ClarencePostBattle:
	.string "{JPN}ポケモンリーグを めざしてるのか?\n"
	.string "{JPN}がんばれ がんばれよ!$"

Route130_Text_RodneyIntro:
	.string "{JPN}うみの ドまんなかで\n"
	.string "{JPN}トレーナーに であうとは めずらしいな\p"
	.string "{JPN}イッパツ しょうぶ するか!?$"

Route130_Text_RodneyDefeat:
	.string "{JPN}なんて つよい こどもだ……$"

Route130_Text_RodneyPostBattle:
	.string "{JPN}きびしい たたかいを くぐりぬけてきた\n"
	.string "{JPN}いい めを しているぜ!$"

Route130_Text_KatieIntro:
	.string "{JPN}あおい うみ\n"
	.string "{JPN}ブルーな こころ\p"
	.string "{JPN}いやされる……$"

Route130_Text_KatieDefeat:
	.string "{JPN}うみ ひろく\n"
	.string "{JPN}ポケモン せかい\p"
	.string "{JPN}また ひろし……$"

Route130_Text_KatiePostBattle:
	.string "{JPN}こどもたち\n"
	.string "{JPN}ポケモン チャンプ\p"
	.string "{JPN}めざしてる……$"

Route130_Text_SantiagoIntro:
	.string "{JPN}なにも ない うみに うかんでると……\n"
	.string "{JPN}へいわだなあー……$"

Route130_Text_SantiagoDefeat:
	.string "{JPN}へいわボケ してて まけました!$"

Route130_Text_SantiagoPostBattle:
	.string "{JPN}こうして およいだり しょうぶしたり……\n"
	.string "{JPN}オレ しあわせだなあー……$"

Route131_Text_RichardIntro:
	.string "{JPN}うみには ポケモンが たくさん いるからね\n"
	.string "{JPN}およいで わたるのも くろう するよ!$"

Route131_Text_RichardDefeat:
	.string "{JPN}トレーナーの そだてた ポケモンは\n"
	.string "{JPN}ホントに つよいなぁ……$"

Route131_Text_RichardPostBattle:
	.string "{JPN}ひいひい…… つかれた……\n"
	.string "{JPN}いきは よいよい かえりは こわい……\p"
	.string "{JPN}かえりの たいりょく のこってるかなあ……$"

Route131_Text_HermanIntro:
	.string "{JPN}うみ うみ うみ……\n"
	.string "{JPN}みわたす かぎり うみ……\p"
	.string "{JPN}うみは もう あきたぞーっ!$"

Route131_Text_HermanDefeat:
	.string "{JPN}ひょえええええっ!$"

Route131_Text_HermanPostBattle:
	.string "{JPN}うみに あきても\n"
	.string "{JPN}およぎ つづけるしか ないのか\l"
	.string "{JPN}そんな オレは\n"
	.string "{JPN}ねっからの スイマー……$"

Route131_Text_SusieIntro:
	.string "{JPN}ちょっと あんた\n"
	.string "{JPN}わたしと しょうぶ しましょ!$"

Route131_Text_SusieDefeat:
	.string "{JPN}みかけに よらず\n"
	.string "{JPN}つよいわねーっ!$"

Route131_Text_SusiePostBattle:
	.string "{JPN}あっちで うみは あきた とか いってる\n"
	.string "{JPN}おとこが いるでしょ?\l"
	.string "{JPN}アレ くちだけ なのよ\n"
	.string "{JPN}ホントは うみが すきで しょうがないの!$"

Route131_Text_KaraIntro:
	.string "{JPN}なんで オトコって\n"
	.string "{JPN}ビキニが すき なのかしらね!\l"
	.string "{JPN}みんな わたしの こと\n"
	.string "{JPN}ジロジロ みるのよ!$"

Route131_Text_KaraDefeat:
	.string "{JPN}じつりょくが ちがい すぎるわ……!$"

Route131_Text_KaraPostBattle:
	.string "{JPN}みんな ビキニを みてるんじゃなくて\n"
	.string "{JPN}わたしの びぼうが げんいん かしら……?$"

Route131_Text_ReliIntro:
	.string "{JPN}アミ: きょうだい ちからを あわせて\n"
	.string "{JPN}がんばっちゃおうかな!?$"

Route131_Text_ReliDefeat:
	.string "{JPN}アミ: きょうだいで ちからを あわせても\n"
	.string "{JPN}かてなかったわ$"

Route131_Text_ReliPostBattle:
	.string "{JPN}アミ: キナギの にんげんは\n"
	.string "{JPN}うまれた ときから\p"
	.string "{JPN}うみと ポケモンと いっしょ なんだ$"

Route131_Text_ReliNotEnoughMons:
	.string "{JPN}アミ”ポケモン 2ひき いないの?\n"
	.string "{JPN}ポケモンしょうぶ たのしめないわね$"
	@ TODO: needs JP translation

Route131_Text_IanIntro:
	.string "{JPN}カツ: きょうだい ちからを あわせて\n"
	.string "{JPN}がんばりまーす!!$"

Route131_Text_IanDefeat:
	.string "{JPN}カツ: あねきと がんばったのに\n"
	.string "{JPN}かてなかったよ……$"

Route131_Text_IanPostBattle:
	.string "{JPN}カツ: キナギって うみの うえに\n"
	.string "{JPN}うかんでる まち だろ?\l"
	.string "{JPN}だから うみが つづくかぎり\n"
	.string "{JPN}そこは キナギ なんだよ!$"

Route131_Text_IanNotEnoughMons:
	.string "{JPN}カツ”ポケモン 2ひき いたら\n"
	.string "{JPN}ポケモンしょうぶ してやるよ!$"
	@ TODO: needs JP translation

Route131_Text_TaliaIntro:
	.string "{JPN}わたしに かてたら\n"
	.string "{JPN}すごい じょうほう おしえてあげる!$"

Route131_Text_TaliaDefeat:
	.string "{JPN}あら まけちゃったのね$"

Route131_Text_TaliaPostBattle:
	.string "{JPN}この そばに ふしぎな ばしょが あるわよ\n"
	.string "{JPN}たかい とうが そびえているの!\p"
	.string "{JPN}みてきたら どうかしら?$"

Route131_Text_KevinIntro:
	.string "{JPN}キナギには おおらかな やつ ばかりだぜ!\n"
	.string "{JPN}ぜったい おこったり しないんだ\p"
	.string "{JPN}もちろん オレもな$"

Route131_Text_KevinDefeat:
	.string "{JPN}あ……っ$"

Route131_Text_KevinPostBattle:
	.string "{JPN}ちっ! ……じゃ なかった\n"
	.string "{JPN}お おこってない おこってないよ!\l"
	.string "{JPN}……ハハ つよいね きみは!\n"
	.string "{JPN}はっハッは!$"

Route132_Text_GilbertIntro:
	.string "{JPN}ちいさい ころは よく カゼを ひいたけど\n"
	.string "{JPN}すいえいを はじめて こんなに じょうぶ!$"

Route132_Text_GilbertDefeat:
	.string "{JPN}もっと つよくなりたい……!$"

Route132_Text_GilbertPostBattle:
	.string "{JPN}ポケモン トレーナーも\n"
	.string "{JPN}のやまを あるき まわるから\p"
	.string "{JPN}とっても けんこうてき だよねー!$"

Route132_Text_DanaIntro:
	.string "{JPN}ながれの つよい ところでは\n"
	.string "{JPN}およがないように しているのよ$"

Route132_Text_DanaDefeat:
	.string "{JPN}いやああああんっ!$"

Route132_Text_DanaPostBattle:
	.string "{JPN}ながされると じぶんが どこに いるのか\n"
	.string "{JPN}わからなく なっちゃうの……$"

Route132_Text_RonaldIntro:
	.string "{JPN}かつか まけるか\n"
	.string "{JPN}やれば わかることだろ!$"

Route132_Text_RonaldDefeat:
	.string "{JPN}わーん\n"
	.string "{JPN}まけて しまった$"

Route132_Text_RonaldPostBattle:
	.string "{JPN}かてると わかる しょうぶは しない!\n"
	.string "{JPN}かつか まけるか\p"
	.string "{JPN}その ギリギリの かんじが いいんだ!$"

Route132_Text_KiyoIntro:
	.string "{JPN}24じかん ポケモンのこと かんがえてる\n"
	.string "{JPN}そんな おれに かてると おもうか!?$"
	@ TODO: needs JP translation

Route132_Text_KiyoDefeat:
	.string "{JPN}まけた\n"
	.string "{JPN}おまえさんには まけたわ$"
	@ TODO: needs JP translation

Route132_Text_KiyoPostBattle:
	.string "{JPN}くう...\n"
	.string "{JPN}おまえも ポケモンばか だな!\p"
	.string "{JPN}24じかん ポケモンのこと ばかり\n"
	.string "{JPN}かんがえて いるんだろ!$"
	@ TODO: needs JP translation

Route132_Text_MakaylaIntro:
	.string "{JPN}いつも いっしょの じいさんが\n"
	.string "{JPN}いなくても かてるわい!$"

Route132_Text_MakaylaDefeat:
	.string "{JPN}あら やっぱり ダメかね$"

Route132_Text_MakaylaPostBattle:
	.string "{JPN}あの わかい おとこのこ\n"
	.string "{JPN}じいさんの わかい ころに そっくりじゃ\p"
	.string "{JPN}ポッ……$"

Route132_Text_JonathanIntro:
	.string "{JPN}さっき から へんな しせんを\n"
	.string "{JPN}かんじると おもったら キミか?$"

Route132_Text_JonathanDefeat:
	.string "{JPN}へえ! つよいね!$"

Route132_Text_JonathanPostBattle:
	.string "{JPN}だれかが ぼくの ことを\n"
	.string "{JPN}みているきが して おちつかないっ!$"

Route132_Text_PaxtonIntro:
	.string "{JPN}いつも いっしょの ばあさんは どこかな?\n"
	.string "{JPN}ひとりで かてるじゃろか$"

Route132_Text_PaxtonDefeat:
	.string "{JPN}ああ やっぱり ダメかね$"

Route132_Text_PaxtonPostBattle:
	.string "{JPN}ばあさんも わしを さがしてるじゃろ\n"
	.string "{JPN}はよう みつけて やらんと$"

Route132_Text_DarcyIntro:
	.string "{JPN}ひとりで この ばしょで\n"
	.string "{JPN}しゅぎょう するのが すきだったのに!\p"
	.string "{JPN}おおぜい やって くるんだもの ひどい!$"

Route132_Text_DarcyDefeat:
	.string "{JPN}わかったわよ\n"
	.string "{JPN}みんなで つかえば いいんでしょ$"

Route132_Text_DarcyPostBattle:
	.string "{JPN}とりあえず そこの おじいさんと くんで\n"
	.string "{JPN}むこうの チームに いどんで みようかな?$"

Route133_Text_FranklinIntro:
	.string "{JPN}キミも しおに ながされて きたの?\n"
	.string "{JPN}これも なにかの えんだね\p"
	.string "{JPN}しょうぶ しようよ!$"

Route133_Text_FranklinDefeat:
	.string "{JPN}つよい!\n"
	.string "{JPN}つよすぎっ!$"

Route133_Text_FranklinPostBattle:
	.string "{JPN}キミみたいな つよい トレーナーが\n"
	.string "{JPN}ながされて くるなんて……\p"
	.string "{JPN}オレも ツキが ないなぁ……$"

Route133_Text_DebraIntro:
	.string "{JPN}わたしは かなしい おんな……\n"
	.string "{JPN}ながれ ながれて ここまで きたの……$"

Route133_Text_DebraDefeat:
	.string "{JPN}まけたぁ……$"

Route133_Text_DebraPostBattle:
	.string "{JPN}ながされる だけの じんせい なんて……\n"
	.string "{JPN}もう イヤっ!$"

Route133_Text_LindaIntro:
	.string "{JPN}いらっしゃーい!\n"
	.string "{JPN}おまち してましたわ!$"

Route133_Text_LindaDefeat:
	.string "{JPN}いやーん!$"

Route133_Text_LindaPostBattle:
	.string "{JPN}つよい こどもの トレーナーなんて……\n"
	.string "{JPN}おねえさん こまっちゃうぅ!$"

Route133_Text_WarrenIntro:
	.string "{JPN}かちたいから って\n"
	.string "{JPN}ひとと おなじように そだては しないぜ!$"

Route133_Text_WarrenDefeat:
	.string "{JPN}くそー!\n"
	.string "{JPN}おれの やりかたは まだまだ あまい!$"

Route133_Text_WarrenPostBattle:
	.string "{JPN}ひとと おなじこと するより\n"
	.string "{JPN}じぶんの したいこと したほうが\p"
	.string "{JPN}たのしいに きまってるだろ!$"

Route133_Text_BeckIntro:
	.string "{JPN}とりポケモンと いっしょに\n"
	.string "{JPN}こんな ところまで きました$"

Route133_Text_BeckDefeat:
	.string "{JPN}きみ……\n"
	.string "{JPN}なんて かっこいいんだ!$"

Route133_Text_BeckPostBattle:
	.string "{JPN}そろそろ ヒワマキに かえりたいけど\n"
	.string "{JPN}なんとなく ここ すきに なっちゃったぞ!?$"

Route133_Text_MollieIntro:
	.string "{JPN}いままでに なんぜんかい\n"
	.string "{JPN}ポケモン しょうぶを したかねえ$"

Route133_Text_MollieDefeat:
	.string "{JPN}なんぜんかい まけても\n"
	.string "{JPN}くやしい もんは くやしいでね$"

Route133_Text_MolliePostBattle:
	.string "{JPN}わたいや じいさんのような\n"
	.string "{JPN}たつじんを めざして がんばんなせえ$"

Route133_Text_ConorIntro:
	.string "{JPN}わかい やつらは\n"
	.string "{JPN}ながされて ばっかりで なさけねぇ!$"

Route133_Text_ConorDefeat:
	.string "{JPN}きみは しっかりしとるな$"

Route133_Text_ConorPostBattle:
	.string "{JPN}まわりに ながされず\n"
	.string "{JPN}しっかりした おとなに なんなさい!$"

Route134_Text_JackIntro:
	.string "{JPN}およぎの とくいな ポケモンだって\n"
	.string "{JPN}ながされる しおの ながれだ!$"

Route134_Text_JackDefeat:
	.string "{JPN}ひえーっ!$"

Route134_Text_JackPostBattle:
	.string "{JPN}ポケモンたちは この ながれを\n"
	.string "{JPN}たのしんでる みたいだよ!$"

Route134_Text_LaurelIntro:
	.string "{JPN}わたしの ラブカスたちと\n"
	.string "{JPN}たのしく しょうぶ しましょうよ!$"

Route134_Text_LaurelDefeat:
	.string "{JPN}あらららららっ!$"

Route134_Text_LaurelPostBattle:
	.string "{JPN}どこかの マニアが\n"
	.string "{JPN}ラブカスの ウロコを あつめてるのよねー$"

Route134_Text_AlexIntro:
	.string "{JPN}よーしっ! きゅうけい おわり!\n"
	.string "{JPN}ポケモンしょうぶ しようぜ!$"

Route134_Text_AlexDefeat:
	.string "{JPN}また バテた……$"

Route134_Text_AlexPostBattle:
	.string "{JPN}オレの とりポケモンたち……\n"
	.string "{JPN}ながいあいだ とぶと すぐに バテるんだ$"

Route134_Text_HitoshiIntro:
	.string "{JPN}ポケモントレーナーなら\n"
	.string "{JPN}だまって ポケモンしょうぶ!$"
	@ TODO: needs JP translation

Route134_Text_HitoshiDefeat:
	.string "{JPN}… … … … … …\n"
	.string "{JPN}… … … … … …$"
	@ TODO: needs JP translation

Route134_Text_HitoshiPostBattle:
	.string "{JPN}じぶんから しょうぶを いどんでおいて\n"
	.string "{JPN}まけるとは... はずかしすぎる...$"
	@ TODO: needs JP translation

Route134_Text_AaronIntro:
	.string "{JPN}このあたりの はげしい しおの ながれ!\n"
	.string "{JPN}それもまた おれたちを きたえてくれる!$"

Route134_Text_AaronDefeat:
	.string "{JPN}すなおに まけを みとめよう$"

Route134_Text_AaronPostBattle:
	.string "{JPN}りゅうせいのたきで\n"
	.string "{JPN}しゅぎょう しなおすと しよう!\l"
	.string "{JPN}よければ きみも いってみたまえ\n"
	.string "{JPN}きっと いまより つよくなる!$"

Route134_Text_KelvinIntro:
	.string "{JPN}ふ ふねが\n"
	.string "{JPN}ながされて しまったんです$"

Route134_Text_KelvinDefeat:
	.string "{JPN}あわわわわ\n"
	.string "{JPN}やめてください やめてくださいよ!$"

Route134_Text_KelvinPostBattle:
	.string "{JPN}このうえ なみのり まで できなかったら\n"
	.string "{JPN}かえれないじゃ ないですか!\l"
	.string "{JPN}……まあ ひんしでも なみのり できますけど\n"
	.string "{JPN}きぶんてきに よろしくなくて$"

Route134_Text_MarleyIntro:
	.string "{JPN}すばやい こうげきを かわせますこと?$"

Route134_Text_MarleyDefeat:
	.string "{JPN}そんな てが あるなんて……!\n"
	.string "{JPN}かんぱい ですわ$"

Route134_Text_MarleyPostBattle:
	.string "{JPN}すばやさへの こだわりは すてきれないの\n"
	.string "{JPN}もっと がんばって みますわ!$"

Route134_Text_ReynaIntro:
	.string "{JPN}あたいの ポケモンは\n"
	.string "{JPN}ちょっとや そっとじゃ たおせないよ!$"

Route134_Text_ReynaDefeat:
	.string "{JPN}うっそだろ!\n"
	.string "{JPN}あたいが まけるなんて!$"

Route134_Text_ReynaPostBattle:
	.string "{JPN}ははっ あんたにゃ まけたよ!\l"
	.string "{JPN}そこらへんの トレーナーでも たおして\n"
	.string "{JPN}いちから しゅぎょう しなおすよ!$"

Route134_Text_HudsonIntro:
	.string "{JPN}なあ このへんで\n"
	.string "{JPN}もうひとり ふなのりを みなかった?$"

Route134_Text_HudsonDefeat:
	.string "{JPN}おー すごいな$"

Route134_Text_HudsonPostBattle:
	.string "{JPN}おれたちの ふねが ながされちゃってさ!\l"
	.string "{JPN}あいぼうが きの よわい やつだから\n"
	.string "{JPN}しんぱい してるんだ$"
