LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "{JPN}おや? あなた ポケモンコンテストに\n"
	.string "{JPN}さんかして いましたね!\l"
	.string "{JPN}その ポケモンを みれば わかりますよ!\p"
	.string "{JPN}わたくし ポケモンコンテストに ついて\n"
	.string "{JPN}きじを かいて いるのですが\p"
	.string "{JPN}できれば すこし かんそうを\n"
	.string "{JPN}きかせて くれませんかね?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "{JPN}ほんとう ですか!\n"
	.string "{JPN}ありがとう ございます\p"
	.string "{JPN}それでは いまの コンテストの かんそうを\n"
	.string "{JPN}ひとことで おねがいします!$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "{JPN}うーん なるほど!\p"
	.string "{JPN}どんな コンテストだったか\n"
	.string "{JPN}よくわかる ひとこと ですね!\p"
	.string "{JPN}......さいごに\n"
	.string "{JPN}ちょっと おききしたいの ですが\p"
	.string "{JPN}あなたが イメージする {STR_VAR_2}って\n"
	.string "{JPN}いったい どんなもの ですかね?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "{JPN}なるほど!\p"
	.string "{JPN}それが あなたの イメージする\n"
	.string "{JPN}{STR_VAR_2} なんですね!\p"
	.string "{JPN}いろいろ さんこうに なりました!\p"
	.string "{JPN}コンテストに ついて\n"
	.string "{JPN}いい きじが かけそう ですよ\p"
	.string "{JPN}もしかしたら テレビで このことが\n"
	.string "{JPN}ながれるかも しれないので\l"
	.string "{JPN}たのしみに してくださいね!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "{JPN}そうですか......\p"
	.string "{JPN}こんど おもしろいことが あれば\n"
	.string "{JPN}きかせて くださいね$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "{JPN}こんどの ポケモンコンテストも\n"
	.string "{JPN}たのしみに してますよ!$"

gTVBravoTrainerText00::
	.string "{JPN}イヤー!\n"
	.string "{JPN}“ブラボー トレーナー”の じかんだ!\p"
	.string "{JPN}きょうは {STR_VAR_3}クラスの\n"
	.string "{JPN}{STR_VAR_2}を ほこる\l"
	.string "{JPN}{STR_VAR_1}さんの ポケモン!$"

gTVBravoTrainerText01::
	.string "{JPN}{STR_VAR_1} の ‘{STR_VAR_2}’の\n"
	.string "{JPN}しょうかいだー!\p"
	.string "{JPN}‘{STR_VAR_2}’か......\p"
	.string "{JPN}もう ニックネーム からして\n"
	.string "{JPN}{STR_VAR_3}が にじみ でているぜ!$"

gTVBravoTrainerText02::
	.string "{JPN}さーて この {STR_VAR_1}さんが\n"
	.string "{JPN}ポケモンコンテストに さんか したとき\p"
	.string "{JPN}じぶんの ポケモンに ついて\n"
	.string "{JPN}あつく はなして くれたぞ!$"

gTVBravoTrainerText03::
	.string "{JPN}コンテストを したあとの\n"
	.string "{JPN}かんそうを きくと\l"
	.string "{JPN}すごく うれしそうに\p"
	.string "{JPN}‘{STR_VAR_2}’って\n"
	.string "{JPN}こたえて くれたぞ!\p"
	.string "{JPN}まあ コンテストでは\n"
	.string "{JPN}{STR_VAR_3}ばん でした からねー!\p"
	.string "{JPN}いまの {STR_VAR_1}さんには\n"
	.string "{JPN}ぴったりの セリフだよ まったく!$"

gTVBravoTrainerText04::
	.string "{JPN}コンテストを したあとの\n"
	.string "{JPN}かんそうを きくと\l"
	.string "{JPN}びみょうに くやしがり ながら\p"
	.string "{JPN}‘{STR_VAR_2}’って\n"
	.string "{JPN}こたえて くれたぞ!\p"
	.string "{JPN}まあ コンテストでは\n"
	.string "{JPN}{STR_VAR_3}ばん でした からねー!\p"
	.string "{JPN}この ことばに {STR_VAR_1}さんの\n"
	.string "{JPN}くやしさが みえかくれ するねー$"

gTVBravoTrainerText05::
	.string "{JPN}ところで {STR_VAR_1}さんの めざしてる\n"
	.string "{JPN}{STR_VAR_2}って いったい なんだろう?\l"
	.string "{JPN}きいて みたいねー!\p"
	.string "{JPN}もちろん きいて きました!\p"
	.string "{JPN}それは つぎの ひとことに\n"
	.string "{JPN}すべてが つまって います!\p"
	.string "{JPN}それは ‘{STR_VAR_3}!’\p"
	.string "{JPN}それこそ {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}の すべて なんです!$"

gTVBravoTrainerText06::
	.string "{JPN}さいごに {STR_VAR_1}が\n"
	.string "{JPN}つかった {STR_VAR_2}も\l"
	.string "{JPN}すべて ‘{STR_VAR_3}’ なんです!$"

gTVBravoTrainerText07::
	.string "{JPN}ブラボー! {STR_VAR_1}\n"
	.string "{JPN}ブラボー!! {STR_VAR_2}\p"
	.string "{JPN}こんごの {STR_VAR_1}さんの かつやくに\n"
	.string "{JPN}きたい したいねー!\p"
	.string "{JPN}それじゃあ また じかいの\n"
	.string "{JPN}ほうそうで あいましょー!$"

gTVBravoTrainerText08::
	.string "{JPN}{STR_VAR_1} の しょうかいだー!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "{JPN}あ! いま たたかっていた\n"
	.string "{JPN}トレーナーの かたですね!\p"
	.string "{JPN}わたし いま いろんな トレーナーの\n"
	.string "{JPN}はなしを きいて まわってるんだけど\p"
	.string "{JPN}たたかいおわった かんそうを\n"
	.string "{JPN}すこしだけ きかせて もらえませんか?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "{JPN}ほんと!?\n"
	.string "{JPN}ありがとう!\l"
	.string "{JPN}えっと それじゃあねぇ......\p"
	.string "{JPN}こんかいの バトルタワーの\n"
	.string "{JPN}たいせんは どうでしたか\p"
	.string "{JPN}まんぞく でしたか!\n"
	.string "{JPN}それとも ふまん ですか!?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "{JPN}あぁ!\n"
	.string "{JPN}ごめんなさい\p"
	.string "{JPN}じゃあ またこんど バトルタワーに きたら\n"
	.string "{JPN}きかせて くださいね$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "{JPN}さっすが!\p"
	.string "{JPN}その まんぞくした かおを みれば\n"
	.string "{JPN}どんなに いいしあいだったか\l"
	.string "{JPN}わかりますよ!$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "{JPN}うーん そうですか......\p"
	.string "{JPN}おもいどおりに しょうぶを するのって\n"
	.string "{JPN}なかなか むずかしい ですからね......$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "{JPN}あぁっ あと\n"
	.string "{JPN}もう ひとつだけ いいですか?\p"
	.string "{JPN}この たたかいの かんそうを\n"
	.string "{JPN}ひとことで ビシッと きかせてください!$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "{JPN}かっこいー!!\p"
	.string "{JPN}いい きめゼリフ ですね\n"
	.string "{JPN}つぎの たたかいも きたい してますよ\p"
	.string "{JPN}それでは また!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "{JPN}そうですか......\p"
	.string "{JPN}でも なにも いわないのも\n"
	.string "{JPN}また かっこいいですね!\p"
	.string "{JPN}それじゃあ またの きかいに\n"
	.string "{JPN}かんそうを きかせて ください!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "{JPN}つぎの たたかいも\n"
	.string "{JPN}きたい してますよ$"

BravoTrainerBattleTower_Text_Intro::
	.string "{JPN}イヤー!\n"
	.string "{JPN}“ブラボー トレーナー”の じかんだ!\p"
	.string "{JPN}きょうは バトルタワーに ちょうせんした\n"
	.string "{JPN}{STR_VAR_1}さんの しょうかいだー!\p"
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}を\n"
	.string "{JPN}つかった たたかいをして$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "{JPN}なんと {STR_VAR_1}の へやで\n"
	.string "{JPN}{STR_VAR_2}れんしょう という\l"
	.string "{JPN}きろくを うちたてたぞ!$"

BravoTrainerBattleTower_Text_Lost::
	.string "{JPN}おしくも {STR_VAR_2}にんめで たたかった\n"
	.string "{JPN}{STR_VAR_1}さんに まけて しまいました\l"
	.string "{JPN}うーん! ざんねんだねぇ\p"
	.string "{JPN}でも こんなはじめに {STR_VAR_1}さんに\n"
	.string "{JPN}あたるとは うんがないとしか いえないよ\p"
	.string "{JPN}さて その {STR_VAR_1}さんとの\n"
	.string "{JPN}しょうぶの かんそうを きいたところ$"

BravoTrainerBattleTower_Text_Won::
	.string "{JPN}さいごには {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}を みごとに たおして\l"
	.string "{JPN}しょうり したんですねぇ\p"
	.string "{JPN}いや {STR_VAR_1}さんに かつなんて\n"
	.string "{JPN}すごいとしか いいようがないよ まったく\p"
	.string "{JPN}さて そのしょうりを つかんだ\n"
	.string "{JPN}しゅんかんの かんそうを きいたところ$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "{JPN}しかし さいごに とうじょうした\n"
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}に\l"
	.string "{JPN}ついに まけて しまったんですねぇ\p"
	.string "{JPN}まあ ‘{STR_VAR_1}の {STR_VAR_2}’\n"
	.string "{JPN}といえば ゆうめいな コンビ ですからね\p"
	.string "{JPN}......さて その ゆうめいじんとの\n"
	.string "{JPN}しょうぶの かんそうを きいたところ$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "{JPN}まんぞく した!!\p"
	.string "{JPN}と すがすがしく こたえてくれたよ\n"
	.string "{JPN}さすがだぜ!\p"
	.string "{JPN}まんぞくいく たたかいが できるなんて\n"
	.string "{JPN}ほんと すごいよねぇ まったく!\p"
	.string "{JPN}その まんぞくかんは つぎの ひとことを\n"
	.string "{JPN}きいたとき すべて わかったよ$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "{JPN}ふまんだった......\p"
	.string "{JPN}と びみょうに おちこみながら\n"
	.string "{JPN}こたえて くれたよ\p"
	.string "{JPN}......まあ まんぞくいく たたかいって\n"
	.string "{JPN}なかなかできる もんじゃないからねー\p"
	.string "{JPN}そのときの くやしさは\n"
	.string "{JPN}つぎの ひとことが よくあらわしてるよ$"

BravoTrainerBattleTower_Text_None1::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_None2::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_None3::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_None4::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_Response::
	.string "{JPN}その ことばは\n"
	.string "‘{STR_VAR_1}!’$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "{JPN}‘{STR_VAR_1}!’\n"
	.string "{JPN}うーん  いい ことばだねぇ!!\p"
	.string "{JPN}{STR_VAR_2}さんの うれしさを\n"
	.string "{JPN}このことばが よく あらわしているよ!\p"
	.string "{JPN}たしかに {STR_VAR_3}さんとの たたかいは\n"
	.string "{JPN}まさに ‘{STR_VAR_1}’ という\l"
	.string "{JPN}かんじ だったからねぇ!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "{JPN}‘{STR_VAR_1}!’\n"
	.string "{JPN}なるほどねぇ\p"
	.string "{JPN}たしかに {STR_VAR_3}さんとの たたかいは\n"
	.string "{JPN}‘{STR_VAR_1}’ としか いいようがない\l"
	.string "{JPN}たたかい でしたからねぇ\p"
	.string "{JPN}{STR_VAR_2}さんの くやしさが\n"
	.string "{JPN}よく つたわってくるよ! くー!$"

BravoTrainerBattleTower_Text_Outro::
	.string "{JPN}ブラボー! {STR_VAR_1}\n"
	.string "{JPN}ブラボー!! {STR_VAR_2}\p"
	.string "{JPN}こんごの {STR_VAR_1}さんの かつやくに\n"
	.string "{JPN}きたい したいねぇ!\p"
	.string "{JPN}それじゃあ また じかいの\n"
	.string "{JPN}ほうそうで あいましょー!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "{JPN}わあ!\p"
	.string "{JPN}きみ その {STR_VAR_1}を とても\n"
	.string "{JPN}だいじに している みたいね!\p"
	.string "{JPN}{STR_VAR_2} って いうんだ......\p"
	.string "{JPN}そうだ!\p"
	.string "{JPN}いま わたし テレビの しゅざいで\n"
	.string "{JPN}ポケモンの アンケートを してるんだけど\p"
	.string "{JPN}すこしだけ しつもんに\n"
	.string "{JPN}こたえて くれないかな?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "{JPN}ありがとう!\p"
	.string "{JPN}じゃあ きくね\n"
	.string "{JPN}ずばり ひとことで こたえて!$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "{JPN}きみが {STR_VAR_1}と\n"
	.string "{JPN}であったときって\p"
	.string "{JPN}なにか かんじた?\n"
	.string "{JPN}どう おもったか おしえて!$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "{JPN}きみの かわいがってる {STR_VAR_1}!\p"
	.string "{JPN}もし なにか すきなものに たとえると\n"
	.string "{JPN}すれば なんだと おもう?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "{JPN}きみの かわいがってる {STR_VAR_1}!\p"
	.string "{JPN}きみは {STR_VAR_1}の どこに\n"
	.string "{JPN}ひかれたの?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "{JPN}うーん なるほどね\p"
	.string "{JPN}じゃあ つぎは ちょっと\n"
	.string "{JPN}むずかしい しつもんを するね!\p"
	.string "{JPN}じゃあ......\p"
	.string "{JPN}きみに とって ポケモンって\n"
	.string "{JPN}ひとことで いうと なんだと おもう?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "{JPN}なるほどー!\p"
	.string "{JPN}ふむふむ......\p"
	.string "{JPN}あ!\n"
	.string "{JPN}きょうりょく ありがとうね!\p"
	.string "{JPN}いろいろ はなしが きけて\n"
	.string "{JPN}おもしろ かったよ\p"
	.string "{JPN}このはなし もしかしたら テレビで\n"
	.string "{JPN}ながすかも しれないから きたい しててね\p"
	.string "{JPN}じゃあね\n"
	.string "{JPN}バイバイ!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "{JPN}そっか......\p"
	.string "{JPN}じゃあ また ポケモンの ことを\n"
	.string "{JPN}はなしたく なったら いつでも きてね$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "{JPN}ここに いると いろんな ポケモンの\n"
	.string "{JPN}はなしが きけるから おもしろいわ$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "{JPN}きみの その {STR_VAR_1}と\n"
	.string "{JPN}とても なかが よさそうね\p"
	.string "{JPN}そうだ! いま わたし\n"
	.string "{JPN}テレビの しゅざいで\p"
	.string "{JPN}いろんな ポケモンの はなしを\n"
	.string "{JPN}きいて まわってるんだけど\p"
	.string "{JPN}よかったら きみの {STR_VAR_1}の\n"
	.string "{JPN}はなしを きかせて くれないかな?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "{JPN}わあ!\n"
	.string "{JPN}ありがとう!\p"
	.string "{JPN}じゃあ {STR_VAR_1}の はなし\n"
	.string "{JPN}なんでも いいので きかせてよ!$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "{JPN}へー......\n"
	.string "{JPN}おもしろい はなし だね!\p"
	.string "{JPN}きみは ほんとうに {STR_VAR_1}と\n"
	.string "{JPN}なかが いいんだね\p"
	.string "{JPN}うーん なんか このはなしで\n"
	.string "{JPN}いい ばんぐみが できそうな よかん!\p"
	.string "{JPN}きっと おもしろい ばんぐみに\n"
	.string "{JPN}するから たのしみに まっててね\p"
	.string "{JPN}じゃあ ありがとうね\n"
	.string "{JPN}バイバイ!$"

gTVFanClubOpinionsText00::
	.string "{JPN}“ぼくたち!\n"
	.string "{JPN}ポケモン だいすきクラブ!”\p"
	.string "{JPN}はい はじまりました!\p"
	.string "{JPN}このばんぐみは みなさんの\n"
	.string "{JPN}いけんを このわたしが\l"
	.string "{JPN}かわりに さけんで しまおう!\l"
	.string "{JPN}という すごい ばんぐみ!!\p"
	.string "{JPN}さて きょうは ポケモンだいすきクラブ に\n"
	.string "{JPN}いって いろんな はなしを きいてきた\l"
	.string "{JPN}リポーターからの じょうほうだ!\p"
	.string "{JPN}さて きょうの\n"
	.string "{JPN}ポケモンだいすき にんげんは?\p"
	.string "{JPN}んー......\p"
	.string "{JPN}{STR_VAR_1}さんだー!!\p"
	.string "{JPN}それでは ごじぶんの ポケモン\p"
	.string "{JPN}{STR_VAR_2}の ‘{STR_VAR_3}’に\n"
	.string "{JPN}ついての あつい きもちを\p"
	.string "{JPN}かわりに この わたくしが テレビに\n"
	.string "{JPN}むかって さけんで あげましょう!\p"
	.string "{JPN}うー!!\p"
	.string "{JPN}レッツ シャウト!!!$"

gTVFanClubOpinionsText01::
	.string "{JPN}さて {STR_VAR_1}さんが はじめて\n"
	.string "{JPN}{STR_VAR_2}と あったとき ちょっかんてきに\l"
	.string "{JPN}おもった ことは......\l"
	.string "......\p"
	.string "‘{STR_VAR_3}!!’\p"
	.string "{JPN}んー いい さけびだ!\p"
	.string "{JPN}まるで そのときの おもいでが\n"
	.string "{JPN}よみがえる ようだー!!$"

gTVFanClubOpinionsText02::
	.string "{JPN}さて {STR_VAR_1}さんの だいすきな\n"
	.string "{JPN}{STR_VAR_2}を なにかに たとえると したら\l"
	.string "......\p"
	.string "‘{STR_VAR_3}!!’\p"
	.string "{JPN}んー すごい はっそうだ!!\p"
	.string "{JPN}はげしい {STR_VAR_2}への おもいこみが\n"
	.string "{JPN}かんじられるねー!$"

gTVFanClubOpinionsText03::
	.string "{JPN}さて {STR_VAR_1}さんが {STR_VAR_2}に\n"
	.string "{JPN}ひかれた りゆうは......\l"
	.string "......\p"
	.string "‘{STR_VAR_3}!!’\p"
	.string "{JPN}おー!! すんばらしい いけんだー!\p"
	.string "{JPN}{STR_VAR_2}を どんなに すきか\n"
	.string "{JPN}ビンビン つたわって くるねー!$"

gTVFanClubOpinionsText04::
	.string "{JPN}んー? まだ つづきが ありますねー\n"
	.string "{JPN}よんで みましょう!\p"
	.string "{JPN}えーと......\p"
	.string "{JPN}{STR_VAR_1}さんに とって ポケモンを\n"
	.string "{JPN}ひとことで たとえると すれば それは!\l"
	.string "......\p"
	.string "‘{STR_VAR_3}!!’\p"
	.string "{JPN}ブラボー!!\p"
	.string "{JPN}いままでの なかで いちばん\n"
	.string "{JPN}いい さけび だったー!\p"
	.string "‘{STR_VAR_3}!!’\p"
	.string "{JPN}なんども さけびたくなる ことばだねー!\p"
	.string "{JPN}それでは いいさけびと であった ところで\n"
	.string "{JPN}また じかい おあいしましょう!\p"
	.string "{JPN}さいごに もういちど\n"
	.string "{JPN}みんなで さけびましょう!\p"
	.string "‘{STR_VAR_3}!!’$"

gTVFanClubText00::
	.string "{JPN}“ぼくたち!\n"
	.string "{JPN}ポケモン だいすきクラブ!”\p"
	.string "{JPN}はい はじまりました!\p"
	.string "{JPN}じゃあ きょうは ポケモンアンケートの\n"
	.string "{JPN}コーナーから!\p"
	.string "{JPN}かずある ポケモンと トレーナーの\n"
	.string "{JPN}はなしの なかから\p"
	.string "{JPN}きょうは どんな はなしが\n"
	.string "{JPN}とびだして くるのでしょうか!?\l"
	.string "{JPN}さて きょうの はなしは?\p"
	.string "{JPN}んー......\p"
	.string "{JPN}これだ!\p"
	.string "{JPN}では てがみの しょうかい から!!\p"
	.string "{JPN}{STR_VAR_2}の ことに ついて\n"
	.string "{JPN}{STR_VAR_1}さん からの おてがみだー\p"
	.string "{JPN}では どれだけ {STR_VAR_2}への\n"
	.string "{JPN}あつい いけんが かいてあるか\l"
	.string "{JPN}よませて もらいましょう!\l"
	.string "{JPN}えーと......$"

gTVFanClubText01::
	.string "{JPN}おー!!\n"
	.string "{JPN}なんて すばらしい てがみなんだ!!$"

gTVFanClubText02::
	.string "{JPN}きにいったから もういちど!$"

gTVFanClubText03::
	.string "{JPN}いい てがみは\n"
	.string "{JPN}なんど きいても いいねー!!$"

gTVFanClubText04::
	.string "{JPN}‘{STR_VAR_3}’ っていう ことばの\n"
	.string "{JPN}おかげで グッと こころに つたわってくる\l"
	.string "{JPN}いい てがみに なっているねー!!$"

gTVFanClubText05::
	.string "{JPN}とくに‘{STR_VAR_3}’って ところ!\p"
	.string "{JPN}‘{STR_VAR_3}’っていう ところが\n"
	.string "{JPN}きにいったぞー!$"

gTVFanClubText06::
	.string "{JPN}ところで あんまり かんけい ないけど\n"
	.string "{JPN}‘{STR_VAR_3}’って いいことば だよね\p"
	.string "{JPN}じつは おれも ‘{STR_VAR_3}’って\n"
	.string "{JPN}ことば さいきん よく つかうんだよね$"

gTVFanClubText07::
	.string "{JPN}このてがみ じぶんてきには\n"
	.string "{JPN}{STR_VAR_3}てん ていう かんじかなー!\p"
	.string "{JPN}つぎは もっと いい てがみを\n"
	.string "{JPN}きたい してるよ! {STR_VAR_1}さん!!\p"
	.string "{JPN}おっと もう こんなじかんだ!\n"
	.string "{JPN}それでは また じかい\l"
	.string "{JPN}みなさま おあい しましょう!!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "{JPN}おや?\n"
	.string "{JPN}あなたも ポケモンのことが おすきで?\p"
	.string "{JPN}わたくし テレビきょくの もので\n"
	.string "{JPN}さいきん おきた\p"
	.string "{JPN}トレーナーと ポケモンの できごとを\n"
	.string "{JPN}きいて まわって いるのです\p"
	.string "{JPN}もし よければ なにか\n"
	.string "{JPN}はなしを きかせて くれませんかね?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "{JPN}いま さいきん おきた\n"
	.string "{JPN}トレーナーと ポケモンの できごとを\l"
	.string "{JPN}きいて まわって いるのですが\p"
	.string "{JPN}もし よければ なにか\n"
	.string "{JPN}はなしを きかせて くれませんかね?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "{JPN}おお きかせて くれますか!\n"
	.string "{JPN}ありがとう ございます\p"
	.string "{JPN}では さいきん おきたこと なら\n"
	.string "{JPN}なんでも よいので\l"
	.string "{JPN}はなしを きかせて ください!$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "{JPN}そうですか......\p"
	.string "{JPN}では また なにか おもしろい はなしが\n"
	.string "{JPN}あったら きかせて くださいね$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "{JPN}......おお\n"
	.string "{JPN}なんて いいはなしだ!\p"
	.string "{JPN}このはなし テレビで\n"
	.string "{JPN}つかわせて いただきます!\p"
	.string "{JPN}いつか ほうそう するかも しれないので\n"
	.string "{JPN}たのしみに まっていて くださいね$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "{JPN}うーん\n"
	.string "{JPN}いい テレビばんぐみが できそうだ!\p"
	.string "{JPN}いそいで まとめないと!$"

gTVRecentHappeningsText00::
	.string "{JPN}“さいきんの できごと”\p"
	.string "{JPN}ポケモントレーナーに とって\n"
	.string "{JPN}まいにちが ものがたりです\l"
	.string "{JPN}その ものがたりを すこしでも\l"
	.string "{JPN}しょうかい できたら うれしいですね\p"
	.string "{JPN}さて きょうは トレーナーの\n"
	.string "{JPN}{STR_VAR_1}さんの おはなしです\p"
	.string "{JPN}{STR_VAR_1}さん さいきん\n"
	.string "{JPN}どんなことが あったんで しょうか?\l"
	.string "{JPN}さっそく みてみることに しましょう\p"
	.string "{JPN}えーと......$"

gTVRecentHappeningsText01::
	.string "{JPN}なるほど {STR_VAR_1}さんの\n"
	.string "{JPN}まわりで さいきん おきている ことが\l"
	.string "{JPN}てに とるように わかりますね$"

gTVRecentHappeningsText02::
	.string "{JPN}‘{STR_VAR_3}’という ことばが\n"
	.string "{JPN}おはなしに ストーリーを かんじさせますね$"

gTVRecentHappeningsText03::
	.string "{JPN}‘{STR_VAR_3}’という ことばの\n"
	.string "{JPN}おかげで まるで じょうけいが\l"
	.string "{JPN}うかんで くるようですね$"

gTVRecentHappeningsText04::
	.string "{JPN}このおはなしは ‘{STR_VAR_3}’という\n"
	.string "{JPN}ぶぶんが とても いんしょうてき ですね$"

gTVRecentHappeningsText05::
	.string "{JPN}{STR_VAR_1}さんは とても いい\n"
	.string "{JPN}おはなしを きかせて くれましたね\p"
	.string "{JPN}これで あなたの こころにも\n"
	.string "{JPN}{STR_VAR_1}さん という ストーリーが\l"
	.string "{JPN}きざみ こまれましたよ\p"
	.string "{JPN}それでは また じかいの\n"
	.string "{JPN}ほうそうで おあいしましょう$"

gTVMassOutbreakText00::
	.string "{JPN}こんにちは\n"
	.string "{JPN}“ポケモン ニュース”の じかんです\p"
	.string "{JPN}たいへん めずらしい ニュースが\n"
	.string "{JPN}はいって きました\p"
	.string "{JPN}{STR_VAR_1}で\n"
	.string "{JPN}{STR_VAR_2}が たいりょうはっせい した\l"
	.string "{JPN}という ほうこくが ありました!\p"
	.string "{JPN}{STR_VAR_2}と いえば\n"
	.string "{JPN}なかなか みつけることが むずかしい\l"
	.string "{JPN}ポケモンとしても ゆうめい ですね\p"
	.string "{JPN}あなたも このしんぴてきな\n"
	.string "{JPN}{STR_VAR_2}の たいりょうはっせいを\l"
	.string "{JPN}みにいっては いかが でしょうか?\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}“ポケモン ニュース”でした$"

gTV3CheersForPokeblocksText00::
	.string "{JPN}しかい“ごきげん いかがですか?\n"
	.string "{JPN}“ポロック バンザイ!”の おじかんです\p"
	.string "{JPN}きょうの ポロックは\n"
	.string "{JPN}{STR_VAR_1}さんと その おなかまが\l"
	.string "{JPN}ブレンドした ポロックです\p"
	.string "{JPN}さっそく わたしの グルメな ポケモン\n"
	.string "{JPN}ゴクリンちゃんに たべさせて みましょう!\p"
	.string "...... ...... ...... ......\n"
	.string "...... ...... ...... ......$"

gTV3CheersForPokeblocksText01::
	.string "{JPN}ゴクリン“グビィ! グビィ!\p"
	.string "{JPN}しかい“おお! とっても {STR_VAR_1}くて\n"
	.string "{JPN}‘{STR_VAR_2}!’と いってますね\p"
	.string "{JPN}きっと これは {STR_VAR_3}さんが\n"
	.string "{JPN}がんばって まわした おかげですね!\p"
	.string "{JPN}{STR_VAR_3}さん!\n"
	.string "{JPN}ごちそうさま でした!$"

gTV3CheersForPokeblocksText02::
	.string "{JPN}こんかい いまいち だった\n"
	.string "{JPN}{STR_VAR_1}さんが\l"
	.string "{JPN}もっと じょうずに まわすことが できれば\l"
	.string "{JPN}さらに おいしく なるかも しれませんよ!$"

gTV3CheersForPokeblocksText03::
	.string "{JPN}ゴクリン“グビィ! グビィ!\p"
	.string "{JPN}しかい“うーん...... ちょっと {STR_VAR_1}すぎて\n"
	.string "{JPN}‘{STR_VAR_2}!’と いってますね......\p"
	.string "{JPN}やっぱり {STR_VAR_3}さんの しっぱいが\n"
	.string "{JPN}いたかった ですね......$"

gTV3CheersForPokeblocksText04::
	.string "{JPN}こんかい いちばん がんばっていた\n"
	.string "{JPN}{STR_VAR_1}さんが かわいそうです......\p"
	.string "{JPN}......{STR_VAR_2}さん!\n"
	.string "{JPN}つぎは がんばって ください!$"

gTV3CheersForPokeblocksText05::
	.string "{JPN}では また おあいしましょう!\n"
	.string "{JPN}あいことばは “ポロック バンザイ!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "{JPN}やあ!\p"
	.string "{JPN}ボク {STR_VAR_1}の ファン なんだけど\n"
	.string "{JPN}{STR_VAR_1} って どう おもう?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "{JPN}なるほどねー\n"
	.string "{JPN}そんな ふうに おもっているんだね!$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "{JPN}{STR_VAR_1}の こと\n"
	.string "{JPN}わすれちゃったの......?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "{JPN}ボク {STR_VAR_1}の ファン なんだけど\n"
	.string "{JPN}{STR_VAR_1} って どうおもう?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "{JPN}じゃあ こんどは\n"
	.string "{JPN}{STR_VAR_1}の つよさを\l"
	.string "{JPN}てんすうで おしえてくれる?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "{JPN}{STR_VAR_1}の こと\n"
	.string "{JPN}わすれちゃったの......?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "{JPN}そっか!\n"
	.string "{JPN}こんど {STR_VAR_1}に あってみてよ!\l"
	.string "{JPN}きみも きっと ファンに なっちゃうよ!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "{JPN}そうなんだー!\p"
	.string "{JPN}ありがとう!\n"
	.string "{JPN}とっても さんこうに なったよ!\p"
	.string "{JPN}さっそく {STR_VAR_1}の ファン みんなで\n"
	.string "{JPN}この ことに ついて はなしあって みるよ!$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "{JPN}もうすぐ {STR_VAR_1}に ついての\n"
	.string "{JPN}テレビ ばんぐみが ほうそう されるんだ!\p"
	.string "{JPN}きみも ぜひ みてね!$"

gTVTrainerFanClubSpecialText00::
	.string "{JPN}“トレーナー ファンクラブ\n"
	.string "{JPN} {STR_VAR_1} スペシャル!”\p"
	.string "{JPN}ホウエン かくちに いらっしゃる\n"
	.string "{JPN}{STR_VAR_1}ファンの みなさま\l"
	.string "{JPN}おまたせしました!\p"
	.string "{JPN}きょうは {STR_VAR_1}さんが\n"
	.string "{JPN}‘どのように おもわれているか?’を\l"
	.string "{JPN}いっしょに かんがえて いきましょう!\p"
	.string "{JPN}ほかの トレーナーさんを だいひょうして\n"
	.string "{JPN}{STR_VAR_2}さん から ごいけんを\l"
	.string "{JPN}いただきました!\p"
	.string "{JPN}まず {STR_VAR_1}さんを\n"
	.string "{JPN}ひとことで いい あらわすと......\p"
	.string "‘{STR_VAR_3}’\p"
	.string "{JPN}さすが {STR_VAR_2}さん!\n"
	.string "{JPN}よく みて いらっしゃいますね!\p"
	.string "‘{STR_VAR_3} {STR_VAR_1}!’\n"
	.string "{JPN}いいですねー\p"
	.string "{JPN}つづいて {STR_VAR_1}さんの つよさに\n"
	.string "{JPN}てんすうを つけると......$"

gTVTrainerFanClubSpecialText01::
	.string "{JPN}‘{STR_VAR_3}てん!’\p"
	.string "{JPN}すごい こうとくてん ですね\n"
	.string "{JPN}{STR_VAR_2}さんは {STR_VAR_1}さんを\l"
	.string "{JPN}とっても そんけい していますね$"

gTVTrainerFanClubSpecialText02::
	.string "{JPN}‘{STR_VAR_3}てん!’\p"
	.string "{JPN}いい てんすう ですね\n"
	.string "{JPN}{STR_VAR_2}さんは {STR_VAR_1}さんを\l"
	.string "{JPN}ライバル として みていますね$"

gTVTrainerFanClubSpecialText03::
	.string "{JPN}‘{STR_VAR_3}てん!’\p"
	.string "{JPN}ちょっと いまいち ですね\n"
	.string "{JPN}{STR_VAR_2}さんは {STR_VAR_1}さんを\l"
	.string "{JPN}じぶんの こぶん として みていますね$"

gTVTrainerFanClubSpecialText04::
	.string "{JPN}‘{STR_VAR_3}てん!’\p"
	.string "{JPN}ひどい てんすう ですね\n"
	.string "{JPN}{STR_VAR_2}さんは {STR_VAR_1}さんを\l"
	.string "{JPN}したっぱ として みていますね$"

gTVTrainerFanClubSpecialText05::
	.string "{JPN}いやー なるほど!\p"
	.string "{JPN}{STR_VAR_1}さんに ついて\n"
	.string "{JPN}あたらしい はっけんが ありましたね!\p"
	.string "{JPN}では さいごに {STR_VAR_2}さんの\n"
	.string "{JPN}ことばで おわかれ しましょう!\p"
	.string "{STR_VAR_1} {STR_VAR_3}!$"

gTVNameRaterText00::
	.string "{JPN}“せいめい はんだん”の\n"
	.string "{JPN}じかんが やって まいりました\p"
	.string "{JPN}あなたの つけた ニックネームから\n"
	.string "{JPN}ポケモンの ことを\l"
	.string "{JPN}うらなって さしあげます\p"
	.string "{JPN}すこしでも アドバイスに\n"
	.string "{JPN}なれば よいと おもいますな\p"
	.string "{JPN}きょうは {STR_VAR_1}さんの ポケモン\n"
	.string "{JPN}{STR_VAR_2}の ‘{STR_VAR_3}’の\l"
	.string "{JPN}ニックネームを うらなって みますかな\p"
	.string "{JPN}ふむふむ......\p"
	.string "{JPN}うーむ\n"
	.string "{JPN}この ニックネームは......$"

gTVNameRaterText01::
	.string "{JPN}いろいろな ところで さいのうを\n"
	.string "{JPN}はっき できる ニックネーム ですなぁ!\p"
	.string "{JPN}こんご いろいろな ことに\n"
	.string "{JPN}チャレンジ すると よいと おもいますよ$"

gTVNameRaterText02::
	.string "{JPN}{STR_VAR_1}さん との あいしょうが\n"
	.string "{JPN}とても よい ニックネーム ですなぁ!\p"
	.string "{JPN}いきの ぴったり あった\n"
	.string "{JPN}よい コンビに なると おもいますよ$"

gTVNameRaterText03::
	.string "{JPN}とても こせいてきな ポケモンに\n"
	.string "{JPN}なる ニックネーム ですなぁ!\p"
	.string "{JPN}きちんと そだてて やれば その こせいが\n"
	.string "{JPN}おおきく はな ひらくと おもいますよ$"

gTVNameRaterText04::
	.string "{JPN}とても おもいやりの ある\n"
	.string "{JPN}ポケモンに なる ニックネーム ですなぁ!\p"
	.string "{JPN}きちんと そだてて やれば\n"
	.string "{JPN}それに こたえて くれると おもいますよ$"

gTVNameRaterText05::
	.string "{JPN}しょうらい おおものに なる\n"
	.string "{JPN}とても よい ニックネーム ですなぁ!\p"
	.string "{JPN}しょうらいが とても\n"
	.string "{JPN}たのしみな ポケモン ですな$"

gTVNameRaterText06::
	.string "{JPN}とても けんこうてきな ポケモンに\n"
	.string "{JPN}なる よい ニックネーム ですなぁ!\p"
	.string "{JPN}いつまでも げんきで\n"
	.string "{JPN}いて くれる でしょう$"

gTVNameRaterText07::
	.string "{JPN}とても かつどうてきな ポケモンに\n"
	.string "{JPN}なる よい ニックネーム ですなぁ!\p"
	.string "{JPN}ポケモンしょうぶ では\n"
	.string "{JPN}おおいに かつやく すると おもいますよ$"

gTVNameRaterText08::
	.string "{JPN}とても あいきょうの ある\n"
	.string "{JPN}ポケモンになる ニックネーム ですなぁ!\p"
	.string "{JPN}ポケモンコンテスト では\n"
	.string "{JPN}とても かつやく できると おもいますよ$"

gTVNameRaterText09::
	.string "{JPN}この ‘{STR_VAR_1}’という ニックネームは\n"
	.string "{JPN}‘{STR_VAR_3}’の もじを ちゅうしん として\l"
	.string "{JPN}これに ‘{STR_VAR_2}’が つくことで\p"
	.string "{JPN}どっしり とした\n"
	.string "{JPN}よい ニックネームに なっていますな$"

gTVNameRaterText10::
	.string "{JPN}この ‘{STR_VAR_1}’という ニックネームは\n"
	.string "{JPN}とても かたちの よい\l"
	.string "{JPN}ニックネーム ですなぁ\p"
	.string "{JPN}ニックネームに ‘{STR_VAR_2}’と ‘{STR_VAR_3}’が\n"
	.string "{JPN}はいって いるのが とても よい!$"

gTVNameRaterText11::
	.string "{JPN}この ‘{STR_VAR_1}’という ニックネームは\n"
	.string "{JPN}とても ながれの よい\l"
	.string "{JPN}ニックネーム ですなぁ\p"
	.string "{JPN}‘{STR_VAR_2}’の もじの あとに\n"
	.string "{JPN}‘{STR_VAR_3}’がくる ながれが とても よい!$"

gTVNameRaterText12::
	.string "{JPN}......さて そのほかに\n"
	.string "{JPN}よい ニックネームの れい として$"

gTVNameRaterText13::
	.string "{JPN}トレーナーの {STR_VAR_1}さんの\n"
	.string "{JPN}なまえを もってきて\p"
	.string "{JPN}‘{STR_VAR_2}{STR_VAR_3}’と いうのも\n"
	.string "{JPN}とても よい ニックネーム ですなぁ$"

gTVNameRaterText14::
	.string "{JPN}もしくは ‘{STR_VAR_2}{STR_VAR_3}’と\n"
	.string "{JPN}いうのも よい ニックネーム ですな$"

gTVNameRaterText15::
	.string "{JPN}もとの ポケモンの なまえ\n"
	.string "{JPN}{STR_VAR_2}から すこし もらって\p"
	.string "{JPN}‘{STR_VAR_1}{STR_VAR_3}’や$"

gTVNameRaterText16::
	.string "{JPN}‘{STR_VAR_1}{STR_VAR_3}’と いうのも\n"
	.string "{JPN}よい ニックネーム ですなぁ$"

gTVNameRaterText17::
	.string "{JPN}まちがっても ほかの ポケモンの なまえ\n"
	.string "{JPN}たとえば {STR_VAR_2}の なまえを つけて\p"
	.string "{JPN}‘{STR_VAR_1}{STR_VAR_3}’の ような\n"
	.string "{JPN}ニックネームに しては いけませんな$"

gTVNameRaterText18::
	.string "{JPN}うむ それにしても ‘{STR_VAR_1}’は\n"
	.string "{JPN}なかなか よい ニックネーム ですな\p"
	.string "{JPN}これからも ‘{STR_VAR_1}’の ことを\n"
	.string "{JPN}たいせつに して ほしい ものですなぁ\p"
	.string "{JPN}それでは また\n"
	.string "{JPN}ごえんが あれば$"

gTVPokemonAnglerText00::
	.string "{JPN}“{STR_VAR_2}を つる”\p"
	.string "{JPN}アナウンサー‘こんにちは! きょうは\n"
	.string "{JPN}{STR_VAR_2}つりを おそわりに きました\p"
	.string "{JPN}さて せんせい {STR_VAR_2}を つるには\n"
	.string "{JPN}どんな コツが いるのですか?\p"
	.string "{JPN}せんせい‘ん?\n"
	.string "{JPN}{STR_VAR_2}を つる コツかい\l"
	.string "{JPN}それはね じーっと まつことだね\p"
	.string "{JPN}ほら あそこにいる {STR_VAR_1}さん\n"
	.string "{JPN}なんて いい みほん じゃないか?\p"
	.string "{JPN}もう かれこれ......\n"
	.string "{JPN}{STR_VAR_3}かいは にげられて いるけど\p"
	.string "{JPN}あきらめず じーっと まちつづけて いるよ\n"
	.string "{JPN}あれが {STR_VAR_2}つりの ごくいだね\p"
	.string "{JPN}アナウンサー‘なるほど......\p"
	.string "{JPN}あ! {STR_VAR_1}さん\n"
	.string "{JPN}やっと {STR_VAR_2}を つりました!\l"
	.string "{JPN}なきそうな かおして よろこんで ますよ!\p"
	.string "{JPN}...わたしも あんな うれしそうな\n"
	.string "{JPN}かおを みたら つりをしたく なりました!\p"
	.string "{JPN}みなさんも これを きに {STR_VAR_2}つりを\n"
	.string "{JPN}してみては いかがですか?\p"
	.string "{JPN}それでは また じかいの\n"
	.string "{JPN}ほうそうで あいましょう$"

gTVPokemonAnglerText01::
	.string "{JPN}“{STR_VAR_2}を つる”\p"
	.string "{JPN}インタビュアー“こんにちは! きょうは\n"
	.string "{JPN}{STR_VAR_2}つりを おそわりに きました\p"
	.string "{JPN}さて せんせい {STR_VAR_2}を つるには\n"
	.string "{JPN}どんな コツが いるのですか?\p"
	.string "{JPN}せんせい“ん?\n"
	.string "{JPN}{STR_VAR_2}を つる コツかい\l"
	.string "{JPN}それはね つりざおを あらしの ごとく\n"
	.string "{JPN}あつかう ことだね!\p"
	.string "{JPN}ほら あそこにいる {STR_VAR_1}さんの\n"
	.string "{JPN}つりざお さばきを みてみなさい!\p"
	.string "{JPN}もう {STR_VAR_3}ひきは れんぞくで\n"
	.string "{JPN}つって いるぞ!\p"
	.string "{JPN}インタビュアー“すっ すごい!\n"
	.string "{JPN}まさに あらしの ようね......\p"
	.string "{JPN}......あんなに すごい わざを みたら\n"
	.string "{JPN}わたしも つりを したくなって きました!\p"
	.string "{JPN}みなさんも これを きに {STR_VAR_2}つりを\n"
	.string "{JPN}してみては いかがですか?\p"
	.string "{JPN}それでは また じかいの\n"
	.string "{JPN}ほうそうで あいましょう$"

gTVPokemonTodayFailedText00::
	.string "{JPN}こんにちはー!\p"
	.string "{JPN}“きょうの ポケモン”の\n"
	.string "{JPN}じかんだよー!!\p"
	.string "{JPN}おねえさん“こんにちは みんな げんき!\n"
	.string "{JPN}きょうは {STR_VAR_1}さんの ポケモン\l"
	.string "{JPN}{STR_VAR_2}の しょうかいを するよ!\p"
	.string "{JPN}おにいさん“するぞー!$"

gTVPokemonTodayFailedText01::
	.string "{JPN}あ!\n"
	.string "{JPN}{STR_VAR_1}さん といえば......\p"
	.string "{JPN}おねえさん このまえ\n"
	.string "{JPN}ぼく みちゃった!!\p"
	.string "{JPN}おねえさん“みちゃった って\n"
	.string "{JPN}なにを みちゃったの?\p"
	.string "{JPN}おにいさん“このまえ\n"
	.string "{JPN}{STR_VAR_2}に でかけたとき\l"
	.string "{JPN}{STR_VAR_1}さんを みかけたんだ\p"
	.string "{JPN}ちょうど {STR_VAR_3}を つかまえてる\n"
	.string "{JPN}ところ だったん だけど......$"

gTVPokemonTodayFailedText02::
	.string "{JPN}とちゅうで ポケモンに\n"
	.string "{JPN}にげられ ちゃったんだよ!!\p"
	.string "{JPN}ボールを {STR_VAR_2}こも なげたのに\n"
	.string "{JPN}ぜんぶ むだ......\p"
	.string "{JPN}ポケモンに にげられた ときの\n"
	.string "{JPN}{STR_VAR_1}さんの くやしがった かお\l"
	.string "{JPN}すごかったなぁ......$"

gTVPokemonTodayFailedText03::
	.string "{JPN}とちゅうで まちがって ポケモンを\n"
	.string "{JPN}たおし ちゃったんだよ!!\p"
	.string "{JPN}ボールを {STR_VAR_2}こも なげたのに\n"
	.string "{JPN}ぜんぶ むだ......\p"
	.string "{JPN}ポケモンを たおしちゃった ときの\n"
	.string "{JPN}{STR_VAR_1}さんの あぜんと した かお\l"
	.string "{JPN}なんとも いえなかったなぁ......$"

gTVPokemonTodayFailedText04::
	.string "{JPN}おねえさん“こらこらっ!\n"
	.string "{JPN}たにんの ふこうを わらっちゃ だめだよ\p"
	.string "{JPN}あぁ {STR_VAR_1}さん\n"
	.string "{JPN}とっても かわいそう......\p"
	.string "{JPN}おにいさん“はーい!\n"
	.string "{JPN}わらって すいませーん$"

gTVPokemonTodayFailedText05::
	.string "{JPN}おねえさん“プッ!\p"
	.string "{JPN}おにいさん“あ! いま\n"
	.string "{JPN}わらったでしょ!?\p"
	.string "{JPN}おねえさん“え!?\p"
	.string "{JPN}わらってない\n"
	.string "{JPN}わらってないよ!\p"
	.string "{JPN}あぁ {STR_VAR_1}さん\n"
	.string "{JPN}とっても かわいそう......\p"
	.string "{JPN}おにいさん“......$"

gTVPokemonTodayFailedText06::
	.string "{JPN}おねえさん“じゃあ きを とりなおして\n"
	.string "{JPN}ポケモンの しょうかいを......\p"
	.string "{JPN}え?\n"
	.string "{JPN}もう じかんが ない?\p"
	.string "{JPN}もう! ポケモンの しょうかいが\n"
	.string "{JPN}できなかった じゃない!\p"
	.string "{JPN}おにいさん“また じかい あおうぜ!\p"
	.string "{JPN}おねえさん“かってに しめるなー!!$"

gTVPokemonTodaySuccessfulText00::
	.string "{JPN}こんにちはー!\p"
	.string "{JPN}“きょうの ポケモン”の\n"
	.string "{JPN}じかんだよー!!\p"
	.string "{JPN}おねえさん“こんにちは みんな げんき!\n"
	.string "{JPN}きょうは {STR_VAR_1}さんの ポケモン\l"
	.string "{JPN}{STR_VAR_2}の しょうかいを するよ!\p"
	.string "{JPN}おにいさん“するぞー!$"

gTVPokemonTodaySuccessfulText01::
	.string "{JPN}おねえさん“{STR_VAR_1}さんは\n"
	.string "{JPN}{STR_VAR_2}に ‘{STR_VAR_3}’って\p"
	.string "{JPN}ニックネームを つけて たいせつに\n"
	.string "{JPN}そだてて るんだって!$"

gTVPokemonTodaySuccessfulText02::
	.string "{JPN}おにいさん“ちなみに\n"
	.string "{JPN}ボールを ぜんぶで {STR_VAR_3}こ なげて\p"
	.string "{JPN}さいごは {STR_VAR_2}で\n"
	.string "{JPN}つかまえたって うわさだよ!$"

gTVPokemonTodaySuccessfulText03::
	.string "{JPN}おねえさん“そんなに かんたんに\n"
	.string "{JPN}つかまえる なんて\p"
	.string "{JPN}{STR_VAR_1}さんと {STR_VAR_2}の\n"
	.string "{JPN}であいは きっと うんめい だったのよ!$"

gTVPokemonTodaySuccessfulText04::
	.string "{JPN}おねえさん“くろうして やっと\n"
	.string "{JPN}つかまえた ポケモンは\l"
	.string "{JPN}だいじに されるって いうしね!$"

gTVPokemonTodaySuccessfulText05::
	.string "{JPN}おねえさん“{STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}は だいじな マスターボールを\p"
	.string "{JPN}つかって やっと つかまえた\n"
	.string "{JPN}おもいでの ポケモン なんだって!\p"
	.string "{JPN}おにいさん“えー! すごいねー!\p"
	.string "{JPN}おねえさん“{STR_VAR_1}さん ほんとうに\n"
	.string "{JPN}{STR_VAR_2}を つかまえ たかったんだね!$"

gTVPokemonTodaySuccessfulText06::
	.string "{JPN}おにいさん“でも その\n"
	.string "{JPN}{STR_VAR_2}に ‘{STR_VAR_3}’って\p"
	.string "{JPN}ニックネームを つけるあたり\n"
	.string "{JPN}{STR_VAR_1}さんの センスが わかるね!\p"
	.string "{JPN}おねえさん“そうだねー$"

gTVPokemonTodaySuccessfulText07::
	.string "{JPN}わたしなら {STR_VAR_3} とかに\n"
	.string "{JPN}そのニックネームを つけちゃう けどね!\p"
	.string "{JPN}おにいさん“おー!\n"
	.string "{JPN}それ なかなか あたらしいかも!$"

gTVPokemonTodaySuccessfulText08::
	.string "{JPN}‘{STR_VAR_2}’かー\n"
	.string "{JPN}まさに {STR_VAR_1}って かんじよね!\p"
	.string "{JPN}ほら! もじの ふんいきとか なんとなく\n"
	.string "{JPN}{STR_VAR_1}って かんじが するもの!\p"
	.string "{JPN}おにいさん“......そうだね$"

gTVPokemonTodaySuccessfulText09::
	.string "{JPN}わたしの しってるかぎり {STR_VAR_1}に\n"
	.string "{JPN}‘{STR_VAR_2}’って ニックネームを\l"
	.string "{JPN}つけている トレーナーなんて いないよ!\p"
	.string "{JPN}おにいさん“それだけ ニックネームをつける\n"
	.string "{JPN}センスが いいって ことだよ!$"

gTVPokemonTodaySuccessfulText10::
	.string "{JPN}わたしも こんど ポケモンを つかまえたら\n"
	.string "{JPN}‘{STR_VAR_2}’って つけて みようかな?\p"
	.string "{JPN}おにいさん“え? じゃあ ぼくも\n"
	.string "{JPN}‘{STR_VAR_2}’って つけよー!$"

gTVPokemonTodaySuccessfulText11::
	.string "{JPN}おねえさん“あ! もう こんなじかん!\p"
	.string "{JPN}それでは また じかいの\n"
	.string "{JPN}ほうそうで おあいしましょう\p"
	.string "{JPN}おにいさん“つぎは あなたの ポケモンを\n"
	.string "{JPN}しょうかい するかもよ!$"

SmartShopper_Text_Intro::
	.string "{JPN}こんにちは\p"
	.string "{JPN}“きょうの かいもの じょうず”の\n"
	.string "{JPN}じかん です\p"
	.string "{JPN}インタビュアー“みなさん おげんきですか?\p"
	.string "{JPN}きょうは {STR_VAR_2}の\n"
	.string "{JPN}おみせに きています\p"
	.string "{JPN}さいきん なにが うれているのか\n"
	.string "{JPN}チェック してみましょう!$"

SmartShopper_Text_ClerkNormal::
	.string "{JPN}それでは てんいんさんに\n"
	.string "{JPN}インタビュー してみましょう\l"
	.string "{JPN}どうですか うれて いますか?\p"
	.string "{JPN}てんいん“はい おかげさまで\p"
	.string "{JPN}とくに {STR_VAR_2}が\n"
	.string "{JPN}いま うれて いるんですよ\p"
	.string "{JPN}このまえも {STR_VAR_1}さん という\n"
	.string "{JPN}かたが {STR_VAR_3}こも かって いかれました$"

SmartShopper_Text_RandomComment1::
	.string "{JPN}インタビュアー“{STR_VAR_2}を\n"
	.string "{JPN}{STR_VAR_3}こも かうなんて すごいですね!\p"
	.string "{JPN}もしかしたら {STR_VAR_1}さんは\n"
	.string "{JPN}これから とおくまで いくための\l"
	.string "{JPN}たびじたくを していたのかも しれませんね\p"
	.string "{JPN}やっぱり たびには {STR_VAR_2}ですね!$"

SmartShopper_Text_RandomComment2::
	.string "{JPN}インタビュアー“{STR_VAR_2} といえば\n"
	.string "{JPN}わたし なんか このまえ\l"
	.string "{JPN}{STR_VAR_3}こも かいましたよ!\p"
	.string "{JPN}{STR_VAR_2}って いいですからねー!$"

SmartShopper_Text_RandomComment3::
	.string "{JPN}インタビュアー“{STR_VAR_2}を!!\n"
	.string "{JPN}{STR_VAR_3}こも!?\p"
	.string "{JPN}......そんなに かうひとが\n"
	.string "{JPN}いるなんて しらなかったわ\p"
	.string "{JPN}わたし なんか せいぜい 1こか 2こしか\n"
	.string "{JPN}かわないから......$"

SmartShopper_Text_RandomComment4::
	.string "{JPN}インタビュアー“わたしも むかし\n"
	.string "{JPN}{STR_VAR_2}を たくさん かったことが\l"
	.string "{JPN}あったん ですけど\p"
	.string "{JPN}あまって しまって\n"
	.string "{JPN}こうかい したわ......\p"
	.string "{JPN}それからと いうもの ひつような\n"
	.string "{JPN}ぶんだけ かうように してるの......\p"
	.string "{JPN}おっと!\p"
	.string "{JPN}わたしの ことを はなしても\n"
	.string "{JPN}しょうがない ですね!$"

SmartShopper_Text_SecondItem::
	.string "{JPN}てんいん“{STR_VAR_1}さんは そのほかにも\n"
	.string "{JPN}{STR_VAR_2}を {STR_VAR_3}こ\l"
	.string "{JPN}まとめて かわれましたよ\p"
	.string "{JPN}インタビュアー“おー {STR_VAR_2}も\n"
	.string "{JPN}なかなか よい ですもんね!$"

SmartShopper_Text_ThirdItem::
	.string "{JPN}てんいん“ついでに {STR_VAR_2}も\n"
	.string "{JPN}{STR_VAR_3}こ かわれて いきました$"

SmartShopper_Text_DuringSale::
	.string "{JPN}てんいん“しかも おおやすうりの とき\n"
	.string "{JPN}ですから さすが ですよね!$"

SmartShopper_Text_OutroNormal::
	.string "{JPN}インタビュアー“うーん......\n"
	.string "{JPN}{STR_VAR_1}さんって かなりの\l"
	.string "{JPN}かいものじょうず なのかも しれませんね!\p"
	.string "{JPN}これで ごうけいは......\p"
	.string "{JPN}{STR_VAR_2}えん!?\n"
	.string "{JPN}さすが ですね!\p"
	.string "{JPN}おっと それでは またじかいの\n"
	.string "{JPN}ほうそうで おあい しましょう!$"

SmartShopper_Text_IsVIP::
	.string "{JPN}てんいん“{STR_VAR_1}さんは ほんとうに\n"
	.string "{JPN}だいじな おきゃくさま ですよ$"

SmartShopper_Text_ClerkMax::
	.string "{JPN}それでは てんいんさんに\n"
	.string "{JPN}インタビュー して みましょう\l"
	.string "{JPN}どうですか うれて ますか?\p"
	.string "{JPN}てんいん“はい おかげさまで\n"
	.string "{JPN}うれてうれて こまって ますよ!\p"
	.string "{JPN}このまえ {STR_VAR_1}さん というかたが\n"
	.string "{JPN}{STR_VAR_2}を たくさん かわれまして\p"
	.string "{JPN}みせのなかに {STR_VAR_2}が\n"
	.string "{JPN}なくなって しまいそう だったんですよ!\p"
	.string "{JPN}わたくしも {STR_VAR_2}を そんなに\n"
	.string "{JPN}かう おきゃくさまが いるなんて\l"
	.string "{JPN}ゆめにも おもいません でした からね!\p"
	.string "{JPN}インタビュアー“と いうことは......\n"
	.string "{JPN}100こ とか 200こ とか ですか?\p"
	.string "{JPN}てんいん“いや もっと でしたよ!\p"
	.string "{JPN}インタビュアー“うひゃー!\n"
	.string "{JPN}{STR_VAR_1}さんって すごい ですね!\p"
	.string "{JPN}てんいん“{STR_VAR_1}さんは ほんとうに\n"
	.string "{JPN}だいじな おきゃくさま ですよ$"

SmartShopper_Text_OutroMax::
	.string "{JPN}インタビュアー“うーん すごい ですね\p"
	.string "{JPN}でも なんで そんなに\n"
	.string "{JPN}いっぱい かったので しょう?\p"
	.string "......\p"
	.string "{JPN}なぞは ふかまる ばかりですが\n"
	.string "{JPN}じかんの ようなので\l"
	.string "{JPN}またじかい おあい しましょう!\p"
	.string "{JPN}それに しても\n"
	.string "{JPN}{STR_VAR_1}さんって なぞだわ......$"

gTVWorldOfMastersText00::
	.string "{JPN}“めいじんの せかい”\p"
	.string "{JPN}みなさん こんにちは\p"
	.string "{JPN}みなさんは {STR_VAR_1}さん という\n"
	.string "{JPN}トレーナーを しってますか?\p"
	.string "{JPN}{STR_VAR_1}さんは ポケモンを つかまえる\n"
	.string "{JPN}めいじん として ゆうめい なんです\p"
	.string "{JPN}{STR_VAR_1}さんの ポケモンさがしは\n"
	.string "{JPN}あるきまわる ところから はじまります\p"
	.string "{JPN}このまえは ポケモンを さがすために\n"
	.string "{JPN}1にちで {STR_VAR_2}ほ いじょうも あるき\p"
	.string "{JPN}つかまえた ポケモンの かずは\n"
	.string "{JPN}なんと {STR_VAR_3} ひきにも なったとか!$"

gTVWorldOfMastersText01::
	.string "{JPN}きっと あいぼうの {STR_VAR_1}と\n"
	.string "{JPN}しんらい しあっている からこそ\l"
	.string "{JPN}こんな すごいことが できるんですね$"

gTVWorldOfMastersText02::
	.string "{JPN}めいじんは さいごに\n"
	.string "{JPN}{STR_VAR_2}で\l"
	.string "{JPN}{STR_VAR_3}を つかまえ\p"
	.string "{JPN}きねんの ポケモンとして だいじに\n"
	.string "{JPN}している らしいですよ\p"
	.string "{JPN}じしんのある トレーナーは このきろくに\n"
	.string "{JPN}ちょうせんして みては いかがですか?\p"
	.string "{JPN}それでは また\n"
	.string "{JPN}じかい おあいしましょう$"

gTVTodaysRivalTrainerText00::
	.string "{JPN}“きょうの ライバル トレーナー”\p"
	.string "{JPN}ポケモン トレーナーの みなさん!\n"
	.string "{JPN}ごきげん いかがですか?\p"
	.string "{JPN}きょうも みなさんの ライバルたちの\n"
	.string "{JPN}ようすに ついて おつたえします!$"

gTVTodaysRivalTrainerText07::
	.string "{JPN}こんかいの トレーナーは\n"
	.string "{JPN}げんざい {STR_VAR_3}に\l"
	.string "{JPN}いらっしゃる {STR_VAR_1}さん です!\p"
	.string "{JPN}{STR_VAR_1}さんは\n"
	.string "{JPN}ポケモン ずかんを {STR_VAR_2}ひき\l"
	.string "{JPN}とうろく されていますねー!$"

gTVTodaysRivalTrainerText08::
	.string "{JPN}こんかいの トレーナーは\n"
	.string "{JPN}げんざい ひみつきちに\l"
	.string "{JPN}いらっしゃる {STR_VAR_1}さん です!\p"
	.string "{JPN}{STR_VAR_1}さんは\n"
	.string "{JPN}ポケモン ずかんを {STR_VAR_2}ひき\l"
	.string "{JPN}とうろく されていますねー!$"

gTVTodaysRivalTrainerText09::
	.string "{JPN}こんかいの トレーナーは\n"
	.string "{JPN}{STR_VAR_1}さん です!\p"
	.string "{JPN}げんざい {STR_VAR_1}さんは\n"
	.string "{JPN}ポケモン ずかんを {STR_VAR_2}ひき\l"
	.string "{JPN}とうろく されていますねー!$"

gTVTodaysRivalTrainerText10::
	.string "{JPN}こんかいの トレーナーは\n"
	.string "{JPN}げんざい れんらくせんに のっている\l"
	.string "{JPN}{STR_VAR_1}さん です!\p"
	.string "{JPN}{STR_VAR_1}さんは\n"
	.string "{JPN}ポケモン ずかんを {STR_VAR_2}ひき\l"
	.string "{JPN}とうろく されていますねー!$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "{JPN}バッジは {STR_VAR_1}こ\n"
	.string "{JPN}かくとく されていますよー!$"

gTVTodaysRivalTrainerText02::
	.string "{JPN}バッジは まだ 1こも\n"
	.string "{JPN}かくとく されていませんねー!$"

gTVTodaysRivalTrainerText03::
	.string "{JPN}バトルフロンティアの シンボルは\n"
	.string "{JPN}1こも かくとく されていませんねー!$"

gTVTodaysRivalTrainerText04::
	.string "{JPN}バトルフロンティアの シンボルは\n"
	.string "{JPN}ゴールドシンボルを {STR_VAR_1}こ\l"
	.string "{JPN}シルバーシンボルを {STR_VAR_2}こ\l"
	.string "{JPN}かくとく されていますねー!$"

gTVTodaysRivalTrainerText05::
	.string "{JPN}バトルフロンティアでの\n"
	.string "{JPN}バトルポイントは げんざい\l"
	.string "{JPN}{STR_VAR_1} BP あつめていますねー!$"

gTVTodaysRivalTrainerText06::
	.string "{JPN}{STR_VAR_1}さんの ようすは\n"
	.string "{JPN}みなさんと くらべて いかが でしたか?\p"
	.string "{JPN}まだまだ ぼうけんは つづきます\p"
	.string "{JPN}トレーナーの みなさん!\p"
	.string "{JPN}ライバルたちに まけずに\n"
	.string "{JPN}がんばって くださいねー!$"

TrendWatcher_Text_Intro::
	.string "{JPN}“ムロタウン\n"
	.string "{JPN} りゅうこう じょうほうきょく”\p"
	.string "{JPN}しかい“さあ きょうも ムロタウンの\n"
	.string "{JPN}りゅうこうを いちはやく おとどけします\p"
	.string "{JPN}ゲストは ムロタウン いち\n"
	.string "{JPN}ものしり という この おじいさんです!\p"
	.string "{JPN}ろうじん“......ふむ よろしくじゃ\p"
	.string "{JPN}しかい“さっそく ですが ムロタウンで\n"
	.string "{JPN}いま はやっている ことと いえば......\p"
	.string "{JPN}ろうじん“{STR_VAR_1} {STR_VAR_2}\p"
	.string "{JPN}しかい“{STR_VAR_1} {STR_VAR_2}\n"
	.string "{JPN}......ですか?\p"
	.string "{JPN}ろうじん“......いいや!\n"
	.string "{JPN}{STR_VAR_1} {STR_VAR_2} は\l"
	.string "{JPN}まったく はやらんかった のじゃ......\l"
	.string "{JPN}この はなし ききたいか のう......?\p"
	.string "{JPN}しかい“いや いまの りゅうこうを......$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "{JPN}ろうじん“{STR_VAR_1} {STR_VAR_2} は\n"
	.string "{JPN}ミシロから きた {STR_VAR_3}くんが\l"
	.string "{JPN}おしえて くれたの じゃがのう......$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "{JPN}ろうじん“{STR_VAR_1} {STR_VAR_2} は\n"
	.string "{JPN}ミシロから きた {STR_VAR_3}ちゃんが\l"
	.string "{JPN}おしえて くれたの じゃがのう......$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "{JPN}まったく ダメ じゃった......\p"
	.string "{JPN}{STR_VAR_1} {STR_VAR_2} まつり!\p"
	.string "{JPN}{STR_VAR_1} {STR_VAR_2} たいかい!\p"
	.string "{JPN}わしも みんなに いっしょうけんめい\n"
	.string "{JPN}おしえたの じゃがのう......\p"
	.string "{JPN}‘{STR_VAR_1}’が わるかったのか のう......\p"
	.string "{JPN}しかい“......すいませんが\n"
	.string "{JPN}いまの りゅうこうを......$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "{JPN}ろうじん“{STR_VAR_3}くん!\n"
	.string "{JPN}{STR_VAR_1} {STR_VAR_2} より\l"
	.string "{JPN}すごい こと また おしえて おくれー$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "{JPN}ろうじん“{STR_VAR_3}ちゃん!\n"
	.string "{JPN}{STR_VAR_1} {STR_VAR_2} より\l"
	.string "{JPN}すごい こと また おしえて おくれー$"

TrendWatcher_Text_Outro::
	.string "{JPN}しかい“......えーと ......はい! ということで\n"
	.string "{JPN}{STR_VAR_1} {STR_VAR_2} は......\l"
	.string "{JPN}ムロタウンで はやらなかった!\p"
	.string "{JPN}......いじょうを おつたえしました\p"
	.string "{JPN}ろうじん“{STR_VAR_1} {STR_VAR_2}$"

gTVHoennTreasureInvestigatorsText00::
	.string "{JPN}“ホウエン おたから たんていだん!”\p"
	.string "{JPN}みんなー!\n"
	.string "{JPN}かくしアイテム みつけてるー!?\p"
	.string "{JPN}きょうも かくちで もくげき された\n"
	.string "{JPN}ひみつの じょうほうを しょうかい するよ!\p"
	.string "{JPN}きょうの おてがみは\n"
	.string "{JPN}‘{STR_VAR_1} はっけん!’に\l"
	.string "{JPN}ついてだよー!!$"

gTVHoennTreasureInvestigatorsText01::
	.string "{JPN}さっそく よんでみるねー!\p"
	.string "{JPN}......たんていだんの みなさん こんにちは\p"
	.string "{JPN}この あいだ {STR_VAR_2}さんが\n"
	.string "{JPN}‘{STR_VAR_3}’で なんと!\l"
	.string "{JPN}‘{STR_VAR_1}’を みつけて いました\l"
	.string "{JPN}もう とっても うらやましかったです\p"
	.string "{JPN}......やったね! {STR_VAR_2}さん!\p"
	.string "{JPN}テレビの まえの みんなも まけずに\n"
	.string "{JPN}ダウジングマシンを つかって さがしてね!\p"
	.string "{JPN}きみの とっておきの じょうほう\n"
	.string "{JPN}まってるよー!$"

gTVHoennTreasureInvestigatorsText02::
	.string "{JPN}さっそく よんでみるねー!\p"
	.string "{JPN}......たんていだんの みなさん こんにちは\p"
	.string "{JPN}この あいだ {STR_VAR_2}さんが\n"
	.string "{JPN}‘れんらくせん’で なんと!\l"
	.string "{JPN}‘{STR_VAR_1}’を みつけて いました\l"
	.string "{JPN}もう とっても うらやましかったです\p"
	.string "{JPN}......やったね! {STR_VAR_2}さん!\p"
	.string "{JPN}テレビの まえの みんなも まけずに\n"
	.string "{JPN}ダウジングマシンを つかって さがしてね!\p"
	.string "{JPN}きみの とっておきの じょうほう\n"
	.string "{JPN}まってるよー!$"

gTVFindThatGamerText00::
	.string "{JPN}“ギャンブラーを さがせー!”\p"
	.string "{JPN}みなさーん!\n"
	.string "{JPN}{STR_VAR_2} ガンガン まわしてますかー?\p"
	.string "{JPN}さあ きょうも ゲームコーナーで\n"
	.string "{JPN}すごかった トレーナーさんを\l"
	.string "{JPN}はっぴょう させて いただきますよ!\p"
	.string "{JPN}きょうの ナンバー1 ギャンブラーは......\l"
	.string "{JPN}{STR_VAR_1}さん です!$"

gTVFindThatGamerText01::
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で\n"
	.string "{JPN}なんと {STR_VAR_3}まいも\l"
	.string "{JPN}コインを だした そうです!\p"
	.string "{JPN}‘{STR_VAR_1}さんが きたら\n"
	.string "{JPN} あかじ かくご!’\p"
	.string "{JPN}......という ことばが てんいんたちの\n"
	.string "{JPN}あいだで ささやかれた そうです!\p"
	.string "{JPN}テレビの まえの みなさんも\n"
	.string "{JPN}{STR_VAR_1}さんの ように {STR_VAR_2}で\l"
	.string "{JPN}あそんで みては いかがでしょうか?\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}ホウエン いち ドキドキの スポット!\l"
	.string "{JPN}ゲームコーナー より おおくりしました$"

gTVFindThatGamerText02::
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で\n"
	.string "{JPN}なんと {STR_VAR_3}まいも\l"
	.string "{JPN}まけてしまった そうです!\p"
	.string "{JPN}‘{STR_VAR_1}さんが きたら\n"
	.string "{JPN} うりあげ 2ばい!’\p"
	.string "{JPN}......という ことばが てんいんたちの\n"
	.string "{JPN}あいだで ささやかれた そうです$"

gTVFindThatGamerText03::
	.string "{JPN}テレビの まえの みなさんは\n"
	.string "{JPN}{STR_VAR_1}さん みたいに ならないように\l"
	.string "{JPN}{STR_VAR_2}で あそんでみては\l"
	.string "{JPN}いかがで しょうか?\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}ホウエン いち ドキドキの スポット!\l"
	.string "{JPN}ゲームコーナー より おおくりしました$"

gTVBreakingNewsText00::
	.string "{JPN}......きんきゅう スペシャル テレビ!!$"

gTVBreakingNewsText01::
	.string "{JPN}“{STR_VAR_1}さん レア {STR_VAR_2}を\n"
	.string "{JPN} つかまえるーーー!!”\p"
	.string "{JPN}......はい!\n"
	.string "{JPN}こちら {STR_VAR_3} です!\p"
	.string "{JPN}さきほど {STR_VAR_1}さんが\n"
	.string "{JPN}レア {STR_VAR_2}を つかまえる ことに\l"
	.string "{JPN}せいこう しました!$"

gTVBreakingNewsText02::
	.string "{JPN}レア {STR_VAR_2}に であった\n"
	.string "{JPN}{STR_VAR_1}さんは\l"
	.string "{JPN}{STR_VAR_3}で たたかいを いどみました!\p"
	.string "{JPN}そして......$"

gTVBreakingNewsText03::
	.string "{JPN}ボールを {STR_VAR_1}かい なげて\n"
	.string "{JPN}みごと {STR_VAR_2}の なかに\l"
	.string "{JPN}つかまえた のです!$"

gTVBreakingNewsText04::
	.string "{JPN}その しゅんかん {STR_VAR_2}には\n"
	.string "{JPN}{STR_VAR_1}さんの よろこびの おたけびが\l"
	.string "{JPN}ひびき わたった そうです!\p"
	.string "{JPN}いやー {STR_VAR_1}さん!\n"
	.string "{JPN}うらやましいです!\l"
	.string "{JPN}わたしも いっしょに さけびたいです!\p"
	.string "{JPN}......いじょう\n"
	.string "{JPN}よろこび いっぱいの げんばより\l"
	.string "{JPN}おつたえ しました!$"

gTVBreakingNewsText05::
	.string "{JPN}“{STR_VAR_1}さん レア {STR_VAR_2}を\n"
	.string "{JPN} とりにがすーーー!!”\p"
	.string "{JPN}......はい!\n"
	.string "{JPN}こちら {STR_VAR_3}です!\p"
	.string "{JPN}さきほど {STR_VAR_1}さんが\n"
	.string "{JPN}レア {STR_VAR_2}を つかまえることに\l"
	.string "{JPN}しっぱい しました!$"

gTVBreakingNewsText06::
	.string "{JPN}レア {STR_VAR_2}に であった\n"
	.string "{JPN}{STR_VAR_1}さんは\l"
	.string "{JPN}{STR_VAR_3}で たたかいを いどみました$"

gTVBreakingNewsText07::
	.string "{JPN}そして......\p"
	.string "{JPN}{STR_VAR_2}に {STR_VAR_1} などを\n"
	.string "{JPN}めいれい している うちに\l"
	.string "{JPN}きが つくと たおしていた のです......$"

gTVBreakingNewsText12::
	.string "{JPN}しかし......\p"
	.string "{JPN}レア {STR_VAR_2}に おどろいて\n"
	.string "{JPN}こんらんした {STR_VAR_1}さんは\l"
	.string "{JPN}わけも わからないまま\l"
	.string "{JPN}{STR_VAR_3}に めいれいを してしまい\l"
	.string "{JPN}きが つくと たおしていた のです......$"

gTVBreakingNewsText08::
	.string "{JPN}その しゅんかん {STR_VAR_2}には\n"
	.string "{JPN}{STR_VAR_1}さんの かなしみの さけびが\l"
	.string "{JPN}ひびき わたった そうです......$"

gTVBreakingNewsText09::
	.string "{JPN}しかし......\p"
	.string "{JPN}ボールが なかったのか このあと\n"
	.string "{JPN}{STR_VAR_2}から にげてしまった のです\p"
	.string "{JPN}その しゅんかん {STR_VAR_3}には\n"
	.string "{JPN}{STR_VAR_1}さんの かなしみの さけびが\l"
	.string "{JPN}ひびき わたった そうです......$"

gTVBreakingNewsText10::
	.string "{JPN}しかし......\p"
	.string "{JPN}{STR_VAR_2}は あっというまに\n"
	.string "{JPN}にげてしまった のです\p"
	.string "{JPN}その しゅんかん {STR_VAR_3}には\n"
	.string "{JPN}{STR_VAR_1}さんの かなしみの さけびが\l"
	.string "{JPN}ひびき わたった そうです......$"

gTVBreakingNewsText11::
	.string "{JPN}いやー {STR_VAR_1}さん!\n"
	.string "{JPN}ざんねん でした......\l"
	.string "{JPN}わたしも いっしょに さけびたいです\p"
	.string "{JPN}......いじょう\n"
	.string "{JPN}かなしみ いっぱいの げんばより\l"
	.string "{JPN}おつたえ しました......!$"

gTVSecretBaseVisitText00::
	.string "{JPN}みなさん こんにちは!\n"
	.string "{JPN}“ひみつきち ほうもん!”の じかんです\p"
	.string "{JPN}きょうは {STR_VAR_1}さんの ひみつきちに\n"
	.string "{JPN}おじゃま させて いただきます\p"
	.string "{JPN}{STR_VAR_1}さんの きちは どんな\n"
	.string "{JPN}おへやに なっている のでしょうか?\p"
	.string "{JPN}さっそく はいって みましょう!\n"
	.string "......... ......... ......... .........$"

gTVSecretBaseVisitText01::
	.string "{JPN}おおー!\p"
	.string "{JPN}こんな ところに ‘{STR_VAR_2}’が!\n"
	.string "{JPN}すばらしい ですねー$"

gTVSecretBaseVisitText02::
	.string "{JPN}おおー!\p"
	.string "{JPN}なんと!\n"
	.string "{JPN}グッズが なにも ありません!\p"
	.string "{JPN}ふつうの ひとには まね できない\n"
	.string "{JPN}この だいたんさ!\p"
	.string "{JPN}シンプルで ありながら\n"
	.string "{JPN}あふれでる この ワイルドさ!\p"
	.string "{JPN}いやー\n"
	.string "{JPN}さすが {STR_VAR_1}さん ですねー$"

gTVSecretBaseVisitText03::
	.string "{JPN}ああー! なるほど!\p"
	.string "{JPN}ここに ‘{STR_VAR_2}’ ですか!\n"
	.string "{JPN}これは こうかてき ですねー$"

gTVSecretBaseVisitText04::
	.string "{JPN}ああー! なるほど!\p"
	.string "{JPN}ここには わざと グッズを おかずに\n"
	.string "{JPN}あけて いるのですねー\p"
	.string "{JPN}これは こうかてき ですねー$"

gTVSecretBaseVisitText05::
	.string "{JPN}ふぇー!\p"
	.string "{JPN}‘{STR_VAR_2}’と\n"
	.string "{JPN}‘{STR_VAR_3}’の くみあわせ!\p"
	.string "{JPN}ゆめの がったいに なっていますねー$"

gTVSecretBaseVisitText06::
	.string "{JPN}ふぇー!\p"
	.string "{JPN}ここに ‘{STR_VAR_2}’ですか!\n"
	.string "{JPN}ひみつきち ぜんたいに きいていますねー$"

gTVSecretBaseVisitText07::
	.string "{JPN}ふぇー!\p"
	.string "{JPN}ここには なにも おいていません\p"
	.string "{JPN}いやー この なにもない スペースが\n"
	.string "{JPN}ひみつきち ぜんたいに きいてますねー$"

gTVSecretBaseVisitText08::
	.string "{JPN}あっ!\n"
	.string "{JPN}{STR_VAR_1}さんが いらっしゃいます!\l"
	.string "{JPN}さっそく たいせん してみましょう!\p"
	.string "...... ...... ...... ......\n"
	.string "...... ...... ...... ......$"

gTVSecretBaseVisitText09::
	.string "{JPN}はぁー!\n"
	.string "{JPN}さすが {STR_VAR_1}さん です\p"
	.string "{JPN}チャンピオンと よぶに ふさわしい\n"
	.string "{JPN}つよさの ポケモン でした\p"
	.string "{JPN}{STR_VAR_1}さんの ちからづよさが\n"
	.string "{JPN}とっても でていましたよ\p"
	.string "{JPN}とくに {STR_VAR_2}に\n"
	.string "{JPN}‘{STR_VAR_3}’ なんて\l"
	.string "{JPN}{STR_VAR_1}さん らしいですねー\p"
	.string "{JPN}いやー べんきょう させて いただきました$"

gTVSecretBaseVisitText10::
	.string "{JPN}ひぃー!\n"
	.string "{JPN}さすが {STR_VAR_1}さん です\p"
	.string "{JPN}ものすごく つよい ポケモン でしたよ\p"
	.string "{JPN}{STR_VAR_1}さんの がんばりやさんな\n"
	.string "{JPN}ところが でていましたよ\p"
	.string "{JPN}とくに {STR_VAR_2}に\n"
	.string "{JPN}‘{STR_VAR_3}’ なんて\l"
	.string "{JPN}{STR_VAR_1}さん らしいですねー\p"
	.string "{JPN}いやー べんきょう させて いただきました$"

gTVSecretBaseVisitText11::
	.string "{JPN}ふぇー!\n"
	.string "{JPN}さすが {STR_VAR_1}さん です\p"
	.string "{JPN}バランスよく\n"
	.string "{JPN}そだてられた ポケモン でしたよ\p"
	.string "{JPN}{STR_VAR_1}さんの きくばり じょうずな\n"
	.string "{JPN}ところが でていましたよ\p"
	.string "{JPN}とくに {STR_VAR_2}に\n"
	.string "{JPN}‘{STR_VAR_3}’ なんて\l"
	.string "{JPN}{STR_VAR_1}さん らしいですねー\p"
	.string "{JPN}いやー べんきょう させて いただきました$"

gTVSecretBaseVisitText12::
	.string "{JPN}ほぉー!\n"
	.string "{JPN}さすが {STR_VAR_1}さん です\p"
	.string "{JPN}しょうらいの せいちょうが\n"
	.string "{JPN}たのしみな ポケモン でしたよ\p"
	.string "{JPN}{STR_VAR_1}さんの ゆめと きぼうが\n"
	.string "{JPN}でていましたよ\p"
	.string "{JPN}とくに {STR_VAR_2}に\n"
	.string "{JPN}‘{STR_VAR_3}’ なんて\l"
	.string "{JPN}{STR_VAR_1}さん らしいですねー\p"
	.string "{JPN}いやー\n"
	.string "{JPN}べんきょう させて いただきました$"

gTVSecretBaseVisitText13::
	.string "{JPN}いやー\n"
	.string "{JPN}すばらしい おへや でしたねー\p"
	.string "{JPN}みなさんも いちど {STR_VAR_1}さんの\n"
	.string "{JPN}ひみつきちを ごほうもん されてみては\l"
	.string "{JPN}いかが でしょうか?\p"
	.string "{JPN}では また じかい おあいしましょう!\n"
	.string "{JPN}さようなら!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "{JPN}“ドキドキ! ワクワク!\n"
	.string "{JPN} ポケモンくじ とうせんしゃ そくほう!”\p"
	.string "{JPN}こんにちは!\n"
	.string "{JPN}こちらは ミナモデパート 1かい\l"
	.string "{JPN}ポケモンくじ うりば です!\p"
	.string "{JPN}きょうも ひとりの ラッキートレーナーが\n"
	.string "{JPN}あらわれました!\p"
	.string "{JPN}その かたの おなまえは......\l"
	.string "{JPN}{STR_VAR_1}さん です!\p"
	.string "{JPN}{STR_VAR_1}さんは\n"
	.string "{JPN}みごと {STR_VAR_2}とうを あてて\l"
	.string "{JPN}{STR_VAR_3}を かくとく しました!\p"
	.string "{JPN}{STR_VAR_1}さん!\n"
	.string "{JPN}おめでとう ございました!\p"
	.string "{JPN}テレビの まえの みなさんも ぜひ\n"
	.string "{JPN}ミナモデパートへ ごらいてん ください!\l"
	.string "{JPN}てんいん いちどう おまち しております!\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}ホウエン いちの しなぞろえ\l"
	.string "{JPN}ミナモデパート より おおくり しました!$"

gTVThePokemonBattleSeminarText00::
	.string "{JPN}“ポケモン バトル こうざ!”\p"
	.string "{JPN}きょうも みなさんと ごいっしょに\n"
	.string "{JPN}バトルに ついて べんきょう しましょう\p"
	.string "{JPN}きょうの もんだいは\n"
	.string "{JPN}{STR_VAR_1}さんの バトルに ついてです\p"
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で\n"
	.string "{JPN}{STR_VAR_3}と たたかったの ですが......$"

gTVThePokemonBattleSeminarText01::
	.string "{JPN}{STR_VAR_2}に たいして\n"
	.string "{JPN}‘{STR_VAR_3}’を やってしまいました......\p"
	.string "{JPN}うーん...... {STR_VAR_1}さん!\n"
	.string "{JPN}これは いけませんね......$"

gTVThePokemonBattleSeminarText02::
	.string "{JPN}{STR_VAR_1}は そのほかに......$"

gTVThePokemonBattleSeminarText03::
	.string "{JPN}‘{STR_VAR_1}’ ‘{STR_VAR_2}’\n"
	.string "{JPN}‘{STR_VAR_3}’ ......を おぼえていました$"

gTVThePokemonBattleSeminarText04::
	.string "{JPN}‘{STR_VAR_1}’ ‘{STR_VAR_2}’\n"
	.string "{JPN}......を おぼえていました$"

gTVThePokemonBattleSeminarText05::
	.string "{JPN}‘{STR_VAR_2}’\n"
	.string "{JPN}......を おぼえていました$"

gTVThePokemonBattleSeminarText06::
	.string "{JPN}この なかで いちばん よいのは\n"
	.string "................................................\p"
	.string "{JPN}‘{STR_VAR_1}’ ですね!\p"
	.string "{JPN}‘{STR_VAR_2}’より\n"
	.string "{JPN}ぜったい ‘{STR_VAR_1}’です\p"
	.string "{JPN}テレビの まえの みなさんも\n"
	.string "{JPN}よーく かんがえて バトルを しましょう!\p"
	.string "{JPN}それでは さようなら!$"

gTVTrainerFanClubText00::
	.string "{JPN}せーの!\n"
	.string "{JPN}“トレーナー だいすき クラブ!!”\p"
	.string "{JPN}しかい“みんなー げんきかーい!?\n"
	.string "{JPN}きょうは いま だいにんきの トレーナー\l"
	.string "{JPN}{STR_VAR_1}さんの ファンに\l"
	.string "{JPN}あつまって もらったよ!\p"
	.string "{JPN}ファン“ワアアアアアアアアアーーー!\p"
	.string "{JPN}ファン“{STR_VAR_1}さまーーーー!\p"
	.string "{JPN}しかい“みんなー!\n"
	.string "{JPN}{STR_VAR_1}さんの ことは すきかいー?\p"
	.string "{JPN}ファン“だいすきー!!\p"
	.string "{JPN}しかい“どんな ところがー?$"

gTVTrainerFanClubText01::
	.string "{JPN}ファン“モンスターボールを なげる しぐさが\n"
	.string "{JPN}かっこいい ところ!!$"

gTVTrainerFanClubText02::
	.string "{JPN}ファン“はしる すがたが\n"
	.string "{JPN}かわいい ところ!!$"

gTVTrainerFanClubText03::
	.string "{JPN}ファン“ポケモンバトルで\n"
	.string "{JPN}ここ いちばんに つよい ところ!!$"

gTVTrainerFanClubText04::
	.string "{JPN}ファン“ポケモンの ことに ついて\n"
	.string "{JPN}くわしい ところ!!$"

gTVTrainerFanClubText05::
	.string "{JPN}ファン“ポケモンに たいして\n"
	.string "{JPN}いつも やさしい ところ!!$"

gTVTrainerFanClubText06::
	.string "{JPN}ファン“じてんしゃを あやつる\n"
	.string "{JPN}テクニックが すごい ところ!!$"

gTVTrainerFanClubText07::
	.string "{JPN}ファン“アイテムの かいかたが\n"
	.string "{JPN}ごうかいな ところ!!$"

gTVTrainerFanClubText08::
	.string "{JPN}ファン“ポケモンに つける ニックネームが\n"
	.string "{JPN}おちゃめな ところ!!$"

gTVTrainerFanClubText09::
	.string "{JPN}ファン“ひみつきちの センスが\n"
	.string "{JPN}いい ところ!!$"

gTVTrainerFanClubText10::
	.string "{JPN}ファン“わざマシンの つかい かたが\n"
	.string "{JPN}だいたんな ところ!!$"

gTVTrainerFanClubText11::
	.string "{JPN}しかい“そんな ホットな\n"
	.string "{JPN}{STR_VAR_1}さん ファンの あいだには\l"
	.string "{JPN}とくべつな あいことばが あるんだよー!\p"
	.string "{JPN}しかい“{STR_VAR_1} といえば......\p"
	.string "{JPN}しかい“{STR_VAR_2}!\p"
	.string "{JPN}ファン“{STR_VAR_3}!\p"
	.string "{JPN}しかい“{STR_VAR_2}!\p"
	.string "{JPN}ファン“{STR_VAR_3}!\p"
	.string "{JPN}しかい“{STR_VAR_1} といえば......\n"
	.string "{STR_VAR_2} {STR_VAR_3}\l"
	.string "{JPN}うーん! いい ひびきだねー!\p"
	.string "{JPN}{STR_VAR_1}さんの ファンに\n"
	.string "{JPN}なっちゃうのも わかる きが するよー!\p"
	.string "{JPN}よーし! テレビの まえの みんなも\n"
	.string "{JPN}いっしょに いってみよー!!\p"
	.string "{JPN}しかい“{STR_VAR_1} といえば......\p"
	.string "{JPN}しかい“{STR_VAR_2}!\p"
	.string "{JPN}ファン“{STR_VAR_3}!\p"
	.string "{JPN}しかい“{STR_VAR_2}!\p"
	.string "{JPN}ファン“{STR_VAR_3}!\p"
	.string "{JPN}しかい“{STR_VAR_1}さん ファンの\n"
	.string "{JPN}みんなー ありがとーーー!!\l"
	.string "{JPN}それじゃー またねー!!\p"
	.string "{JPN}しかい“{STR_VAR_1} といえば......\p"
	.string "{JPN}しかい“{STR_VAR_2}!\p"
	.string "{JPN}ファン“{STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "{JPN}“ステキに はっけん!\n"
	.string "{JPN} リボンを つけた ポケモンちゃん!!”\p"
	.string "{JPN}......はぁー\p"
	.string "{JPN}ポケモンちゃんに リボンって\n"
	.string "{JPN}ほんと ステキ ざますねー\p"
	.string "{JPN}きょうも まちで みかけた\n"
	.string "{JPN}ステキな ポケモンちゃんを\l"
	.string "{JPN}みなさまに ごしょうかい するざます\p"
	.string "{JPN}きょうの ポケモンちゃんは\n"
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2} ざます$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "{JPN}{STR_VAR_2}は なんと!\n"
	.string "{JPN}リボンを {STR_VAR_3}こ つけている ざますよ\p"
	.string "{JPN}{STR_VAR_1}さんの あいを\n"
	.string "{JPN}かんじる ざますねー$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{JPN}{STR_VAR_2}は ビックリ ざます!\n"
	.string "{JPN}リボンを {STR_VAR_3}こも つけている ざますよ\p"
	.string "{JPN}{STR_VAR_1}さんの しゅうねんを\n"
	.string "{JPN}かんじる ざますねー$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{JPN}{STR_VAR_2}は すごい ざます!\n"
	.string "{JPN}リボンを {STR_VAR_3}こも つけている ざますよ\p"
	.string "{JPN}{STR_VAR_1}さんの コレクターだましいを\n"
	.string "{JPN}かんじる ざますねー$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "{JPN}さて {STR_VAR_2}に ついている\n"
	.string "{JPN}たくさんの リボン ざますが......$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "{JPN}とくに でんどういりの きねんで もらった\n"
	.string "{JPN}チャンプリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の ゆうかんさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に チャンプリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "{JPN}とくに かっこよさ コンテストで もらった\n"
	.string "{JPN}クールリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の かっこよさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に クールリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "{JPN}とくに うつくしさ コンテストで もらった\n"
	.string "{JPN}ビューティリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の うつくしさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に ビューティリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "{JPN}とくに かわいさ コンテストで もらった\n"
	.string "{JPN}キュートリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の かわいさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に キュートリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "{JPN}とくに かしこさ コンテストで もらった\n"
	.string "{JPN}ジーニアスリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の かしこさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に ジーニアスリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "{JPN}とくに たくましさ コンテストで もらった\n"
	.string "{JPN}パワフルリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の たくましさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に パワフルリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "{JPN}とくに バトルタワーで もらった\n"
	.string "{JPN}ウイニングリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の つよさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に ウイニングリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "{JPN}とくに バトルタワーで もらった\n"
	.string "{JPN}ビクトリーリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の ものすごい つよさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に ビクトリーリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "{JPN}とくに えかきさん から もらった\n"
	.string "{JPN}プロマイドリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の アイドルらしさを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に プロマイドリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "{JPN}とくに がんばりやで もらった\n"
	.string "{JPN}がんばリボンが おにあい ざますね\p"
	.string "{JPN}{STR_VAR_2}の がんばりぶりを\n"
	.string "{JPN}とっても ひきたたせている ざますよー\p"
	.string "{JPN}{STR_VAR_2}に がんばリボン!\n"
	.string "{JPN}こうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_Outro::
	.string "{JPN}......はぁー\p"
	.string "{JPN}ポケモンに リボンって......\n"
	.string "{JPN}ホントに いい ざますね!\p"
	.string "{JPN}ウットリ したところで\n"
	.string "{JPN}さよなら ざますー!$"

gTVPokemonNewsBattleFrontierText00::
	.string "{JPN}こんにちは!\n"
	.string "{JPN}“ポケモン ニュース”の じかんです\p"
	.string "{JPN}バトルフロンティアから\n"
	.string "{JPN}うれしい ニュースが はいって きました!$"

gTVPokemonNewsBattleFrontierText01::
	.string "{JPN}バトルタワー シングル バトルルームに\n"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText02::
	.string "{JPN}バトルタワー ダブル バトルルームに\n"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText03::
	.string "{JPN}バトルタワー マルチ バトルルームに\n"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText04::
	.string "{JPN}バトルタワー\n"
	.string "{JPN}つうしん マルチ バトルルームに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText05::
	.string "{JPN}バトルドーム\n"
	.string "{JPN}シングル バトルトーナメントに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんぱで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText06::
	.string "{JPN}バトルドーム\n"
	.string "{JPN}ダブル バトルトーナメントに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんぱで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText07::
	.string "{JPN}バトルファクトリー\n"
	.string "{JPN}バトルトレード シングルに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText08::
	.string "{JPN}バトルファクトリー\n"
	.string "{JPN}バトルトレード ダブルに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText09::
	.string "{JPN}バトルチューブで\n"
	.string "{JPN}バトルゲームに ちょうせんした\l"
	.string "{JPN}{STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} へや とっぱで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText10::
	.string "{JPN}バトルアリーナで\n"
	.string "{JPN}かちぬきチームバトルに ちょうせんした\l"
	.string "{JPN}{STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} にんぬきで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText11::
	.string "{JPN}バトルパレス\n"
	.string "{JPN}シングル バトルホールに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText12::
	.string "{JPN}バトルパレス\n"
	.string "{JPN}ダブル バトルホールに\l"
	.string "{JPN}ちょうせんした {STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} れんしょうで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText13::
	.string "{JPN}バトルピラミッドで\n"
	.string "{JPN}バトルアドベンチャーに ちょうせんした\l"
	.string "{JPN}{STR_VAR_1}さんが\l"
	.string "{JPN}{STR_VAR_2} だん せいはで\l"
	.string "{JPN}きろくを こうしん しました!\p"
	.string "{JPN}......{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText14::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}と\n"
	.string "{JPN}{STR_VAR_3}の 3ひきの ポケモンたち!\p"
	.string "{JPN}きろく こうしん\n"
	.string "{JPN}おめでとう ございました!!$"

gTVPokemonNewsBattleFrontierText15::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}の\n"
	.string "{JPN}2ひきの ポケモンたち!\p"
	.string "{JPN}きろく こうしん\n"
	.string "{JPN}おめでとう ございました!!$"

gTVPokemonNewsBattleFrontierText16::
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "{JPN}そして {STR_VAR_1}の\n"
	.string "{JPN}4ひきの ポケモンたち!\p"
	.string "{JPN}きろく こうしん\n"
	.string "{JPN}おめでとう ございました!!$"

gTVPokemonNewsBattleFrontierText18::
	.string "{JPN}{STR_VAR_1}さんと ポケモンたちの\n"
	.string "{JPN}つぎの チャレンジに きたい しましょう!\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}“ポケモン ニュース” でした!$"

gTVWhatsNo1InHoennTodayText00::
	.string "{JPN}“ホウエン きょうの\n"
	.string "{JPN} なんでも ナンバー1!!”\p"
	.string "{JPN}テレビの まえの みなさん\n"
	.string "{JPN}がんばってますかー?\p"
	.string "{JPN}きょうも いちにちで いちばん がんばった\n"
	.string "{JPN}トレーナーを しょうかい しますよ!\p"
	.string "{JPN}......さあ\n"
	.string "{JPN}きょうの ナンバー1 トレーナーは......\l"
	.string "{JPN}{STR_VAR_1}さんです!!$"

gTVWhatsNo1InHoennTodayText01::
	.string "{JPN}{STR_VAR_1}さんは ゲームコーナーの\n"
	.string "{JPN}スロットを いちにちで\l"
	.string "{JPN}{STR_VAR_2} かい まわしました!\p"
	.string "{JPN}{STR_VAR_1}さんは あそんで いるときに\n"
	.string "{JPN}‘スロットが とまって みえる......!’と\l"
	.string "{JPN}ブツブツ ぶきみに\l"
	.string "{JPN}つぶやいていた そうですよ!$"

gTVWhatsNo1InHoennTodayText02::
	.string "{JPN}{STR_VAR_1}さんは ゲームコーナーの\n"
	.string "{JPN}ルーレットを いちにちで\l"
	.string "{JPN}{STR_VAR_2} かい まわしました!\p"
	.string "{JPN}{STR_VAR_1}さんは あそんで いるとき\n"
	.string "{JPN}‘ボールの うごきが よめた......!’と\l"
	.string "{JPN}めを まっかにして\l"
	.string "{JPN}それは すごい かおで\l"
	.string "{JPN}さけんでいた そうですよ!$"

gTVWhatsNo1InHoennTodayText03::
	.string "{JPN}{STR_VAR_1}さんは やせい ポケモンと\n"
	.string "{JPN}いちにちで {STR_VAR_2} かい たたかいました!\p"
	.string "{JPN}{STR_VAR_1}さんの ポケモンたちは\n"
	.string "{JPN}いぜんと くらべものに ならないほど\l"
	.string "{JPN}つよくなった らしく......\p"
	.string "{JPN}だれかと ポケモンしょうぶが したくて\n"
	.string "{JPN}たまらない そうですよ!$"

gTVWhatsNo1InHoennTodayText04::
	.string "{JPN}{STR_VAR_1}さんは きのみブレンダーを\n"
	.string "{JPN}いちにちで {STR_VAR_2} かい まわしました!\p"
	.string "{JPN}さすがに さいごの ほうでは\n"
	.string "{JPN}{STR_VAR_1}さんの めも\l"
	.string "{JPN}くるくる まわってしまい\l"
	.string "{JPN}まるで パッチールの ように\l"
	.string "{JPN}なってしまった そうですよ!$"

gTVWhatsNo1InHoennTodayText05::
	.string "{JPN}{STR_VAR_1}さんは きのみを\n"
	.string "{JPN}いちにちで {STR_VAR_2} こ うえました!\p"
	.string "{JPN}{STR_VAR_1}さんの\n"
	.string "{JPN}ふくは まっくろに なりましたが......\p"
	.string "{JPN}きのみを うえた ところには\n"
	.string "{JPN}きれいな はなが たくさん さきほこり\l"
	.string "{JPN}みる ひとの こころを\l"
	.string "{JPN}なごませている そうですよ!$"

gTVWhatsNo1InHoennTodayText06::
	.string "{JPN}{STR_VAR_1}さんは きのみを いちにちで\n"
	.string "{JPN}{STR_VAR_2} こ とりました\p"
	.string "{JPN}{STR_VAR_1}さんの バックは\n"
	.string "{JPN}きのみで いっぱいに なり\l"
	.string "{JPN}あるくのも たいへんだった そうですよ!$"

gTVWhatsNo1InHoennTodayText07::
	.string "{JPN}{STR_VAR_1}さんは いちにちで\n"
	.string "{JPN}バトルポイントを\l"
	.string "{JPN}{STR_VAR_2} BP ためました!\p"
	.string "{JPN}{STR_VAR_1}さんは \n"
	.string "{JPN}たまった バトルポイントで\l"
	.string "{JPN}すごい グッズを もらうべきか......\l"
	.string "{JPN}すごい アイテムを もらうべきか......と\l"
	.string "{JPN}ニタニタ しながら\l"
	.string "{JPN}ずっと なやんでいた そうですよ!$"

gTVWhatsNo1InHoennTodayText08::
	.string "{JPN}いやー すごい ですね!\p"
	.string "{JPN}{STR_VAR_1}さん!\n"
	.string "{JPN}あなたが きょうの ナンバー1です!!\p"
	.string "{JPN}テレビの まえの みなさんも\n"
	.string "{JPN}{STR_VAR_1}さんに まけずに\l"
	.string "{JPN}いちにち がんばりましょうね!$"

TVSecretBaseSecrets_Text_Intro::
	.string "{JPN}“ひみつきちの ヒミツー!”\p"
	.string "{JPN}ひみつきちで トレーナーは いったい\n"
	.string "{JPN}どんな こうどうを とる のでしょうか?\p"
	.string "{JPN}きょうは\n"
	.string "{JPN}{STR_VAR_1}さんの ひみつきちです\p"
	.string "{JPN}......さあ {STR_VAR_2}さんが\n"
	.string "{JPN}あそびに いらした ようですね!\p"
	.string "{JPN}さっそく のぞいてみましょう!\p"
	.string "{JPN}まず {STR_VAR_2}さんは......$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "{JPN}{STR_VAR_2}さんは つぎに......$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "{JPN}この あと\n"
	.string "{JPN}{STR_VAR_2}さんは......$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "{JPN}......と いうような かんじで\n"
	.string "{JPN}{STR_VAR_2}さんは\l"
	.string "{JPN}{STR_VAR_1}さんの きちを\l"
	.string "{JPN}{STR_VAR_3}ほ あるいて かえりました$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "{JPN}......うーん\p"
	.string "{JPN}どうやら {STR_VAR_2}さんは\n"
	.string "{JPN}{STR_VAR_1}さんの ひみつきちに\l"
	.string "{JPN}きょうみが わかなかった ようですね......$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{JPN}{STR_VAR_2}さんは\n"
	.string "{JPN}{STR_VAR_1}さんの ひみつきちを\l"
	.string "{JPN}とっても たのしんだ ようですね$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{JPN}{STR_VAR_2}さんは\n"
	.string "{JPN}{STR_VAR_1}さんの ひみつきちマニアに\l"
	.string "{JPN}なった ようですね$"

TVSecretBaseSecrets_Text_Outro::
	.string "{JPN}テレビの まえの みなさんも\n"
	.string "{JPN}{STR_VAR_1}さんの ひみつきちを\l"
	.string "{JPN}たずねて みては いかがでしょうか?\p"
	.string "{JPN}それでは また だれかの ひみつきちで\n"
	.string "{JPN}おあいしましょう! さようなら!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "{JPN}......たちどまって しまいました!\p"
	.string "{JPN}ぜんぜん うごきません!\p"
	.string "{JPN}{STR_VAR_1}さんの ひみつきちが\n"
	.string "{JPN}きに いらなかった のでしょうか?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "{JPN}......たちどまって しまいました!\p"
	.string "{JPN}ぜんぜん うごきません!\p"
	.string "{JPN}......つかれちゃった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "{JPN}いすに すわりましたー!\p"
	.string "{JPN}とっても うれしそうです\p"
	.string "{JPN}すわりごこちが\n"
	.string "{JPN}よかった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "{JPN}ふうせんに とつげきだー!\p"
	.string "{JPN}わっちゃいました!\p"
	.string "{JPN}ちょっと おとに\n"
	.string "{JPN}ビックリ しています$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "{JPN}テントに はいったー!\p"
	.string "{JPN}はしりまわって います!\p"
	.string "{JPN}あばれまわって います!\p"
	.string "{JPN}テントの おおきさに\n"
	.string "{JPN}びっくり しています!!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "{JPN}はちうえを かんさつ しています!\p"
	.string "{JPN}いがいに アダルトな しゅみを\n"
	.string "{JPN}もっていますね......$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "{JPN}きんのたてを みています!\p"
	.string "{JPN}キラキラと めを\n"
	.string "{JPN}かがやかせて いますね$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "{JPN}ぎんのたてを みています!\p"
	.string "{JPN}めを まるーく していますね$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "{JPN}ガラスのオブジェを みています......\p"
	.string "{JPN}あっ!\p"
	.string "{JPN}さわっちゃいました......\p"
	.string "{JPN}しもんを ペタペタ つけています$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "{JPN}テレビを みています!\p"
	.string "{JPN}かなりの テレビっこ みたいですねー$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "{JPN}どろだんごを ふみつけましたー!\p"
	.string "{JPN}とっても うれしそうです$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "{JPN}......おや?\p"
	.string "{JPN}とつぜん バッグの なかみを\n"
	.string "{JPN}ガサガサと いじりだしましたよ!\p"
	.string "{JPN}そして {STR_VAR_2}を\n"
	.string "{JPN}とりだしたー!\p"
	.string "{JPN}{STR_VAR_2}を もって\n"
	.string "{JPN}スマイル! スマイル!!\p"
	.string "{JPN}テレビの コマーシャル みたいだー!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "{JPN}クッションを つかんで......$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "{JPN}たたいてます!\p"
	.string "{JPN}だいぶ ストレスが\n"
	.string "{JPN}たまっている のでしょうか?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "{JPN}だきついたー!\p"
	.string "{JPN}なにか いいことでも あった のでしょうか?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\p"
	.string "{JPN}どうやら ポケモンバトルを やるようです\p"
	.string "{JPN}そして......\p"
	.string "{JPN}かったー!!\p"
	.string "{JPN}うれしがっています$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\p"
	.string "{JPN}どうやら ポケモンバトルを やるようです\p"
	.string "{JPN}そして......\p"
	.string "{JPN}まけたー!!\p"
	.string "{JPN}がっかり しています$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\p"
	.string "{JPN}どうやら ポケモンバトルを やるようです\p"
	.string "{JPN}そして......\p"
	.string "{JPN}いや ことわった!\p"
	.string "{JPN}たいせんを ことわりました!\p"
	.string "{JPN}{STR_VAR_1}さんの ことが\n"
	.string "{JPN}きに いらなかった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "{JPN}ポスターを じーっと みつめています!\p"
	.string "{JPN}きに いった のでしょうか?\p"
	.string "{JPN}......でも\n"
	.string "{JPN}ちょっと めつきが やばいですねー$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "{JPN}おんぷマットに のったー!\p"
	.string "{JPN}......うーん\n"
	.string "{JPN}ふしぎな きょくを つくっちゃいました......$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\p"
	.string "{JPN}どうやら ポケモンバトルを やるようです\p"
	.string "{JPN}そして......\p"
	.string "{JPN}ひきわけたー!\p"
	.string "{JPN}ふたりとも とっても くやしそうです$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "{JPN}くるっとマットに のったー!\p"
	.string "{JPN}めが まわった ようです!\p"
	.string "{JPN}クラクラ しています$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "{JPN}すなのおきものに てを ふれて......\p"
	.string "{JPN}あっ!\p"
	.string "{JPN}こわしちゃいましたー!\p"
	.string "{JPN}かおが すこし ひきつっています$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "{JPN}つくえの うえを\n"
	.string "{JPN}ゆびで さわっています!\p"
	.string "{JPN}どうやら ほこりが\n"
	.string "{JPN}きに なっている みたいです!\p"
	.string "{JPN}いやー\n"
	.string "{JPN}いがいに こまかい ですねー$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "{JPN}レンガを じーっと みつめています!\p"
	.string "{JPN}この レンガにあう グッズの ことでも\n"
	.string "{JPN}かんがえている のでしょうか?$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "{JPN}じょうぶないたの うえを あるいています!\p"
	.string "{JPN}ちょっと したを きにしています\p"
	.string "{JPN}いがいに きが ちっちゃいですねー$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "{JPN}さくを じーっと ながめています!\p"
	.string "{JPN}あたらしい トラップでも\n"
	.string "{JPN}ひらめいた のでしょうか?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "{JPN}きらきらマットに のったー!\p"
	.string "{JPN}いろんな ポーズを きめています!\p"
	.string "{JPN}きぶんは アイドル でしょうか?$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "{JPN}タイヤを じーっと みつめています!\p"
	.string "{JPN}この タイヤで はしる くるまの ことでも\n"
	.string "{JPN}かんがえている のでしょうか?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "{JPN}おおきなだいに のぼりました!\p"
	.string "{JPN}{STR_VAR_1}さんの きちを\n"
	.string "{JPN}うえから みわたしています!\p"
	.string "{JPN}......そして\p"
	.string "{JPN}さけんだー!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "{JPN}やぶれるドアに むかって とつげきー!\p"
	.string "{JPN}わらっています......$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "{JPN}ぬいぐるみに はなし かけています!\p"
	.string "{JPN}ちょっと こわい ですね......$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "{JPN}すべりだいの はしごを のぼりました!\p"
	.string "{JPN}......そして\p"
	.string "{JPN}すべったー!\p"
	.string "{JPN}とっても たのしそうだ!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "{JPN}すべりだいの はしごを のぼりました!\p"
	.string "{JPN}......そして\p"
	.string "{JPN}もどったー!\p"
	.string "{JPN}ハシゴを おりて ひきかえしました!\p"
	.string "{JPN}こわくなった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "{JPN}ジャンプマットに のったー!\p"
	.string "{JPN}ジャンプを 1かい!\p"
	.string "{JPN}ジャンプを 2かい!\p"
	.string "{JPN}ちゃくち せいこう!\p"
	.string "{JPN}......ひとりで じぶんに\n"
	.string "{JPN}はくしゅを おくっています$"

gTVSafariFanClubText00::
	.string "{JPN}“サファリ だいすき クラブ!”\p"
	.string "{JPN}レポーター“サファリボール なげてますか?\n"
	.string "{JPN}わたしは いま めずらしい ポケモンが\l"
	.string "{JPN}いっぱいの サファリゾーンに きています\p"
	.string "{JPN}さっそく かかりいんさんに\n"
	.string "{JPN}おはなしを うかがって みましょう!\p"
	.string "{JPN}......サファリに きている トレーナーたちの\n"
	.string "{JPN}ようすは いかがですか?$"

gTVSafariFanClubText01::
	.string "{JPN}かかりいん“みんな がんばってますよ\p"
	.string "{JPN}とくに {STR_VAR_1}さん なんて\n"
	.string "{JPN}すごいです\p"
	.string "{JPN}この あいだ なんて {STR_VAR_2}ひきも\n"
	.string "{JPN}つかまえたんですよ!$"

gTVSafariFanClubText02::
	.string "{JPN}{STR_VAR_2}この ポロックを\n"
	.string "{JPN}じょうずに つかっていました!$"

gTVSafariFanClubText03::
	.string "{JPN}しかも ポロックを 1こも\n"
	.string "{JPN}つかって いないんです!\p"
	.string "{JPN}いやー すごい うで でしたよ$"

gTVSafariFanClubText04::
	.string "{JPN}レポーター“そうですかー\p"
	.string "{JPN}{STR_VAR_1}さんは\n"
	.string "{JPN}サファリの めいじん ですね\p"
	.string "{JPN}かかりいん“また おとずれて\n"
	.string "{JPN}あの すごい わざを みせて ほしいです$"

gTVSafariFanClubText05::
	.string "{JPN}かかりいん“みんな いまいち ですね......\p"
	.string "{JPN}とくに {STR_VAR_1}さんは\n"
	.string "{JPN}ひどかった ですね\p"
	.string "{JPN}この あいだ なんて {STR_VAR_2}ひき しか\n"
	.string "{JPN}つかまえられません でしたから$"

gTVSafariFanClubText06::
	.string "{JPN}かかりいん“みんな いまいち ですね......\p"
	.string "{JPN}とくに {STR_VAR_1}さんは\n"
	.string "{JPN}ひどかった ですね\p"
	.string "{JPN}この あいだ なんて 1ひきも\n"
	.string "{JPN}つかまえられません でしたから......$"

gTVSafariFanClubText07::
	.string "{JPN}いちおう ポロックは {STR_VAR_2}こ\n"
	.string "{JPN}つかって いましたけどね\p"
	.string "{JPN}もう ちょっと\n"
	.string "{JPN}うでを あげて ほしいですねー$"

gTVSafariFanClubText08::
	.string "{JPN}1こも つかってなかった\n"
	.string "{JPN}ポロックを つかうように なれば\l"
	.string "{JPN}よくなると おもうんですがね......$"

gTVSafariFanClubText09::
	.string "{JPN}レポーター“そうですかー\p"
	.string "{JPN}{STR_VAR_1}さん には\n"
	.string "{JPN}サファリを とっくんして ほしいですね\p"
	.string "{JPN}かかりいん“なんども おとずれて\n"
	.string "{JPN}コツを つかんで ほしいです$"

gTVSafariFanClubText10::
	.string "{JPN}レポーター“そうです!\n"
	.string "{JPN}チャレンジは たいせつです\p"
	.string "{JPN}テレビの まえの みなさんも なんどでも\n"
	.string "{JPN}サファリに チャレンジ しましょう!\p"
	.string "{JPN}では また!$"

ContestLiveUpdates_Text_Intro::
	.string "{JPN}“ポケモン コンテスト\n"
	.string "{JPN} けっか そくほう!”\p"
	.string "{JPN}しかい“......はい!\n"
	.string "{JPN}こちら さきほど おわりました\l"
	.string "{JPN}{STR_VAR_1} コンテストの かいじょうです\p"
	.string "{JPN}かいじょうには まだ たくさんの\n"
	.string "{JPN}おきゃくさんが のこっています\p"
	.string "{JPN}かんきゃく“{STR_VAR_2}ーーー!\p"
	.string "{JPN}かんきゃく“{STR_VAR_3}ーーー!\p"
	.string "{JPN}しかい“......と みなさんが おっしゃる\n"
	.string "{JPN}とおりに ゆうしょう ポケモンは\l"
	.string "{JPN}{STR_VAR_3}さんの {STR_VAR_2} でした!\p"
	.string "{JPN}かんきゃく“{STR_VAR_2}! さいこー!\p"
	.string "{JPN}かんきゃく“{STR_VAR_3}! えらいー!\p"
	.string "{JPN}しかい“それでは...... おきゃくさんに\n"
	.string "{JPN}ちょっと かんそうを きいて みましょう!$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "{JPN}かんきゃく“1じ しんさも 2じ しんさも\n"
	.string "{JPN}だんとつで 1ばん でしたー!\l"
	.string "{JPN}{STR_VAR_2} つぎも ゆうしょうだー!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "{JPN}かんきゃく“1じ しんさが だめ だったのに\n"
	.string "{JPN}2じ しんさで だいぎゃくてん!\l"
	.string "{JPN}ミラクル {STR_VAR_2} ばんざいーー!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "{JPN}かんきゃく“1じ しんさも 2じ しんさも\n"
	.string "{JPN}あんてい しておったのう......\p"
	.string "{JPN}{STR_VAR_2}に {STR_VAR_3}さん!\n"
	.string "{JPN}あんたら ただものでは ないのう......$"

ContestLiveUpdates_Text_BetterRound1::
	.string "{JPN}かんきゃく“{STR_VAR_2}の\n"
	.string "{JPN}あの {STR_VAR_1}は ケタちがい でしたね!\l"
	.string "{JPN}つぎは もっと アピールを がんばってー!$"

ContestLiveUpdates_Text_GotNervous::
	.string "{JPN}かんきゃく“{STR_VAR_2}が\n"
	.string "{JPN}きんちょう したとき おもわず\l"
	.string "{JPN}がんばれー って さけんじゃいました\p"
	.string "{JPN}{STR_VAR_2} よかったね おめでとう!$"

ContestLiveUpdates_Text_StartledFoes::
	.string "{JPN}かんきゃく“{STR_VAR_2}の アピールで\n"
	.string "{JPN}おもわず ボクも おどろいちゃった!\p"
	.string "{JPN}{STR_VAR_2}! きみは スゴイ!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "{JPN}かんきゃく“{STR_VAR_2}の\n"
	.string "{JPN}あの コンボでの アピール!\l"
	.string "{JPN}ああ もう ウットリ......$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "{JPN}かんきゃく“{STR_VAR_2}の アピールに\n"
	.string "{JPN}もう もえあがっちゃいました!$"

ContestLiveUpdates_Text_WasCool::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}かっこよかった よー!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{JPN}{STR_VAR_2}\n"
	.string "{JPN}うつくしかった よー!$"

ContestLiveUpdates_Text_WasCute::
	.string "{JPN}{STR_VAR_2}\n"
	.string "{JPN}かわいかった よー!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}かしこかった よー!$"

ContestLiveUpdates_Text_WasTough::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}たくましかった よー!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "{JPN}かんきゃく“{STR_VAR_2}の アピールに\n"
	.string "{JPN}もう もえつきちゃい ました!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}さいこうに かっこいいー!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}さいこうに うつくしいー!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}さいこうに かわいいー!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}さいこうに かしこいー!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{JPN}{STR_VAR_2}!\n"
	.string "{JPN}さいこうに たくましいー!$"

ContestLiveUpdates_Text_TookBreak::
	.string "{JPN}かんきゃく“{STR_VAR_2}が とちゅうで\n"
	.string "{JPN}アピールを やすんだ ときも......\l"
	.string "{JPN}ずーっと {STR_VAR_2}だけ みてました!\p"
	.string "{JPN}もう {STR_VAR_2}の とりこ です......$"

ContestLiveUpdates_Text_GotStartled::
	.string "{JPN}かんきゃく“{STR_VAR_2}が ほかの\n"
	.string "{JPN}ポケモンの アピールに おどろいた ときは\l"
	.string "{JPN}もう なきそうに なっちゃいました!\p"
	.string "{STR_VAR_2}\n"
	.string "{JPN}がんばったねー! えらい!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "{JPN}かんきゃく“ああ......\n"
	.string "{JPN}{STR_VAR_2}の {STR_VAR_3}!\l"
	.string "{JPN}{STR_VAR_2}の {STR_VAR_3}!\l"
	.string "{JPN}{STR_VAR_2}の {STR_VAR_3}!\l"
	.string "{JPN}なんで あんなに ステキなんだー!$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "{JPN}しかい“......いやー すごいですね\n"
	.string "{JPN}{STR_VAR_1}ファン いっしょくです\p"
	.string "{JPN}その ほかの トレーナーさんと ポケモンで\n"
	.string "{JPN}わたしの いんしょうに のこったのは......\l"
	.string "{JPN}{STR_VAR_2}さんと {STR_VAR_3}ですね\p"
	.string "{JPN}{STR_VAR_2}さんの {STR_VAR_3}は......$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "{JPN}きんちょうして 2じしんさで 1かいも\n"
	.string "{JPN}アピールが できませんでした\p"
	.string "{JPN}つぎは 1かい だけでも {STR_VAR_1}の\n"
	.string "{JPN}アピールを みたいものです$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "{JPN}1じしんさも 2じしんさも\n"
	.string "{JPN}ダントツで ビリでした\p"
	.string "{JPN}{STR_VAR_1}さんには {STR_VAR_2}を\n"
	.string "{JPN}きたえ なおして\l"
	.string "{JPN}ビリから ぬけだして ほしいです$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "{JPN}かいじょうが もりあがっている ときに\n"
	.string "{JPN}ふさわしい アピールが できません でした\p"
	.string "{JPN}{STR_VAR_1}さんには ながれを よんで\n"
	.string "{JPN}つぎこそ かいじょうを エキサイト させて\l"
	.string "{JPN}さいこうに もりあげて ほしいです$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "{JPN}1じしんさで いちばん だったのに\n"
	.string "{JPN}2じしんさの アピールが うまくいかず\l"
	.string "{JPN}ぎゃくてん まけを してしまいました\p"
	.string "{JPN}きっと いまごろ {STR_VAR_1}さんは\n"
	.string "{JPN}アピールに ついて\l"
	.string "{JPN}べんきょう していると おもいます$"

ContestLiveUpdates_Text_NeverExciting::
	.string "{JPN}2じ しんさの アピールで 1ども\n"
	.string "{JPN}かんきゃくが もりあがり ませんでした\p"
	.string "{JPN}ほかの ポケモンの ことは きにせず\n"
	.string "{JPN}もっと かんきゃくに むかって\l"
	.string "{JPN}アピールをして ほしいです$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}と\n"
	.string "{JPN}ちょっとの さで まけて しまいました\p"
	.string "{JPN}あと すこしで ゆうしょう だったのに\n"
	.string "{JPN}とっても ざんねんです\p"
	.string "{JPN}いまごろ {STR_VAR_3}さんは\n"
	.string "{JPN}ないていると おもいます$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "{JPN}おなじ アピールを つづけて しんさいんに\n"
	.string "{JPN}がっかりされて しまいました\p"
	.string "{JPN}コンテストで やっては いけない\n"
	.string "{JPN}ミスを したのが いたかったですね\p"
	.string "{JPN}いまごろ {STR_VAR_1}さんは\n"
	.string "{JPN}じぶんを せめていると おもいます$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{JPN}{STR_VAR_1}さん なりに がんばって\n"
	.string "{JPN}いたのですが......\p"
	.string "{JPN}けっかてきに ビリに なってしまいました\p"
	.string "{JPN}{STR_VAR_1}さんには まけた りゆうを\n"
	.string "{JPN}かんがえて つぎに つなげて ほしいです$"

ContestLiveUpdates_Text_Outro::
	.string "{JPN}それでは さいごに みなさんと ごいっしょに\n"
	.string "{JPN}{STR_VAR_1}さんと {STR_VAR_2}に\l"
	.string "{JPN}ひとこと おくりたいと おもいます\p"
	.string "{JPN}しかい“みなさん いいですかー? せーの\p"
	.string "{JPN}みんな“{STR_VAR_1}さん! {STR_VAR_2}!\n"
	.string "{JPN}コンテスト ゆうしょう おめでとうー!$"

gTVPokemonBattleUpdateText00::
	.string "{JPN}“ポケモン たいせん そくほう!”\p"
	.string "{JPN}さきほど おこなわれた ポケモンバトルの\n"
	.string "{JPN}けっかを おつたえします$"

gTVPokemonBattleUpdateText01::
	.string "{JPN}{STR_VAR_1}さん たい\n"
	.string "{JPN}{STR_VAR_2}さんの {STR_VAR_3}バトルは......\p"
	.string "{JPN}{STR_VAR_1}さんが\n"
	.string "{JPN}しょうり しました!$"

gTVPokemonBattleUpdateText02::
	.string "{JPN}バトルは {STR_VAR_1}さんの\n"
	.string "{JPN}{STR_VAR_2}が {STR_VAR_3}を つかって\l"
	.string "{JPN}だいかつやく しました!$"

gTVPokemonBattleUpdateText03::
	.string "{JPN}{STR_VAR_1}さんに とっては\n"
	.string "{JPN}{STR_VAR_2}が ブレーキ だったのが\l"
	.string "{JPN}いたかった ようです$"

gTVPokemonBattleUpdateText04::
	.string "{JPN}しょうりを おさめた\n"
	.string "{JPN}{STR_VAR_1}さん!\l"
	.string "{JPN}おめでとう ございました!\p"
	.string "{JPN}やぶれて しまった\n"
	.string "{JPN}{STR_VAR_2}さん!\l"
	.string "{JPN}つぎは がんばって ください!\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}“ポケモン たいせん そくほう!” でした$"

gTVPokemonBattleUpdateText05::
	.string "{JPN}{STR_VAR_1}さん チーム たい\n"
	.string "{JPN}{STR_VAR_2}さん チームの\l"
	.string "{JPN}マルチバトルの けっかは......\p"
	.string "{JPN}{STR_VAR_1}さん チームが\n"
	.string "{JPN}しょうり しました$"

gTVPokemonBattleUpdateText06::
	.string "{JPN}バトルは {STR_VAR_1}さん チームの\n"
	.string "{JPN}{STR_VAR_2}が {STR_VAR_3}を つかって\l"
	.string "{JPN}だいかつやく しました!$"

gTVPokemonBattleUpdateText07::
	.string "{JPN}{STR_VAR_2}さん チームに とっては\n"
	.string "{JPN}{STR_VAR_3}が ブレーキ だったのが\l"
	.string "{JPN}いたかった ようです\p"
	.string "{JPN}しょうりを おさめた\n"
	.string "{JPN}{STR_VAR_1}さん チーム!\l"
	.string "{JPN}おめでとう ございました!\p"
	.string "{JPN}やぶれて しまった\n"
	.string "{JPN}{STR_VAR_2}さん チーム!\l"
	.string "{JPN}つぎこそ がんばって ください!\p"
	.string "{JPN}いじょう\n"
	.string "{JPN}“ポケモン たいせん そくほう!” でした$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "{JPN}マリ“おっ こんなところに\n"
	.string "{JPN}つよそうな トレーナー はっけん!\p"
	.string "{JPN}よーし カメラを まわして\n"
	.string "{JPN}インタビュー かいしよ!$"

GabbyAndTy_Text_GabbyIntro:
	.string "{JPN}マリ“あ! あなたは\n"
	.string "{JPN}このあいだの {PLAYER}さん!\p"
	.string "{JPN}よーし どのくらい つよく なったか\n"
	.string "{JPN}さっそく インタビュー かいしよ!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "{JPN}マリ“わたしの めに くるいはないわ\n"
	.string "{JPN}すごい トレーナーの はっけんよ!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "{JPN}マリ“すごい! すごい!\n"
	.string "{JPN}あなた いったい なにもの!?\p"
	.string "{JPN}さすが わたしたちが\n"
	.string "{JPN}めを つけただけ あるわ!\p"
	.string "{JPN}......あっ じつは わたしたち\n"
	.string "{JPN}いろんな ばしょの いろんな トレーナーを\l"
	.string "{JPN}インタビューして まわっているのよ\p"
	.string "{JPN}だから すこしだけ\n"
	.string "{JPN}インタビュー させて もらえないかな?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "{JPN}マリ“‘{STR_VAR_1}!’\p"
	.string "{JPN}おぼえてる? まえに たたかった とき\n"
	.string "{JPN}あなたが いった きめゼリフよ\p"
	.string "{JPN}わたしたち ちゃーんと\n"
	.string "{JPN}おぼえてるん だからね!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "{JPN}そうそう まえに たたかった ときは\n"
	.string "{JPN}ても あしも でなかった のよねぇ......\p"
	.string "{JPN}ところで どう?\n"
	.string "{JPN}また インタビュー うけてみる?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "{JPN}そうそう まえに たたかった ときは\n"
	.string "{JPN}ボールを なげられ たんだっけ......\p"
	.string "{JPN}もう びっくりして みんなに\n"
	.string "{JPN}いいふらし ちゃったわよ!\p"
	.string "{JPN}ところで どう?\n"
	.string "{JPN}また インタビュー うけてみる?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "{JPN}そうそう まえに たたかった ときは\n"
	.string "{JPN}どうぐを うまく つかわれて\l"
	.string "{JPN}まけちゃった のよね\p"
	.string "{JPN}ところで どう?\n"
	.string "{JPN}また インタビュー うけてみる?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "{JPN}そうそう まえに たたかった ときは\n"
	.string "{JPN}けっこう いいしょうぶ だったんだよね......\p"
	.string "{JPN}ところで どう?\n"
	.string "{JPN}また インタビュー うけてみる?$"

GabbyAndTy_Text_InterviewAgain:
	.string "{JPN}ところで どう?\n"
	.string "{JPN}また インタビュー うけてみる?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "{JPN}ほんと!?\n"
	.string "{JPN}ありがとう!\p"
	.string "{JPN}じゃあ たたかいの あとの\n"
	.string "{JPN}かんそうを ビシッと ひとことで\l"
	.string "{JPN}どうぞ!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "{JPN}マリ“んー!\n"
	.string "{JPN}さいこうの きめゼリフね\p"
	.string "{JPN}なんか いいテレビばんぐみが\n"
	.string "{JPN}できそうな よかん!\p"
	.string "{JPN}もしかしたら このことを\n"
	.string "{JPN}テレビで ほうそうするかも しれないから\l"
	.string "{JPN}テレビの チェックを わすれないでね!\p"
	.string "{JPN}それじゃあ\n"
	.string "{JPN}また どこかで!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "{JPN}マリ“そう......\p"
	.string "{JPN}でも これからも がんばってね!\n"
	.string "{JPN}あなたのこと ちゅうもく してるわ!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "{JPN}マリ“あなたの こと\n"
	.string "{JPN}ちゅうもく してるわ!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "{JPN}マリ“ポケモンを いっぱい つれてる\n"
	.string "{JPN}つよい トレーナーって いない かしら?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "{JPN}マリ“うーん さすがね!\p"
	.string "{JPN}まえに たたかった ときより\n"
	.string "{JPN}ずっと つよく なってる!\p"
	.string "{JPN}やっぱり わたしたちが みつけた\n"
	.string "{JPN}トレーナー よね!\p"
	.string "{JPN}ところで どう?\n"
	.string "{JPN}こんどこそ インタビューを\l"
	.string "{JPN}うけて もらえないかな?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "{JPN}マリ“すごい たたかいだったわ!\n"
	.string "{JPN}ほら ちゃんと カメラにとった!?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "{JPN}ダイ“おっ こんなところに\n"
	.string "{JPN}つよそうな トレーナー はっけん!\l"
	.string "{JPN}さっそく ろくが かいしだ!$"

GabbyAndTy_Text_TyIntro:
	.string "{JPN}ダイ“きみは このあいだの!\p"
	.string "{JPN}よーし この たたかいを\n"
	.string "{JPN}すべて カメラに おさめてやる$"

GabbyAndTy_Text_TyPostBattle:
	.string "{JPN}ダイ“さすがだな!\n"
	.string "{JPN}いい えいぞうを とることが できたよ!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "{JPN}ダイ“きみは 1ぴきしか ポケモンを\n"
	.string "{JPN}もって ないのかい?\p"
	.string "{JPN}ポケモンが いっぱい いたほうが\n"
	.string "{JPN}いい えいぞうに なるんだが......$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "{JPN}ダイ“すごい トレーナーの はっけんだ\n"
	.string "{JPN}これは だいスクープだぞ!$"

GabbyAndTy_Text_TyDefeat:
	.string "{JPN}ダイ“いまの たたかいの すべてが\n"
	.string "{JPN}この カメラのなかに!$"

gTVInSearchOfTrainersText00::
	.string "{JPN}“トレーナーを もとめて”\p"
	.string "{JPN}マリ“はーい わたしは いま\n"
	.string "{JPN}{STR_VAR_1}に きています!\p"
	.string "{JPN}きょうは ここで あたらしい さいのうを\n"
	.string "{JPN}はっくつ しようと おもいます!\p"
	.string "{JPN}きょう わたしが ちゅうもく した\n"
	.string "{JPN}トレーナーは {PLAYER}さん!\p"
	.string "{JPN}わたしは この トレーナーに\n"
	.string "{JPN}なにかを かんじます!$"

gTVInSearchOfTrainersText01::
	.string "{JPN}{PLAYER}さんとは まえに\n"
	.string "{JPN}たたかった ことが あるのですが\p"
	.string "{JPN}かくじつに まえより\n"
	.string "{JPN}つよく なっている かんじが します!\p"
	.string "{JPN}さっすが わたしの\n"
	.string "{JPN}ちゅうもく した トレーナー!$"

gTVInSearchOfTrainersText02::
	.string "{JPN}さて トレーナーの じつりょくを\n"
	.string "{JPN}みるには...\p"
	.string "{JPN}たたかって みるのが いちばん はやい!\n"
	.string "{JPN}さっそく ちょうさを かいし します!\p"
	.string "......\p"
	.string "{JPN}と いうわけで\n"
	.string "{JPN}たたかって みたの ですが\p"
	.string "{JPN}みごとに ボコボコに されました!\n"
	.string "{JPN}{PLAYER}さん やたら つよいですね......\p"
	.string "{JPN}で たたかった かんそうを\n"
	.string "{JPN}いわせて もらいますと$"

gTVInSearchOfTrainersText03::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_3}の\n"
	.string "{JPN}コンビが さいこう でしたね!\p"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_3}が おたがい\n"
	.string "{JPN}たすけあって たたかう すがた......\p"
	.string "{JPN}あぁ なんて\n"
	.string "{JPN}すばらしいんでしょう!\p"
	.string "{JPN}わたしたちとの しょうぶで\n"
	.string "{JPN}さいごに つかった ‘{STR_VAR_2}’も\p"
	.string "{JPN}{STR_VAR_1}と {STR_VAR_3}の ゆうじょうの\n"
	.string "{JPN}‘{STR_VAR_2}’なんですね!$"

gTVInSearchOfTrainersText04::
	.string "{JPN}......わたくし じしんを\n"
	.string "{JPN}なくして しまいました\p"
	.string "{JPN}いっかいも こうげきする ひまもなく\n"
	.string "{JPN}すぐに まけて しまいました\l"
	.string "{JPN}ああ グスン......\p"
	.string "{JPN}でも {PLAYER}さんの たたかいは\n"
	.string "{JPN}いっけんのかち あり です!\p"
	.string "{JPN}じしんの ある トレーナーは いちど\n"
	.string "{JPN}たたかって みることを おすすめ しますよ!$"

gTVInSearchOfTrainersText05::
	.string "{JPN}トレーナーと たたかって いるときは\n"
	.string "{JPN}モンスターボールを なげるな!\l"
	.string "{JPN}という ことです\p"
	.string "{JPN}{PLAYER}さん しょうぶは つよいのに\n"
	.string "{JPN}きほんが なって ませんよ!\p"
	.string "{JPN}もう テレビを みてる みんな!\p"
	.string "{JPN}{PLAYER}さんに あったら\n"
	.string "{JPN}ちゅういして やってね!$"

gTVInSearchOfTrainersText06::
	.string "{JPN}{PLAYER}さん あいての こうどうを\n"
	.string "{JPN}よむのが とても うまいです!\p"
	.string "{JPN}どうぐを つかう タイミング なんか\n"
	.string "{JPN}なかなかの ものでしたよ!$"

gTVInSearchOfTrainersText07::
	.string "{JPN}しょうじき わたしも なかなか\n"
	.string "{JPN}つよいかも と おもっちゃい ましたー!\p"
	.string "{JPN}さいごは けっきょく まけちゃった けど\n"
	.string "{JPN}いい しあい だったなー\p"
	.string "{JPN}でも わたしに くせん してるようじゃ\n"
	.string "{JPN}まだまだ ですよ {PLAYER}さん!$"

gTVInSearchOfTrainersText08::
	.string "{JPN}たいせんの あと {PLAYER}さんに\n"
	.string "{JPN}いまの たいせんの かんそうを きくと\p"
	.string "{JPN}‘{STR_VAR_1}’って\n"
	.string "{JPN}こたえて くれました\p"
	.string "{JPN}{PLAYER}さんの ポケモンの\n"
	.string "{JPN}{STR_VAR_2}と {STR_VAR_3}\l"
	.string "{JPN}そして ‘{STR_VAR_1}’......\p"
	.string "{JPN}んー!!\n"
	.string "{JPN}なんか いみのふかい ことば よね!\p"
	.string "{JPN}やはり いい トレーナーは\n"
	.string "{JPN}いいことを いって くれますね\p"
	.string "{JPN}さて それじゃあ また\n"
	.string "{JPN}じかいの ほうそうで おあい しましょう!$"

ContestLadyShow_Text_Intro::
	.string "{JPN}“ポケモン コンテスト けっか そくほう”\p"
	.string "{JPN}しかい“みなさん きょうしゅく です!\p"
	.string "{JPN}ほんじつは {STR_VAR_1}さ コンテストが\n"
	.string "{JPN}しゅうりょうした ばかりの こちらの\l"
	.string "{JPN}かいじょう から おおくり します!\p"
	.string "{JPN}かんきゃく“?ーーー!!\p"
	.string "{JPN}しかい“おおっと どうやら\n"
	.string "{JPN}コンテスト さんかしゃ たちが\l"
	.string "{JPN}こちらに むかって くるようですっ!\p"
	.string "{JPN}わたくし さっそく とつげき しゅざいを\n"
	.string "{JPN}おこないたいと おもいます!\p"
	.string "{JPN}かんきゃく“?ーーー!! ?ーーー!!$"

ContestLadyShow_Text_Won::
	.string "{JPN}しかい“きょうしゅく です!\p"
	.string "{JPN}ゆうしょう おめでとう ございます!\n"
	.string "{JPN}こんかいの きめてに なったのは\l"
	.string "{JPN}どんな ところ なので しょうか?\p"
	.string "{JPN}おねえさん“あたしも {STR_VAR_2}も\n"
	.string "{JPN}とっても がんばりました!\p"
	.string "{JPN}だけど きっと コンテストに でるまでに\n"
	.string "{JPN}きょうりょくして くれた ひとたちの\l"
	.string "{JPN}おかげだと おもいますっ!\p"
	.string "{JPN}しかい“では この よろこびを\n"
	.string "{JPN}いちばん つたえたい かたに むけて\l"
	.string "{JPN}ひとこと メッセージを おねがい します!\p"
	.string "{JPN}おねえさん“おーいっ!\p"
	.string "{JPN}{STR_VAR_3}さーん! みてるーっ!?\n"
	.string "{JPN}あたしたち やったよーっ!\l"
	.string "{JPN}どうも ありがとーっ!$"

ContestLadyShow_Text_Lost::
	.string "{JPN}しかい“きょうしゅく です!\p"
	.string "{JPN}しかし こんかいは ざんねん でしたね!\n"
	.string "{JPN}なにか コメントを おねがい します!\p"
	.string "{JPN}おねえさん“ざんねんでした......\n"
	.string "{JPN}あたしも {STR_VAR_2}も がんばったけど\l"
	.string "{JPN}おうえん してくれた ひとたちに\l"
	.string "{JPN}もうしわけ ないです......\p"
	.string "{JPN}しかい“うーん たしかに けづやが\n"
	.string "{JPN}ちょっと いまいちな かんじ ですねー\p"
	.string "{JPN}おねえさん“......{STR_VAR_3}さん ごめんね\n"
	.string "{JPN}こんどは がんばるから......\l"
	.string "{JPN}...... ...... うっ ...... うわーん!\p"
	.string "{JPN}かんきゃく“ガヤガヤ ガヤガヤ\p"
	.string "{JPN}しかい“あわぁぁ...... しまった......\p"
	.string "{JPN}そっ それでは このあたりで\n"
	.string "{JPN}おわかれです! みなさん さようならー!$"

ContestLadyShow_Text_LostBadly::
	.string "{JPN}しかい“きょうしゅく です!\p"
	.string "{JPN}こんかいの コンテスト いかが でした?\p"
	.string "{JPN}おねえさん“ぜんぜん だめでした......\n"
	.string "{JPN}あたしの {STR_VAR_2}は なんだか\l"
	.string "{JPN}にんきが なかった みたいで......\p"
	.string "{JPN}しかい“うーん たしかに けづやが\n"
	.string "{JPN}ちょっと いまいちな かんじ ですねー\p"
	.string "{JPN}おねえさん“...... ...... ...... ......\n"
	.string "{JPN}...... うっ ...... うっ うわーん!\p"
	.string "{JPN}かんきゃく“ガヤガヤ ガヤガヤ\p"
	.string "{JPN}しかい“あわぁぁ...... しまった......\p"
	.string "{JPN}そっ それでは このあたりで\n"
	.string "{JPN}おわかれです! みなさん さようならー!$"
