VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "{JPN}はるかかなた サイユウ\n"
	.string "{JPN}シティのおくふかくに \l"
	.string "{JPN}ポケモンリーグがあるのじゃ.\p"
	.string "{JPN}そこにあつまるトレーナーたち\nは みんなおそろしいほど\lつよいのじゃよ.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "{JPN}ポケモンリーグでは してんのう\n"
	.string "{JPN}ぜんいんと れんぞくして\l"
	.string "{JPN}たたかわなければならん.\p"
	.string "{JPN}だれかひとりにでもまけたら \n"
	.string "{JPN}また さいしょから\l"
	.string "{JPN}ちょうせんしなおしじゃ.$"

