SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "{JPN}かいていかざんが ふんかして\n"
	.string "{JPN}ふかい うみのそこから せりあがったんだ.\p"
	.string "{JPN}かざんの かこうが うみから でてきて\n"
	.string "{JPN}あまみずで みたされたのさ.\p"
	.string "{JPN}そうやって ルネシティが\n"
	.string "{JPN}できあがったんだよ.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "{JPN}ルネシティと がいかいを\n"
	.string "{JPN}つなぐ どうくつ...\p"
	.string "{JPN}あの どうくつは なにかを\n"
	.string "{JPN}そとに ださないように\l"
	.string "{JPN}つくられた みたいだね.\pそれとも わたしの\nきのせい かしら?$"

