.set LOCALID_ATTENDANT_SINGLES, 1
.set LOCALID_ATTENDANT_DOUBLES, 6

BattleFrontier_BattleDomeLobby_MapScripts::
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattleDomeLobby_OnResume
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleDomeLobby_OnFrame
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattleDomeLobby_OnWarp
	.byte 0

BattleFrontier_BattleDomeLobby_OnResume:
	dome_initresultstree
	end

BattleFrontier_BattleDomeLobby_OnWarp:
	map_script_2 VAR_TEMP_1, 0, BattleFrontier_BattleDomeLobby_EventScript_TurnPlayerNorth
	.2byte 0

BattleFrontier_BattleDomeLobby_EventScript_TurnPlayerNorth::
	setvar VAR_TEMP_1, 1
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	end

BattleFrontier_BattleDomeLobby_OnFrame:
	map_script_2 VAR_TEMP_CHALLENGE_STATUS, 0, BattleFrontier_BattleDomeLobby_EventScript_GetChallengeStatus
	map_script_2 VAR_TEMP_CHALLENGE_STATUS, CHALLENGE_STATUS_SAVING, BattleFrontier_BattleDomeLobby_EventScript_QuitWithoutSaving
	map_script_2 VAR_TEMP_CHALLENGE_STATUS, CHALLENGE_STATUS_PAUSED, BattleFrontier_BattleDomeLobby_EventScript_ResumeChallenge
	map_script_2 VAR_TEMP_CHALLENGE_STATUS, CHALLENGE_STATUS_WON, BattleFrontier_BattleDomeLobby_EventScript_WonChallenge
	map_script_2 VAR_TEMP_CHALLENGE_STATUS, CHALLENGE_STATUS_LOST, BattleFrontier_BattleDomeLobby_EventScript_LostChallenge
	.2byte 0

BattleFrontier_BattleDomeLobby_EventScript_GetChallengeStatus::
	frontier_getstatus
	end

BattleFrontier_BattleDomeLobby_EventScript_QuitWithoutSaving::
	lockall
	msgbox BattleFrontier_BattleDomeLobby_Text_DidntSaveBeforeQuitting, MSGBOX_DEFAULT
	closemessage
	dome_set DOME_DATA_WIN_STREAK, 0
	dome_set DOME_DATA_WIN_STREAK_ACTIVE, FALSE
	dome_set DOME_DATA_ATTEMPTED_CHALLENGE, TRUE
	frontier_set FRONTIER_DATA_CHALLENGE_STATUS, 0
	setvar VAR_TEMP_CHALLENGE_STATUS, 255
	releaseall
	end

BattleFrontier_BattleDomeLobby_EventScript_WonChallenge::
	call BattleFrontier_EventScript_IncrementWinStreak
	lockall
	frontier_isbrain
	goto_if_eq VAR_RESULT, TRUE, BattleFrontier_BattleDomeLobby_EventScript_DefeatedAce
	msgbox BattleFrontier_BattleDomeLobby_Text_CongratsForWinningTourney, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_GiveBattlePoints

BattleFrontier_BattleDomeLobby_EventScript_DefeatedAce::
	msgbox BattleFrontier_BattleDomeLobby_Text_CongratsDefeatedTucker, MSGBOX_DEFAULT
BattleFrontier_BattleDomeLobby_EventScript_GiveBattlePoints::
	msgbox BattleFrontier_BattleDomeLobby_Text_AwardTheseBattlePoints, MSGBOX_DEFAULT
	frontier_givepoints
	msgbox BattleFrontier_Text_ObtainedXBattlePoints, MSGBOX_GETPOINTS
	message BattleFrontier_BattleDomeLobby_Text_RecordWillBeSaved
	waitmessage
	special LoadPlayerParty
	frontier_setpartyorder FRONTIER_PARTY_SIZE
	frontier_checkairshow
	dome_set DOME_DATA_ATTEMPTED_CHALLENGE, TRUE
	dome_set DOME_DATA_HAS_WON_CHALLENGE, TRUE
	dome_set DOME_DATA_WIN_STREAK_ACTIVE, TRUE
	special LoadPlayerParty
	special HealPlayerParty
	callnative UpdateFollowingPokemon
	goto BattleFrontier_BattleDomeLobby_EventScript_AskRecordBattle

BattleFrontier_BattleDomeLobby_EventScript_LostChallenge::
	lockall
	msgbox BattleFrontier_BattleDomeLobby_Text_ThankYouForPlaying, MSGBOX_DEFAULT
	message BattleFrontier_BattleDomeLobby_Text_RecordWillBeSaved
	waitmessage
	special LoadPlayerParty
	frontier_setpartyorder FRONTIER_PARTY_SIZE
	frontier_checkairshow
	dome_set DOME_DATA_WIN_STREAK_ACTIVE, FALSE
	dome_set DOME_DATA_ATTEMPTED_CHALLENGE, TRUE
	special LoadPlayerParty
	special HealPlayerParty
	callnative UpdateFollowingPokemon
BattleFrontier_BattleDomeLobby_EventScript_AskRecordBattle::
	dome_save 0
	playse SE_SAVE
	waitse
	call BattleFrontier_EventScript_GetCantRecordBattle
	goto_if_eq VAR_RESULT, TRUE, BattleFrontier_BattleDomeLobby_EventScript_EndChallenge
	message BattleFrontier_BattleDomeLobby_Text_RecordLastMatch
	waitmessage
	multichoicedefault 20, 8, MULTI_YESNO, 1, FALSE
	switch VAR_RESULT
	case 1, BattleFrontier_BattleDomeLobby_EventScript_EndChallenge
	case 0, BattleFrontier_BattleDomeLobby_EventScript_RecordBattle
	case MULTI_B_PRESSED, BattleFrontier_BattleDomeLobby_EventScript_EndChallenge

BattleFrontier_BattleDomeLobby_EventScript_RecordBattle::
	call BattleFrontier_EventScript_SaveBattle
BattleFrontier_BattleDomeLobby_EventScript_EndChallenge::
	msgbox BattleFrontier_BattleDomeLobby_Text_HopeToSeeYouAgain, MSGBOX_DEFAULT
	closemessage
	setvar VAR_TEMP_CHALLENGE_STATUS, 255
	releaseall
	end

BattleFrontier_BattleDomeLobby_EventScript_ResumeChallenge::
	lockall
	msgbox BattleFrontier_BattleDomeLobby_Text_WeveBeenWaitingForYou, MSGBOX_DEFAULT
	message BattleFrontier_BattleDomeLobby_Text_OkayToSaveBeforeChallenge2
	waitmessage
	dome_save CHALLENGE_STATUS_SAVING
	playse SE_SAVE
	waitse
	frontier_set FRONTIER_DATA_PAUSED, FALSE
	setvar VAR_TEMP_CHALLENGE_STATUS, 255
	goto BattleFrontier_BattleDomeLobby_EventScript_EnterChallenge

BattleFrontier_BattleDomeLobby_EventScript_SinglesAttendant::
	lock
	faceplayer
	setvar VAR_FRONTIER_FACILITY, FRONTIER_FACILITY_DOME
	setvar VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES
	goto BattleFrontier_BattleDomeLobby_EventScript_AttendantWelcome
	end

BattleFrontier_BattleDomeLobby_EventScript_DoublesAttendant::
	lock
	faceplayer
	setvar VAR_FRONTIER_FACILITY, FRONTIER_FACILITY_DOME
	setvar VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES
	goto BattleFrontier_BattleDomeLobby_EventScript_AttendantWelcome
	end

BattleFrontier_BattleDomeLobby_EventScript_AttendantWelcome::
	special SavePlayerParty
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_WelcomeSingles
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_WelcomeDoubles
BattleFrontier_BattleDomeLobby_EventScript_AskTakeChallenge::
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_TakeSinglesChallenge
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_TakeDoublesChallenge
	waitmessage
	multichoice 17, 6, MULTI_CHALLENGEINFO, FALSE
	switch VAR_RESULT
	case 0, BattleFrontier_BattleDomeLobby_EventScript_TryEnterChallenge
	case 1, BattleFrontier_BattleDomeLobby_EventScript_ExplainChallenge
	case 2, BattleFrontier_BattleDomeLobby_EventScript_CancelChallenge
	case MULTI_B_PRESSED, BattleFrontier_BattleDomeLobby_EventScript_CancelChallenge

BattleFrontier_BattleDomeLobby_EventScript_TryEnterChallenge::
	message BattleFrontier_BattleDomeLobby_Text_WhichLevelMode
	waitmessage
	multichoice 17, 6, MULTI_LEVEL_MODE, FALSE
	switch VAR_RESULT
	case FRONTIER_LVL_TENT, BattleFrontier_BattleDomeLobby_EventScript_CancelChallenge
	case MULTI_B_PRESSED, BattleFrontier_BattleDomeLobby_EventScript_CancelChallenge
	frontier_checkineligible
	goto_if_eq VAR_0x8004, TRUE, BattleFrontier_BattleDomeLobby_EventScript_NotEnoughValidMons
	frontier_set FRONTIER_DATA_LVL_MODE, VAR_RESULT
	msgbox BattleFrontier_BattleDomeLobby_Text_SelectThreeMons, MSGBOX_DEFAULT
	fadescreen FADE_TO_BLACK
	callnative RemoveFollowingPokemon
	call BattleFrontier_EventScript_GetLvlMode
	copyvar VAR_0x8004, VAR_RESULT
	setvar VAR_0x8005, FRONTIER_PARTY_SIZE
	special ChoosePartyForBattleFrontier
	waitstate
	goto_if_eq VAR_RESULT, 0, BattleFrontier_BattleDomeLobby_EventScript_LoadPartyCancelChallenge
	msgbox BattleFrontier_BattleDomeLobby_Text_OkayToSaveBeforeChallenge, MSGBOX_YESNO
	switch VAR_RESULT
	case NO, BattleFrontier_BattleDomeLobby_EventScript_LoadPartyCancelChallenge
	case YES, BattleFrontier_BattleDomeLobby_EventScript_SaveBeforeChallenge
	case MULTI_B_PRESSED, BattleFrontier_BattleDomeLobby_EventScript_LoadPartyCancelChallenge

BattleFrontier_BattleDomeLobby_EventScript_SaveBeforeChallenge::
	setvar VAR_TEMP_CHALLENGE_STATUS, 0
	frontier_set FRONTIER_DATA_SELECTED_MON_ORDER
	dome_init
	frontier_set FRONTIER_DATA_CHALLENGE_STATUS, CHALLENGE_STATUS_SAVING
	frontier_set FRONTIER_DATA_PAUSED, FALSE
	special LoadPlayerParty
	closemessage
	delay 2
	call Common_EventScript_SaveGame
	setvar VAR_TEMP_CHALLENGE_STATUS, 255
	goto_if_eq VAR_RESULT, 0, BattleFrontier_BattleDomeLobby_EventScript_CancelChallengeSaveFailed
	dome_inittrainers
BattleFrontier_BattleDomeLobby_EventScript_EnterChallenge::
	special SavePlayerParty
	frontier_setpartyorder FRONTIER_PARTY_SIZE
	dome_settrainers
	msgbox BattleFrontier_BattleDomeLobby_Text_ShowYouToBattleDome, MSGBOX_DEFAULT
	closemessage
	call BattleFrontier_BattleDomeLobby_EventScript_WalkToDoor
	special HealPlayerParty
	warp MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR, 23, 6
	setvar VAR_TEMP_CHALLENGE_STATUS, 0
	waitstate
	end

BattleFrontier_BattleDomeLobby_EventScript_ExplainChallenge::
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_ExplainSinglesChallenge
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_ExplainDoublesChallenge
	goto BattleFrontier_BattleDomeLobby_EventScript_AskTakeChallenge

BattleFrontier_BattleDomeLobby_EventScript_NotEnoughValidMons::
	switch VAR_RESULT
	case FRONTIER_LVL_50, BattleFrontier_BattleDomeLobby_EventScript_NotEnoughValidMonsLv50
	case FRONTIER_LVL_OPEN, BattleFrontier_BattleDomeLobby_EventScript_NotEnoughValidMonsLvOpen

BattleFrontier_BattleDomeLobby_EventScript_NotEnoughValidMonsLv50::
	msgbox BattleFrontier_BattleDomeLobby_Text_NotEnoughValidMonsLv50, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_EndCancelChallenge

BattleFrontier_BattleDomeLobby_EventScript_NotEnoughValidMonsLvOpen::
	msgbox BattleFrontier_BattleDomeLobby_Text_NotEnoughValidMonsLvOpen, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_EndCancelChallenge

BattleFrontier_BattleDomeLobby_EventScript_CancelChallengeSaveFailed::
	frontier_set FRONTIER_DATA_CHALLENGE_STATUS, 0
	goto BattleFrontier_BattleDomeLobby_EventScript_CancelChallenge

BattleFrontier_BattleDomeLobby_EventScript_LoadPartyCancelChallenge::
	special LoadPlayerParty
	callnative UpdateFollowingPokemon
BattleFrontier_BattleDomeLobby_EventScript_CancelChallenge::
	msgbox BattleFrontier_BattleDomeLobby_Text_HopeToSeeYouAgain, MSGBOX_DEFAULT
BattleFrontier_BattleDomeLobby_EventScript_EndCancelChallenge::
	release
	end

BattleFrontier_BattleDomeLobby_EventScript_WalkToDoor::
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_SinglesAttendantWalkToDoor
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_DoublesAttendantWalkToDoor
	applymovement OBJ_EVENT_ID_PLAYER, BattleFrontier_BattleDomeLobby_Movement_WalkToDoor
	waitmovement 0
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_OpenSinglesDoor
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_OpenDoublesDoor
	waitdooranim
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_SinglesAttendantEnterDoor
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_DoublesAttendantEnterDoor
	applymovement OBJ_EVENT_ID_PLAYER, BattleFrontier_BattleDomeLobby_Movement_PlayerEnterDoor
	waitmovement 0
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_SINGLES, BattleFrontier_BattleDomeLobby_EventScript_CloseSinglesDoor
	call_if_eq VAR_FRONTIER_BATTLE_MODE, FRONTIER_MODE_DOUBLES, BattleFrontier_BattleDomeLobby_EventScript_CloseDoublesDoor
	waitdooranim
	return

BattleFrontier_BattleDomeLobby_EventScript_SinglesAttendantWalkToDoor::
	applymovement LOCALID_ATTENDANT_SINGLES, BattleFrontier_BattleDomeLobby_Movement_WalkToDoor
	return

BattleFrontier_BattleDomeLobby_EventScript_DoublesAttendantWalkToDoor::
	applymovement LOCALID_ATTENDANT_DOUBLES, BattleFrontier_BattleDomeLobby_Movement_WalkToDoor
	return

BattleFrontier_BattleDomeLobby_EventScript_SinglesAttendantEnterDoor::
	applymovement LOCALID_ATTENDANT_SINGLES, BattleFrontier_BattleDomeLobby_Movement_AttendantEnterDoor
	return

BattleFrontier_BattleDomeLobby_EventScript_DoublesAttendantEnterDoor::
	applymovement LOCALID_ATTENDANT_DOUBLES, BattleFrontier_BattleDomeLobby_Movement_AttendantEnterDoor
	return

BattleFrontier_BattleDomeLobby_EventScript_WelcomeSingles::
	msgbox BattleFrontier_BattleDomeLobby_Text_WelcomeSingleBattle, MSGBOX_DEFAULT
	return

BattleFrontier_BattleDomeLobby_EventScript_WelcomeDoubles::
	msgbox BattleFrontier_BattleDomeLobby_Text_WelcomeDoubleBattle, MSGBOX_DEFAULT
	return

BattleFrontier_BattleDomeLobby_EventScript_TakeSinglesChallenge::
	message BattleFrontier_BattleDomeLobby_Text_TakeSinglesChallenge
	return

BattleFrontier_BattleDomeLobby_EventScript_TakeDoublesChallenge::
	message BattleFrontier_BattleDomeLobby_Text_TakeDoublesChallenge
	return

BattleFrontier_BattleDomeLobby_EventScript_ExplainSinglesChallenge::
	msgbox BattleFrontier_BattleDomeLobby_Text_ExplainSinglesChallenge, MSGBOX_DEFAULT
	return

BattleFrontier_BattleDomeLobby_EventScript_ExplainDoublesChallenge::
	msgbox BattleFrontier_BattleDomeLobby_Text_ExplainDoublesChallenge, MSGBOX_DEFAULT
	return

BattleFrontier_BattleDomeLobby_EventScript_OpenSinglesDoor::
	opendoor 5, 4
	return

BattleFrontier_BattleDomeLobby_EventScript_OpenDoublesDoor::
	opendoor 17, 4
	return

BattleFrontier_BattleDomeLobby_EventScript_CloseSinglesDoor::
	closedoor 5, 4
	return

BattleFrontier_BattleDomeLobby_EventScript_CloseDoublesDoor::
	closedoor 17, 4
	return

BattleFrontier_BattleDomeLobby_Movement_WalkToDoor:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

BattleFrontier_BattleDomeLobby_Movement_AttendantEnterDoor:
	walk_up
	set_invisible
	step_end

BattleFrontier_BattleDomeLobby_Movement_PlayerEnterDoor:
	walk_up
	walk_up
	set_invisible
	step_end

BattleFrontier_BattleDomeLobby_EventScript_ShowSinglesResults::
	lockall
	frontier_results FRONTIER_FACILITY_DOME, FRONTIER_MODE_SINGLES
	waitbuttonpress
	special RemoveRecordsWindow
	releaseall
	end

BattleFrontier_BattleDomeLobby_EventScript_ShowDoublesResults::
	lockall
	frontier_results FRONTIER_FACILITY_DOME, FRONTIER_MODE_DOUBLES
	waitbuttonpress
	special RemoveRecordsWindow
	releaseall
	end

BattleFrontier_BattleDomeLobby_EventScript_ShowPrevTourneyTree::
	dome_get DOME_DATA_PREV_TOURNEY_TYPE
	call_if_eq VAR_RESULT, 0, BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsSinglesLv50
	call_if_eq VAR_RESULT, 1, BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsDoublesLv50
	call_if_eq VAR_RESULT, 2, BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsSinglesLvOpen
	call_if_eq VAR_RESULT, 3, BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsDoublesLvOpen
	fadescreen FADE_TO_BLACK
	dome_showprevtourneytree
	waitstate
	end

BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsSinglesLv50::
	msgbox BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsSinglesLv50, MSGBOX_SIGN
	return

BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsDoublesLv50::
	msgbox BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsDoublesLv50, MSGBOX_SIGN
	return

BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsSinglesLvOpen::
	msgbox BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsSinglesLvOpen, MSGBOX_SIGN
	return

BattleFrontier_BattleDomeLobby_EventScript_PrevTourneyResultsDoublesLvOpen::
	msgbox BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsDoublesLvOpen, MSGBOX_SIGN
	return

BattleFrontier_BattleDomeLobby_EventScript_Maniac::
	dome_getwinnersname
	msgbox BattleFrontier_BattleDomeLobby_Text_LastWinnerWasTough, MSGBOX_NPC
	end

BattleFrontier_BattleDomeLobby_EventScript_Lass::
	msgbox BattleFrontier_BattleDomeLobby_Text_WinnersGainReputation, MSGBOX_NPC
	end

BattleFrontier_BattleDomeLobby_EventScript_FatMan::
	msgbox BattleFrontier_BattleDomeLobby_Text_TrashedInFirstRound, MSGBOX_NPC
	end

BattleFrontier_BattleDomeLobby_EventScript_Man::
	msgbox BattleFrontier_BattleDomeLobby_Text_NeedToCheckOpponentCarefully, MSGBOX_NPC
	end

@ A few OutsideWest event scripts are inserted here instead, two of which are unused
BattleFrontier_OutsideWest_EventScript_Man3::
	msgbox BattleFrontier_OutsideWest_Text_LongDreamedAboutBattleFrontier, MSGBOX_NPC
	end

@ Unused
BattleFrontier_OutsideWest_EventScript_BattleDomeSign2::
	msgbox BattleFrontier_OutsideWest_Text_BattleDomeSign2, MSGBOX_NPC
	end

@ Unused
BattleFrontier_OutsideWest_EventScript_UnderConstructionSign::
	msgbox BattleFrontier_OutsideWest_Text_QuestionMarkUnderConstruction, MSGBOX_NPC
	end

BattleFrontier_BattleDomeLobby_EventScript_RulesBoard::
	lockall
	msgbox BattleFrontier_BattleDomeLobby_Text_RulesAreListed, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_ReadRulesBoard
	end

BattleFrontier_BattleDomeLobby_EventScript_ReadRulesBoard::
	message BattleFrontier_BattleDomeLobby_Text_ReadWhichHeading
	waitmessage
	multichoice 17, 4, MULTI_BATTLE_DOME_RULES, FALSE
	switch VAR_RESULT
	case 0, BattleFrontier_BattleDomeLobby_EventScript_RulesMatchup
	case 1, BattleFrontier_BattleDomeLobby_EventScript_RulesTourneyTree
	case 2, BattleFrontier_BattleDomeLobby_EventScript_RulesDoubleKO
	case 3, BattleFrontier_BattleDomeLobby_EventScript_ExitRules
	case MULTI_B_PRESSED, BattleFrontier_BattleDomeLobby_EventScript_ExitRules
	end

BattleFrontier_BattleDomeLobby_EventScript_RulesMatchup::
	msgbox BattleFrontier_BattleDomeLobby_Text_ExplainMatchupRules, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_ReadRulesBoard
	end

BattleFrontier_BattleDomeLobby_EventScript_RulesTourneyTree::
	msgbox BattleFrontier_BattleDomeLobby_Text_ExplainTourneyTree, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_ReadRulesBoard
	end

BattleFrontier_BattleDomeLobby_EventScript_RulesDoubleKO::
	msgbox BattleFrontier_BattleDomeLobby_Text_ExplainDoubleKORules, MSGBOX_DEFAULT
	goto BattleFrontier_BattleDomeLobby_EventScript_ReadRulesBoard
	end

BattleFrontier_BattleDomeLobby_EventScript_ExitRules::
	releaseall
	end

BattleFrontier_BattleDomeLobby_Text_WelcomeSingleBattle:
	.string "{JPN}トレーナーの せんりゃくが\n"
	.string "{JPN}ためされる ばしょ!\p"
	.string "{JPN}バトルドームへ ようこそ!\p"
	.string "{JPN}わたしは シングルバトル\n"
	.string "{JPN}たいかいの あんないがかりです$"

BattleFrontier_BattleDomeLobby_Text_TakeSinglesChallenge:
	.string "{JPN}シングルバトル たいかいに\n"
	.string "{JPN}ちょうせん しますか?$"

BattleFrontier_BattleDomeLobby_Text_HopeToSeeYouAgain:
	.string "{JPN}また おこし ください$"

BattleFrontier_BattleDomeLobby_Text_ExplainSinglesChallenge:
	.string "{JPN}シングルバトル たいかいは\n"
	.string "{JPN}その なまえの とおり\l"
	.string "{JPN}シングルバトルの たいかいです\p"
	.string "{JPN}さんか する トレーナーは\n"
	.string "{JPN}3ひきの ポケモンを つれてきます\p"
	.string "{JPN}かくバトルでは 3ひきの うち\n"
	.string "{JPN}1ひきを よびに おく ひつようが\l"
	.string "{JPN}あります\p"
	.string "{JPN}のこりの 2ひきが\n"
	.string "{JPN}1ひきずつ たたかいます\p"
	.string "{JPN}あいての 3ひきを けんとうしてから\n"
	.string "{JPN}たたかう 2ひきを えらびます\p"
	.string "{JPN}4にんの トレーナーを たおすと\n"
	.string "{JPN}たいかい ゆうしょうです\p"
	.string "{JPN}ゆうしょうしゃには\n"
	.string "{JPN}バトルポイントが もらえます\p"
	.string "{JPN}たいかいを ちゅうだんしたいときは\n"
	.string "{JPN}セーブを してください\p"
	.string "{JPN}セーブしないで ちゅうだんすると\nしっかく となります$"

BattleFrontier_BattleDomeLobby_Text_OkayToSaveBeforeChallenge:
	.string "{JPN}バトルドームへ あんないする まえに\n"
	.string "{JPN}データを セーブします よろしいですか?$"

BattleFrontier_BattleDomeLobby_Text_WhichLevelMode:
	.string "{JPN}たいかいには ノーマル と ハード\n"
	.string "{JPN}の 2つの レベルが あります\l"
	.string "{JPN}どちらを えらびますか?$"

BattleFrontier_BattleDomeLobby_Text_SelectThreeMons:
	.string "{JPN}それでは エントリーする\n"
	.string "{JPN}3ひきの ポケモンを えらんでください$"

BattleFrontier_BattleDomeLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}すみません!\p"
	.string "{JPN}さんか できる ポケモンが\n"
	.string "{JPN}3ひき いません\p"
	.string "{JPN}また ポケモンは それぞれ\n"
	.string "{JPN}ちがう しゅるいの どうぐを\l"
	.string "{JPN}もたせて ください\pタマゴ{STR_VAR_1}は さんか できません\pじゅんびが できたら きてください$"

BattleFrontier_BattleDomeLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}すみません!\p"
	.string "{JPN}さんか できる ポケモンが\n"
	.string "{JPN}3ひき いません\p"
	.string "{JPN}3ひきとも ちがう ポケモンで\n"
	.string "{JPN}なければ いけません\p"
	.string "{JPN}また それぞれ ちがう しゅるいの\n"
	.string "{JPN}どうぐを もたせて ください\pタマゴ{STR_VAR_1}は さんか できません\pじゅんびが できたら きてください$"

BattleFrontier_BattleDomeLobby_Text_ShowYouToBattleDome:
	.string "{JPN}それでは バトルドームへ\n"
	.string "{JPN}あんない いたします$"

BattleFrontier_BattleDomeLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}すみません!\p"
	.string "{JPN}まえかい セーブしないで\n"
	.string "{JPN}ちょうせんを やめられました\p"
	.string "{JPN}そのため これまでの\n"
	.string "{JPN}ちょうせんは しっかくです すみません!$"

BattleFrontier_BattleDomeLobby_Text_CongratsForWinningTourney:
	.string "{JPN}バトルたいかい ゆうしょう\n"
	.string "{JPN}おめでとうございます!$"

@ Unused
BattleFrontier_BattleDomeLobby_Text_HereIsYourPrize:
	.string "{JPN}バトルたいかい ゆうしょうの\n"
	.string "{JPN}しょうひんです$"

@ Used by Verdanturf Tent
BattleFrontier_BattleDomeLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は しょうひん\n"
	.string "{JPN}{STR_VAR_1}を もらった!$"

@ Unused
BattleFrontier_BattleDomeLobby_Text_BagFullMakeRoom:
	.string "{JPN}あ! バッグが いっぱいの ようですね\p"
	.string "{JPN}バッグに ばしょを つくってから\n"
	.string "{JPN}また きてください$"

BattleFrontier_BattleDomeLobby_Text_ThankYouForPlaying:
	.string "{JPN}ありがとうございました!$"

BattleFrontier_BattleDomeLobby_Text_RecordWillBeSaved:
	.string "{JPN}きろくを セーブします\n"
	.string "{JPN}しょうしょう おまちください$"

BattleFrontier_BattleDomeLobby_Text_WeveBeenWaitingForYou:
	.string "{JPN}おまち していました!$"

BattleFrontier_BattleDomeLobby_Text_OkayToSaveBeforeChallenge2:
	.string "{JPN}バトルドームへ あんないする まえに\n"
	.string "{JPN}データを セーブします よろしいですか?$"

BattleFrontier_BattleDomeLobby_Text_WelcomeDoubleBattle:
	.string "{JPN}トレーナーの せんりゃくが\n"
	.string "{JPN}ためされる ばしょ!\p"
	.string "{JPN}バトルドームへ ようこそ!\p"
	.string "{JPN}わたしは ダブルバトル\n"
	.string "{JPN}たいかいの あんないがかりです$"

BattleFrontier_BattleDomeLobby_Text_TakeDoublesChallenge:
	.string "{JPN}ダブルバトル たいかいに\n"
	.string "{JPN}ちょうせん しますか?$"

BattleFrontier_BattleDomeLobby_Text_ExplainDoublesChallenge:
	.string "{JPN}ダブルバトル たいかいは\n"
	.string "{JPN}その なまえの とおり\l"
	.string "{JPN}ダブルバトルの たいかいです\p"
	.string "{JPN}さんか する トレーナーは\n"
	.string "{JPN}3ひきの ポケモンを つれてきます\p"
	.string "{JPN}かくバトルでは 3ひきの うち\n"
	.string "{JPN}1ひきを よびに おく ひつようが\l"
	.string "{JPN}あります\p"
	.string "{JPN}のこりの 2ひきで\n"
	.string "{JPN}ダブルバトルを おこないます\p"
	.string "{JPN}あいての 3ひきを けんとうしてから\n"
	.string "{JPN}たたかう 2ひきを えらびます\p"
	.string "{JPN}4にんの トレーナーを たおすと\n"
	.string "{JPN}たいかい ゆうしょうです\p"
	.string "{JPN}ゆうしょうしゃには\n"
	.string "{JPN}バトルポイントが もらえます\p"
	.string "{JPN}たいかいを ちゅうだんしたいときは\n"
	.string "{JPN}セーブを してください\p"
	.string "{JPN}セーブしないで ちゅうだんすると\nしっかく となります$"

BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsSinglesLv50:
	.string "{JPN}これは ぜんかいの\n"
	.string "{JPN}ノーマル シングルバトル たいかいの\lけっかです$"

BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsDoublesLv50:
	.string "{JPN}これは ぜんかいの\n"
	.string "{JPN}ノーマル ダブルバトル たいかいの\lけっかです$"

BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsSinglesLvOpen:
	.string "{JPN}これは ぜんかいの\n"
	.string "{JPN}ハード シングルバトル たいかいの\lけっかです$"

BattleFrontier_BattleDomeLobby_Text_PrevTourneyResultsDoublesLvOpen:
	.string "{JPN}さっきの\n"
	.string "{JPN}ハードレベル ダブルバトル\lトーナメントの けっかです$"

BattleFrontier_BattleDomeLobby_Text_LastWinnerWasTough:
	.string "{JPN}みましたか?\n"
	.string "{JPN}さいごの バトルトーナメント?\p"
	.string "{JPN}{STR_VAR_1}が\n"
	.string "{JPN}かったんですが ほんとうに\l"
	.string "{JPN}つよかったですね\p"
	.string "{JPN}パソコンの よこの モニターで\nけっかを チェックしてください$"

BattleFrontier_OutsideWest_Text_LongDreamedAboutBattleFrontier:
	.string "{JPN}バトルフロンティア...\n"
	.string "{JPN}ながいあいだ このような\nばしょを ゆめみていたのだ$"

@ Functionally unused
BattleFrontier_OutsideWest_Text_BattleDomeSign2:
	.string "{JPN}バトルドーム\n"
	.string "{JPN}ムテキの スーパースターに なれ!$"

@ Functionally unused
BattleFrontier_OutsideWest_Text_QuestionMarkUnderConstruction:
	.string "{JPN}??????\n"
	.string "{JPN}けんせつちゅう!$"

BattleFrontier_BattleDomeLobby_Text_WinnersGainReputation:
	.string "{JPN}トレーナーが バトルドームで\n"
	.string "{JPN}トーナメントを つづけて\l"
	.string "{JPN}かちつづけると\l"
	.string "{JPN}スターとして ひょうばんになる\p"
	.string "{JPN}その ひょうばんに ひかれて\n"
	.string "{JPN}つよい トレーナーたちが\l"
	.string "{JPN}バトルドームに あつまってくる\pほんとうの スーパースターは\nトーナメントで かちつづける\lトレーナーなんだ$"

BattleFrontier_BattleDomeLobby_Text_TrashedInFirstRound:
	.string "{JPN}トーナメントの ゆうりょくしゃに\n"
	.string "{JPN}いちかいせんめから\n"
	.string "{JPN}であってしまった\p{JPN}もちろん ぼろまけさ...$"
BattleFrontier_BattleDomeLobby_Text_NeedToCheckOpponentCarefully:
	.string "{JPN}この ポケモンを とっておけば\n"
	.string "{JPN}かてたのに...\p"
	.string "{JPN}あいての ポケモンを よく\n"
	.string "{JPN}チェックしてから たたかう\l"
	.string "{JPN}ポケモンを えらばないとね$"

BattleFrontier_BattleDomeLobby_Text_CongratsDefeatedTucker:
	.string "{JPN}おめでとう!\p"
	.string "{JPN}ドームエースを たおして\n"
	.string "{JPN}バトルトーナメントで\lゆうしょうしました!$"

BattleFrontier_BattleDomeLobby_Text_AwardTheseBattlePoints:
	.string "{JPN}あなたの せんりゃくは\n"
	.string "{JPN}うつくしいものでした\l"
	.string "{JPN}そのしょうとして\lバトルポイントを さしあげます!$"

BattleFrontier_BattleDomeLobby_Text_RecordLastMatch:
	.string "{JPN}さっきの バトルドームの\n"
	.string "{JPN}しあいを フロンティアパスに\l"
	.string "{JPN}きろくしますか?$"

BattleFrontier_BattleDomeLobby_Text_RulesAreListed:
	.string "{JPN}バトルトーナメントの\n"
	.string "{JPN}ルールです$"

BattleFrontier_BattleDomeLobby_Text_ReadWhichHeading:
	.string "{JPN}どの こうもくを よみますか?$"

BattleFrontier_BattleDomeLobby_Text_ExplainMatchupRules:
	.string "{JPN}トーナメントの たいせんひょうは\n"
	.string "{JPN}トレーナーの もつ ポケモンの\l"
	.string "{JPN}つよさに もとづいて つくられます\p"
	.string "{JPN}つよい トレーナーどうしが\n"
	.string "{JPN}さいしょから たたかわないように\lくみあわせを ちょうせいします$"

BattleFrontier_BattleDomeLobby_Text_ExplainTourneyTree:
	.string "{JPN}トーナメントひょう つまり\n"
	.string "{JPN}トーナメントツリーは\l"
	.string "{JPN}たいきしつで ガイドから\l"
	.string "{JPN}みることが できます\p"
	.string "{JPN}トーナメントツリーでは\n"
	.string "{JPN}いろいろな じょうほうが\l"
	.string "{JPN}みられます\p"
	.string "{JPN}まえの トーナメントの けっか\n"
	.string "{JPN}トレーナーの もつ ポケモン\lトレーナーの たたかいかたなど\lいろんな じょうほうです$"

BattleFrontier_BattleDomeLobby_Text_ExplainDoubleKORules:
	.string "{JPN}トーナメントで たたかう\n"
	.string "{JPN}ポケモンが どうじに\l"
	.string "{JPN}たおれた ばあい\p"
	.string "{JPN}しんぱんが しあいを\nけんとうして しょうしゃを\lきめることに なります$"
