SaffronCity_Mart_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "{JPN}ラベンダーには おおきな\n"
	.string "{JPN}ラジオとうが あるんだ.$"

SaffronMart_Text_CooltrainerF:
	.string "{JPN}もっと つよくなりたいけど\n"
	.string "{JPN}まだまだ へたくそで...\p"
	.string "{JPN}こんど おしえてくれる?$"
