Route2_House_MapScripts::
	.byte 0

Route2_House_EventScript_Man::
	lock
	faceplayer
	goto_if_set FLAG_GOT_ROUTE2_NUGGET, Route2_House_EventScript_ManAfter
	msgbox Route2_House_Text_Fisher, MSGBOX_DEFAULT 
	giveitem ITEM_NUGGET
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	msgbox Route2_House_Text_Fisher_GotNugget, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_GOT_ROUTE2_NUGGET
	release
	end

Route2_House_EventScript_ManAfter::
	msgbox Route2_House_Text_Fisher_GotNugget, MSGBOX_DEFAULT
	closemessage
	release
	end

Route2_House_Text_Fisher:
	.string "{JPN}やあ! わあ きみにあえて\n"
	.string "{JPN}うれしいよ.\p"
	.string "{JPN}ながいあいだ はじめての\n"
	.string "{JPN}おきゃくさんだ.\p"
	.string "{JPN}とってもうれしい!\nちょっとしたプレゼントを\nあげるね.$"

Route2_House_Text_Fisher_GotNugget:
	.string "{JPN}それはおじさんのきんのたま！\n"
	.string "{JPN}ゆうこうにかつようしてくれたまえ\l"
	.string "{JPN}おじさんのきんのたまだからね！$"
