Route21_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route21_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route21_OnTransition:
	callnative SetTimeBasedEncounters
	end

Route21_EventScript_Seth::
	trainerbattle_single TRAINER_SETH Route21_Text_SwimmermSethSeen, Route21_Text_SwimmermSethBeaten
	msgbox Route21_Text_SwimmermSethAfterBattle, MSGBOX_AUTOCLOSE
	end

Route21_EventScript_Nikki::
	trainerbattle_single TRAINER_NIKKI Route21_Text_SwimmerfNikkiSeen, Route21_Text_SwimmerfNikkiBeaten
	msgbox Route21_Text_SwimmerfNikkiAfterBattle, MSGBOX_AUTOCLOSE
	end

Route21_EventScript_Arnold::
	trainerbattle_single TRAINER_ARNOLD Route21_Text_FisherArnoldSeen, Route21_Text_FisherArnoldBeaten
	msgbox Route21_Text_FisherArnoldAfterBattle, MSGBOX_AUTOCLOSE
	end

Route21_Text_SwimmermSethSeen:
	.string "{JPN}りくちが みえるぞ!\nいくしかない!$"

Route21_Text_SwimmermSethBeaten:
	.string "{JPN}Glug...$"
Route21_Text_SwimmermSethAfterBattle:
	.string "{JPN}グレンとうの かざんに\n"
	.string "{JPN}なまいきなやつが いたんだ$"

Route21_Text_SwimmerfNikkiSeen:
	.string "{JPN}わたしが かったら\n"
	.string "{JPN}ひやけどめを ぬって!$"

Route21_Text_SwimmerfNikkiBeaten:
	.string "{JPN}I'm worried about sunburn...$"
Route21_Text_SwimmerfNikkiAfterBattle:
	.string "{JPN}たいようの ひかりで\n"
	.string "{JPN}はだが あれちゃうのよ$"

Route21_Text_FisherArnoldSeen:
	.string "{JPN}つりに あきたから\nバトルしよう!$"

Route21_Text_FisherArnoldBeaten:
	.string "{JPN}Utter failure...$"
Route21_Text_FisherArnoldAfterBattle:
	.string "{JPN}I'll just go back to fishing...$"
