SootopolisCity_House1_MapScripts::
	.byte 0

SootopolisCity_House1_EventScript_BrickBreakBlackBelt::
	lock
	faceplayer
	goto_if_set FLAG_RECEIVED_TM_BRICK_BREAK, SootopolisCity_House1_EventScript_ReceivedBrickBreak
	msgbox SootopolisCity_House1_Text_DevelopedThisTM, MSGBOX_DEFAULT
	giveitem ITEM_TM_BRICK_BREAK
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_RECEIVED_TM_BRICK_BREAK
	msgbox SootopolisCity_House1_Text_ExplainBrickBreak, MSGBOX_DEFAULT
	release
	end

SootopolisCity_House1_EventScript_ReceivedBrickBreak::
	msgbox SootopolisCity_House1_Text_ExplainBrickBreak, MSGBOX_DEFAULT
	release
	end

SootopolisCity_House1_EventScript_Kecleon::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_KECLEON, CRY_MODE_NORMAL
	msgbox SootopolisCity_House1_Text_Kecleon, MSGBOX_DEFAULT
	waitmoncry
	release
	end

SootopolisCity_House1_Text_DevelopedThisTM:
	.string "{JPN}30ねんかん わしは ソーテポリス\n"
	.string "{JPN}にこもって わざを みがいてきた.\p"
	.string "{JPN}はかいてきな わざマシンを\n"
	.string "{JPN}かいはつした.きみに ゆずろう!$"

SootopolisCity_House1_Text_ExplainBrickBreak:
	.string "{JPN}わざマシン31は かわらわり!\n"
	.string "{JPN}あまりに おそろしくて\nせつめいできない わざじゃ.$"

SootopolisCity_House1_Text_Kecleon:
	.string "{JPN}カクレオン: プー プヒャー.$"

