OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "{JPN}ポケモンバトルが はじまるとき\n"
	.string "{JPN}いちばん ひだりにいる ポケモンが\l"
	.string "{JPN}さいしょに でてくるんだ.\p"
	.string "{JPN}だから てもちポケモンが ふえたら\n"
	.string "{JPN}ポケモンの じゅんばんを\l"
	.string "{JPN}いれかえて みるといいよ.\pゆうりに なるかも しれないからね.$"

