CeladonCity_GameCorner_MapScripts::
	.byte 0

CeladonGameCorner_EventScript_PokefanM::
	msgbox CeladonGameCorner_Text_PokefanM, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Teacher::
	msgbox CeladonGameCorner_Text_Teacher, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_FishingGuru::
	msgbox CeladonGameCorner_Text_FishingGuru, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Fisher1::
	msgbox CeladonGameCorner_Text_Fisher1, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Fisher2::
	msgbox CeladonGameCorner_Text_Fisher2, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_GymGuide::
	msgbox CeladonGameCorner_Text_GymGuide, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Gramps::
	msgbox CeladonGameCorner_Text_Gramps, MSGBOX_NPC
	end

CeladonGameCorner_Text_PokefanM:
	.string "{JPN}スロットマシンは\n"
	.string "{JPN}ぜんぶ さいしんがただよ$"

CeladonGameCorner_Text_Teacher:
	.string "{JPN}わたしが ねらってるのは\n"
	.string "{JPN}このマシンなの\p"
	.string "{JPN}きのうは すっからかんに\nされたから きょうは\nはらってくれるはずよ$"

CeladonGameCorner_Text_FishingGuru:
	.string "{JPN}このスロットマシンは\n"
	.string "{JPN}あたりそうだな...\p"
	.string "{JPN}かくりつは マシンによって\nちがうんだよ$"

CeladonGameCorner_Text_Fisher1:
	.string "{JPN}がはははは!\p"
	.string "{JPN}コインが どんどん\n"
	.string "{JPN}でてくるじゃないか!\p"
	.string "{JPN}ん? なんだ こぞう?\nやってみたいのか?\pおじさんの うんを\nわけてやろう!$"

CeladonGameCorner_Text_Fisher2:
	.string "{JPN}がはははは!\p"
	.string "{JPN}ひとに しんせつにすると\n"
	.string "{JPN}きもちが いいもんだな!$"

CeladonGameCorner_Text_GymGuide:
	.string "{JPN}おお! みらいのチャンピオン!\p"
	.string "{JPN}きみも スロットで\n"
	.string "{JPN}あそんでるのかい?\p"
	.string "{JPN}しょうひんの ポケモンを\n"
	.string "{JPN}もらうために\lコインを ためてるんだ\pでも まだ\nコインが たりないんだよな...$"
CeladonGameCorner_Text_Gramps:
	.string "{JPN}うーむ... ピカチュウの\n"
	.string "{JPN}ならびの ほうが\l"
	.string "{JPN}かくりつは よさそうじゃが...\lどうしたものかのう?$"
