@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "{JPN}おじさんと いっしょに\n"
	.string "{JPN}ポロックを つくりたいのかい?$"

BerryBlender_Text_Excellent:
	.string "{JPN}そうか!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "{JPN}そうか...\n"
	.string "{JPN}おじさん さみしい...$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "{JPN}じゃあ ポロックの つくりかたは\n"
	.string "{JPN}もう しってるかい?$"

BerryBlender_Text_LetsBerryBlender:
	.string "{JPN}じゃあ はじめるぞ!\p"
	.string "{JPN}レッツ きのみブレンダー!!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "{JPN}よし せつめいするぞ!\p"
	.string "{JPN}なぁに かんたんな ことだ!\p"
	.string "{JPN}きのみブレンダーの マークが\n"
	.string "{JPN}じぶんの ところに きたら\l"
	.string "{JPN}ボタンを おせば いいだけだ\p"
	.string "{JPN}まあ じっさいに やってみれば\n"
	.string "{JPN}すぐ わかるさ!$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "{JPN}あれ?\n"
	.string "{JPN}でも きのみを もってない みたいだね\p"
	.string "{JPN}きのみが ないと ポロックは\n"
	.string "{JPN}つくれないんだよ$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "{JPN}しかたないなぁ もう\p"
	.string "{JPN}おじさんの あまった きのみで\n"
	.string "{JPN}よければ あげるよ!\p"
	.string "{JPN}これで いっしょに きのみブレンダーで\n"
	.string "{JPN}ポロックを つくろうや$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "{JPN}おじさんの あまりの きのみが あれば\n"
	.string "{JPN}あげるん だけど...\p"
	.string "{JPN}きょうは もう あまって ないんだ\n"
	.string "{JPN}また こんど やろうな$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "{JPN}でも ポロックケースが\n"
	.string "{JPN}いっぱいの ようだね\p"
	.string "{JPN}ポロックを へらしてから\n"
	.string "{JPN}また おいで$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "{JPN}でも ポロックケースを\n"
	.string "{JPN}まだもって ないようだね\p"
	.string "{JPN}ポロックケースを\n"
	.string "{JPN}もらってから またおいで$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "{JPN}はやく まぜようぜ!!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "{JPN}どんな ポロックが できるのかしら?\n"
	.string "{JPN}ドキドキ しちゃう!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "{JPN}よっしっ! おにいさん たちと いっしょに\n"
	.string "{JPN}ポロックを つくりたいんだね!$"

BerryBlender_Text_Okay:
	.string "{JPN}よっしっ!$"

BerryBlender_Text_ThatsTooBad:
	.string "{JPN}ざんねんだよ...\p"
	.string "{JPN}でも おにいさん たちは\n"
	.string "{JPN}いつでも きみを まってる からね!$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "{JPN}もちろん ポロックの つくりかたは\n"
	.string "{JPN}しっているよね?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "{JPN}よっしっ! じゃあ はじめるよ!\p"
	.string "{JPN}レッツ きのみブレンダー!!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "{JPN}よっしっ!\n"
	.string "{JPN}おにいさんが せつめいして あげよう!\p"
	.string "{JPN}きのみブレンダーの マークが\n"
	.string "{JPN}じぶんの ところに きたら\l"
	.string "{JPN}ボタンを おすんだよ!\p"
	.string "{JPN}とっても\n"
	.string "{JPN}かんたんな ことだろう?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "{JPN}...と おもったら\n"
	.string "{JPN}きみ きのみを もっていない みたいだね\p"
	.string "{JPN}きのみが ないと ポロックは\n"
	.string "{JPN}つくれないんだよ...\p"
	.string "{JPN}おにいさん たちは\n"
	.string "{JPN}いつも ここに いるから\l"
	.string "{JPN}きのみを みつけたら また やろうね!$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "{JPN}...と おもったら\n"
	.string "{JPN}ポロックケースが いっぱいの ようだね\p"
	.string "{JPN}ポロックを へらしてから\n"
	.string "{JPN}また きてね$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "{JPN}...と おもったら\n"
	.string "{JPN}きみ ポロックケースを\l"
	.string "{JPN}まだ もって ないようだね\p"
	.string "{JPN}ポロックケースを\n"
	.string "{JPN}もらってから また きてね$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "{JPN}あらあら! おばさん たちと いっしょに\n"
	.string "{JPN}ポロックを つくりたいのかしら?$"

BerryBlender_Text_OhDear:
	.string "{JPN}あらあら!$"

BerryBlender_Text_LeftUsInShock:
	.string "{JPN}あらあら...\p"
	.string "{JPN}おばさん たち とっても ショック!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "{JPN}じゃあ もちろん ポロックの つくりかたは\n"
	.string "{JPN}しっているわね?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "{JPN}あらあら! じゃあ はじめるよ!\p"
	.string "{JPN}レッツ きのみブレンダー!!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "{JPN}あらあら!\p"
	.string "{JPN}じゃあ おばさんが\n"
	.string "{JPN}やさしく せつめいして あげるわね!\p"
	.string "{JPN}きのみブレンダーの マークが\n"
	.string "{JPN}じぶんの ところに きたら\l"
	.string "{JPN}ボタンを バシッと おすだけで いいのよ!\l"
	.string "{JPN}かんたん ねー!$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "{JPN}あなた きのみを もってないわね\p"
	.string "{JPN}きのみが ないと ポロックは\n"
	.string "{JPN}つくれないのよ...\p"
	.string "{JPN}おばさん たち いつでも ここで\n"
	.string "{JPN}ポロックを つくっているから\l"
	.string "{JPN}きのみを みつけたら また やろうね!$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "{JPN}ポロックケースが\n"
	.string "{JPN}いっぱいの ようね\p"
	.string "{JPN}ポロックを へらしてから\n"
	.string "{JPN}また きてね$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "{JPN}ポロックケースを\n"
	.string "{JPN}まだ もって ないようね\p"
	.string "{JPN}ポロックケースを\n"
	.string "{JPN}もらってから また きてね$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "{JPN}よっしっ! きょうこそ\n"
	.string "{JPN}ブレンダーの さいこうそくどを だすぞ!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "{JPN}あらあら!\n"
	.string "{JPN}あなた まぜるの うまそうね!\l"
	.string "{JPN}いっしょに やらない?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "{JPN}おいしい ポロックを つくって\n"
	.string "{JPN}わたしの ポケモンを\l"
	.string "{JPN}もっと もっと かわいく するのー$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "{JPN}きのみブレンダーで ともだちと いっしょに\n"
	.string "{JPN}きのみから ポロックを つくります\p"
	.string "{JPN}つうしんに はいる まえに\n"
	.string "{JPN}レポートを かいても よろしいですか?$"

BerryBlender_Text_SearchingForFriends:
	.string "{JPN}ともだちを さがしています\n"
	.string "{JPN}...Bボタンで キャンセル$"

BerryBlender_Text_Player1Arrived:
	.string "{JPN}{STR_VAR_1}さんが きました$"

BerryBlender_Text_Player1And2Arrived:
	.string "{JPN}{STR_VAR_1}さんと {STR_VAR_2}さんが\n"
	.string "{JPN}きました$"

BerryBlender_Text_AllPlayersArrived:
	.string "{JPN}{STR_VAR_1}さん {STR_VAR_2}さん\n"
	.string "{JPN}{STR_VAR_3}さんが きました$"

BerryBlender_Text_NoBerriesLink:
	.string "{JPN}きのみが ないので\n"
	.string "{JPN}きのみブレンダーは つかえません$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "{JPN}ポロックケースが いっぱい なので\n"
	.string "{JPN}きのみブレンダーは つかえません$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "{JPN}ポロックケースが ないので\n"
	.string "{JPN}きのみブレンダーは つかえません$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "{JPN}わしは ポロックを\n"
	.string "{JPN}つくるのが だいすきで\p"
	.string "{JPN}いつも きのみを\n"
	.string "{JPN}もって きてるんだ$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "{JPN}もし よかったら\n"
	.string "{JPN}いっしょに きのみブレンダーで\l"
	.string "{JPN}ポロックを つくろうや$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "{JPN}あれ?\n"
	.string "{JPN}きのみを もってないの?\p"
	.string "{JPN}しかたないなぁ もう\p"
	.string "{JPN}おじさんの あまった きのみで\n"
	.string "{JPN}よければ あげるよ!$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "{JPN}これで いっしょに きのみブレンダーで\n"
	.string "{JPN}ポロックを つくろうや$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "{JPN}あれ?\n"
	.string "{JPN}きのみを もってないの?\p"
	.string "{JPN}おじさんの あまりの きのみが あれば\n"
	.string "{JPN}あげるん だけど...\p"
	.string "{JPN}きょうは もう あまって\n"
	.string "{JPN}ないんだ すまんな$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_GARBAGEFLAG, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
