.set LOCALID_BLACKTHORN_SAGE, 7
.set LOCALID_BLACKTHORN_BOY, 2

BlackthornCity_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BlackthornCity_OnFrame
	map_script MAP_SCRIPT_ON_LOAD, BlackthornCity_OnLoad
	map_script MAP_SCRIPT_ON_TRANSITION, BlackthornCity_EventScript_CityEnter
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

BlackthornCity_OnLoad::
	goto_if_unset FLAG_BADGE05_GET, BlackThornCity_EventScript_MoveGymBoy
	goto_if_unset FLAG_BADGE06_GET, BlackThornCity_EventScript_MoveGymBoy
	goto_if_unset FLAG_BADGE07_GET, BlackThornCity_EventScript_MoveGymBoy
	end

BlackThornCity_EventScript_MoveGymBoy::
	setobjectxyperm LOCALID_BLACKTHORN_BOY, 24, 27
	end

BlackthornCity_OnFrame::
	map_script_2 VAR_BLACKTHORN_CITY_STATE, 4, BlackthornCity_EventScript_Call
	.2byte 0

BlackthornCity_EventScript_CityEnter:: 
	setflag FLAG_VISITED_BLACKTHORN_CITY
	callnative SetTimeBasedEncounters
	end

BlackthornCity_EventScript_Call::
	lock
	pokenavcall BlackthornCity_Text_ElmCall
	waitmessage
	delay 30
	setvar VAR_BLACKTHORN_CITY_STATE, 5
	setvar VAR_NEWBARKTOWN_LABSTATE, 7
	release
	end

BlackthornCity_Text_BaobaCall:
	.string "{JPN}バオバえんちょう{PLAYER}！\pわしはサファリゾーンの\pえんちょうのバオバじゃ！\nサファリゾーンがかくだいしたぞ！\pぜひあそびにきておくれ！$"
BlackthornCity_Text_ElmCall:
	.string "{JPN}ウツギはかせもしもし{PLAYER}？\pきみにわたしたいものがあるんだ\nけんきゅうじょにきてくれるかい？\pそれではまたね！$"
BlackThornCity_EventScript_Sage::
	lock
	faceplayer
	goto_if_eq VAR_BLACKTHORN_CITY_STATE, 1, BlackThornCity_EventScript_SageRefuse
	msgbox BlackthornGrampsGrantsEntryText, MSGBOX_DEFAULT
	closemessage
	release
	end

BlackThornCity_EventScript_SageRefuse::
	msgbox BlackthornGrampsRefusesEntryText, MSGBOX_DEFAULT
	closemessage
	release
	end

BlackThornCity_Trigger_Sage::
	lock
	turnobject LOCALID_BLACKTHORN_SAGE, DIR_EAST
	msgbox BlackthornGrampsRefusesEntryText, MSGBOX_DEFAULT
	closemessage
	applymovement OBJ_EVENT_ID_PLAYER Common_Movement_WalkDown1
	waitmovement 0
	turnobject LOCALID_BLACKTHORN_SAGE, DIR_SOUTH
	release
	end

BlackthornCity_EventScript_GymBoy::
	lock
	faceplayer
	goto_if_unset FLAG_BADGE05_GET, BlackThornCity_EventScript_GymBoyNotReady
	goto_if_unset FLAG_BADGE06_GET, BlackThornCity_EventScript_GymBoyNotReady
	goto_if_unset FLAG_BADGE07_GET, BlackThornCity_EventScript_GymBoyNotReady
	goto_if_eq VAR_BLACKTHORN_CITY_STATE, 1, BlackThornCity_EventScript_GymBoyBefore
	msgbox BlackthornCity_Text_ClairIsBeaten, MSGBOX_DEFAULT
	closemessage
	release
	end	

BlackThornCity_EventScript_GymBoyNotReady::
	msgbox BlackthornCity_Text_ClairNotReady, MSGBOX_DEFAULT
	closemessage
	release
	end

BlackThornCity_EventScript_GymBoyBefore::
	msgbox BlackthornCity_Text_ClairIsIn, MSGBOX_DEFAULT
	closemessage
	release
	end	

BlackthornCity_EventScript_BlackBelt::
	msgbox BlackBeltText_VoicesInMyHead, MSGBOX_NPC
	end

BlackthornCity_EventScript_CoolTrainerF::
	msgbox BlackthornCooltrainerF1Text, MSGBOX_NPC
	end

BlackthornCity_EventScript_Youngster::
	msgbox BlackthornYoungsterText, MSGBOX_NPC
	end

BlackthornCity_EventScript_CoolTrainerF2::
	msgbox BlackthornCooltrainerF2Text, MSGBOX_NPC
	end

BlackthornCity_EventScript_CitySign::
	msgbox BlackthornCitySignText, MSGBOX_SIGN
	end

BlackthornCity_EventScript_GymSign::
	msgbox BlackthornGymSignText, MSGBOX_SIGN
	end

BlackthornCity_EventScript_MoveHouseSign::
	msgbox BlackthornCity_Text_MoveDeletersHouseSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_DragonsDenSign::
	msgbox BlackthornCity_Text_DragonDenSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_Santos::
	lock
	faceplayer
	goto_if_set FLAG_GOT_SPELL_TAG, BlackthornCity_EventScript_SantosCompleted
	msgbox BlackthornCity_MeetSantosText, MSGBOX_DEFAULT
	closemessage
	multichoice 20, 0, MULTI_DAYS_OF_WEEK, FALSE
	switch VAR_RESULT
	case 0, BlackthornCity_EventScript_SantosNope
	case 1, BlackthornCity_EventScript_SantosNope
	case 2, BlackthornCity_EventScript_SantosNope
	case 3, BlackthornCity_EventScript_SantosNope
	case 4, BlackthornCity_EventScript_SantosNope
	case 5, BlackthornCity_EventScript_SantosNope
	case 6, BlackthornCity_EventScript_SantosYes
	case 7 BlackthornCity_EventScript_SantosCancel
	case MULTI_B_PRESSED, BlackthornCity_EventScript_SantosCancel
	closemessage
	release
	end
BlackthornCity_EventScript_SantosYes::
	msgbox BlackthornCity_SantosGivesGiftText, MSGBOX_DEFAULT
	giveitem ITEM_SPELL_TAG
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_GOT_SPELL_TAG
	msgbox BlackthornCity_SantosGaveGiftText, MSGBOX_DEFAULT
	closemessage
	release
	end
BlackthornCity_EventScript_SantosNope::
	msgbox BlackthornCity_SantosNopeText, MSGBOX_DEFAULT
	closemessage
	release
	end
BlackthornCity_EventScript_SantosCancel::
	closemessage
	release
	end
BlackthornCity_EventScript_SantosCompleted::
	msgbox BlackthornCity_SantosSaturdayText, MSGBOX_DEFAULT
	closemessage
	release
	end


BlackthornCity_Text_ClairNotReady:
	.string "{JPN}ジムリーダーのイブキさまは\nきみのかつやくをみておられる\pだがバッジを7こもっている\nトレーナーとしかたたかわないのだ$"
BlackthornCity_Text_ClairIsIn:
	.string "{JPN}ジムリーダーのイブキさまが\n"
	.string "{JPN}おまちになっておられます\p"
	.string "{JPN}ですがなみたいていの\n"
	.string "{JPN}じつりょくではかてませんよ$"
BlackthornCity_Text_ClairIsBeaten:
	.string "{JPN}イブキさまにかたれたのですか！\n"
	.string "{JPN}それはすごい..\p"
	.string "{JPN}ワタルさまいがいに\n"
	.string "{JPN}まけるのをみるのははじめてです！$"
BlackthornGrampsRefusesEntryText:
	.string "{JPN}だめじゃ.えらばれた\n"
	.string "{JPN}トレーナーだけが\l"
	.string "{JPN}ここで しゅぎょうできる.\pかえりなさい.$"

BlackthornGrampsGrantsEntryText:
	.string "{JPN}イブキが みとめるなら\n"
	.string "{JPN}かのじょの そふ...\l"
	.string "{JPN}われらの しはんも みとめよう.\pはいって よろしい.$"

BlackBeltText_VoicesInMyHead:
	.string "{JPN}うおー!あたまのなかに\n"
	.string "{JPN}こえが!\pあ?ラジオを きいてるんだ!$"

BlackthornCooltrainerF1Text:
	.string "{JPN}あなたの ポケモンに\n"
	.string "{JPN}わざを おもいださせるの?$"

BlackthornYoungsterText:
	.string "{JPN}ドラゴンの たつじんは みんな\n"
	.string "{JPN}フスベシティの しゅっしんなんだ.$"

BlackthornCity_MeetSantosText:
	.string "{JPN}サントス: ...\p"
	.string "{JPN}わたしは ようびきょうだいの\n"
	.string "{JPN}サントスです.\pあててみてください.$"

BlackthornCity_SantosGivesGiftText:
	.string "{JPN}これを どうぞ...$"
BlackthornCity_SantosGaveGiftText:
	.string "{JPN}サントス: ...\p"
	.string "{JPN}のろいのおふだ...\p"
	.string "{JPN}ゴーストタイプの わざが\n"
	.string "{JPN}つよくなります...\pおそろしいでしょう...$"
BlackthornCity_SantosSaturdayText:
	.string "{JPN}サントス: ...\p"
	.string "{JPN}また べつの どようびに\n"
	.string "{JPN}あいましょう...\pもう おくりものは\nありません...$"
BlackthornCity_SantosNopeText:
	.string "{JPN}サントス:だめ.$"

BlackthornCooltrainerF2Text:
	.string "{JPN}わあ!こおりのぬけみちを\n"
	.string "{JPN}とおってきたの?\pほんとうに すごい トレーナー\nなのね!$"

BlackthornCitySignText:
	.string "{JPN}フスベシティ\p"
	.string "{JPN}しずかな やまおくの きゅうけいち$"

BlackthornGymSignText:
	.string "{JPN}フスベシティ ポケモンジム\n"
	.string "{JPN}ジムリーダー:イブキ\p"
	.string "{JPN}ドラゴン ポケモンの せいなる つかいて$"

BlackthornCity_Text_MoveDeletersHouseSign:
	.string "{JPN}わざけしきょうだいのいえ$"
BlackthornCity_Text_DragonDenSign:
	.string "{JPN}このさきりゅうのあな$"
