AquaHideout_UnusedRubyMap3_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_UnusedRubyMap3_OnTransition
	.byte 0

AquaHideout_UnusedRubyMap3_OnTransition::
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo::
	msgbox AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text, MSGBOX_NPC
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text:
	.string "{JPN}あやしく うごく きを みた\n"
	.string "{JPN}ことが ありますか? あれは\l"
	.string "{JPN}ウソッキーという ポケモン\p"
	.string "{JPN}なんです! しっていましたか?\p"
	.string "{JPN}ちいさな きに ばけるのが\n"
	.string "{JPN}とくいな ポケモンなんです.\p"
	.string "{JPN}それと ウソハチも おなじ\n"
	.string "{JPN}ことを しますが... あまり\l"
	.string "{JPN}リアルじゃないと おもいます.\p"
	.string "{JPN}そういえば ほかの ウソッキーの\n"
	.string "{JPN}まねを しながら しんかする\p"
	.string "{JPN}のを みたことが あります.\p"
	.string "{JPN}それが しんかの ほうほう\n"
	.string "{JPN}なのでしょうか?\p"
	.string "{JPN}たしか マネネも ほかの\nポケモンの まねをして\lしんかしますよね.\pぼくの ゴンベは なつきで\nしんかしたので ぜんぜん\lちがいますね!$"
