.set LOCALID_NURSE, 1

SafariZoneGate_PokemonCenter_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, SafariZoneGate_PokemonCenter_OnTransition
	.byte 0

SafariZoneGate_PokemonCenter_OnTransition::
	setrespawn HEAL_LOCATION_SAFARI_ZONE_GATE
	end

SafariZoneGate_PokemonCenter_EventScript_NPC1::
	lock
	faceplayer
	msgbox SafariZoneGate_PokemonCenter_Text_NPC1, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_PokemonCenter_EventScript_NPC2::
	lock
	faceplayer
	msgbox SafariZoneGate_PokemonCenter_Text_NPC2, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_PokemonCenter_Text_Boy::
	lock
	faceplayer
	msgbox SafariZoneGate_PokemonCenter_Text_SafariSong, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_PokemonCenter_Text_NPC1:
	.string "{JPN}ポケモンセンターに くるひとは\n"
	.string "{JPN}ポケモンを たいせつにしてるよね.\p"
	.string "{JPN}きみも そうおもうでしょ?$"

SafariZoneGate_PokemonCenter_Text_NPC2:
	.string "{JPN}やまみちを あるいて あるいて\n"
	.string "{JPN}ポケモンセンターを みつけたとき\l"
	.string "{JPN}たおれそうになっていても...\p"
	.string "{JPN}そこは らくえんに かんじるよ!$"

SafariZoneGate_PokemonCenter_Text_SafariSong:
	.string "{JPN}サファリ サファリ たのしいな\n"
	.string "{JPN}サファリ サファリ おもしろいな!\p"
	.string "{JPN}たくさんの ポケモンが まってるよ!\p"
	.string "{JPN}...これは わたしが つくったうた.\n"
	.string "{JPN}サファリゾーンで うたってるの.$"
