PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "{JPN}たびって すばらしいのう!\p"
	.string "{JPN}わしが わかいころは うみや\n"
	.string "{JPN}やまを かけまわったもんじゃ!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "{JPN}はあ...\p"
	.string "{JPN}わたしも ポケモンと いっしょに\n"
	.string "{JPN}ぼうけんに でかけたいなあ...\p"
	.string "{JPN}しめった くさむらを はいつくばり...\n"
	.string "{JPN}ごつごつした やまを のぼって...\p"
	.string "{JPN}あらなみの うみを わたって...\n"
	.string "{JPN}くらい ほらあなを さまよって...\p"
	.string "{JPN}ときには ちょっと\n"
	.string "{JPN}ホームシックに なったりして...\p"
	.string "{JPN}りょこうって すてきでしょうね!$"

