.set LOCALID_STAIR_GUARD, 2

RustboroCity_DevonCorp_1F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, RustboroCity_DevonCorp_1F_OnTransition
	.byte 0

RustboroCity_DevonCorp_1F_OnTransition:
	call_if_unset FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_BlockStairs
	end

RustboroCity_DevonCorp_1F_EventScript_BlockStairs::
	setobjectxyperm LOCALID_STAIR_GUARD, 14, 2
	setobjectmovementtype LOCALID_STAIR_GUARD, MOVEMENT_TYPE_FACE_DOWN
	return

RustboroCity_DevonCorp_1F_EventScript_Employee::
	lock
	faceplayer
	goto_if_set FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_GoodsRecovered
	goto_if_set FLAG_DEVON_GOODS_STOLEN, RustboroCity_DevonCorp_1F_EventScript_RobberWasntBright
	msgbox RustboroCity_DevonCorp_1F_Text_ThoseShoesAreOurProduct, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_RobberWasntBright::
	msgbox RustboroCity_DevonCorp_1F_Text_RobberWasntVeryBright, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_GoodsRecovered::
	msgbox RustboroCity_DevonCorp_1F_Text_SoundsLikeStolenGoodsRecovered, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_StairGuard::
	lock
	faceplayer
	goto_if_set FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_AlwaysWelcome
	goto_if_set FLAG_RECOVERED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_GotRobbed
	goto_if_set FLAG_DEVON_GOODS_STOLEN, RustboroCity_DevonCorp_1F_EventScript_GotRobbed
	msgbox RustboroCity_DevonCorp_1F_Text_OnlyAuthorizedPeopleEnter, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_AlwaysWelcome::
	msgbox RustboroCity_DevonCorp_1F_Text_YoureAlwaysWelcomeHere, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_GotRobbed::
	msgbox RustboroCity_DevonCorp_1F_Text_HowCouldWeGetRobbed, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_Greeter::
	lock
	faceplayer
	goto_if_set FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_WelcomeToDevonCorp
	goto_if_set FLAG_RECOVERED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_StaffGotRobbed
	goto_if_set FLAG_DEVON_GOODS_STOLEN, RustboroCity_DevonCorp_1F_EventScript_StaffGotRobbed
	msgbox RustboroCity_DevonCorp_1F_Text_WelcomeToDevonCorp, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_WelcomeToDevonCorp::
	msgbox RustboroCity_DevonCorp_1F_Text_WelcomeToDevonCorp, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_StaffGotRobbed::
	msgbox RustboroCity_DevonCorp_1F_Text_StaffGotRobbed, MSGBOX_DEFAULT
	release
	end

RustboroCity_DevonCorp_1F_EventScript_RocksMetalDisplay::
	msgbox RustboroCity_DevonCorp_1F_Text_RocksMetalDisplay, MSGBOX_SIGN
	end

RustboroCity_DevonCorp_1F_EventScript_ProductsDisplay::
	msgbox RustboroCity_DevonCorp_1F_Text_ProductDisplay, MSGBOX_SIGN
	end

RustboroCity_DevonCorp_1F_Text_WelcomeToDevonCorp:
	.string "{JPN}こんにちは デボンコーポ\n"
	.string "{JPN}レーションへようこそ.\p"
	.string "{JPN}わたしたちは せいかつを\n"
	.string "{JPN}ゆたかにする どうぐや\lくすりを つくっています.$"

RustboroCity_DevonCorp_1F_Text_StaffGotRobbed:
	.string "{JPN}けんきゅういんの ひとりが\n"
	.string "{JPN}たいせつな にもつを\lぬすまれてしまったんです.$"

RustboroCity_DevonCorp_1F_Text_ThoseShoesAreOurProduct:
	.string "{JPN}おや そのランニングシューズ!\n"
	.string "{JPN}わたしたちの しょうひんですね!\p"
	.string "{JPN}じぶんたちが つくったものを\n"
	.string "{JPN}つかってもらえて うれしいです.$"

RustboroCity_DevonCorp_1F_Text_RobberWasntVeryBright:
	.string "{JPN}あの ぬすまれた にもつ...\p"
	.string "{JPN}まあ たいせつな ものだけど\n"
	.string "{JPN}だれでも つかえる ものじゃない\p"
	.string "{JPN}わたしが おもうに あの どろぼうは\n"
	.string "{JPN}あまり あたまが よくなかったんだ$"

RustboroCity_DevonCorp_1F_Text_SoundsLikeStolenGoodsRecovered:
	.string "{JPN}ぬすまれた デボンのしょうひんが\n"
	.string "{JPN}もどってきたそうですね.$"

RustboroCity_DevonCorp_1F_Text_OnlyAuthorizedPeopleEnter:
	.string "{JPN}すみません きょかされた\n"
	.string "{JPN}ひとしか はいれないんです.$"

RustboroCity_DevonCorp_1F_Text_HowCouldWeGetRobbed:
	.string "{JPN}ばかばかしいことです.\n"
	.string "{JPN}どうして ぬすまれたんでしょう?$"

RustboroCity_DevonCorp_1F_Text_YoureAlwaysWelcomeHere:
	.string "{JPN}やあ!\n"
	.string "{JPN}いつでも きてくださいね!$"

RustboroCity_DevonCorp_1F_Text_RocksMetalDisplay:
	.string "{JPN}ガラスケースに いわと きんぞくの\n"
	.string "{JPN}サンプルが てんじされている\p"
	.string "{JPN}そこには せつめいがきが\n"
	.string "{JPN}ついている...\p"
	.string "{JPN}デボンコーポレーションは\n"
	.string "{JPN}さいせきじょうの いしを\l"
	.string "{JPN}せいぞうする かいしゃとして\l"
	.string "{JPN}スタートしました\p"
	.string "{JPN}かいしゃは すなてつから\n"
	.string "{JPN}てつも せいぞうしていました\p"
	.string "{JPN}そざいの せいぞうしゃとしての\n"
	.string "{JPN}ささやかな スタートから\lデボンは はってんしました\pデボンは いまでは こうぎょう\nせいひんの はんいひろい\lメーカーです$"

RustboroCity_DevonCorp_1F_Text_ProductDisplay:
	.string "{JPN}ガラスの てんじケースに\n"
	.string "{JPN}シサク ひんと テストせいひんが\l"
	.string "{JPN}ならんでいる\p"
	.string "{JPN}せつめいがきが ついている...\p"
	.string "{JPN}こうぎょうせいひんに くわえて\n"
	.string "{JPN}デボンは いまでは より よい\l"
	.string "{JPN}ライフスタイルの ための\l"
	.string "{JPN}ざっかや やくひんも はんばい\l"
	.string "{JPN}しています\pさいきん デボンは ポケモン\nトレーナーの ための どうぐ\lたとえば モンスターボールや\lポケナビ システムの はんばいを\lはじめました$"

