FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "{JPN}ポケモンずかんの はなしで\n"
	.string "{JPN}おもいだしたことが あるんじゃ.\p"
	.string "{JPN}めずらしい いしを さがしてるとき\n"
	.string "{JPN}ダイゴって トレーナーに\l"
	.string "{JPN}あったんじゃよ.\p"
	.string "{JPN}いやあ すごい ポケモンを\n"
	.string "{JPN}つれておったなあ.\p"
	.string "{JPN}めずらしいだけじゃなくて\n"
	.string "{JPN}おそろしいほど きたえられてた!\p"
	.string "{JPN}このまちの ジムリーダーより\nつよいんじゃないかのう...$"
FortreeCity_House3_Text_OhYouHavePokedex:
	.string "{JPN}それは なんじゃ?\p"
	.string "{JPN}ふむふむ...\p"
	.string "{JPN}ポケモンずかんって いうのかい?\n"
	.string "{JPN}すばらしいのう!$"

