SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "{JPN}おおきな ふねの せっけいは\n"
	.string "{JPN}のりものを つくるより\l"
	.string "{JPN}おおきな たてものを つくるのに\lちかいんだよ$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "{JPN}おもい てつで できた ふねが\n"
	.string "{JPN}ういているって ふしぎだと\l"
	.string "{JPN}おもわない?\p"
	.string "{JPN}ふりょくという げんりで\nういているんだよ$"

