VermilionCity_House2_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "{JPN}リニアでんしゃって\n"
	.string "{JPN}しってる?\p"
	.string "{JPN}ジョウトちほうの\n"
	.string "{JPN}コガネシティまで\nいけるのよ!$"

VermilionCity_House2_Text_Youngster:
	.string "{JPN}ヤマブキシティで\n"
	.string "{JPN}リニアでんしゃを\nみてみたいな!$"
