LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "{JPN}このほしの いちばん ふかい\n"
	.string "{JPN}なぞは うみの そこに あるって\p"
	.string "{JPN}だれかが いってたけど\nほんとかなあ...$"
LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "{JPN}トクサネと\n"
	.string "{JPN}ソウトポリスのあいだには\l"
	.string "{JPN}ふかい かいていの みぞが\lあるんだって.\pだれかが おしえて\nくれたんだよ.$"

